SATOX SDK: satox::core::IPFSManager Class Reference
satox::core::IPFSManager Class Reference
#include <ipfs_manager.hpp>
Classes
struct ContentInfo
struct IPFSStats
struct NodeInfo
Public Types
enum class NodeState {
UNINITIALIZED , INITIALIZING , CONNECTING , CONNECTED ,
DISCONNECTED , ERROR
}
enum class ContentType {
FILE , DIRECTORY , SYMLINK , RAW ,
JSON , TEXT , BINARY
}
using NodeCallback = std::function<void(const std::string&, NodeState)>
using ContentCallback = std::function<void(const std::string&, const ContentInfo&)>
using ErrorCallback = std::function<void(const std::string&, const std::string&)>
Public Member Functions
bool initialize (const nlohmann::json &config)
void shutdown ()
bool connectNode (const std::string &address)
bool disconnectNode (const std::string &address)
bool isNodeConnected (const std::string &address) const
NodeInfo getNodeInfo (const std::string &address) const
std::vector< NodeInfo > getAllNodes () const
std::vector< NodeInfo > getNodesByState (NodeState state) const
bool addContent (const std::string &path, ContentType type, const std::vector< uint8_t > &data)
bool addContentFromFile (const std::string &filePath)
bool addContentFromDirectory (const std::string &dirPath)
bool getContent (const std::string &hash, std::vector< uint8_t > &data)
bool getContentToFile (const std::string &hash, const std::string &filePath)
bool pinContent (const std::string &hash)
bool unpinContent (const std::string &hash)
bool isContentPinned (const std::string &hash) const
ContentInfo getContentInfo (const std::string &hash) const
std::vector< ContentInfo > getContentByType (ContentType type) const
std::vector< ContentInfo > getContentByTag (const std::string &tag) const
bool removeContent (const std::string &hash)
std::vector< ContentInfo > searchContent (const std::string &query) const
std::vector< ContentInfo > findContentByHash (const std::string &hash) const
std::vector< ContentInfo > findContentByName (const std::string &name) const
std::vector< ContentInfo > findContentByMimeType (const std::string &mimeType) const
bool updateContentMetadata (const std::string &hash, const nlohmann::json &metadata)
bool addContentTag (const std::string &hash, const std::string &tag)
bool removeContentTag (const std::string &hash, const std::string &tag)
bool updateContentName (const std::string &hash, const std::string &name)
bool updateContentMimeType (const std::string &hash, const std::string &mimeType)
IPFSStats getStats () const
void resetStats ()
bool enableStats (bool enable)
void registerNodeCallback (NodeCallback callback)
void registerContentCallback (ContentCallback callback)
void registerErrorCallback (ErrorCallback callback)
void unregisterNodeCallback ()
void unregisterContentCallback ()
void unregisterErrorCallback ()
std::string getLastError () const
void clearLastError ()
Static Public Member Functions
static IPFSManager & getInstance ()
Detailed Description
Definition at line 39 of file ipfs_manager.hpp.
Member Typedef Documentation
ContentCallback
using satox::core::IPFSManager::ContentCallback = std::function<void(const std::string&, const ContentInfo&)>
Definition at line 101 of file ipfs_manager.hpp.
ErrorCallback
using satox::core::IPFSManager::ErrorCallback = std::function<void(const std::string&, const std::string&)>
Definition at line 102 of file ipfs_manager.hpp.
NodeCallback
using satox::core::IPFSManager::NodeCallback = std::function<void(const std::string&, NodeState)>
Definition at line 100 of file ipfs_manager.hpp.
Member Enumeration Documentation
ContentType
enum class satox::core::IPFSManager::ContentType strong
Enumerator
FILE
DIRECTORY
SYMLINK
RAW
JSON
TEXT
BINARY
Definition at line 52 of file ipfs_manager.hpp.
NodeState
enum class satox::core::IPFSManager::NodeState strong
Enumerator
UNINITIALIZED
INITIALIZING
CONNECTING
CONNECTED
DISCONNECTED
ERROR
Definition at line 42 of file ipfs_manager.hpp.
Member Function Documentation
addContent()
bool satox::core::IPFSManager::addContent (const std::string & path, ContentType type, const std::vector< uint8_t > & data)
Definition at line 205 of file ipfs_manager.cpp.
Referenced by addContentFromFile().
addContentFromDirectory()
bool satox::core::IPFSManager::addContentFromDirectory (const std::string & dirPath)
Definition at line 262 of file ipfs_manager.cpp.
References addContentFromFile().
addContentFromFile()
bool satox::core::IPFSManager::addContentFromFile (const std::string & filePath)
Definition at line 239 of file ipfs_manager.cpp.
References addContent().
Referenced by addContentFromDirectory().
addContentTag()
bool satox::core::IPFSManager::addContentTag (const std::string & hash, const std::string & tag)
Definition at line 488 of file ipfs_manager.cpp.
clearLastError()
void satox::core::IPFSManager::clearLastError ()
Definition at line 627 of file ipfs_manager.cpp.
connectNode()
bool satox::core::IPFSManager::connectNode (const std::string & address)
Definition at line 109 of file ipfs_manager.cpp.
References CONNECTED, and CONNECTING.
disconnectNode()
bool satox::core::IPFSManager::disconnectNode (const std::string & address)
Definition at line 146 of file ipfs_manager.cpp.
References DISCONNECTED.
enableStats()
bool satox::core::IPFSManager::enableStats (bool enable)
Definition at line 586 of file ipfs_manager.cpp.
findContentByHash()
std::vector< ContentInfo > satox::core::IPFSManager::findContentByHash (const std::string & hash) const
Definition at line 435 of file ipfs_manager.cpp.
findContentByMimeType()
std::vector< ContentInfo > satox::core::IPFSManager::findContentByMimeType (const std::string & mimeType) const
Definition at line 456 of file ipfs_manager.cpp.
findContentByName()
std::vector< ContentInfo > satox::core::IPFSManager::findContentByName (const std::string & name) const
Definition at line 445 of file ipfs_manager.cpp.
getAllNodes()
std::vector< IPFSManager::NodeInfo > satox::core::IPFSManager::getAllNodes () const
Definition at line 185 of file ipfs_manager.cpp.
getContent()
bool satox::core::IPFSManager::getContent (const std::string & hash, std::vector< uint8_t > & data)
Definition at line 286 of file ipfs_manager.cpp.
Referenced by getContentToFile().
getContentByTag()
std::vector< ContentInfo > satox::core::IPFSManager::getContentByTag (const std::string & tag) const
Definition at line 385 of file ipfs_manager.cpp.
getContentByType()
std::vector< ContentInfo > satox::core::IPFSManager::getContentByType (ContentType type) const
Definition at line 374 of file ipfs_manager.cpp.
getContentInfo()
ContentInfo satox::core::IPFSManager::getContentInfo (const std::string & hash) const
Definition at line 365 of file ipfs_manager.cpp.
getContentToFile()
bool satox::core::IPFSManager::getContentToFile (const std::string & hash, const std::string & filePath)
Definition at line 304 of file ipfs_manager.cpp.
References getContent().
getInstance()
IPFSManager & satox::core::IPFSManager::getInstance () static
Definition at line 69 of file ipfs_manager.cpp.
Referenced by satox::core::CoreManager::getIPFSManager(), and satox::core::SatoxManager::getIPFSManager().
getLastError()
std::string satox::core::IPFSManager::getLastError () const
Definition at line 622 of file ipfs_manager.cpp.
getNodeInfo()
IPFSManager::NodeInfo satox::core::IPFSManager::getNodeInfo (const std::string & address) const
Definition at line 176 of file ipfs_manager.cpp.
getNodesByState()
std::vector< IPFSManager::NodeInfo > satox::core::IPFSManager::getNodesByState (IPFSManager::NodeState state) const
Definition at line 194 of file ipfs_manager.cpp.
getStats()
IPFSStats satox::core::IPFSManager::getStats () const
Definition at line 576 of file ipfs_manager.cpp.
initialize()
bool satox::core::IPFSManager::initialize (const nlohmann::json & config)
Definition at line 74 of file ipfs_manager.cpp.
isContentPinned()
bool satox::core::IPFSManager::isContentPinned (const std::string & hash) const
Definition at line 356 of file ipfs_manager.cpp.
isNodeConnected()
bool satox::core::IPFSManager::isNodeConnected (const std::string & address) const
Definition at line 167 of file ipfs_manager.cpp.
References CONNECTED.
pinContent()
bool satox::core::IPFSManager::pinContent (const std::string & hash)
Definition at line 320 of file ipfs_manager.cpp.
registerContentCallback()
void satox::core::IPFSManager::registerContentCallback (ContentCallback callback)
Definition at line 597 of file ipfs_manager.cpp.
registerErrorCallback()
void satox::core::IPFSManager::registerErrorCallback (ErrorCallback callback)
Definition at line 602 of file ipfs_manager.cpp.
registerNodeCallback()
void satox::core::IPFSManager::registerNodeCallback (NodeCallback callback)
Definition at line 592 of file ipfs_manager.cpp.
removeContent()
bool satox::core::IPFSManager::removeContent (const std::string & hash)
Definition at line 400 of file ipfs_manager.cpp.
removeContentTag()
bool satox::core::IPFSManager::removeContentTag (const std::string & hash, const std::string & tag)
Definition at line 509 of file ipfs_manager.cpp.
resetStats()
void satox::core::IPFSManager::resetStats ()
Definition at line 581 of file ipfs_manager.cpp.
searchContent()
std::vector< ContentInfo > satox::core::IPFSManager::searchContent (const std::string & query) const
Definition at line 423 of file ipfs_manager.cpp.
shutdown()
void satox::core::IPFSManager::shutdown ()
Definition at line 92 of file ipfs_manager.cpp.
unpinContent()
bool satox::core::IPFSManager::unpinContent (const std::string & hash)
Definition at line 338 of file ipfs_manager.cpp.
unregisterContentCallback()
void satox::core::IPFSManager::unregisterContentCallback ()
Definition at line 612 of file ipfs_manager.cpp.
unregisterErrorCallback()
void satox::core::IPFSManager::unregisterErrorCallback ()
Definition at line 617 of file ipfs_manager.cpp.
unregisterNodeCallback()
void satox::core::IPFSManager::unregisterNodeCallback ()
Definition at line 607 of file ipfs_manager.cpp.
updateContentMetadata()
bool satox::core::IPFSManager::updateContentMetadata (const std::string & hash, const nlohmann::json & metadata)
Definition at line 467 of file ipfs_manager.cpp.
updateContentMimeType()
bool satox::core::IPFSManager::updateContentMimeType (const std::string & hash, const std::string & mimeType)
Definition at line 555 of file ipfs_manager.cpp.
updateContentName()
bool satox::core::IPFSManager::updateContentName (const std::string & hash, const std::string & name)
Definition at line 535 of file ipfs_manager.cpp.
The documentation for this class was generated from the following files:
src/core/include/satox/core/ipfs_manager.hpp
src/core/src/ipfs_manager.cpp