SATOX SDK: satox::core::MerkleTree Class Reference
satox::core::MerkleTree Class Reference
#include <merkle_tree.h>
Public Member Functions
MerkleTree ()
~MerkleTree ()=default
MerkleTree (const MerkleTree &)=delete
MerkleTree & operator= (const MerkleTree &)=delete
MerkleTree (MerkleTree &&) noexcept=default
MerkleTree & operator= (MerkleTree &&) noexcept=default
void buildTree (const std::vector< std::string > &transactions)
std::string getRoot () const
std::vector< std::string > getProof (const std::string &transaction) const
bool verifyProof (const std::string &transaction, const std::string &root, const std::vector< std::string > &proof) const
Detailed Description
Definition at line 36 of file merkle_tree.h.
Constructor & Destructor Documentation
MerkleTree() [1/3]
satox::core::MerkleTree::MerkleTree ()
Definition at line 38 of file merkle_tree.cpp.
Referenced by MerkleTree(), MerkleTree(), operator=(), and operator=().
~MerkleTree()
satox::core::MerkleTree::~MerkleTree () default
MerkleTree() [2/3]
satox::core::MerkleTree::MerkleTree (const MerkleTree &) delete
References MerkleTree().
MerkleTree() [3/3]
satox::core::MerkleTree::MerkleTree (MerkleTree &&) default noexcept
References MerkleTree().
Member Function Documentation
buildTree()
void satox::core::MerkleTree::buildTree (const std::vector< std::string > & transactions)
Definition at line 40 of file merkle_tree.cpp.
Referenced by operator=().
getProof()
std::vector< std::string > satox::core::MerkleTree::getProof (const std::string & transaction) const
Definition at line 80 of file merkle_tree.cpp.
Referenced by operator=().
getRoot()
std::string satox::core::MerkleTree::getRoot () const
Definition at line 76 of file merkle_tree.cpp.
Referenced by operator=().
operator=() [1/2]
MerkleTree & satox::core::MerkleTree::operator= (const MerkleTree &) delete
References MerkleTree().
operator=() [2/2]
MerkleTree & satox::core::MerkleTree::operator= (MerkleTree &&) default noexcept
References buildTree(), getProof(), getRoot(), MerkleTree(), and verifyProof().
verifyProof()
bool satox::core::MerkleTree::verifyProof (const std::string & transaction, const std::string & root, const std::vector< std::string > & proof) const
Definition at line 90 of file merkle_tree.cpp.
Referenced by operator=().
The documentation for this class was generated from the following files:
src/core/include/satox/core/merkle_tree.h
src/core/src/merkle_tree.cpp