SATOX SDK: satox::core::BlockchainManager Class Reference
satox::core::BlockchainManager Class Reference
#include <blockchain.h>
Classes
struct Block
struct BlockchainInfo
struct Config
struct Stats
struct Transaction
Public Types
enum class BlockchainState {
UNINITIALIZED , INITIALIZING , INITIALIZED , CONNECTING ,
CONNECTED , DISCONNECTED , SYNCING , SYNCED ,
ERROR , SHUTDOWN
}
using TransactionCallback = std::function<void(const Transaction&)>
using BlockCallback = std::function<void(const Block&)>
using StateCallback = std::function<void(BlockchainState)>
using ErrorCallback = std::function<void(const std::string&)>
Public Member Functions
BlockchainManager ()
~BlockchainManager ()
BlockchainManager (const BlockchainManager &)=delete
BlockchainManager & operator= (const BlockchainManager &)=delete
BlockchainManager (BlockchainManager &&) noexcept=default
BlockchainManager & operator= (BlockchainManager &&) noexcept=default
bool initialize (const std::string &network="mainnet")
void cleanup ()
bool isChainValid () const
bool validateBlock (const Block &block) const
bool validateChain () const
void updateChainState (const Block &block)
std::vector< Block > getBlockRange (uint64_t startHeight, uint64_t endHeight) const
ChainState getChainState () const
void loadChainState ()
std::string getStateDirectory () const
std::string getLatestBlock ()
std::string getBlockByHash (const std::string &hash)
std::string getTransactionByHash (const std::string &hash)
std::string getBalance (const std::string &address)
std::string sendTransaction (const std::string &transaction)
void connectToNetwork (const std::string &nodeAddress, uint16_t port)
void disconnectFromNetwork ()
bool isConnected () const
void startSync ()
void stopSync ()
bool isSyncing () const
void setSyncCallback (std::function< void(const Block &)> callback)
std::vector< std::string > getPeers () const
bool validateTransaction (const std::string &transaction) const
BlockchainManager ()
~BlockchainManager ()
bool initialize (const nlohmann::json &config=nlohmann::json::object())
bool shutdown ()
std::string getLastError () const
void clearLastError ()
bool updateConfig (const Config &config)
bool connect ()
bool disconnect ()
bool isConnected () const
std::optional< std::string > getBlockHash (uint64_t height)
std::optional< uint64_t > getBlockHeight (const std::string &hash)
std::optional< nlohmann::json > getBlock (const std::string &hash)
std::optional< nlohmann::json > getBlockByHeight (uint64_t height)
uint64_t getBestBlockHeight () const
std::string getBestBlockHash () const
bool getBlockByHeight (uint64_t height, Block &block) const
std::vector< Block > getBlocks (uint64_t startHeight, uint64_t endHeight) const
std::optional< nlohmann::json > getTransaction (const std::string &txid)
std::optional< std::string > sendTransaction (const std::string &hex)
std::optional< std::string > createTransaction (const std::vector< Input > &inputs, const std::vector< Output > &outputs)
bool validateTransaction (const std::string &hex)
bool getTransaction (const std::string &txid, Transaction &transaction) const
std::vector< Transaction > getTransactions (uint64_t startHeight, uint64_t endHeight) const
size_t getConnectionCount () const
std::vector< nlohmann::json > getPeerInfo () const
bool addNode (const std::string &address, bool add_to_banlist=false)
bool removeNode (const std::string &address)
bool startMining ()
bool stopMining ()
bool isMining () const
std::optional< std::string > getMiningInfo ()
void registerTransactionCallback (TransactionCallback callback)
void registerBlockCallback (BlockCallback callback)
void registerStateCallback (StateCallback callback)
void registerErrorCallback (ErrorCallback callback)
void unregisterBlockCallback ()
void unregisterTransactionCallback ()
void unregisterStateCallback ()
void unregisterErrorCallback ()
Stats getStats () const
bool enableStats (bool enable)
bool isHealthy () const
BlockchainState getState () const
BlockchainInfo getInfo () const
void resetStats ()
uint64_t getCurrentHeight () const
uint64_t getCurrentHeightInternal () const
uint64_t getDifficulty () const
uint64_t getNetworkHashRate () const
Static Public Member Functions
static BlockchainManager & getInstance ()
Detailed Description
Definition at line 60 of file blockchain.h.
Member Typedef Documentation
BlockCallback
using satox::core::BlockchainManager::BlockCallback = std::function<void(const Block&)>
Definition at line 67 of file blockchain_manager.hpp.
ErrorCallback
using satox::core::BlockchainManager::ErrorCallback = std::function<void(const std::string&)>
Definition at line 69 of file blockchain_manager.hpp.
StateCallback
using satox::core::BlockchainManager::StateCallback = std::function<void(BlockchainState)>
Definition at line 68 of file blockchain_manager.hpp.
TransactionCallback
using satox::core::BlockchainManager::TransactionCallback = std::function<void(const Transaction&)>
Definition at line 66 of file blockchain_manager.hpp.
Member Enumeration Documentation
BlockchainState
enum class satox::core::BlockchainManager::BlockchainState strong
Enumerator
UNINITIALIZED
INITIALIZING
INITIALIZED
CONNECTING
CONNECTED
DISCONNECTED
SYNCING
SYNCED
ERROR
SHUTDOWN
Definition at line 25 of file blockchain_manager.hpp.
Constructor & Destructor Documentation
BlockchainManager() [1/4]
satox::core::BlockchainManager::BlockchainManager ()
Definition at line 45 of file blockchain.cpp.
Referenced by BlockchainManager(), BlockchainManager(), getInstance(), operator=(), operator=(), and ~BlockchainManager().
~BlockchainManager() [1/2]
satox::core::BlockchainManager::~BlockchainManager ()
Definition at line 51 of file blockchain.cpp.
References cleanup().
BlockchainManager() [2/4]
satox::core::BlockchainManager::BlockchainManager (const BlockchainManager &) delete
References BlockchainManager().
BlockchainManager() [3/4]
satox::core::BlockchainManager::BlockchainManager (BlockchainManager &&) default noexcept
References BlockchainManager().
BlockchainManager() [4/4]
satox::core::BlockchainManager::BlockchainManager ()
~BlockchainManager() [2/2]
satox::core::BlockchainManager::~BlockchainManager ()
References BlockchainManager().
Member Function Documentation
addNode()
bool satox::core::BlockchainManager::addNode (const std::string & address, bool add_to_banlist = false)
cleanup()
void satox::core::BlockchainManager::cleanup ()
Definition at line 268 of file blockchain.cpp.
Referenced by operator=(), and ~BlockchainManager().
clearLastError()
void satox::core::BlockchainManager::clearLastError ()
Definition at line 495 of file blockchain_manager.cpp.
References clearLastError().
Referenced by clearLastError().
connect()
bool satox::core::BlockchainManager::connect ()
Definition at line 122 of file blockchain_manager.cpp.
References connect(), CONNECTED, and CONNECTING.
Referenced by connect().
connectToNetwork()
void satox::core::BlockchainManager::connectToNetwork (const std::string & nodeAddress, uint16_t port)
Definition at line 75 of file blockchain.cpp.
Referenced by operator=().
createTransaction()
std::optional< std::string > satox::core::BlockchainManager::createTransaction (const std::vector< Input > & inputs, const std::vector< Output > & outputs)
disconnect()
bool satox::core::BlockchainManager::disconnect ()
Definition at line 141 of file blockchain_manager.cpp.
References disconnect(), and DISCONNECTED.
Referenced by disconnect().
disconnectFromNetwork()
void satox::core::BlockchainManager::disconnectFromNetwork ()
Definition at line 79 of file blockchain.cpp.
Referenced by operator=().
enableStats()
bool satox::core::BlockchainManager::enableStats (bool enable)
Definition at line 444 of file blockchain_manager.cpp.
References enableStats().
Referenced by enableStats().
getBalance()
std::string satox::core::BlockchainManager::getBalance (const std::string & address)
Definition at line 258 of file blockchain.cpp.
Referenced by operator=().
getBestBlockHash()
std::string satox::core::BlockchainManager::getBestBlockHash () const
Definition at line 337 of file blockchain_manager.cpp.
References getBestBlockHash().
Referenced by getBestBlockHash().
getBestBlockHeight()
uint64_t satox::core::BlockchainManager::getBestBlockHeight () const
getBlock()
std::optional< nlohmann::json > satox::core::BlockchainManager::getBlock (const std::string & hash)
getBlockByHash()
std::string satox::core::BlockchainManager::getBlockByHash (const std::string & hash)
Definition at line 248 of file blockchain.cpp.
Referenced by operator=().
getBlockByHeight() [1/2]
std::optional< nlohmann::json > satox::core::BlockchainManager::getBlockByHeight (uint64_t height)
Referenced by getBlockByHeight().
getBlockByHeight() [2/2]
bool satox::core::BlockchainManager::getBlockByHeight (uint64_t height, BlockchainManager::Block & block) const
Definition at line 180 of file blockchain_manager.cpp.
References getBlockByHeight().
getBlockHash()
std::optional< std::string > satox::core::BlockchainManager::getBlockHash (uint64_t height)
getBlockHeight()
std::optional< uint64_t > satox::core::BlockchainManager::getBlockHeight (const std::string & hash)
getBlockRange()
std::vector< Block > satox::core::BlockchainManager::getBlockRange (uint64_t startHeight, uint64_t endHeight) const
Definition at line 200 of file blockchain.cpp.
Referenced by operator=().
getBlocks()
std::vector< BlockchainManager::Block > satox::core::BlockchainManager::getBlocks (uint64_t startHeight, uint64_t endHeight) const
Definition at line 209 of file blockchain_manager.cpp.
References getBlocks().
Referenced by getBlocks().
getChainState()
ChainState satox::core::BlockchainManager::getChainState () const
Definition at line 170 of file blockchain.cpp.
Referenced by operator=().
getConnectionCount()
size_t satox::core::BlockchainManager::getConnectionCount () const
getCurrentHeight()
uint64_t satox::core::BlockchainManager::getCurrentHeight () const
Definition at line 320 of file blockchain_manager.cpp.
References getCurrentHeight(), and getCurrentHeightInternal().
Referenced by getCurrentHeight(), and getDifficulty().
getCurrentHeightInternal()
uint64_t satox::core::BlockchainManager::getCurrentHeightInternal () const
Definition at line 325 of file blockchain_manager.cpp.
References getCurrentHeightInternal().
Referenced by getCurrentHeight(), and getCurrentHeightInternal().
getDifficulty()
uint64_t satox::core::BlockchainManager::getDifficulty () const
Definition at line 352 of file blockchain_manager.cpp.
References getCurrentHeight(), and getDifficulty().
Referenced by getDifficulty(), and getNetworkHashRate().
getInfo()
BlockchainManager::BlockchainInfo satox::core::BlockchainManager::getInfo () const
Definition at line 283 of file blockchain_manager.cpp.
References satox::core::BlockchainManager::BlockchainInfo::additionalInfo, satox::core::BlockchainManager::BlockchainInfo::bestBlockHash, satox::core::BlockchainManager::BlockchainInfo::difficulty, getInfo(), satox::core::BlockchainManager::BlockchainInfo::height, satox::core::BlockchainManager::BlockchainInfo::lastBlockTime, satox::core::BlockchainManager::BlockchainInfo::mempoolSize, satox::core::BlockchainManager::BlockchainInfo::mempoolTransactions, satox::core::BlockchainManager::BlockchainInfo::network, and satox::core::BlockchainManager::BlockchainInfo::networkHashrate.
Referenced by getInfo().
getInstance()
BlockchainManager & satox::core::BlockchainManager::getInstance () static
Definition at line 50 of file blockchain_manager.cpp.
References BlockchainManager(), and getInstance().
Referenced by satox::core::CoreManager::getBlockchainManager(), satox::core::SatoxManager::getBlockchainManager(), and getInstance().
getLastError()
std::string satox::core::BlockchainManager::getLastError () const
Definition at line 490 of file blockchain_manager.cpp.
References getLastError().
Referenced by getLastError().
getLatestBlock()
std::string satox::core::BlockchainManager::getLatestBlock ()
Definition at line 243 of file blockchain.cpp.
Referenced by operator=().
getMiningInfo()
std::optional< std::string > satox::core::BlockchainManager::getMiningInfo ()
getNetworkHashRate()
uint64_t satox::core::BlockchainManager::getNetworkHashRate () const
Definition at line 418 of file blockchain_manager.cpp.
References getDifficulty(), and getNetworkHashRate().
Referenced by getNetworkHashRate().
getPeerInfo()
std::vector< nlohmann::json > satox::core::BlockchainManager::getPeerInfo () const
getPeers()
std::vector< std::string > satox::core::BlockchainManager::getPeers () const
Definition at line 137 of file blockchain.cpp.
Referenced by operator=().
getState()
BlockchainManager::BlockchainState satox::core::BlockchainManager::getState () const
Definition at line 163 of file blockchain_manager.cpp.
References getState().
Referenced by getState().
getStateDirectory()
std::string satox::core::BlockchainManager::getStateDirectory () const
Definition at line 209 of file blockchain.cpp.
Referenced by initialize(), and operator=().
getStats()
BlockchainManager::Stats satox::core::BlockchainManager::getStats () const
Definition at line 434 of file blockchain_manager.cpp.
References getStats().
Referenced by getStats().
getTransaction() [1/2]
std::optional< nlohmann::json > satox::core::BlockchainManager::getTransaction (const std::string & txid)
getTransaction() [2/2]
bool satox::core::BlockchainManager::getTransaction (const std::string & txid, Transaction & transaction) const
getTransactionByHash()
std::string satox::core::BlockchainManager::getTransactionByHash (const std::string & hash)
Definition at line 253 of file blockchain.cpp.
Referenced by operator=().
getTransactions()
std::vector< Transaction > satox::core::BlockchainManager::getTransactions (uint64_t startHeight, uint64_t endHeight) const
initialize() [1/2]
bool satox::core::BlockchainManager::initialize (const nlohmann::json & config = nlohmann::json::object())
Definition at line 55 of file blockchain_manager.cpp.
References satox::core::LoggingManager::LogConfig::asyncLogging, satox::core::LoggingManager::LogConfig::consoleOutput, satox::core::LoggingManager::DEBUG, satox::core::LoggingManager::LogConfig::fileOutput, satox::core::LoggingManager::LogConfig::flushInterval, satox::core::LoggingManager::LogConfig::includeSource, satox::core::LoggingManager::LogConfig::includeThreadId, satox::core::LoggingManager::LogConfig::includeTimestamp, initialize(), satox::core::LoggingManager::LogConfig::logDir, satox::core::LoggingManager::LogConfig::logFile, satox::core::LoggingManager::LogConfig::logFormat, satox::core::LoggingManager::LogConfig::maxFiles, satox::core::LoggingManager::LogConfig::maxFileSize, satox::core::LoggingManager::LogConfig::minLevel, and satox::core::LoggingManager::LogConfig::queueSize.
initialize() [2/2]
bool satox::core::BlockchainManager::initialize (const std::string & network = "mainnet")
Definition at line 55 of file blockchain.cpp.
References getStateDirectory().
Referenced by initialize(), and operator=().
isChainValid()
bool satox::core::BlockchainManager::isChainValid () const
Definition at line 165 of file blockchain.cpp.
References validateChain().
Referenced by operator=().
isConnected() [1/2]
bool satox::core::BlockchainManager::isConnected () const
Definition at line 83 of file blockchain.cpp.
Referenced by operator=().
isConnected() [2/2]
bool satox::core::BlockchainManager::isConnected () const
isHealthy()
bool satox::core::BlockchainManager::isHealthy () const
isMining()
bool satox::core::BlockchainManager::isMining () const
isSyncing()
bool satox::core::BlockchainManager::isSyncing () const
Definition at line 96 of file blockchain.cpp.
Referenced by operator=().
loadChainState()
void satox::core::BlockchainManager::loadChainState ()
Definition at line 183 of file blockchain.cpp.
Referenced by operator=().
operator=() [1/2]
BlockchainManager & satox::core::BlockchainManager::operator= (BlockchainManager &&) default noexcept
References BlockchainManager(), cleanup(), connectToNetwork(), disconnectFromNetwork(), getBalance(), getBlockByHash(), getBlockRange(), getChainState(), getLatestBlock(), getPeers(), getStateDirectory(), getTransactionByHash(), initialize(), isChainValid(), isConnected(), isSyncing(), loadChainState(), sendTransaction(), setSyncCallback(), startSync(), stopSync(), updateChainState(), validateBlock(), validateChain(), and validateTransaction().
operator=() [2/2]
BlockchainManager & satox::core::BlockchainManager::operator= (const BlockchainManager &) delete
References BlockchainManager().
registerBlockCallback()
void satox::core::BlockchainManager::registerBlockCallback (BlockCallback callback)
Definition at line 450 of file blockchain_manager.cpp.
References registerBlockCallback().
Referenced by registerBlockCallback().
registerErrorCallback()
void satox::core::BlockchainManager::registerErrorCallback (ErrorCallback callback)
Definition at line 465 of file blockchain_manager.cpp.
References registerErrorCallback().
Referenced by registerErrorCallback().
registerStateCallback()
void satox::core::BlockchainManager::registerStateCallback (StateCallback callback)
Definition at line 460 of file blockchain_manager.cpp.
References registerStateCallback().
Referenced by registerStateCallback().
registerTransactionCallback()
void satox::core::BlockchainManager::registerTransactionCallback (TransactionCallback callback)
Definition at line 455 of file blockchain_manager.cpp.
References registerTransactionCallback().
Referenced by registerTransactionCallback().
removeNode()
bool satox::core::BlockchainManager::removeNode (const std::string & address)
resetStats()
void satox::core::BlockchainManager::resetStats ()
Definition at line 439 of file blockchain_manager.cpp.
References resetStats().
Referenced by resetStats().
sendTransaction() [1/2]
std::optional< std::string > satox::core::BlockchainManager::sendTransaction (const std::string & hex)
sendTransaction() [2/2]
std::string satox::core::BlockchainManager::sendTransaction (const std::string & transaction)
Definition at line 263 of file blockchain.cpp.
Referenced by operator=().
setSyncCallback()
void satox::core::BlockchainManager::setSyncCallback (std::function< void(const Block &)> callback)
Definition at line 101 of file blockchain.cpp.
Referenced by operator=().
shutdown()
bool satox::core::BlockchainManager::shutdown ()
Definition at line 98 of file blockchain_manager.cpp.
References DISCONNECTED, and shutdown().
Referenced by shutdown().
startMining()
bool satox::core::BlockchainManager::startMining ()
startSync()
void satox::core::BlockchainManager::startSync ()
Definition at line 88 of file blockchain.cpp.
Referenced by operator=().
stopMining()
bool satox::core::BlockchainManager::stopMining ()
stopSync()
void satox::core::BlockchainManager::stopSync ()
Definition at line 92 of file blockchain.cpp.
Referenced by operator=().
unregisterBlockCallback()
void satox::core::BlockchainManager::unregisterBlockCallback ()
Definition at line 470 of file blockchain_manager.cpp.
References unregisterBlockCallback().
Referenced by unregisterBlockCallback().
unregisterErrorCallback()
void satox::core::BlockchainManager::unregisterErrorCallback ()
Definition at line 485 of file blockchain_manager.cpp.
References unregisterErrorCallback().
Referenced by unregisterErrorCallback().
unregisterStateCallback()
void satox::core::BlockchainManager::unregisterStateCallback ()
Definition at line 480 of file blockchain_manager.cpp.
References unregisterStateCallback().
Referenced by unregisterStateCallback().
unregisterTransactionCallback()
void satox::core::BlockchainManager::unregisterTransactionCallback ()
Definition at line 475 of file blockchain_manager.cpp.
References unregisterTransactionCallback().
Referenced by unregisterTransactionCallback().
updateChainState()
void satox::core::BlockchainManager::updateChainState (const Block & block)
Definition at line 175 of file blockchain.cpp.
Referenced by operator=().
updateConfig()
bool satox::core::BlockchainManager::updateConfig (const Config & config)
validateBlock()
bool satox::core::BlockchainManager::validateBlock (const Block & block) const
Definition at line 150 of file blockchain.cpp.
Referenced by operator=().
validateChain()
bool satox::core::BlockchainManager::validateChain () const
Definition at line 160 of file blockchain.cpp.
Referenced by isChainValid(), and operator=().
validateTransaction() [1/2]
bool satox::core::BlockchainManager::validateTransaction (const std::string & hex)
validateTransaction() [2/2]
bool satox::core::BlockchainManager::validateTransaction (const std::string & transaction) const
Definition at line 155 of file blockchain.cpp.
Referenced by operator=().
The documentation for this class was generated from the following files:
src/core/include/satox/core/blockchain.h
src/core/include/satox/core/blockchain_manager.hpp
src/core/src/blockchain.cpp
src/core/src/blockchain_manager.cpp