SATOX SDK: satox::ipfs::ContentStorage Class Reference
satox::ipfs::ContentStorage Class Reference
#include <content_storage.hpp>
Classes
struct ContentInfo
struct Error
Public Member Functions
ContentStorage (const ContentStorage &)=delete
ContentStorage & operator= (const ContentStorage &)=delete
bool initialize (const std::string &storagePath)
void shutdown ()
std::future< ContentInfo > storeContent (const std::string &content, const std::string &name="")
std::future< ContentInfo > storeFile (const std::string &filePath)
std::future< std::vector< ContentInfo > > storeDirectory (const std::string &directoryPath)
std::future< std::string > getContent (const std::string &hash)
std::future< bool > getFile (const std::string &hash, const std::string &outputPath)
std::future< bool > getDirectory (const std::string &hash, const std::string &outputPath)
bool updateContent (const std::string &hash, const std::string &newContent)
bool updateMetadata (const std::string &hash, const nlohmann::json &metadata)
bool deleteContent (const std::string &hash)
bool pinContent (const std::string &hash)
bool unpinContent (const std::string &hash)
ContentInfo getContentInfo (const std::string &hash) const
std::vector< ContentInfo > getContentByTag (const std::string &tag) const
std::vector< ContentInfo > getContentByMimeType (const std::string &mimeType) const
std::vector< ContentInfo > searchContent (const std::string &query) const
std::vector< ContentInfo > getPinnedContent () const
void enableCache (bool enable)
void clearCache ()
void setCacheSize (size_t maxSize)
size_t getCacheSize () const
size_t getCacheUsage () const
bool createBackup (const std::string &backupPath)
bool restoreFromBackup (const std::string &backupPath)
Error getLastError () const
void clearLastError ()
Static Public Member Functions
static ContentStorage & getInstance ()
Detailed Description
Definition at line 41 of file content_storage.hpp.
Constructor & Destructor Documentation
ContentStorage()
satox::ipfs::ContentStorage::ContentStorage (const ContentStorage &) delete
References ContentStorage().
Referenced by ContentStorage(), getInstance(), and operator=().
Member Function Documentation
clearCache()
void satox::ipfs::ContentStorage::clearCache ()
Definition at line 479 of file content_storage.cpp.
Referenced by enableCache(), and setCacheSize().
clearLastError()
void satox::ipfs::ContentStorage::clearLastError ()
Definition at line 579 of file content_storage.cpp.
createBackup()
bool satox::ipfs::ContentStorage::createBackup (const std::string & backupPath)
Definition at line 505 of file content_storage.cpp.
deleteContent()
bool satox::ipfs::ContentStorage::deleteContent (const std::string & hash)
Definition at line 328 of file content_storage.cpp.
enableCache()
void satox::ipfs::ContentStorage::enableCache (bool enable)
Definition at line 471 of file content_storage.cpp.
References clearCache().
getCacheSize()
size_t satox::ipfs::ContentStorage::getCacheSize () const
Definition at line 492 of file content_storage.cpp.
getCacheUsage()
size_t satox::ipfs::ContentStorage::getCacheUsage () const
Definition at line 496 of file content_storage.cpp.
Referenced by setCacheSize().
getContent()
std::future< std::string > satox::ipfs::ContentStorage::getContent (const std::string & hash)
Definition at line 196 of file content_storage.cpp.
Referenced by getDirectory(), and getFile().
getContentByMimeType()
std::vector< ContentStorage::ContentInfo > satox::ipfs::ContentStorage::getContentByMimeType (const std::string & mimeType) const
Definition at line 417 of file content_storage.cpp.
getContentByTag()
std::vector< ContentStorage::ContentInfo > satox::ipfs::ContentStorage::getContentByTag (const std::string & tag) const
Definition at line 402 of file content_storage.cpp.
getContentInfo()
ContentStorage::ContentInfo satox::ipfs::ContentStorage::getContentInfo (const std::string & hash) const
Definition at line 393 of file content_storage.cpp.
getDirectory()
std::future< bool > satox::ipfs::ContentStorage::getDirectory (const std::string & hash, const std::string & outputPath)
Definition at line 245 of file content_storage.cpp.
References getContent(), and getFile().
getFile()
std::future< bool > satox::ipfs::ContentStorage::getFile (const std::string & hash, const std::string & outputPath)
Definition at line 229 of file content_storage.cpp.
References getContent().
Referenced by getDirectory().
getInstance()
ContentStorage & satox::ipfs::ContentStorage::getInstance () static
Definition at line 94 of file content_storage.cpp.
References ContentStorage(), and satox::ipfs::instance.
getLastError()
ContentStorage::Error satox::ipfs::ContentStorage::getLastError () const
Definition at line 575 of file content_storage.cpp.
getPinnedContent()
std::vector< ContentStorage::ContentInfo > satox::ipfs::ContentStorage::getPinnedContent () const
Definition at line 460 of file content_storage.cpp.
initialize()
bool satox::ipfs::ContentStorage::initialize (const std::string & storagePath)
Definition at line 99 of file content_storage.cpp.
operator=()
ContentStorage & satox::ipfs::ContentStorage::operator= (const ContentStorage &) delete
References ContentStorage().
pinContent()
bool satox::ipfs::ContentStorage::pinContent (const std::string & hash)
Definition at line 357 of file content_storage.cpp.
restoreFromBackup()
bool satox::ipfs::ContentStorage::restoreFromBackup (const std::string & backupPath)
Definition at line 538 of file content_storage.cpp.
searchContent()
std::vector< ContentStorage::ContentInfo > satox::ipfs::ContentStorage::searchContent (const std::string & query) const
Definition at line 432 of file content_storage.cpp.
setCacheSize()
void satox::ipfs::ContentStorage::setCacheSize (size_t maxSize)
Definition at line 484 of file content_storage.cpp.
References clearCache(), and getCacheUsage().
shutdown()
void satox::ipfs::ContentStorage::shutdown ()
Definition at line 118 of file content_storage.cpp.
storeContent()
std::future< ContentStorage::ContentInfo > satox::ipfs::ContentStorage::storeContent (const std::string & content, const std::string & name = "")
Definition at line 127 of file content_storage.cpp.
References satox::ipfs::ContentStorage::ContentInfo::createdAt, satox::ipfs::ContentStorage::ContentInfo::hash, satox::ipfs::ContentStorage::ContentInfo::isPinned, satox::ipfs::ContentStorage::ContentInfo::mimeType, satox::ipfs::ContentStorage::ContentInfo::name, satox::ipfs::ContentStorage::ContentInfo::size, and satox::ipfs::ContentStorage::ContentInfo::updatedAt.
Referenced by storeFile().
storeDirectory()
std::future< std::vector< ContentStorage::ContentInfo > > satox::ipfs::ContentStorage::storeDirectory (const std::string & directoryPath)
Definition at line 177 of file content_storage.cpp.
References storeFile().
storeFile()
std::future< ContentStorage::ContentInfo > satox::ipfs::ContentStorage::storeFile (const std::string & filePath)
Definition at line 159 of file content_storage.cpp.
References storeContent().
Referenced by storeDirectory().
unpinContent()
bool satox::ipfs::ContentStorage::unpinContent (const std::string & hash)
Definition at line 375 of file content_storage.cpp.
updateContent()
bool satox::ipfs::ContentStorage::updateContent (const std::string & hash, const std::string & newContent)
Definition at line 274 of file content_storage.cpp.
updateMetadata()
bool satox::ipfs::ContentStorage::updateMetadata (const std::string & hash, const nlohmann::json & metadata)
Definition at line 310 of file content_storage.cpp.
The documentation for this class was generated from the following files:
src/ipfs/include/satox/ipfs/content_storage.hpp
src/ipfs/src/content_storage.cpp