SATOX SDK: satox::nft::NftException Class Reference
satox::nft::NftException Class Reference
#include <error.hpp>
Public Member Functions
NftException (NftErrorCode code, const std::string &message="")
const char * what () const noexcept override
NftErrorCode code () const
const std::string & message () const
Detailed Description
Definition at line 52 of file error.hpp.
Constructor & Destructor Documentation
NftException()
satox::nft::NftException::NftException (NftErrorCode code, const std::string & message = "") inline
Definition at line 54 of file error.hpp.
References code(), and message().
Referenced by satox::nft::NftInitializationException::NftInitializationException(), and satox::nft::NftOperationException::NftOperationException().
Member Function Documentation
code()
NftErrorCode satox::nft::NftException::code () const inline
Definition at line 61 of file error.hpp.
Referenced by NftException().
message()
const std::string & satox::nft::NftException::message () const inline
Definition at line 65 of file error.hpp.
Referenced by NftException(), satox::nft::NftInitializationException::NftInitializationException(), and satox::nft::NftOperationException::NftOperationException().
what()
const char * satox::nft::NftException::what () const inline override noexcept
Definition at line 57 of file error.hpp.
The documentation for this class was generated from the following file:
src/nft/include/satox/nft/error.hpp