SATOX SDK: satox::wallet::KeyManager Class Reference
satox::wallet::KeyManager Class Reference
#include <key_manager.hpp>
Classes
struct KeyPair
Public Member Functions
KeyManager ()
~KeyManager ()
bool initialize ()
void cleanup ()
bool generateKeyPair (KeyPair &keyPair)
bool deriveKeyPairFromSeed (const std::vector< uint8_t > &seed, KeyPair &keyPair)
bool deriveKeyPairFromPrivateKey (const std::vector< uint8_t > &privateKey, KeyPair &keyPair)
bool deriveChildKeyPair (const KeyPair &parent, uint32_t index, KeyPair &child)
bool validatePrivateKey (const std::vector< uint8_t > &privateKey) const
bool validatePublicKey (const std::vector< uint8_t > &publicKey) const
bool validateKeyPair (const KeyPair &keyPair) const
bool privateKeyToPublicKey (const std::vector< uint8_t > &privateKey, std::vector< uint8_t > &publicKey) const
bool publicKeyToAddress (const std::vector< uint8_t > &publicKey, std::string &address) const
bool encryptPrivateKey (const std::vector< uint8_t > &privateKey, const std::string &password, std::vector< uint8_t > &encrypted) const
bool decryptPrivateKey (const std::vector< uint8_t > &encrypted, const std::string &password, std::vector< uint8_t > &privateKey) const
std::string getLastError () const
void clearLastError ()
Detailed Description
Definition at line 39 of file key_manager.hpp.
Constructor & Destructor Documentation
KeyManager()
satox::wallet::KeyManager::KeyManager ()
Definition at line 40 of file key_manager.cpp.
~KeyManager()
satox::wallet::KeyManager::~KeyManager ()
Definition at line 42 of file key_manager.cpp.
References cleanup().
Member Function Documentation
cleanup()
void satox::wallet::KeyManager::cleanup ()
Definition at line 60 of file key_manager.cpp.
Referenced by ~KeyManager().
clearLastError()
void satox::wallet::KeyManager::clearLastError ()
Definition at line 481 of file key_manager.cpp.
decryptPrivateKey()
bool satox::wallet::KeyManager::decryptPrivateKey (const std::vector< uint8_t > & encrypted, const std::string & password, std::vector< uint8_t > & privateKey) const
Definition at line 389 of file key_manager.cpp.
References validatePrivateKey().
deriveChildKeyPair()
bool satox::wallet::KeyManager::deriveChildKeyPair (const KeyPair & parent, uint32_t index, KeyPair & child)
Definition at line 131 of file key_manager.cpp.
References satox::wallet::KeyManager::KeyPair::address, satox::wallet::KeyManager::KeyPair::chainCode, satox::wallet::KeyManager::KeyPair::privateKey, privateKeyToPublicKey(), and satox::wallet::KeyManager::KeyPair::publicKey.
deriveKeyPairFromPrivateKey()
bool satox::wallet::KeyManager::deriveKeyPairFromPrivateKey (const std::vector< uint8_t > & privateKey, KeyPair & keyPair)
Definition at line 111 of file key_manager.cpp.
References satox::wallet::KeyManager::KeyPair::address, satox::wallet::KeyManager::KeyPair::privateKey, privateKeyToPublicKey(), satox::wallet::KeyManager::KeyPair::publicKey, and validatePrivateKey().
deriveKeyPairFromSeed()
bool satox::wallet::KeyManager::deriveKeyPairFromSeed (const std::vector< uint8_t > & seed, KeyPair & keyPair)
Definition at line 94 of file key_manager.cpp.
References satox::wallet::KeyManager::KeyPair::address, satox::wallet::KeyManager::KeyPair::privateKey, privateKeyToPublicKey(), and satox::wallet::KeyManager::KeyPair::publicKey.
encryptPrivateKey()
bool satox::wallet::KeyManager::encryptPrivateKey (const std::vector< uint8_t > & privateKey, const std::string & password, std::vector< uint8_t > & encrypted) const
Definition at line 322 of file key_manager.cpp.
References validatePrivateKey().
generateKeyPair()
bool satox::wallet::KeyManager::generateKeyPair (KeyPair & keyPair)
Definition at line 70 of file key_manager.cpp.
References satox::wallet::KeyManager::KeyPair::address, satox::wallet::KeyManager::KeyPair::privateKey, privateKeyToPublicKey(), and satox::wallet::KeyManager::KeyPair::publicKey.
getLastError()
std::string satox::wallet::KeyManager::getLastError () const
Definition at line 476 of file key_manager.cpp.
initialize()
bool satox::wallet::KeyManager::initialize ()
Definition at line 46 of file key_manager.cpp.
privateKeyToPublicKey()
bool satox::wallet::KeyManager::privateKeyToPublicKey (const std::vector< uint8_t > & privateKey, std::vector< uint8_t > & publicKey) const
Definition at line 261 of file key_manager.cpp.
References validatePrivateKey().
Referenced by deriveChildKeyPair(), deriveKeyPairFromPrivateKey(), deriveKeyPairFromSeed(), and generateKeyPair().
publicKeyToAddress()
bool satox::wallet::KeyManager::publicKeyToAddress (const std::vector< uint8_t > & publicKey, std::string & address) const
Definition at line 284 of file key_manager.cpp.
References validatePublicKey().
validateKeyPair()
bool satox::wallet::KeyManager::validateKeyPair (const KeyPair & keyPair) const
Definition at line 255 of file key_manager.cpp.
References satox::wallet::KeyManager::KeyPair::address, satox::wallet::KeyManager::KeyPair::privateKey, satox::wallet::KeyManager::KeyPair::publicKey, validatePrivateKey(), and validatePublicKey().
validatePrivateKey()
bool satox::wallet::KeyManager::validatePrivateKey (const std::vector< uint8_t > & privateKey) const
Definition at line 229 of file key_manager.cpp.
Referenced by decryptPrivateKey(), deriveKeyPairFromPrivateKey(), encryptPrivateKey(), privateKeyToPublicKey(), and validateKeyPair().
validatePublicKey()
bool satox::wallet::KeyManager::validatePublicKey (const std::vector< uint8_t > & publicKey) const
Definition at line 245 of file key_manager.cpp.
Referenced by publicKeyToAddress(), and validateKeyPair().
The documentation for this class was generated from the following files:
src/wallet/include/satox/wallet/key_manager.hpp
src/key_manager.cpp
src/wallet/src/key_manager.cpp