SATOX SDK: src/asset/src/asset_manager_pybind.cpp File Reference
asset_manager_pybind.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/chrono.h>
#include <nlohmann/json.hpp>
#include "satox/asset/asset_manager.hpp"
Functions
AssetManager::AssetMetadata dict_to_metadata (const py::dict &d)
py::dict metadata_to_dict (const AssetManager::AssetMetadata &m)
PYBIND11_MODULE (satox_asset, m)
Function Documentation
dict_to_metadata()
AssetManager::AssetMetadata dict_to_metadata (const py::dict & d)
Definition at line 36 of file asset_manager_pybind.cpp.
Referenced by PYBIND11_MODULE().
metadata_to_dict()
py::dict metadata_to_dict (const AssetManager::AssetMetadata & m)
Definition at line 50 of file asset_manager_pybind.cpp.
Referenced by PYBIND11_MODULE().
PYBIND11_MODULE()
PYBIND11_MODULE (satox_asset , m)
Definition at line 63 of file asset_manager_pybind.cpp.
References satox::asset::AssetManager::createAsset(), dict_to_metadata(), satox::asset::AssetManager::getAssetMetadata(), satox::asset::AssetManager::getInstance(), satox::asset::AssetManager::getLastError(), satox::asset::AssetManager::initialize(), satox::asset::AssetManager::isInitialized(), and metadata_to_dict().