SATOX SDK: satox::core::CoreManager Class Reference
satox::core::CoreManager Class Reference
#include <core_manager.hpp>
Public Member Functions
CoreManager ()
~CoreManager ()
CoreManager (const CoreManager &)=delete
CoreManager & operator= (const CoreManager &)=delete
bool initialize (const CoreConfig &config)
void shutdown ()
bool isRunning () const
bool isInitialized () const
std::string getLastError () const
NetworkManager & getNetworkManager () const
AssetManager & getAssetManager () const
IPFSManager & getIPFSManager () const
WalletManager & getWalletManager () const
BlockchainManager & getBlockchainManager () const
bool start ()
bool stop ()
bool restartComponent (const std::string &component)
bool updateComponent (const std::string &component, const std::unordered_map< std::string, std::string > &config)
std::optional< ComponentStatus > getComponentStatus (const std::string &component) const
bool updateConfig (const CoreConfig &config)
std::optional< CoreConfig > getConfig () const
bool validateConfig (const CoreConfig &config) const
bool backupConfig (const std::string &backup_path) const
bool restoreConfig (const std::string &backup_path)
std::optional< SystemInfo > getSystemInfo () const
CoreStats getStats () const
bool isHealthy () const
void registerErrorCallback (ErrorCallback callback)
void registerStatusCallback (StatusCallback callback)
void registerShutdownCallback (ShutdownCallback callback)
Static Public Member Functions
static CoreManager & getInstance ()
Detailed Description
Definition at line 116 of file core_manager.hpp.
Constructor & Destructor Documentation
CoreManager() [1/2]
satox::core::CoreManager::CoreManager ()
Definition at line 71 of file core_manager.cpp.
Referenced by CoreManager(), getInstance(), and operator=().
~CoreManager()
satox::core::CoreManager::~CoreManager ()
Definition at line 79 of file core_manager.cpp.
References shutdown().
CoreManager() [2/2]
satox::core::CoreManager::CoreManager (const CoreManager &) delete
References CoreManager().
Member Function Documentation
backupConfig()
bool satox::core::CoreManager::backupConfig (const std::string & backup_path) const
Definition at line 442 of file core_manager.cpp.
getAssetManager()
AssetManager & satox::core::CoreManager::getAssetManager () const
Definition at line 202 of file core_manager.cpp.
References satox::core::AssetManager::getInstance().
Referenced by restartComponent().
getBlockchainManager()
BlockchainManager & satox::core::CoreManager::getBlockchainManager () const
Definition at line 217 of file core_manager.cpp.
References satox::core::BlockchainManager::getInstance().
Referenced by restartComponent().
getComponentStatus()
std::optional< ComponentStatus > satox::core::CoreManager::getComponentStatus (const std::string & component) const
Definition at line 271 of file core_manager.cpp.
getConfig()
std::optional< CoreConfig > satox::core::CoreManager::getConfig () const
Definition at line 424 of file core_manager.cpp.
getInstance()
CoreManager & satox::core::CoreManager::getInstance () static
Definition at line 66 of file core_manager.cpp.
References CoreManager().
Referenced by satox::core::SatoxManager::getCoreManager().
getIPFSManager()
IPFSManager & satox::core::CoreManager::getIPFSManager () const
Definition at line 207 of file core_manager.cpp.
References satox::core::IPFSManager::getInstance().
Referenced by restartComponent().
getLastError()
std::string satox::core::CoreManager::getLastError () const
Definition at line 192 of file core_manager.cpp.
getNetworkManager()
NetworkManager & satox::core::CoreManager::getNetworkManager () const
Definition at line 197 of file core_manager.cpp.
References satox::core::NetworkManager::getInstance().
Referenced by restartComponent().
getStats()
CoreStats satox::core::CoreManager::getStats () const
Definition at line 169 of file core_manager.cpp.
References satox::core::CoreStats::last_activity.
getSystemInfo()
std::optional< SystemInfo > satox::core::CoreManager::getSystemInfo () const
Definition at line 252 of file core_manager.cpp.
References satox::core::SystemInfo::metadata, satox::core::SystemInfo::network, satox::core::SystemInfo::start_time, satox::core::SystemInfo::uptime, and satox::core::SystemInfo::version.
getWalletManager()
WalletManager & satox::core::CoreManager::getWalletManager () const
Definition at line 212 of file core_manager.cpp.
References satox::core::WalletManager::getInstance().
Referenced by restartComponent().
initialize()
bool satox::core::CoreManager::initialize (const CoreConfig & config)
Definition at line 83 of file core_manager.cpp.
References validateConfig().
isHealthy()
bool satox::core::CoreManager::isHealthy () const
Definition at line 176 of file core_manager.cpp.
References satox::core::ERROR.
isInitialized()
bool satox::core::CoreManager::isInitialized () const
Definition at line 164 of file core_manager.cpp.
isRunning()
bool satox::core::CoreManager::isRunning () const
Definition at line 159 of file core_manager.cpp.
operator=()
CoreManager & satox::core::CoreManager::operator= (const CoreManager &) delete
References CoreManager(), and running.
registerErrorCallback()
void satox::core::CoreManager::registerErrorCallback (ErrorCallback callback)
Definition at line 545 of file core_manager.cpp.
registerShutdownCallback()
void satox::core::CoreManager::registerShutdownCallback (ShutdownCallback callback)
Definition at line 555 of file core_manager.cpp.
registerStatusCallback()
void satox::core::CoreManager::registerStatusCallback (StatusCallback callback)
Definition at line 550 of file core_manager.cpp.
restartComponent()
bool satox::core::CoreManager::restartComponent (const std::string & component)
Definition at line 280 of file core_manager.cpp.
References satox::core::ERROR, satox::core::ComponentStatus::error_count, getAssetManager(), getBlockchainManager(), getIPFSManager(), getNetworkManager(), getWalletManager(), satox::core::ComponentStatus::last_update, satox::core::ComponentStatus::name, satox::core::RESTARTING, satox::core::RUNNING, and satox::core::ComponentStatus::state.
restoreConfig()
bool satox::core::CoreManager::restoreConfig (const std::string & backup_path)
Definition at line 484 of file core_manager.cpp.
References satox::core::CoreConfig::data_dir, satox::core::CoreConfig::enable_mining, satox::core::CoreConfig::enable_sync, satox::core::CoreConfig::mining_threads, satox::core::CoreConfig::network, satox::core::CoreConfig::rpc_endpoint, satox::core::CoreConfig::rpc_password, satox::core::CoreConfig::rpc_username, satox::core::CoreConfig::sync_interval_ms, satox::core::CoreConfig::timeout_ms, and validateConfig().
shutdown()
void satox::core::CoreManager::shutdown ()
Definition at line 116 of file core_manager.cpp.
Referenced by ~CoreManager().
start()
bool satox::core::CoreManager::start ()
Definition at line 222 of file core_manager.cpp.
stop()
bool satox::core::CoreManager::stop ()
Definition at line 239 of file core_manager.cpp.
updateComponent()
bool satox::core::CoreManager::updateComponent (const std::string & component, const std::unordered_map< std::string, std::string > & config)
Definition at line 347 of file core_manager.cpp.
References satox::core::ComponentStatus::last_update, satox::core::ComponentStatus::name, satox::core::RUNNING, and satox::core::ComponentStatus::state.
updateConfig()
bool satox::core::CoreManager::updateConfig (const CoreConfig & config)
Definition at line 407 of file core_manager.cpp.
References validateConfig().
validateConfig()
bool satox::core::CoreManager::validateConfig (const CoreConfig & config) const
Definition at line 432 of file core_manager.cpp.
References satox::core::CoreConfig::data_dir, satox::core::CoreConfig::mining_threads, satox::core::CoreConfig::network, satox::core::CoreConfig::sync_interval_ms, and satox::core::CoreConfig::timeout_ms.
Referenced by initialize(), restoreConfig(), and updateConfig().
The documentation for this class was generated from the following files:
src/core/include/satox/core/core_manager.hpp
src/core/src/core_manager.cpp