SATOX SDK: satox::ipfs::IPFSManager Class Reference
satox::ipfs::IPFSManager Class Reference
#include <ipfs_manager.hpp>
Classes
struct IPFSStatistics
Public Types
using ContentCallback = std::function<void(const std::string&, const IPFSContent&)>
using ErrorCallback = std::function<void(const std::string&)>
using ProgressCallback = std::function<void(const std::string&, uint32_t)>
Public Member Functions
IPFSManager ()
~IPFSManager ()
bool initialize (const IPFSConfig &config)
void shutdown ()
std::string getLastError () const
std::string addContent (const std::vector< uint8_t > &data, const std::string &content_type, const std::unordered_map< std::string, std::string > &metadata={})
bool removeContent (const std::string &cid)
std::optional< IPFSContent > getContent (const std::string &cid)
std::vector< std::string > listContent () const
bool pinContent (const std::string &cid)
bool unpinContent (const std::string &cid)
bool isContentPinned (const std::string &cid) const
std::vector< std::string > listPinnedContent () const
std::string getGatewayUrl (const std::string &cid) const
bool isGatewayEnabled () const
bool batchAddContent (const std::vector< std::pair< std::vector< uint8_t >, std::string > > &contents)
bool batchPinContent (const std::vector< std::string > &cids)
bool batchUnpinContent (const std::vector< std::string > &cids)
bool updateMetadata (const std::string &cid, const std::unordered_map< std::string, std::string > &metadata)
std::optional< std::unordered_map< std::string, std::string > > getMetadata (const std::string &cid) const
bool setContentType (const std::string &cid, const std::string &content_type)
std::optional< std::string > getContentType (const std::string &cid) const
std::optional< IPFSStatistics > getStatistics () const
void clearCache ()
bool isCached (const std::string &cid) const
std::optional< IPFSContent > getFromCache (const std::string &cid) const
void registerContentCallback (ContentCallback callback)
void registerErrorCallback (ErrorCallback callback)
void registerProgressCallback (ProgressCallback callback)
IPFSManager (const IPFSManager &)=delete
IPFSManager & operator= (const IPFSManager &)=delete
IPFSManager (IPFSManager &&)=default
IPFSManager & operator= (IPFSManager &&)=default
bool initialize (const Config &config)
void shutdown ()
bool isRunning () const
bool isInitialized () const
bool isHealthy () const
bool addFile (const std::string &filePath, std::string &hash)
bool addFileData (const std::string &data, std::string &hash)
bool getFile (const std::string &hash, const std::string &outputPath)
bool getFile (const std::string &hash, std::string &data)
bool pinFile (const std::string &hash)
bool unpinFile (const std::string &hash)
bool getPinnedFiles (std::vector< std::string > &pinnedFiles)
std::string getLastError () const
std::string addData (const std::vector< uint8_t > &data)
std::vector< uint8_t > getData (const std::string &ipfs_hash)
bool pinHash (const std::string &ipfs_hash)
bool unpinHash (const std::string &ipfs_hash)
std::vector< std::string > listPinnedHashes ()
nlohmann::json getIPFSInfo (const std::string &ipfs_hash)
std::vector< nlohmann::json > getIPFSHistory (const std::string &ipfs_hash)
std::vector< nlohmann::json > getIPFSBalances (const std::string &ipfs_hash)
std::vector< nlohmann::json > getIPFSTransactions (const std::string &ipfs_hash)
std::vector< std::string > getIPFSAddresses (const std::string &ipfs_hash)
std::vector< nlohmann::json > getIPFSAddressBalances (const std::string &ipfs_hash)
std::vector< nlohmann::json > getIPFSAddressTransactions (const std::string &ipfs_hash)
std::vector< nlohmann::json > getIPFSAddressHistory (const std::string &ipfs_hash)
Static Public Member Functions
static IPFSManager & getInstance ()
Detailed Description
Definition at line 62 of file ipfs_manager.hpp.
Member Typedef Documentation
ContentCallback
using satox::ipfs::IPFSManager::ContentCallback = std::function<void(const std::string&, const IPFSContent&)>
Definition at line 64 of file ipfs_manager.hpp.
ErrorCallback
using satox::ipfs::IPFSManager::ErrorCallback = std::function<void(const std::string&)>
Definition at line 65 of file ipfs_manager.hpp.
ProgressCallback
using satox::ipfs::IPFSManager::ProgressCallback = std::function<void(const std::string&, uint32_t)>
Definition at line 66 of file ipfs_manager.hpp.
Constructor & Destructor Documentation
IPFSManager() [1/3]
satox::ipfs::IPFSManager::IPFSManager ()
Definition at line 334 of file ipfs_manager.cpp.
Referenced by getInstance(), IPFSManager(), IPFSManager(), operator=(), and operator=().
~IPFSManager()
satox::ipfs::IPFSManager::~IPFSManager () default
IPFSManager() [2/3]
satox::ipfs::IPFSManager::IPFSManager (const IPFSManager &) delete
References IPFSManager().
IPFSManager() [3/3]
satox::ipfs::IPFSManager::IPFSManager (IPFSManager &&) default
References IPFSManager().
Member Function Documentation
addContent()
std::string satox::ipfs::IPFSManager::addContent (const std::vector< uint8_t > & data, const std::string & content_type, const std::unordered_map< std::string, std::string > & metadata = {})
addData()
std::string satox::ipfs::IPFSManager::addData (const std::vector< uint8_t > & data)
Definition at line 444 of file ipfs_manager.cpp.
addFile()
bool satox::ipfs::IPFSManager::addFile (const std::string & filePath, std::string & hash)
Definition at line 379 of file ipfs_manager.cpp.
Referenced by getLastError().
addFileData()
bool satox::ipfs::IPFSManager::addFileData (const std::string & data, std::string & hash)
Definition at line 383 of file ipfs_manager.cpp.
batchAddContent()
bool satox::ipfs::IPFSManager::batchAddContent (const std::vector< std::pair< std::vector< uint8_t >, std::string > > & contents)
batchPinContent()
bool satox::ipfs::IPFSManager::batchPinContent (const std::vector< std::string > & cids)
batchUnpinContent()
bool satox::ipfs::IPFSManager::batchUnpinContent (const std::vector< std::string > & cids)
clearCache()
void satox::ipfs::IPFSManager::clearCache ()
getContent()
std::optional< IPFSContent > satox::ipfs::IPFSManager::getContent (const std::string & cid)
getContentType()
std::optional< std::string > satox::ipfs::IPFSManager::getContentType (const std::string & cid) const
getData()
std::vector< uint8_t > satox::ipfs::IPFSManager::getData (const std::string & ipfs_hash)
Definition at line 449 of file ipfs_manager.cpp.
getFile() [1/2]
bool satox::ipfs::IPFSManager::getFile (const std::string & hash, const std::string & outputPath)
Definition at line 401 of file ipfs_manager.cpp.
Referenced by getLastError().
getFile() [2/2]
bool satox::ipfs::IPFSManager::getFile (const std::string & hash, std::string & data)
Definition at line 405 of file ipfs_manager.cpp.
getFromCache()
std::optional< IPFSContent > satox::ipfs::IPFSManager::getFromCache (const std::string & cid) const
getGatewayUrl()
std::string satox::ipfs::IPFSManager::getGatewayUrl (const std::string & cid) const
getInstance()
IPFSManager & satox::ipfs::IPFSManager::getInstance () static
Definition at line 41 of file ipfs_manager.cpp.
References satox::ipfs::instance, and IPFSManager().
getIPFSAddressBalances()
std::vector< nlohmann::json > satox::ipfs::IPFSManager::getIPFSAddressBalances (const std::string & ipfs_hash)
Definition at line 492 of file ipfs_manager.cpp.
getIPFSAddresses()
std::vector< std::string > satox::ipfs::IPFSManager::getIPFSAddresses (const std::string & ipfs_hash)
Definition at line 487 of file ipfs_manager.cpp.
getIPFSAddressHistory()
std::vector< nlohmann::json > satox::ipfs::IPFSManager::getIPFSAddressHistory (const std::string & ipfs_hash)
Definition at line 502 of file ipfs_manager.cpp.
getIPFSAddressTransactions()
std::vector< nlohmann::json > satox::ipfs::IPFSManager::getIPFSAddressTransactions (const std::string & ipfs_hash)
Definition at line 497 of file ipfs_manager.cpp.
getIPFSBalances()
std::vector< nlohmann::json > satox::ipfs::IPFSManager::getIPFSBalances (const std::string & ipfs_hash)
Definition at line 477 of file ipfs_manager.cpp.
getIPFSHistory()
std::vector< nlohmann::json > satox::ipfs::IPFSManager::getIPFSHistory (const std::string & ipfs_hash)
Definition at line 472 of file ipfs_manager.cpp.
getIPFSInfo()
nlohmann::json satox::ipfs::IPFSManager::getIPFSInfo (const std::string & ipfs_hash)
Definition at line 467 of file ipfs_manager.cpp.
getIPFSTransactions()
std::vector< nlohmann::json > satox::ipfs::IPFSManager::getIPFSTransactions (const std::string & ipfs_hash)
Definition at line 482 of file ipfs_manager.cpp.
getLastError() [1/2]
std::string satox::ipfs::IPFSManager::getLastError () const
Definition at line 439 of file ipfs_manager.cpp.
Referenced by getLastError().
getLastError() [2/2]
std::string satox::ipfs::IPFSManager::getLastError () const
References addFile(), getFile(), getLastError(), getPinnedFiles(), initialize(), isInitialized(), pinFile(), and unpinFile().
getMetadata()
std::optional< std::unordered_map< std::string, std::string > > satox::ipfs::IPFSManager::getMetadata (const std::string & cid) const
getPinnedFiles()
bool satox::ipfs::IPFSManager::getPinnedFiles (std::vector< std::string > & pinnedFiles)
Definition at line 435 of file ipfs_manager.cpp.
Referenced by getLastError().
getStatistics()
std::optional< IPFSStatistics > satox::ipfs::IPFSManager::getStatistics () const
initialize() [1/2]
bool satox::ipfs::IPFSManager::initialize (const Config & config)
Definition at line 337 of file ipfs_manager.cpp.
initialize() [2/2]
bool satox::ipfs::IPFSManager::initialize (const IPFSConfig & config)
Referenced by getLastError().
isCached()
bool satox::ipfs::IPFSManager::isCached (const std::string & cid) const
isContentPinned()
bool satox::ipfs::IPFSManager::isContentPinned (const std::string & cid) const
isGatewayEnabled()
bool satox::ipfs::IPFSManager::isGatewayEnabled () const
isHealthy()
bool satox::ipfs::IPFSManager::isHealthy () const
Definition at line 353 of file ipfs_manager.cpp.
isInitialized()
bool satox::ipfs::IPFSManager::isInitialized () const
Definition at line 349 of file ipfs_manager.cpp.
Referenced by getLastError().
isRunning()
bool satox::ipfs::IPFSManager::isRunning () const
Definition at line 345 of file ipfs_manager.cpp.
listContent()
std::vector< std::string > satox::ipfs::IPFSManager::listContent () const
listPinnedContent()
std::vector< std::string > satox::ipfs::IPFSManager::listPinnedContent () const
listPinnedHashes()
std::vector< std::string > satox::ipfs::IPFSManager::listPinnedHashes ()
Definition at line 462 of file ipfs_manager.cpp.
operator=() [1/2]
IPFSManager & satox::ipfs::IPFSManager::operator= (const IPFSManager &) delete
References IPFSManager().
operator=() [2/2]
IPFSManager & satox::ipfs::IPFSManager::operator= (IPFSManager &&) default
References IPFSManager().
pinContent()
bool satox::ipfs::IPFSManager::pinContent (const std::string & cid)
pinFile()
bool satox::ipfs::IPFSManager::pinFile (const std::string & hash)
Definition at line 427 of file ipfs_manager.cpp.
Referenced by getLastError(), and pinHash().
pinHash()
bool satox::ipfs::IPFSManager::pinHash (const std::string & ipfs_hash)
Definition at line 454 of file ipfs_manager.cpp.
References pinFile().
registerContentCallback()
void satox::ipfs::IPFSManager::registerContentCallback (ContentCallback callback)
registerErrorCallback()
void satox::ipfs::IPFSManager::registerErrorCallback (ErrorCallback callback)
registerProgressCallback()
void satox::ipfs::IPFSManager::registerProgressCallback (ProgressCallback callback)
removeContent()
bool satox::ipfs::IPFSManager::removeContent (const std::string & cid)
setContentType()
bool satox::ipfs::IPFSManager::setContentType (const std::string & cid, const std::string & content_type)
shutdown() [1/2]
void satox::ipfs::IPFSManager::shutdown ()
Definition at line 341 of file ipfs_manager.cpp.
shutdown() [2/2]
void satox::ipfs::IPFSManager::shutdown ()
unpinContent()
bool satox::ipfs::IPFSManager::unpinContent (const std::string & cid)
unpinFile()
bool satox::ipfs::IPFSManager::unpinFile (const std::string & hash)
Definition at line 431 of file ipfs_manager.cpp.
Referenced by getLastError(), and unpinHash().
unpinHash()
bool satox::ipfs::IPFSManager::unpinHash (const std::string & ipfs_hash)
Definition at line 458 of file ipfs_manager.cpp.
References unpinFile().
updateMetadata()
bool satox::ipfs::IPFSManager::updateMetadata (const std::string & cid, const std::unordered_map< std::string, std::string > & metadata)
The documentation for this class was generated from the following files:
src/core/include/satox/ipfs/ipfs_manager.hpp
src/ipfs/include/satox/ipfs/ipfs_manager.hpp
src/ipfs/src/ipfs_manager.cpp