SATOX SDK: satox::core::PerformanceOptimization Class Reference
satox::core::PerformanceOptimization Class Reference
Performance optimization class for managing various optimization strategies.
#include <performance_optimization.hpp>
Classes
class Impl
Public Member Functions
PerformanceOptimization ()
~PerformanceOptimization ()
PerformanceOptimization (const PerformanceOptimization &)=delete
PerformanceOptimization & operator= (const PerformanceOptimization &)=delete
void addToCache (const std::string &key, const std::string &value)
std::optional< std::string > getFromCache (const std::string &key)
void addConnection (const std::string &address)
void removeConnection (const std::string &address)
void addToBatch (const std::string &operation, const std::string &data)
void optimizeMemory ()
Detailed Description
Performance optimization class for managing various optimization strategies.
This class provides functionality for:
Cache management
Connection pooling
Batch processing
Parallel processing
Memory optimization
Definition at line 45 of file performance_optimization.hpp.
Constructor & Destructor Documentation
PerformanceOptimization() [1/2]
satox::core::PerformanceOptimization::PerformanceOptimization ()
Definition at line 176 of file performance_optimization.cpp.
Referenced by operator=(), and PerformanceOptimization().
~PerformanceOptimization()
satox::core::PerformanceOptimization::~PerformanceOptimization () default
PerformanceOptimization() [2/2]
satox::core::PerformanceOptimization::PerformanceOptimization (const PerformanceOptimization &) delete
References PerformanceOptimization().
Member Function Documentation
addConnection()
void satox::core::PerformanceOptimization::addConnection (const std::string & address)
Definition at line 187 of file performance_optimization.cpp.
addToBatch()
void satox::core::PerformanceOptimization::addToBatch (const std::string & operation, const std::string & data)
Definition at line 195 of file performance_optimization.cpp.
addToCache()
void satox::core::PerformanceOptimization::addToCache (const std::string & key, const std::string & value)
Definition at line 179 of file performance_optimization.cpp.
getFromCache()
std::optional< std::string > satox::core::PerformanceOptimization::getFromCache (const std::string & key)
Definition at line 183 of file performance_optimization.cpp.
operator=()
PerformanceOptimization & satox::core::PerformanceOptimization::operator= (const PerformanceOptimization &) delete
References PerformanceOptimization().
optimizeMemory()
void satox::core::PerformanceOptimization::optimizeMemory ()
Definition at line 199 of file performance_optimization.cpp.
removeConnection()
void satox::core::PerformanceOptimization::removeConnection (const std::string & address)
Definition at line 191 of file performance_optimization.cpp.
The documentation for this class was generated from the following files:
src/core/include/satox/core/performance_optimization.hpp
src/core/src/performance_optimization.cpp