SATOX SDK: satox::core::SecurityManager Class Reference
satox::core::SecurityManager Class Reference
SecurityManager provides cryptographic and security operations for Satox SDK.
#include <security_manager.hpp>
Classes
struct SecurityConfig
Security configuration structure.
struct SecurityStats
Security statistics structure.
Public Types
enum class SecurityLevel { LOW , MEDIUM , HIGH }
Security level enumeration.
using SecurityCallback = std::function<void(const std::string&, SecurityLevel)>
Callback types.
using AuditCallback = std::function<void(const std::string&, const std::string&)>
Public Member Functions
SecurityManager ()
~SecurityManager ()
bool initialize (const SecurityConfig &config)
Initialize the security manager with configuration.
void shutdown ()
bool generateKeyPair (const std::string &key_id)
Key management.
bool validateKey (const std::string &key)
bool storeKey (const std::string &keyId, const std::string &key)
std::string getKey (const std::string &keyId)
std::string generateKey (int length)
std::optional< std::string > sign (const std::string &key_id, const std::string &data)
Signing and verification.
bool verify (const std::string &key_id, const std::string &data, const std::string &signature)
std::optional< std::string > encrypt (const std::string &key_id, const std::string &data)
Encryption and decryption.
std::optional< std::string > decrypt (const std::string &key_id, const std::string &encrypted_data)
std::vector< uint8_t > encrypt (const std::vector< uint8_t > &data, const std::string &key)
std::vector< uint8_t > decrypt (const std::vector< uint8_t > &data, const std::string &key)
std::string encryptString (const std::string &data, const std::string &key)
std::string decryptString (const std::string &data, const std::string &key)
bool authenticate (const std::string &username, const std::string &password)
Authentication and session management.
bool validateSession (const std::string &sessionId)
std::string createSession (const std::string &username)
void invalidateSession (const std::string &sessionId)
bool isSessionExpired (const std::string &sessionId)
void cleanupExpiredSessions ()
bool validateInput (const std::string &input)
Input validation and permissions.
bool checkPermission (const std::string &user, const std::string &resource)
SecurityLevel getSecurityLevel () const
Security level management.
void setSecurityLevel (SecurityLevel level)
void logEvent (const std::string &event, const std::string &details)
Event and audit logging.
std::vector< std::string > getAuditLog () const
void clearAuditLog ()
void registerSecurityCallback (SecurityCallback callback)
void registerAuditCallback (AuditCallback callback)
void unregisterSecurityCallback ()
void unregisterAuditCallback ()
void notifySecurityEvent (const std::string &event, SecurityLevel level)
void notifyAuditEvent (const std::string &event, const std::string &details)
SecurityStats getStats () const
Statistics and config.
void resetStats ()
SecurityConfig getConfig () const
bool updateConfig (const SecurityConfig &config)
std::string getLastError () const
Error handling.
void setLastError (const std::string &error)
Detailed Description
SecurityManager provides cryptographic and security operations for Satox SDK.
Definition at line 44 of file security_manager.hpp.
Member Typedef Documentation
AuditCallback
using satox::core::SecurityManager::AuditCallback = std::function<void(const std::string&, const std::string&)>
Definition at line 73 of file security_manager.hpp.
SecurityCallback
using satox::core::SecurityManager::SecurityCallback = std::function<void(const std::string&, SecurityLevel)>
Callback types.
Definition at line 72 of file security_manager.hpp.
Member Enumeration Documentation
SecurityLevel
enum class satox::core::SecurityManager::SecurityLevel strong
Security level enumeration.
Enumerator
LOW
MEDIUM
HIGH
Definition at line 55 of file security_manager.hpp.
Constructor & Destructor Documentation
SecurityManager()
satox::core::SecurityManager::SecurityManager ()
Definition at line 42 of file security_manager.cpp.
~SecurityManager()
satox::core::SecurityManager::~SecurityManager ()
Definition at line 45 of file security_manager.cpp.
References shutdown().
Member Function Documentation
authenticate()
bool satox::core::SecurityManager::authenticate (const std::string & username, const std::string & password)
Authentication and session management.
Definition at line 290 of file security_manager.cpp.
References setLastError().
checkPermission()
bool satox::core::SecurityManager::checkPermission (const std::string & user, const std::string & resource)
Definition at line 360 of file security_manager.cpp.
cleanupExpiredSessions()
void satox::core::SecurityManager::cleanupExpiredSessions ()
Definition at line 469 of file security_manager.cpp.
References isSessionExpired().
clearAuditLog()
void satox::core::SecurityManager::clearAuditLog ()
Definition at line 390 of file security_manager.cpp.
createSession()
std::string satox::core::SecurityManager::createSession (const std::string & username)
Definition at line 325 of file security_manager.cpp.
References generateKey().
decrypt() [1/2]
std::optional< std::string > satox::core::SecurityManager::decrypt (const std::string & key_id, const std::string & encrypted_data)
References MEDIUM.
Referenced by decryptString().
decrypt() [2/2]
std::vector< uint8_t > satox::core::SecurityManager::decrypt (const std::vector< uint8_t > & data, const std::string & key)
Definition at line 148 of file security_manager.cpp.
References setLastError().
decryptString()
std::string satox::core::SecurityManager::decryptString (const std::string & data, const std::string & key)
Definition at line 216 of file security_manager.cpp.
References decrypt(), and setLastError().
encrypt() [1/2]
std::optional< std::string > satox::core::SecurityManager::encrypt (const std::string & key_id, const std::string & data)
Encryption and decryption.
Referenced by encryptString().
encrypt() [2/2]
std::vector< uint8_t > satox::core::SecurityManager::encrypt (const std::vector< uint8_t > & data, const std::string & key)
Definition at line 90 of file security_manager.cpp.
References setLastError().
encryptString()
std::string satox::core::SecurityManager::encryptString (const std::string & data, const std::string & key)
Definition at line 205 of file security_manager.cpp.
References encrypt().
generateKey()
std::string satox::core::SecurityManager::generateKey (int length)
Definition at line 232 of file security_manager.cpp.
References setLastError().
Referenced by createSession().
generateKeyPair()
bool satox::core::SecurityManager::generateKeyPair (const std::string & key_id)
Key management.
getAuditLog()
std::vector< std::string > satox::core::SecurityManager::getAuditLog () const
Definition at line 385 of file security_manager.cpp.
getConfig()
SecurityManager::SecurityConfig satox::core::SecurityManager::getConfig () const
Definition at line 425 of file security_manager.cpp.
getKey()
std::string satox::core::SecurityManager::getKey (const std::string & keyId)
Definition at line 279 of file security_manager.cpp.
References setLastError().
getLastError()
std::string satox::core::SecurityManager::getLastError () const
Error handling.
Definition at line 436 of file security_manager.cpp.
getSecurityLevel()
SecurityManager::SecurityLevel satox::core::SecurityManager::getSecurityLevel () const
Security level management.
Definition at line 365 of file security_manager.cpp.
getStats()
SecurityManager::SecurityStats satox::core::SecurityManager::getStats () const
Statistics and config.
Definition at line 415 of file security_manager.cpp.
initialize()
bool satox::core::SecurityManager::initialize (const SecurityConfig & config)
Initialize the security manager with configuration.
Definition at line 49 of file security_manager.cpp.
References setLastError().
invalidateSession()
void satox::core::SecurityManager::invalidateSession (const std::string & sessionId)
Definition at line 334 of file security_manager.cpp.
isSessionExpired()
bool satox::core::SecurityManager::isSessionExpired (const std::string & sessionId)
Definition at line 458 of file security_manager.cpp.
Referenced by cleanupExpiredSessions(), and validateSession().
logEvent()
void satox::core::SecurityManager::logEvent (const std::string & event, const std::string & details)
Event and audit logging.
Definition at line 375 of file security_manager.cpp.
References notifyAuditEvent().
notifyAuditEvent()
void satox::core::SecurityManager::notifyAuditEvent (const std::string & event, const std::string & details)
Definition at line 452 of file security_manager.cpp.
Referenced by logEvent().
notifySecurityEvent()
void satox::core::SecurityManager::notifySecurityEvent (const std::string & event, SecurityLevel level)
Definition at line 446 of file security_manager.cpp.
registerAuditCallback()
void satox::core::SecurityManager::registerAuditCallback (AuditCallback callback)
Definition at line 400 of file security_manager.cpp.
registerSecurityCallback()
void satox::core::SecurityManager::registerSecurityCallback (SecurityCallback callback)
Definition at line 395 of file security_manager.cpp.
resetStats()
void satox::core::SecurityManager::resetStats ()
Definition at line 420 of file security_manager.cpp.
setLastError()
void satox::core::SecurityManager::setLastError (const std::string & error)
Definition at line 441 of file security_manager.cpp.
Referenced by authenticate(), decrypt(), decryptString(), encrypt(), generateKey(), getKey(), initialize(), shutdown(), and storeKey().
setSecurityLevel()
void satox::core::SecurityManager::setSecurityLevel (SecurityLevel level)
Definition at line 370 of file security_manager.cpp.
shutdown()
void satox::core::SecurityManager::shutdown ()
Definition at line 72 of file security_manager.cpp.
References setLastError().
Referenced by ~SecurityManager().
sign()
bool satox::security::SecurityManager::sign (const std::string & key_id, const std::string & data)
Signing and verification.
Definition at line 471 of file security_manager.cpp.
References sign().
Referenced by sign().
storeKey()
bool satox::core::SecurityManager::storeKey (const std::string & keyId, const std::string & key)
Definition at line 262 of file security_manager.cpp.
References setLastError(), and validateKey().
unregisterAuditCallback()
void satox::core::SecurityManager::unregisterAuditCallback ()
Definition at line 410 of file security_manager.cpp.
unregisterSecurityCallback()
void satox::core::SecurityManager::unregisterSecurityCallback ()
Definition at line 405 of file security_manager.cpp.
updateConfig()
bool satox::core::SecurityManager::updateConfig (const SecurityConfig & config)
Definition at line 430 of file security_manager.cpp.
validateInput()
bool satox::core::SecurityManager::validateInput (const std::string & input)
Input validation and permissions.
Definition at line 341 of file security_manager.cpp.
validateKey()
bool satox::core::SecurityManager::validateKey (const std::string & key)
Definition at line 258 of file security_manager.cpp.
Referenced by storeKey().
validateSession()
bool satox::core::SecurityManager::validateSession (const std::string & sessionId)
Definition at line 309 of file security_manager.cpp.
References isSessionExpired().
verify()
bool satox::security::SecurityManager::verify (const std::string & key_id, const std::string & data, const std::string & signature)
Definition at line 476 of file security_manager.cpp.
References verify().
Referenced by verify().
The documentation for this class was generated from the following files:
src/core/include/satox/core/security_manager.hpp
src/core/src/security_manager.cpp
src/security/security_manager.cpp