SATOX SDK: satox::core::TransactionManager Class Reference
satox::core::TransactionManager Class Reference
#include <transaction.h>
Classes
struct Config
struct ErrorRecoveryConfig
struct FeeEstimate
struct Input
struct Output
struct PerformanceConfig
struct RecoveryOperation
struct Stats
struct Transaction
struct TransactionStats
struct UTXO
Public Types
enum class Priority { LOW , NORMAL , HIGH , CRITICAL }
enum class TransactionStatus {
PENDING , ACTIVE , COMPLETED , FAILED ,
CANCELLED
}
using TransactionCallback = std::function<void(const Transaction&)>
using ErrorCallback = std::function<void(const std::string&)>
Public Member Functions
TransactionManager ()
~TransactionManager ()
TransactionManager (const TransactionManager &)=delete
TransactionManager & operator= (const TransactionManager &)=delete
TransactionManager (TransactionManager &&) noexcept=default
TransactionManager & operator= (TransactionManager &&) noexcept=default
void initialize ()
Transaction createTransaction (const std::string &from, const std::string &to, const std::string &amount, const std::string &data="")
bool signTransaction (Transaction &transaction, const std::string &privateKey)
bool verifyTransaction (const Transaction &transaction)
bool broadcastTransaction (const Transaction &transaction)
std::string getTransactionStatus (const std::string &transactionId)
std::vector< Transaction > getPendingTransactions ()
std::vector< Transaction > getTransactionHistory (const std::string &address)
TransactionManager ()
~TransactionManager ()
bool initialize (size_t maxTransactions, size_t maxConcurrent)
bool shutdown ()
std::string createTransaction (const std::string &type, const nlohmann::json &data, Priority priority)
bool signTransaction (Transaction &transaction, const std::string &private_key)
bool validateTransaction (const Transaction &transaction) const
bool submitTransaction (Transaction &transaction)
bool broadcastTransaction (const std::string &tx_hash)
std::optional< Transaction > getTransaction (const std::string &tx_hash) const
std::vector< Transaction > getMempool () const
bool removeFromMempool (const std::string &tx_hash)
std::vector< UTXO > getUTXOs (const std::string &address) const
bool isUTXOSpent (const std::string &tx_hash, uint32_t output_index) const
bool updateUTXO (const UTXO &utxo)
bool removeUTXO (const std::string &tx_hash, uint32_t output_index)
FeeEstimate estimateFee (const Transaction &transaction) const
uint64_t calculateFee (const Transaction &transaction) const
bool validateFee (const Transaction &transaction) const
std::vector< Transaction > getTransactionHistory (const std::string &address) const
std::vector< Transaction > getBlockTransactions (const std::string &block_hash) const
std::vector< Transaction > getAddressTransactions (const std::string &address) const
TransactionStats getTransactionStats () const
void registerTransactionCallback (TransactionCallback callback)
void registerErrorCallback (ErrorCallback callback)
void monitorTransaction (const std::string &transaction_id)
void stopMonitoring ()
std::string getLastError () const
void clearLastError ()
bool hasTransaction (const std::string &id) const
bool isTransactionActive (const std::string &id) const
bool isTransactionPending (const std::string &id) const
bool isTransactionCompleted (const std::string &id) const
bool isTransactionFailed (const std::string &id) const
bool isTransactionCancelled (const std::string &id) const
void clearCompletedTransactions (size_t maxAge)
void clearAllTransactions ()
Stats getStats () const
bool isHealthy () const
void setPerformanceConfig (const PerformanceConfig &config)
void clearCache ()
size_t getCacheSize () const
size_t getConnectionPoolSize () const
size_t getBatchSize () const
void processBatch ()
void optimizeMemory ()
void setErrorRecoveryConfig (const ErrorRecoveryConfig &config)
bool recoverFromError (const std::string &operation_id)
std::vector< RecoveryOperation > getRecoveryHistory () const
void clearRecoveryHistory ()
bool isRecoveryInProgress () const
std::string getLastRecoveryError () const
bool startTransaction (const std::string &id)
bool completeTransaction (const std::string &id, const nlohmann::json &result)
bool failTransaction (const std::string &id, const std::string &error)
bool cancelTransaction (const std::string &id)
std::vector< Transaction > getTransactions (TransactionStatus status) const
std::vector< Transaction > getTransactions (const std::string &type) const
std::vector< Transaction > getPendingTransactions () const
std::vector< Transaction > getActiveTransactions () const
std::vector< Transaction > getCompletedTransactions () const
std::vector< Transaction > getFailedTransactions () const
Static Public Member Functions
static std::string TransactionStatusToString (TransactionStatus status)
static TransactionStatus StringToTransactionStatus (const std::string &str)
static TransactionManager & getInstance ()
Friends
void to_json (nlohmann::json &j, const Transaction &t)
void from_json (const nlohmann::json &j, TransactionManager::Transaction &t)
Detailed Description
Definition at line 47 of file transaction.h.
Member Typedef Documentation
ErrorCallback
using satox::core::TransactionManager::ErrorCallback = std::function<void(const std::string&)>
Definition at line 194 of file transaction_manager.hpp.
TransactionCallback
using satox::core::TransactionManager::TransactionCallback = std::function<void(const Transaction&)>
Definition at line 193 of file transaction_manager.hpp.
Member Enumeration Documentation
Priority
enum class satox::core::TransactionManager::Priority strong
Enumerator
LOW
NORMAL
HIGH
CRITICAL
Definition at line 86 of file transaction_manager.hpp.
TransactionStatus
enum class satox::core::TransactionManager::TransactionStatus strong
Enumerator
PENDING
ACTIVE
COMPLETED
FAILED
CANCELLED
Definition at line 93 of file transaction_manager.hpp.
Constructor & Destructor Documentation
TransactionManager() [1/4]
satox::core::TransactionManager::TransactionManager ()
Definition at line 39 of file transaction.cpp.
Referenced by getInstance(), operator=(), operator=(), TransactionManager(), and TransactionManager().
~TransactionManager() [1/2]
satox::core::TransactionManager::~TransactionManager ()
Definition at line 41 of file transaction.cpp.
TransactionManager() [2/4]
satox::core::TransactionManager::TransactionManager (const TransactionManager &) delete
References TransactionManager().
TransactionManager() [3/4]
satox::core::TransactionManager::TransactionManager (TransactionManager &&) default noexcept
References TransactionManager().
TransactionManager() [4/4]
satox::core::TransactionManager::TransactionManager ()
~TransactionManager() [2/2]
satox::core::TransactionManager::~TransactionManager ()
Member Function Documentation
broadcastTransaction() [1/2]
bool satox::core::TransactionManager::broadcastTransaction (const std::string & tx_hash)
broadcastTransaction() [2/2]
bool satox::core::TransactionManager::broadcastTransaction (const Transaction & transaction)
Definition at line 324 of file transaction.cpp.
References verifyTransaction().
Referenced by operator=().
calculateFee()
uint64_t satox::core::TransactionManager::calculateFee (const Transaction & transaction) const
cancelTransaction()
bool satox::core::TransactionManager::cancelTransaction (const std::string & id)
Definition at line 245 of file transaction_manager.cpp.
References CANCELLED, satox::core::TransactionManager::Transaction::cancelledAt, cancelTransaction(), PENDING, satox::core::TransactionManager::Transaction::status, and satox::core::TransactionManager::Transaction::updatedAt.
Referenced by cancelTransaction().
clearAllTransactions()
void satox::core::TransactionManager::clearAllTransactions ()
Definition at line 438 of file transaction_manager.cpp.
References clearAllTransactions().
Referenced by clearAllTransactions().
clearCache()
void satox::core::TransactionManager::clearCache ()
clearCompletedTransactions()
void satox::core::TransactionManager::clearCompletedTransactions (size_t maxAge)
Definition at line 403 of file transaction_manager.cpp.
References clearCompletedTransactions().
Referenced by clearCompletedTransactions().
clearLastError()
void satox::core::TransactionManager::clearLastError ()
Definition at line 470 of file transaction_manager.cpp.
References clearLastError().
Referenced by clearLastError().
clearRecoveryHistory()
void satox::core::TransactionManager::clearRecoveryHistory ()
completeTransaction()
bool satox::core::TransactionManager::completeTransaction (const std::string & id, const nlohmann::json & result)
Definition at line 171 of file transaction_manager.cpp.
References ACTIVE, COMPLETED, satox::core::TransactionManager::Transaction::completedAt, completeTransaction(), satox::core::TransactionManager::Transaction::result, satox::core::TransactionManager::Transaction::status, and satox::core::TransactionManager::Transaction::updatedAt.
Referenced by completeTransaction().
createTransaction() [1/2]
Transaction satox::core::TransactionManager::createTransaction (const std::string & from, const std::string & to, const std::string & amount, const std::string & data = "")
Definition at line 54 of file transaction.cpp.
References satox::core::TransactionManager::Transaction::data, satox::core::TransactionManager::Transaction::id, and satox::core::TransactionManager::Transaction::status.
Referenced by createTransaction(), and operator=().
createTransaction() [2/2]
std::string satox::core::TransactionManager::createTransaction (const std::string & type, const nlohmann::json & data, Priority priority)
Definition at line 92 of file transaction_manager.cpp.
References satox::core::TransactionManager::Transaction::createdAt, createTransaction(), satox::core::TransactionManager::Transaction::data, satox::core::TransactionManager::Transaction::id, PENDING, satox::core::TransactionManager::Transaction::priority, satox::core::TransactionManager::Transaction::status, satox::core::TransactionManager::Transaction::type, and satox::core::TransactionManager::Transaction::updatedAt.
estimateFee()
FeeEstimate satox::core::TransactionManager::estimateFee (const Transaction & transaction) const
failTransaction()
bool satox::core::TransactionManager::failTransaction (const std::string & id, const std::string & error)
Definition at line 208 of file transaction_manager.cpp.
References ACTIVE, satox::core::TransactionManager::Transaction::error, FAILED, satox::core::TransactionManager::Transaction::failedAt, failTransaction(), satox::core::TransactionManager::Transaction::status, and satox::core::TransactionManager::Transaction::updatedAt.
Referenced by failTransaction().
getActiveTransactions()
std::vector< TransactionManager::Transaction > satox::core::TransactionManager::getActiveTransactions () const
Definition at line 330 of file transaction_manager.cpp.
References getActiveTransactions().
Referenced by getActiveTransactions().
getAddressTransactions()
std::vector< Transaction > satox::core::TransactionManager::getAddressTransactions (const std::string & address) const
getBatchSize()
size_t satox::core::TransactionManager::getBatchSize () const
getBlockTransactions()
std::vector< Transaction > satox::core::TransactionManager::getBlockTransactions (const std::string & block_hash) const
getCacheSize()
size_t satox::core::TransactionManager::getCacheSize () const
getCompletedTransactions()
std::vector< TransactionManager::Transaction > satox::core::TransactionManager::getCompletedTransactions () const
Definition at line 344 of file transaction_manager.cpp.
References getCompletedTransactions().
Referenced by getCompletedTransactions().
getConnectionPoolSize()
size_t satox::core::TransactionManager::getConnectionPoolSize () const
getFailedTransactions()
std::vector< TransactionManager::Transaction > satox::core::TransactionManager::getFailedTransactions () const
Definition at line 358 of file transaction_manager.cpp.
References getFailedTransactions().
Referenced by getFailedTransactions().
getInstance()
TransactionManager & satox::core::TransactionManager::getInstance () static
Definition at line 47 of file transaction_manager.cpp.
References getInstance(), and TransactionManager().
Referenced by getInstance(), and satox::core::SatoxManager::getTransactionManager().
getLastError()
std::string satox::core::TransactionManager::getLastError () const
Definition at line 465 of file transaction_manager.cpp.
References getLastError().
Referenced by getLastError().
getLastRecoveryError()
std::string satox::core::TransactionManager::getLastRecoveryError () const
getMempool()
std::vector< Transaction > satox::core::TransactionManager::getMempool () const
getPendingTransactions() [1/2]
std::vector< Transaction > satox::core::TransactionManager::getPendingTransactions ()
Definition at line 368 of file transaction.cpp.
Referenced by getPendingTransactions(), and operator=().
getPendingTransactions() [2/2]
std::vector< TransactionManager::Transaction > satox::core::TransactionManager::getPendingTransactions () const
Definition at line 316 of file transaction_manager.cpp.
References getPendingTransactions().
getRecoveryHistory()
std::vector< RecoveryOperation > satox::core::TransactionManager::getRecoveryHistory () const
getStats()
TransactionManager::Stats satox::core::TransactionManager::getStats () const
Definition at line 450 of file transaction_manager.cpp.
References satox::core::TransactionManager::Stats::activeTransactions, satox::core::TransactionManager::Stats::completedTransactions, satox::core::TransactionManager::Stats::failedTransactions, getStats(), satox::core::TransactionManager::Stats::maxConcurrent, satox::core::TransactionManager::Stats::maxTransactions, satox::core::TransactionManager::Stats::pendingTransactions, and satox::core::TransactionManager::Stats::totalTransactions.
Referenced by getStats().
getTransaction()
std::optional< TransactionManager::Transaction > satox::core::TransactionManager::getTransaction (const std::string & tx_hash) const
Definition at line 279 of file transaction_manager.cpp.
References getTransaction().
Referenced by getTransaction().
getTransactionHistory() [1/2]
std::vector< Transaction > satox::core::TransactionManager::getTransactionHistory (const std::string & address)
Definition at line 376 of file transaction.cpp.
Referenced by operator=().
getTransactionHistory() [2/2]
std::vector< Transaction > satox::core::TransactionManager::getTransactionHistory (const std::string & address) const
getTransactions() [1/2]
std::vector< TransactionManager::Transaction > satox::core::TransactionManager::getTransactions (const std::string & type) const
Definition at line 303 of file transaction_manager.cpp.
References getTransactions().
getTransactions() [2/2]
std::vector< TransactionManager::Transaction > satox::core::TransactionManager::getTransactions (TransactionStatus status) const
Definition at line 290 of file transaction_manager.cpp.
References getTransactions().
Referenced by getTransactions(), and getTransactions().
getTransactionStats()
TransactionStats satox::core::TransactionManager::getTransactionStats () const
getTransactionStatus()
std::string satox::core::TransactionManager::getTransactionStatus (const std::string & transactionId)
Definition at line 342 of file transaction.cpp.
Referenced by operator=().
getUTXOs()
std::vector< UTXO > satox::core::TransactionManager::getUTXOs (const std::string & address) const
hasTransaction()
bool satox::core::TransactionManager::hasTransaction (const std::string & id) const
Definition at line 372 of file transaction_manager.cpp.
References hasTransaction().
Referenced by hasTransaction().
initialize() [1/2]
void satox::core::TransactionManager::initialize ()
Definition at line 47 of file transaction.cpp.
Referenced by initialize(), and operator=().
initialize() [2/2]
bool satox::core::TransactionManager::initialize (size_t maxTransactions, size_t maxConcurrent)
Definition at line 52 of file transaction_manager.cpp.
References initialize().
isHealthy()
bool satox::core::TransactionManager::isHealthy () const
Definition at line 475 of file transaction_manager.cpp.
References isHealthy().
Referenced by isHealthy().
isRecoveryInProgress()
bool satox::core::TransactionManager::isRecoveryInProgress () const
isTransactionActive()
bool satox::core::TransactionManager::isTransactionActive (const std::string & id) const
Definition at line 377 of file transaction_manager.cpp.
References isTransactionActive().
Referenced by isTransactionActive().
isTransactionCancelled()
bool satox::core::TransactionManager::isTransactionCancelled (const std::string & id) const
Definition at line 397 of file transaction_manager.cpp.
References CANCELLED, and isTransactionCancelled().
Referenced by isTransactionCancelled().
isTransactionCompleted()
bool satox::core::TransactionManager::isTransactionCompleted (const std::string & id) const
Definition at line 387 of file transaction_manager.cpp.
References isTransactionCompleted().
Referenced by isTransactionCompleted().
isTransactionFailed()
bool satox::core::TransactionManager::isTransactionFailed (const std::string & id) const
Definition at line 392 of file transaction_manager.cpp.
References isTransactionFailed().
Referenced by isTransactionFailed().
isTransactionPending()
bool satox::core::TransactionManager::isTransactionPending (const std::string & id) const
Definition at line 382 of file transaction_manager.cpp.
References isTransactionPending().
Referenced by isTransactionPending().
isUTXOSpent()
bool satox::core::TransactionManager::isUTXOSpent (const std::string & tx_hash, uint32_t output_index) const
monitorTransaction()
void satox::core::TransactionManager::monitorTransaction (const std::string & transaction_id)
operator=() [1/2]
TransactionManager & satox::core::TransactionManager::operator= (const TransactionManager &) delete
References TransactionManager().
operator=() [2/2]
TransactionManager & satox::core::TransactionManager::operator= (TransactionManager &&) default noexcept
References broadcastTransaction(), createTransaction(), getPendingTransactions(), getTransactionHistory(), getTransactionStatus(), initialize(), signTransaction(), TransactionManager(), and verifyTransaction().
optimizeMemory()
void satox::core::TransactionManager::optimizeMemory ()
processBatch()
void satox::core::TransactionManager::processBatch ()
recoverFromError()
bool satox::core::TransactionManager::recoverFromError (const std::string & operation_id)
registerErrorCallback()
void satox::core::TransactionManager::registerErrorCallback (ErrorCallback callback)
registerTransactionCallback()
void satox::core::TransactionManager::registerTransactionCallback (TransactionCallback callback)
removeFromMempool()
bool satox::core::TransactionManager::removeFromMempool (const std::string & tx_hash)
removeUTXO()
bool satox::core::TransactionManager::removeUTXO (const std::string & tx_hash, uint32_t output_index)
setErrorRecoveryConfig()
void satox::core::TransactionManager::setErrorRecoveryConfig (const ErrorRecoveryConfig & config)
setPerformanceConfig()
void satox::core::TransactionManager::setPerformanceConfig (const PerformanceConfig & config)
shutdown()
bool satox::core::TransactionManager::shutdown ()
Definition at line 69 of file transaction_manager.cpp.
References shutdown().
Referenced by shutdown().
signTransaction() [1/2]
bool satox::core::TransactionManager::signTransaction (Transaction & transaction, const std::string & private_key)
signTransaction() [2/2]
bool satox::core::TransactionManager::signTransaction (Transaction & transaction, const std::string & privateKey)
Definition at line 82 of file transaction.cpp.
References satox::core::TransactionManager::Transaction::data.
Referenced by operator=().
startTransaction()
bool satox::core::TransactionManager::startTransaction (const std::string & id)
Definition at line 131 of file transaction_manager.cpp.
References ACTIVE, PENDING, satox::core::TransactionManager::Transaction::startedAt, startTransaction(), satox::core::TransactionManager::Transaction::status, and satox::core::TransactionManager::Transaction::updatedAt.
Referenced by startTransaction().
stopMonitoring()
void satox::core::TransactionManager::stopMonitoring ()
StringToTransactionStatus()
TransactionManager::TransactionStatus satox::core::TransactionManager::StringToTransactionStatus (const std::string & str) static
Definition at line 496 of file transaction_manager.cpp.
References ACTIVE, CANCELLED, COMPLETED, FAILED, PENDING, and StringToTransactionStatus().
Referenced by from_json, and StringToTransactionStatus().
submitTransaction()
bool satox::core::TransactionManager::submitTransaction (Transaction & transaction)
TransactionStatusToString()
std::string satox::core::TransactionManager::TransactionStatusToString (TransactionStatus status) static
Definition at line 485 of file transaction_manager.cpp.
References ACTIVE, CANCELLED, COMPLETED, FAILED, PENDING, and TransactionStatusToString().
Referenced by to_json, and TransactionStatusToString().
updateUTXO()
bool satox::core::TransactionManager::updateUTXO (const UTXO & utxo)
validateFee()
bool satox::core::TransactionManager::validateFee (const Transaction & transaction) const
validateTransaction()
bool satox::core::TransactionManager::validateTransaction (const Transaction & transaction) const
verifyTransaction()
bool satox::core::TransactionManager::verifyTransaction (const Transaction & transaction)
Definition at line 207 of file transaction.cpp.
References satox::core::TransactionManager::Transaction::data.
Referenced by broadcastTransaction(), and operator=().
Friends And Related Symbol Documentation
from_json
void from_json (const nlohmann::json & j, TransactionManager::Transaction & t) friend
Definition at line 524 of file transaction_manager.cpp.
References satox::core::TransactionManager::Transaction::cancelledAt, satox::core::TransactionManager::Transaction::completedAt, satox::core::TransactionManager::Transaction::createdAt, satox::core::TransactionManager::Transaction::data, satox::core::TransactionManager::Transaction::error, satox::core::TransactionManager::Transaction::failedAt, from_json, satox::core::TransactionManager::Transaction::id, satox::core::TransactionManager::Transaction::metadata, satox::core::TransactionManager::Transaction::priority, satox::core::TransactionManager::Transaction::result, satox::core::TransactionManager::Transaction::startedAt, satox::core::TransactionManager::Transaction::status, StringToTransactionStatus(), satox::core::TransactionManager::Transaction::type, and satox::core::TransactionManager::Transaction::updatedAt.
Referenced by from_json.
to_json
void to_json (nlohmann::json & j, const Transaction & t) friend
Definition at line 505 of file transaction_manager.cpp.
References satox::core::TransactionManager::Transaction::cancelledAt, satox::core::TransactionManager::Transaction::completedAt, satox::core::TransactionManager::Transaction::createdAt, satox::core::TransactionManager::Transaction::data, satox::core::TransactionManager::Transaction::error, satox::core::TransactionManager::Transaction::failedAt, satox::core::TransactionManager::Transaction::id, satox::core::TransactionManager::Transaction::metadata, satox::core::TransactionManager::Transaction::priority, satox::core::TransactionManager::Transaction::result, satox::core::TransactionManager::Transaction::startedAt, satox::core::TransactionManager::Transaction::status, to_json, TransactionStatusToString(), satox::core::TransactionManager::Transaction::type, and satox::core::TransactionManager::Transaction::updatedAt.
Referenced by to_json.
The documentation for this class was generated from the following files:
src/core/include/satox/core/transaction.h
src/core/include/satox/core/transaction_manager.hpp
src/core/src/transaction.cpp
src/core/src/transaction_manager.cpp