SATOX SDK: satox::network::LetsEncryptManager::Impl Class Reference
satox::network::LetsEncryptManager::Impl Class Reference
Public Member Functions
Impl ()
~Impl ()
bool initialize (const Config &config)
void shutdown ()
Certificate getCurrentCertificate () const
bool renewCertificate (const std::string &domain="")
void registerUpdateCallback (CertificateUpdateCallback callback)
bool isConfigured () const
std::string getLastError () const
Detailed Description
Definition at line 48 of file letsencrypt_manager.cpp.
Constructor & Destructor Documentation
Impl()
satox::network::LetsEncryptManager::Impl::Impl () inline
Definition at line 50 of file letsencrypt_manager.cpp.
~Impl()
satox::network::LetsEncryptManager::Impl::~Impl () inline
Definition at line 56 of file letsencrypt_manager.cpp.
References shutdown().
Member Function Documentation
getCurrentCertificate()
Certificate satox::network::LetsEncryptManager::Impl::getCurrentCertificate () const inline
Definition at line 138 of file letsencrypt_manager.cpp.
getLastError()
std::string satox::network::LetsEncryptManager::Impl::getLastError () const inline
Definition at line 224 of file letsencrypt_manager.cpp.
initialize()
bool satox::network::LetsEncryptManager::Impl::initialize (const Config & config) inline
Definition at line 63 of file letsencrypt_manager.cpp.
References satox::network::LetsEncryptManager::Config::cert_path, and satox::network::LetsEncryptManager::renewCertificate().
isConfigured()
bool satox::network::LetsEncryptManager::Impl::isConfigured () const inline
Definition at line 219 of file letsencrypt_manager.cpp.
registerUpdateCallback()
void satox::network::LetsEncryptManager::Impl::registerUpdateCallback (CertificateUpdateCallback callback) inline
Definition at line 214 of file letsencrypt_manager.cpp.
renewCertificate()
bool satox::network::LetsEncryptManager::Impl::renewCertificate (const std::string & domain = "") inline
Definition at line 143 of file letsencrypt_manager.cpp.
shutdown()
void satox::network::LetsEncryptManager::Impl::shutdown () inline
Definition at line 120 of file letsencrypt_manager.cpp.
Referenced by ~Impl().
The documentation for this class was generated from the following file:
src/network/src/letsencrypt_manager.cpp