SATOX SDK: satox::core::cloud::FirebaseManager::Impl Class Reference
satox::core::cloud::FirebaseManager::Impl Class Reference
Public Member Functions
Impl ()
~Impl ()
bool initialize (const FirebaseConfig &config)
bool isConnected () const
nlohmann::json readData (const std::string &path)
nlohmann::json writeData (const std::string &path, const nlohmann::json &data)
nlohmann::json updateData (const std::string &path, const nlohmann::json &data)
nlohmann::json deleteData (const std::string &path)
nlohmann::json queryData (const std::string &path, const nlohmann::json &query)
nlohmann::json executeQuery (const std::string &service, const nlohmann::json &params)
nlohmann::json executeTransaction (const std::string &service, const std::vector< nlohmann::json > &actions)
std::string subscribe (const std::string &path, std::function< void(const nlohmann::json &)> callback)
void unsubscribe (const std::string &subscription_id)
nlohmann::json uploadFile (const std::string &bucket, const std::string &path, const std::string &file_path)
nlohmann::json downloadFile (const std::string &bucket, const std::string &path, const std::string &local_path)
nlohmann::json callFunction (const std::string &function_name, const nlohmann::json &payload)
nlohmann::json sendNotification (const std::string &token, const nlohmann::json &notification)
nlohmann::json getStatus () const
void disconnect ()
Detailed Description
Definition at line 23 of file firebase_manager.cpp.
Constructor & Destructor Documentation
Impl()
satox::core::cloud::FirebaseManager::Impl::Impl () inline
Definition at line 25 of file firebase_manager.cpp.
~Impl()
satox::core::cloud::FirebaseManager::Impl::~Impl () inline
Definition at line 30 of file firebase_manager.cpp.
Member Function Documentation
callFunction()
nlohmann::json satox::core::cloud::FirebaseManager::Impl::callFunction (const std::string & function_name, const nlohmann::json & payload) inline
Definition at line 297 of file firebase_manager.cpp.
References isConnected().
deleteData()
nlohmann::json satox::core::cloud::FirebaseManager::Impl::deleteData (const std::string & path) inline
Definition at line 119 of file firebase_manager.cpp.
References isConnected().
Referenced by executeTransaction().
disconnect()
void satox::core::cloud::FirebaseManager::Impl::disconnect () inline
Definition at line 350 of file firebase_manager.cpp.
downloadFile()
nlohmann::json satox::core::cloud::FirebaseManager::Impl::downloadFile (const std::string & bucket, const std::string & path, const std::string & local_path) inline
Definition at line 277 of file firebase_manager.cpp.
References isConnected().
executeQuery()
nlohmann::json satox::core::cloud::FirebaseManager::Impl::executeQuery (const std::string & service, const nlohmann::json & params) inline
Definition at line 166 of file firebase_manager.cpp.
References isConnected(), and queryData().
executeTransaction()
nlohmann::json satox::core::cloud::FirebaseManager::Impl::executeTransaction (const std::string & service, const std::vector< nlohmann::json > & actions) inline
Definition at line 185 of file firebase_manager.cpp.
References deleteData(), isConnected(), updateData(), and writeData().
getStatus()
nlohmann::json satox::core::cloud::FirebaseManager::Impl::getStatus () const inline
Definition at line 341 of file firebase_manager.cpp.
References isConnected().
initialize()
bool satox::core::cloud::FirebaseManager::Impl::initialize (const FirebaseConfig & config) inline
Definition at line 37 of file firebase_manager.cpp.
isConnected()
bool satox::core::cloud::FirebaseManager::Impl::isConnected () const inline
Definition at line 58 of file firebase_manager.cpp.
Referenced by callFunction(), deleteData(), downloadFile(), executeQuery(), executeTransaction(), getStatus(), queryData(), readData(), sendNotification(), subscribe(), updateData(), uploadFile(), and writeData().
queryData()
nlohmann::json satox::core::cloud::FirebaseManager::Impl::queryData (const std::string & path, const nlohmann::json & query) inline
Definition at line 138 of file firebase_manager.cpp.
References isConnected().
Referenced by executeQuery().
readData()
nlohmann::json satox::core::cloud::FirebaseManager::Impl::readData (const std::string & path) inline
Definition at line 62 of file firebase_manager.cpp.
References isConnected().
sendNotification()
nlohmann::json satox::core::cloud::FirebaseManager::Impl::sendNotification (const std::string & token, const nlohmann::json & notification) inline
Definition at line 316 of file firebase_manager.cpp.
References isConnected().
subscribe()
std::string satox::core::cloud::FirebaseManager::Impl::subscribe (const std::string & path, std::function< void(const nlohmann::json &)> callback) inline
Definition at line 219 of file firebase_manager.cpp.
References isConnected().
unsubscribe()
void satox::core::cloud::FirebaseManager::Impl::unsubscribe (const std::string & subscription_id) inline
Definition at line 242 of file firebase_manager.cpp.
updateData()
nlohmann::json satox::core::cloud::FirebaseManager::Impl::updateData (const std::string & path, const nlohmann::json & data) inline
Definition at line 100 of file firebase_manager.cpp.
References isConnected().
Referenced by executeTransaction().
uploadFile()
nlohmann::json satox::core::cloud::FirebaseManager::Impl::uploadFile (const std::string & bucket, const std::string & path, const std::string & file_path) inline
Definition at line 257 of file firebase_manager.cpp.
References isConnected().
writeData()
nlohmann::json satox::core::cloud::FirebaseManager::Impl::writeData (const std::string & path, const nlohmann::json & data) inline
Definition at line 81 of file firebase_manager.cpp.
References isConnected().
Referenced by executeTransaction().
The documentation for this class was generated from the following file:
src/core/cloud/firebase_manager.cpp