SATOX SDK: satox::security::pqc::MLKEM::Impl Class Reference
satox::security::pqc::MLKEM::Impl Class Reference
Public Member Functions
Impl (SecurityLevel level)
bool generateKeyPair (std::vector< uint8_t > &publicKey, std::vector< uint8_t > &privateKey)
bool encapsulate (const std::vector< uint8_t > &publicKey, std::vector< uint8_t > &ciphertext, std::vector< uint8_t > &sharedSecret)
bool decapsulate (const std::vector< uint8_t > &privateKey, const std::vector< uint8_t > &ciphertext, std::vector< uint8_t > &sharedSecret)
size_t getPublicKeySize () const
size_t getPrivateKeySize () const
size_t getCiphertextSize () const
size_t getSharedSecretSize () const
SecurityLevel getSecurityLevel () const
std::string getLastError () const
void clearLastError ()
Impl (SecurityLevel level)
bool generateKeyPair (std::vector< uint8_t > &publicKey, std::vector< uint8_t > &privateKey)
bool encapsulate (const std::vector< uint8_t > &publicKey, std::vector< uint8_t > &ciphertext, std::vector< uint8_t > &sharedSecret)
bool decapsulate (const std::vector< uint8_t > &privateKey, const std::vector< uint8_t > &ciphertext, std::vector< uint8_t > &sharedSecret)
size_t getPublicKeySize () const
size_t getPrivateKeySize () const
size_t getCiphertextSize () const
size_t getSharedSecretSize () const
SecurityLevel getSecurityLevel () const
std::string getLastError () const
void clearLastError ()
Detailed Description
Definition at line 38 of file ml_kem.cpp.
Constructor & Destructor Documentation
Impl() [1/2]
satox::security::pqc::MLKEM::Impl::Impl (SecurityLevel level) inline
Definition at line 40 of file ml_kem.cpp.
Impl() [2/2]
satox::security::pqc::MLKEM::Impl::Impl (SecurityLevel level) inline
Definition at line 40 of file ml_kem.cpp.
Member Function Documentation
clearLastError() [1/2]
void satox::security::pqc::MLKEM::Impl::clearLastError () inline
Definition at line 152 of file ml_kem.cpp.
clearLastError() [2/2]
void satox::security::pqc::MLKEM::Impl::clearLastError () inline
Definition at line 152 of file ml_kem.cpp.
decapsulate() [1/2]
bool satox::security::pqc::MLKEM::Impl::decapsulate (const std::vector< uint8_t > & privateKey, const std::vector< uint8_t > & ciphertext, std::vector< uint8_t > & sharedSecret) inline
Definition at line 95 of file ml_kem.cpp.
decapsulate() [2/2]
bool satox::security::pqc::MLKEM::Impl::decapsulate (const std::vector< uint8_t > & privateKey, const std::vector< uint8_t > & ciphertext, std::vector< uint8_t > & sharedSecret) inline
Definition at line 95 of file ml_kem.cpp.
encapsulate() [1/2]
bool satox::security::pqc::MLKEM::Impl::encapsulate (const std::vector< uint8_t > & publicKey, std::vector< uint8_t > & ciphertext, std::vector< uint8_t > & sharedSecret) inline
Definition at line 71 of file ml_kem.cpp.
References generateKeyPair().
encapsulate() [2/2]
bool satox::security::pqc::MLKEM::Impl::encapsulate (const std::vector< uint8_t > & publicKey, std::vector< uint8_t > & ciphertext, std::vector< uint8_t > & sharedSecret) inline
Definition at line 71 of file ml_kem.cpp.
References generateKeyPair().
generateKeyPair() [1/2]
bool satox::security::pqc::MLKEM::Impl::generateKeyPair (std::vector< uint8_t > & publicKey, std::vector< uint8_t > & privateKey) inline
Definition at line 46 of file ml_kem.cpp.
References satox::security::pqc::MLKEM::Level1, satox::security::pqc::MLKEM::Level3, and satox::security::pqc::MLKEM::Level5.
Referenced by encapsulate().
generateKeyPair() [2/2]
bool satox::security::pqc::MLKEM::Impl::generateKeyPair (std::vector< uint8_t > & publicKey, std::vector< uint8_t > & privateKey) inline
Definition at line 46 of file ml_kem.cpp.
References satox::security::pqc::MLKEM::Level1, satox::security::pqc::MLKEM::Level3, and satox::security::pqc::MLKEM::Level5.
getCiphertextSize() [1/2]
size_t satox::security::pqc::MLKEM::Impl::getCiphertextSize () const inline
Definition at line 131 of file ml_kem.cpp.
References satox::security::pqc::MLKEM::Level1, satox::security::pqc::MLKEM::Level3, and satox::security::pqc::MLKEM::Level5.
getCiphertextSize() [2/2]
size_t satox::security::pqc::MLKEM::Impl::getCiphertextSize () const inline
Definition at line 131 of file ml_kem.cpp.
References satox::security::pqc::MLKEM::Level1, satox::security::pqc::MLKEM::Level3, and satox::security::pqc::MLKEM::Level5.
getLastError() [1/2]
std::string satox::security::pqc::MLKEM::Impl::getLastError () const inline
Definition at line 148 of file ml_kem.cpp.
getLastError() [2/2]
std::string satox::security::pqc::MLKEM::Impl::getLastError () const inline
Definition at line 148 of file ml_kem.cpp.
getPrivateKeySize() [1/2]
size_t satox::security::pqc::MLKEM::Impl::getPrivateKeySize () const inline
Definition at line 122 of file ml_kem.cpp.
References satox::security::pqc::MLKEM::Level1, satox::security::pqc::MLKEM::Level3, and satox::security::pqc::MLKEM::Level5.
getPrivateKeySize() [2/2]
size_t satox::security::pqc::MLKEM::Impl::getPrivateKeySize () const inline
Definition at line 122 of file ml_kem.cpp.
References satox::security::pqc::MLKEM::Level1, satox::security::pqc::MLKEM::Level3, and satox::security::pqc::MLKEM::Level5.
getPublicKeySize() [1/2]
size_t satox::security::pqc::MLKEM::Impl::getPublicKeySize () const inline
Definition at line 113 of file ml_kem.cpp.
References satox::security::pqc::MLKEM::Level1, satox::security::pqc::MLKEM::Level3, and satox::security::pqc::MLKEM::Level5.
getPublicKeySize() [2/2]
size_t satox::security::pqc::MLKEM::Impl::getPublicKeySize () const inline
Definition at line 113 of file ml_kem.cpp.
References satox::security::pqc::MLKEM::Level1, satox::security::pqc::MLKEM::Level3, and satox::security::pqc::MLKEM::Level5.
getSecurityLevel() [1/2]
SecurityLevel satox::security::pqc::MLKEM::Impl::getSecurityLevel () const inline
Definition at line 144 of file ml_kem.cpp.
getSecurityLevel() [2/2]
SecurityLevel satox::security::pqc::MLKEM::Impl::getSecurityLevel () const inline
Definition at line 144 of file ml_kem.cpp.
getSharedSecretSize() [1/2]
size_t satox::security::pqc::MLKEM::Impl::getSharedSecretSize () const inline
Definition at line 140 of file ml_kem.cpp.
getSharedSecretSize() [2/2]
size_t satox::security::pqc::MLKEM::Impl::getSharedSecretSize () const inline
Definition at line 140 of file ml_kem.cpp.
The documentation for this class was generated from the following files:
src/security/pqc/ml_kem.cpp
src/security/src/ml_kem.cpp