SATOX SDK: satox::core::ProofOfWork Class Reference
satox::core::ProofOfWork Class Reference
#include <proof_of_work.h>
Public Member Functions
ProofOfWork ()
~ProofOfWork ()=default
ProofOfWork (const ProofOfWork &)=delete
ProofOfWork & operator= (const ProofOfWork &)=delete
ProofOfWork (ProofOfWork &&) noexcept=default
ProofOfWork & operator= (ProofOfWork &&) noexcept=default
std::string mineBlock (const std::string &previousHash, const std::string &merkleRoot, uint64_t timestamp, uint64_t difficulty)
bool verifyBlock (const std::string &hash, const std::string &previousHash, const std::string &merkleRoot, uint64_t timestamp, uint64_t difficulty, const std::string &nonce)
Static Public Member Functions
static std::string calculateHash (const std::string &data)
static bool meetsDifficulty (const std::string &hash, uint64_t difficulty)
static uint64_t getDifficulty (uint64_t blockHeight)
Detailed Description
Definition at line 36 of file proof_of_work.h.
Constructor & Destructor Documentation
ProofOfWork() [1/3]
satox::core::ProofOfWork::ProofOfWork ()
Definition at line 44 of file proof_of_work.cpp.
Referenced by operator=(), operator=(), ProofOfWork(), and ProofOfWork().
~ProofOfWork()
satox::core::ProofOfWork::~ProofOfWork () default
ProofOfWork() [2/3]
satox::core::ProofOfWork::ProofOfWork (const ProofOfWork &) delete
References ProofOfWork().
ProofOfWork() [3/3]
satox::core::ProofOfWork::ProofOfWork (ProofOfWork &&) default noexcept
References ProofOfWork().
Member Function Documentation
calculateHash()
std::string satox::core::ProofOfWork::calculateHash (const std::string & data) static
Definition at line 95 of file proof_of_work.cpp.
Referenced by mineBlock(), operator=(), and verifyBlock().
getDifficulty()
uint64_t satox::core::ProofOfWork::getDifficulty (uint64_t blockHeight) static
Definition at line 175 of file proof_of_work.cpp.
Referenced by operator=().
meetsDifficulty()
bool satox::core::ProofOfWork::meetsDifficulty (const std::string & hash, uint64_t difficulty) static
Definition at line 144 of file proof_of_work.cpp.
Referenced by operator=().
mineBlock()
std::string satox::core::ProofOfWork::mineBlock (const std::string & previousHash, const std::string & merkleRoot, uint64_t timestamp, uint64_t difficulty)
Definition at line 46 of file proof_of_work.cpp.
References calculateHash().
Referenced by operator=().
operator=() [1/2]
ProofOfWork & satox::core::ProofOfWork::operator= (const ProofOfWork &) delete
References ProofOfWork().
operator=() [2/2]
ProofOfWork & satox::core::ProofOfWork::operator= (ProofOfWork &&) default noexcept
References calculateHash(), getDifficulty(), meetsDifficulty(), mineBlock(), ProofOfWork(), and verifyBlock().
verifyBlock()
bool satox::core::ProofOfWork::verifyBlock (const std::string & hash, const std::string & previousHash, const std::string & merkleRoot, uint64_t timestamp, uint64_t difficulty, const std::string & nonce)
Definition at line 77 of file proof_of_work.cpp.
References calculateHash().
Referenced by operator=().
The documentation for this class was generated from the following files:
src/core/include/satox/core/proof_of_work.h
src/core/src/proof_of_work.cpp