SATOX SDK: src/blockchain/third_party/keccak/src/KeccakF-1600-reference.c File Reference
KeccakF-1600-reference.c File Reference
#include "KeccakF-1600-reference.h"
#include <string.h>
Macros
#define ROL64(a, offset)
Functions
void KeccakF_1600_Initialize (KeccakF_1600_State *state)
void KeccakF_1600_StateXORBytes (KeccakF_1600_State *state, const unsigned char *data, unsigned int offset, unsigned int length)
void KeccakF_1600_StateExtractBytes (const KeccakF_1600_State *state, unsigned char *data, unsigned int offset, unsigned int length)
void KeccakF_1600_StatePermute (KeccakF_1600_State *state)
Variables
static const uint64_t KeccakF_RoundConstants [KECCAK_F_1600_ROUNDS]
Macro Definition Documentation
ROL64
#define ROL64 (a, offset)
Value:
((((uint64_t)a) << offset) | (((uint64_t)a) >> (64-offset)))
Definition at line 4 of file KeccakF-1600-reference.c.
Referenced by KeccakF_1600_StatePermute().
Function Documentation
KeccakF_1600_Initialize()
void KeccakF_1600_Initialize (KeccakF_1600_State * state)
Definition at line 17 of file KeccakF-1600-reference.c.
References KeccakF_1600_State::A, and KECCAK_F_1600_LANES.
Referenced by KeccakSponge_Initialize().
KeccakF_1600_StateExtractBytes()
void KeccakF_1600_StateExtractBytes (const KeccakF_1600_State * state, unsigned char * data, unsigned int offset, unsigned int length)
Definition at line 28 of file KeccakF-1600-reference.c.
References KeccakF_1600_State::A.
Referenced by KeccakSponge_Squeeze().
KeccakF_1600_StatePermute()
void KeccakF_1600_StatePermute (KeccakF_1600_State * state)
Definition at line 32 of file KeccakF-1600-reference.c.
References KeccakF_1600_State::A, KECCAK_F_1600_LANES, KECCAK_F_1600_ROUNDS, KeccakF_RoundConstants, and ROL64.
Referenced by KeccakSponge_Absorb(), and KeccakSponge_Squeeze().
KeccakF_1600_StateXORBytes()
void KeccakF_1600_StateXORBytes (KeccakF_1600_State * state, const unsigned char * data, unsigned int offset, unsigned int length)
Definition at line 21 of file KeccakF-1600-reference.c.
References KeccakF_1600_State::A.
Referenced by KeccakSponge_Absorb().
Variable Documentation
KeccakF_RoundConstants
const uint64_t KeccakF_RoundConstants[KECCAK_F_1600_ROUNDS] static
Initial value:
= {
    0x0000000000000001ULL, 0x0000000000008082ULL, 0x800000000000808aULL,
    0x8000000080008000ULL, 0x000000000000808bULL, 0x0000000080000001ULL,
    0x8000000080008081ULL, 0x8000000000008009ULL, 0x000000000000008aULL,
    0x0000000000000088ULL, 0x0000000080008009ULL, 0x000000008000000aULL,
    0x000000008000808bULL, 0x800000000000008bULL, 0x8000000000008089ULL,
    0x8000000000008003ULL, 0x8000000000008002ULL, 0x8000000000000080ULL,
    0x000000000000800aULL, 0x800000008000000aULL, 0x8000000080008081ULL,
    0x8000000000008080ULL, 0x0000000080000001ULL, 0x8000000080008008ULL
}
Definition at line 6 of file KeccakF-1600-reference.c.
Referenced by KeccakF_1600_StatePermute().