SATOX SDK: satox::security::pqc::HybridCrypto Class Reference
satox::security::pqc::HybridCrypto Class Reference
#include <hybrid.hpp>
Classes
class Impl
Public Member Functions
HybridCrypto (MLKEM::SecurityLevel kemLevel=MLKEM::SecurityLevel::Level3, MLDSA::SecurityLevel dsaLevel=MLDSA::SecurityLevel::Level3)
~HybridCrypto ()
bool generateHybridKeyPair (std::vector< uint8_t > &publicKey, std::vector< uint8_t > &privateKey)
bool encrypt (const std::vector< uint8_t > &message, const std::vector< uint8_t > &publicKey, std::vector< uint8_t > &ciphertext)
bool decrypt (const std::vector< uint8_t > &ciphertext, const std::vector< uint8_t > &privateKey, std::vector< uint8_t > &message)
bool sign (const std::vector< uint8_t > &message, const std::vector< uint8_t > &privateKey, std::vector< uint8_t > &signature)
bool verify (const std::vector< uint8_t > &message, const std::vector< uint8_t > &signature, const std::vector< uint8_t > &publicKey)
bool rotateKeys (const std::vector< uint8_t > &oldPrivateKey, std::vector< uint8_t > &newPublicKey, std::vector< uint8_t > &newPrivateKey)
size_t getPublicKeySize () const
size_t getPrivateKeySize () const
size_t getCiphertextSize () const
size_t getSignatureSize () const
std::string getLastError () const
void clearLastError ()
HybridCrypto (MLKEM::SecurityLevel kemLevel=MLKEM::SecurityLevel::Level3, MLDSA::SecurityLevel dsaLevel=MLDSA::SecurityLevel::Level3)
~HybridCrypto ()
bool generateHybridKeyPair (std::vector< uint8_t > &publicKey, std::vector< uint8_t > &privateKey)
bool encrypt (const std::vector< uint8_t > &message, const std::vector< uint8_t > &publicKey, std::vector< uint8_t > &ciphertext)
bool decrypt (const std::vector< uint8_t > &ciphertext, const std::vector< uint8_t > &privateKey, std::vector< uint8_t > &message)
bool sign (const std::vector< uint8_t > &message, const std::vector< uint8_t > &privateKey, std::vector< uint8_t > &signature)
bool verify (const std::vector< uint8_t > &message, const std::vector< uint8_t > &signature, const std::vector< uint8_t > &publicKey)
bool rotateKeys (const std::vector< uint8_t > &oldPrivateKey, std::vector< uint8_t > &newPublicKey, std::vector< uint8_t > &newPrivateKey)
size_t getPublicKeySize () const
size_t getPrivateKeySize () const
size_t getCiphertextSize () const
size_t getSignatureSize () const
std::string getLastError () const
void clearLastError ()
Detailed Description
Definition at line 39 of file hybrid.hpp.
Constructor & Destructor Documentation
HybridCrypto() [1/2]
satox::security::pqc::HybridCrypto::HybridCrypto (MLKEM::SecurityLevel kemLevel = MLKEM::SecurityLevel::Level3, MLDSA::SecurityLevel dsaLevel = MLDSA::SecurityLevel::Level3)
Definition at line 351 of file hybrid.cpp.
~HybridCrypto() [1/2]
satox::security::pqc::HybridCrypto::~HybridCrypto () default
HybridCrypto() [2/2]
satox::security::pqc::HybridCrypto::HybridCrypto (MLKEM::SecurityLevel kemLevel = MLKEM::SecurityLevel::Level3, MLDSA::SecurityLevel dsaLevel = MLDSA::SecurityLevel::Level3)
References satox::security::pqc::MLDSA::Level3, and satox::security::pqc::MLKEM::Level3.
~HybridCrypto() [2/2]
satox::security::pqc::HybridCrypto::~HybridCrypto ()
Member Function Documentation
clearLastError() [1/2]
void satox::security::pqc::HybridCrypto::clearLastError ()
Definition at line 420 of file hybrid.cpp.
clearLastError() [2/2]
void satox::security::pqc::HybridCrypto::clearLastError ()
decrypt() [1/2]
bool satox::security::pqc::HybridCrypto::decrypt (const std::vector< uint8_t > & ciphertext, const std::vector< uint8_t > & privateKey, std::vector< uint8_t > & message)
decrypt() [2/2]
bool satox::security::pqc::HybridCrypto::decrypt (const std::vector< uint8_t > & ciphertext, const std::vector< uint8_t > & privateKey, std::vector< uint8_t > & message)
encrypt() [1/2]
bool satox::security::pqc::HybridCrypto::encrypt (const std::vector< uint8_t > & message, const std::vector< uint8_t > & publicKey, std::vector< uint8_t > & ciphertext)
encrypt() [2/2]
bool satox::security::pqc::HybridCrypto::encrypt (const std::vector< uint8_t > & message, const std::vector< uint8_t > & publicKey, std::vector< uint8_t > & ciphertext)
generateHybridKeyPair() [1/2]
bool satox::security::pqc::HybridCrypto::generateHybridKeyPair (std::vector< uint8_t > & publicKey, std::vector< uint8_t > & privateKey)
Definition at line 357 of file hybrid.cpp.
Referenced by satox::security::pqc::KeyManager::Impl::generateAndStoreKey().
generateHybridKeyPair() [2/2]
bool satox::security::pqc::HybridCrypto::generateHybridKeyPair (std::vector< uint8_t > & publicKey, std::vector< uint8_t > & privateKey)
getCiphertextSize() [1/2]
size_t satox::security::pqc::HybridCrypto::getCiphertextSize () const
Definition at line 400 of file hybrid.cpp.
getCiphertextSize() [2/2]
size_t satox::security::pqc::HybridCrypto::getCiphertextSize () const
getLastError() [1/2]
std::string satox::security::pqc::HybridCrypto::getLastError () const
Definition at line 416 of file hybrid.cpp.
Referenced by satox::security::pqc::KeyManager::Impl::generateAndStoreKey(), and satox::security::pqc::KeyManager::Impl::rotateKey().
getLastError() [2/2]
std::string satox::security::pqc::HybridCrypto::getLastError () const
getPrivateKeySize() [1/2]
size_t satox::security::pqc::HybridCrypto::getPrivateKeySize () const
Definition at line 396 of file hybrid.cpp.
getPrivateKeySize() [2/2]
size_t satox::security::pqc::HybridCrypto::getPrivateKeySize () const
getPublicKeySize() [1/2]
size_t satox::security::pqc::HybridCrypto::getPublicKeySize () const
Definition at line 392 of file hybrid.cpp.
getPublicKeySize() [2/2]
size_t satox::security::pqc::HybridCrypto::getPublicKeySize () const
getSignatureSize() [1/2]
size_t satox::security::pqc::HybridCrypto::getSignatureSize () const
Definition at line 404 of file hybrid.cpp.
getSignatureSize() [2/2]
size_t satox::security::pqc::HybridCrypto::getSignatureSize () const
rotateKeys() [1/2]
bool satox::security::pqc::HybridCrypto::rotateKeys (const std::vector< uint8_t > & oldPrivateKey, std::vector< uint8_t > & newPublicKey, std::vector< uint8_t > & newPrivateKey)
Definition at line 386 of file hybrid.cpp.
Referenced by satox::security::pqc::KeyManager::Impl::rotateKey().
rotateKeys() [2/2]
bool satox::security::pqc::HybridCrypto::rotateKeys (const std::vector< uint8_t > & oldPrivateKey, std::vector< uint8_t > & newPublicKey, std::vector< uint8_t > & newPrivateKey)
sign() [1/2]
bool satox::security::pqc::HybridCrypto::sign (const std::vector< uint8_t > & message, const std::vector< uint8_t > & privateKey, std::vector< uint8_t > & signature)
sign() [2/2]
bool satox::security::pqc::HybridCrypto::sign (const std::vector< uint8_t > & message, const std::vector< uint8_t > & privateKey, std::vector< uint8_t > & signature)
verify() [1/2]
bool satox::security::pqc::HybridCrypto::verify (const std::vector< uint8_t > & message, const std::vector< uint8_t > & signature, const std::vector< uint8_t > & publicKey)
verify() [2/2]
bool satox::security::pqc::HybridCrypto::verify (const std::vector< uint8_t > & message, const std::vector< uint8_t > & signature, const std::vector< uint8_t > & publicKey)
The documentation for this class was generated from the following files:
src/security/include/satox/security/pqc/pqc/hybrid.hpp
src/security/include/security/pqc/hybrid.hpp
src/security/pqc/hybrid.cpp
src/security/src/hybrid.cpp