SATOX SDK: satox::core::LoggingManager Class Reference
satox::core::LoggingManager Class Reference
#include <logging_manager.hpp>
Classes
struct LogConfig
struct LogEntry
struct LogStats
Public Types
enum class Level {
TRACE , DEBUG , INFO , WARNING ,
ERROR , FATAL
}
using LogCallback = std::function<void(const LogEntry&)>
Public Member Functions
LoggingManager (const LoggingManager &)=delete
LoggingManager & operator= (const LoggingManager &)=delete
LoggingManager ()
~LoggingManager ()
bool initialize (const LogConfig &config)
void shutdown ()
void log (Level level, const std::string &message, const std::string &source="", const nlohmann::json &metadata=nlohmann::json())
void trace (const std::string &message, const std::string &source="", const nlohmann::json &metadata=nlohmann::json())
void debug (const std::string &message, const std::string &source="", const nlohmann::json &metadata=nlohmann::json())
void info (const std::string &message, const std::string &source="", const nlohmann::json &metadata=nlohmann::json())
void warning (const std::string &message, const std::string &source="", const nlohmann::json &metadata=nlohmann::json())
void error (const std::string &message, const std::string &source="", const nlohmann::json &metadata=nlohmann::json())
void fatal (const std::string &message, const std::string &source="", const nlohmann::json &metadata=nlohmann::json())
void setLogLevel (Level level)
Level getLogLevel () const
void setLogFormat (const std::string &format)
std::string getLogFormat () const
void flush ()
void rotate ()
void registerCallback (LogCallback callback)
void unregisterCallback ()
LogStats getStats () const
std::string getLastError () const
void clearLastError ()
Detailed Description
Definition at line 44 of file logging_manager.hpp.
Member Typedef Documentation
LogCallback
using satox::core::LoggingManager::LogCallback = std::function<void(const LogEntry&)>
Definition at line 85 of file logging_manager.hpp.
Member Enumeration Documentation
Level
enum class satox::core::LoggingManager::Level strong
Enumerator
TRACE
DEBUG
INFO
WARNING
ERROR
FATAL
Definition at line 47 of file logging_manager.hpp.
Constructor & Destructor Documentation
LoggingManager() [1/2]
satox::core::LoggingManager::LoggingManager (const LoggingManager &) delete
References LoggingManager().
Referenced by LoggingManager(), and operator=().
LoggingManager() [2/2]
satox::core::LoggingManager::LoggingManager ()
Definition at line 35 of file logging_manager.cpp.
References INFO.
~LoggingManager()
satox::core::LoggingManager::~LoggingManager ()
Definition at line 55 of file logging_manager.cpp.
References shutdown().
Member Function Documentation
clearLastError()
void satox::core::LoggingManager::clearLastError ()
Definition at line 257 of file logging_manager.cpp.
debug()
void satox::core::LoggingManager::debug (const std::string & message, const std::string & source = "", const nlohmann::json & metadata = nlohmann::json())
Definition at line 147 of file logging_manager.cpp.
References DEBUG, and log().
error()
void satox::core::LoggingManager::error (const std::string & message, const std::string & source = "", const nlohmann::json & metadata = nlohmann::json())
Definition at line 162 of file logging_manager.cpp.
References ERROR, and log().
fatal()
void satox::core::LoggingManager::fatal (const std::string & message, const std::string & source = "", const nlohmann::json & metadata = nlohmann::json())
Definition at line 167 of file logging_manager.cpp.
References FATAL, and log().
flush()
void satox::core::LoggingManager::flush ()
Definition at line 192 of file logging_manager.cpp.
getLastError()
std::string satox::core::LoggingManager::getLastError () const
Definition at line 253 of file logging_manager.cpp.
getLogFormat()
std::string satox::core::LoggingManager::getLogFormat () const
Definition at line 187 of file logging_manager.cpp.
getLogLevel()
LoggingManager::Level satox::core::LoggingManager::getLogLevel () const
Definition at line 177 of file logging_manager.cpp.
getStats()
LoggingManager::LogStats satox::core::LoggingManager::getStats () const
Definition at line 248 of file logging_manager.cpp.
info()
void satox::core::LoggingManager::info (const std::string & message, const std::string & source = "", const nlohmann::json & metadata = nlohmann::json())
Definition at line 152 of file logging_manager.cpp.
References INFO, and log().
initialize()
bool satox::core::LoggingManager::initialize (const LogConfig & config)
Definition at line 59 of file logging_manager.cpp.
References satox::core::LoggingManager::LogStats::lastFlush.
log()
void satox::core::LoggingManager::log (Level level, const std::string & message, const std::string & source = "", const nlohmann::json & metadata = nlohmann::json())
Definition at line 114 of file logging_manager.cpp.
References satox::core::LoggingManager::LogEntry::level, satox::core::LoggingManager::LogEntry::message, satox::core::LoggingManager::LogEntry::metadata, satox::core::LoggingManager::LogEntry::source, satox::core::LoggingManager::LogEntry::threadId, and satox::core::LoggingManager::LogEntry::timestamp.
Referenced by debug(), error(), fatal(), info(), trace(), and warning().
operator=()
LoggingManager & satox::core::LoggingManager::operator= (const LoggingManager &) delete
References LoggingManager().
registerCallback()
void satox::core::LoggingManager::registerCallback (LogCallback callback)
Definition at line 238 of file logging_manager.cpp.
rotate()
void satox::core::LoggingManager::rotate ()
Definition at line 210 of file logging_manager.cpp.
setLogFormat()
void satox::core::LoggingManager::setLogFormat (const std::string & format)
Definition at line 182 of file logging_manager.cpp.
setLogLevel()
void satox::core::LoggingManager::setLogLevel (Level level)
Definition at line 172 of file logging_manager.cpp.
shutdown()
void satox::core::LoggingManager::shutdown ()
Definition at line 95 of file logging_manager.cpp.
Referenced by ~LoggingManager().
trace()
void satox::core::LoggingManager::trace (const std::string & message, const std::string & source = "", const nlohmann::json & metadata = nlohmann::json())
Definition at line 142 of file logging_manager.cpp.
References log(), and TRACE.
unregisterCallback()
void satox::core::LoggingManager::unregisterCallback ()
Definition at line 243 of file logging_manager.cpp.
warning()
void satox::core::LoggingManager::warning (const std::string & message, const std::string & source = "", const nlohmann::json & metadata = nlohmann::json())
Definition at line 157 of file logging_manager.cpp.
References log(), and WARNING.
The documentation for this class was generated from the following files:
src/core/include/satox/core/logging_manager.hpp
src/core/src/logging_manager.cpp