SATOX SDK: satox::core::CacheManager Class Reference
satox::core::CacheManager Class Reference
#include <cache_manager.hpp>
Classes
struct CacheConfig
struct CacheEntry
struct CacheStats
Public Types
using CacheCallback = std::function<void(const std::string&, const std::string&)>
Public Member Functions
CacheManager (const CacheManager &)=delete
CacheManager & operator= (const CacheManager &)=delete
bool initialize (const CacheConfig &config)
void shutdown ()
bool set (const std::string &key, const std::string &value, std::chrono::seconds ttl=std::chrono::seconds(0))
bool set (const std::string &key, const nlohmann::json &value, std::chrono::seconds ttl=std::chrono::seconds(0))
std::optional< std::string > get (const std::string &key)
std::optional< nlohmann::json > getJson (const std::string &key)
bool remove (const std::string &key)
bool exists (const std::string &key)
void clear ()
bool setMulti (const std::unordered_map< std::string, std::string > &entries, std::chrono::seconds ttl=std::chrono::seconds(0))
std::unordered_map< std::string, std::string > getMulti (const std::vector< std::string > &keys)
bool removeMulti (const std::vector< std::string > &keys)
bool setTTL (const std::string &key, std::chrono::seconds ttl)
std::chrono::system_clock::time_point getExpiry (const std::string &key)
size_t getSize (const std::string &key)
size_t getTotalSize ()
size_t getEntryCount ()
CacheStats getStats ()
void registerCallback (CacheCallback callback)
void unregisterCallback ()
void cleanup ()
void resize (size_t newMaxSize)
void setMaxEntries (size_t newMaxEntries)
std::string getLastError () const
void clearLastError ()
Static Public Member Functions
static CacheManager & getInstance ()
Detailed Description
Definition at line 40 of file cache_manager.hpp.
Member Typedef Documentation
CacheCallback
using satox::core::CacheManager::CacheCallback = std::function<void(const std::string&, const std::string&)>
Definition at line 74 of file cache_manager.hpp.
Constructor & Destructor Documentation
CacheManager()
satox::core::CacheManager::CacheManager (const CacheManager &) delete
References CacheManager().
Referenced by CacheManager(), getInstance(), and operator=().
Member Function Documentation
cleanup()
void satox::core::CacheManager::cleanup ()
Definition at line 358 of file cache_manager.cpp.
clear()
void satox::core::CacheManager::clear ()
Definition at line 214 of file cache_manager.cpp.
Referenced by shutdown().
clearLastError()
void satox::core::CacheManager::clearLastError ()
Definition at line 426 of file cache_manager.cpp.
exists()
bool satox::core::CacheManager::exists (const std::string & key)
Definition at line 189 of file cache_manager.cpp.
get()
std::optional< std::string > satox::core::CacheManager::get (const std::string & key)
Definition at line 121 of file cache_manager.cpp.
Referenced by getJson(), and getMulti().
getEntryCount()
size_t satox::core::CacheManager::getEntryCount ()
Definition at line 332 of file cache_manager.cpp.
getExpiry()
std::chrono::system_clock::time_point satox::core::CacheManager::getExpiry (const std::string & key)
Definition at line 295 of file cache_manager.cpp.
getInstance()
CacheManager & satox::core::CacheManager::getInstance () static
Definition at line 33 of file cache_manager.cpp.
References CacheManager().
Referenced by satox::core::SatoxManager::getCacheManager().
getJson()
std::optional< nlohmann::json > satox::core::CacheManager::getJson (const std::string & key)
Definition at line 155 of file cache_manager.cpp.
References get().
getLastError()
std::string satox::core::CacheManager::getLastError () const
Definition at line 422 of file cache_manager.cpp.
getMulti()
std::unordered_map< std::string, std::string > satox::core::CacheManager::getMulti (const std::vector< std::string > & keys)
Definition at line 240 of file cache_manager.cpp.
References get().
getSize()
size_t satox::core::CacheManager::getSize (const std::string & key)
Definition at line 311 of file cache_manager.cpp.
getStats()
CacheManager::CacheStats satox::core::CacheManager::getStats ()
Definition at line 337 of file cache_manager.cpp.
getTotalSize()
size_t satox::core::CacheManager::getTotalSize ()
Definition at line 327 of file cache_manager.cpp.
initialize()
bool satox::core::CacheManager::initialize (const CacheConfig & config)
Definition at line 38 of file cache_manager.cpp.
References satox::core::CacheManager::CacheConfig::maxEntries, satox::core::CacheManager::CacheConfig::maxSize, and satox::core::CacheManager::CacheStats::maxSize.
operator=()
CacheManager & satox::core::CacheManager::operator= (const CacheManager &) delete
References CacheManager().
registerCallback()
void satox::core::CacheManager::registerCallback (CacheCallback callback)
Definition at line 348 of file cache_manager.cpp.
remove()
bool satox::core::CacheManager::remove (const std::string & key)
Definition at line 169 of file cache_manager.cpp.
Referenced by removeMulti().
removeMulti()
bool satox::core::CacheManager::removeMulti (const std::vector< std::string > & keys)
Definition at line 261 of file cache_manager.cpp.
References remove().
resize()
void satox::core::CacheManager::resize (size_t newMaxSize)
Definition at line 385 of file cache_manager.cpp.
set() [1/2]
bool satox::core::CacheManager::set (const std::string & key, const nlohmann::json & value, std::chrono::seconds ttl = std::chrono::seconds(0))
Definition at line 116 of file cache_manager.cpp.
References set().
set() [2/2]
bool satox::core::CacheManager::set (const std::string & key, const std::string & value, std::chrono::seconds ttl = std::chrono::seconds(0))
Definition at line 67 of file cache_manager.cpp.
References satox::core::CacheManager::CacheEntry::accessCount, satox::core::CacheManager::CacheEntry::expiry, satox::core::CacheManager::CacheEntry::key, satox::core::CacheManager::CacheEntry::lastAccess, satox::core::CacheManager::CacheEntry::size, and satox::core::CacheManager::CacheEntry::value.
Referenced by set(), and setMulti().
setMaxEntries()
void satox::core::CacheManager::setMaxEntries (size_t newMaxEntries)
Definition at line 404 of file cache_manager.cpp.
setMulti()
bool satox::core::CacheManager::setMulti (const std::unordered_map< std::string, std::string > & entries, std::chrono::seconds ttl = std::chrono::seconds(0))
Definition at line 222 of file cache_manager.cpp.
References set().
setTTL()
bool satox::core::CacheManager::setTTL (const std::string & key, std::chrono::seconds ttl)
Definition at line 278 of file cache_manager.cpp.
shutdown()
void satox::core::CacheManager::shutdown ()
Definition at line 59 of file cache_manager.cpp.
References clear().
unregisterCallback()
void satox::core::CacheManager::unregisterCallback ()
Definition at line 353 of file cache_manager.cpp.
The documentation for this class was generated from the following files:
src/core/include/satox/core/cache_manager.hpp
src/core/src/cache_manager.cpp