SATOX SDK: satox::security::pqc::MLDSA Class Reference
satox::security::pqc::MLDSA Class Reference
#include <ml_dsa.hpp>
Classes
class Impl
Public Types
enum class SecurityLevel {
Level2 = 2 , Level3 = 3 , Level5 = 5 , Level2 = 2 ,
Level3 = 3 , Level5 = 5
}
enum class SecurityLevel {
Level2 = 2 , Level3 = 3 , Level5 = 5 , Level2 = 2 ,
Level3 = 3 , Level5 = 5
}
Public Member Functions
MLDSA (SecurityLevel level=SecurityLevel::Level3)
~MLDSA ()
bool generateKeyPair (std::vector< uint8_t > &publicKey, std::vector< uint8_t > &privateKey)
bool sign (const std::vector< uint8_t > &message, const std::vector< uint8_t > &privateKey, std::vector< uint8_t > &signature)
bool verify (const std::vector< uint8_t > &message, const std::vector< uint8_t > &signature, const std::vector< uint8_t > &publicKey)
size_t getPublicKeySize () const
size_t getPrivateKeySize () const
size_t getSignatureSize () const
SecurityLevel getSecurityLevel () const
std::string getLastError () const
void clearLastError ()
MLDSA (SecurityLevel level=SecurityLevel::Level3)
~MLDSA ()
bool generateKeyPair (std::vector< uint8_t > &publicKey, std::vector< uint8_t > &privateKey)
bool sign (const std::vector< uint8_t > &message, const std::vector< uint8_t > &privateKey, std::vector< uint8_t > &signature)
bool verify (const std::vector< uint8_t > &message, const std::vector< uint8_t > &signature, const std::vector< uint8_t > &publicKey)
size_t getPublicKeySize () const
size_t getPrivateKeySize () const
size_t getSignatureSize () const
SecurityLevel getSecurityLevel () const
std::string getLastError () const
void clearLastError ()
Detailed Description
Definition at line 37 of file ml_dsa.hpp.
Member Enumeration Documentation
SecurityLevel [1/2]
enum class satox::security::pqc::MLDSA::SecurityLevel strong
Enumerator
Level2
Level3
Level5
Level2
Level3
Level5
Definition at line 40 of file ml_dsa.hpp.
SecurityLevel [2/2]
enum class satox::security::pqc::MLDSA::SecurityLevel strong
Enumerator
Level2
Level3
Level5
Level2
Level3
Level5
Definition at line 40 of file ml_dsa.hpp.
Constructor & Destructor Documentation
MLDSA() [1/2]
satox::security::pqc::MLDSA::MLDSA (SecurityLevel level = SecurityLevel::Level3) explicit
Definition at line 192 of file ml_dsa.cpp.
~MLDSA() [1/2]
satox::security::pqc::MLDSA::~MLDSA () default
MLDSA() [2/2]
satox::security::pqc::MLDSA::MLDSA (SecurityLevel level = SecurityLevel::Level3) explicit
References Level3.
~MLDSA() [2/2]
satox::security::pqc::MLDSA::~MLDSA ()
Member Function Documentation
clearLastError() [1/2]
void satox::security::pqc::MLDSA::clearLastError ()
Definition at line 234 of file ml_dsa.cpp.
clearLastError() [2/2]
void satox::security::pqc::MLDSA::clearLastError ()
generateKeyPair() [1/2]
bool satox::security::pqc::MLDSA::generateKeyPair (std::vector< uint8_t > & publicKey, std::vector< uint8_t > & privateKey)
Definition at line 197 of file ml_dsa.cpp.
Referenced by satox::security::pqc::HybridCrypto::Impl::generateHybridKeyPair().
generateKeyPair() [2/2]
bool satox::security::pqc::MLDSA::generateKeyPair (std::vector< uint8_t > & publicKey, std::vector< uint8_t > & privateKey)
getLastError() [1/2]
std::string satox::security::pqc::MLDSA::getLastError () const
Definition at line 230 of file ml_dsa.cpp.
Referenced by satox::security::pqc::HybridCrypto::Impl::generateHybridKeyPair(), satox::security::pqc::HybridCrypto::Impl::hybridDecrypt(), satox::security::pqc::HybridCrypto::Impl::hybridEncrypt(), satox::security::pqc::HybridCrypto::Impl::hybridSign(), and satox::security::pqc::HybridCrypto::Impl::hybridVerify().
getLastError() [2/2]
std::string satox::security::pqc::MLDSA::getLastError () const
getPrivateKeySize() [1/2]
size_t satox::security::pqc::MLDSA::getPrivateKeySize () const
Definition at line 218 of file ml_dsa.cpp.
Referenced by satox::security::pqc::HybridCrypto::Impl::getPrivateKeySize().
getPrivateKeySize() [2/2]
size_t satox::security::pqc::MLDSA::getPrivateKeySize () const
getPublicKeySize() [1/2]
size_t satox::security::pqc::MLDSA::getPublicKeySize () const
Definition at line 214 of file ml_dsa.cpp.
Referenced by satox::security::pqc::HybridCrypto::Impl::getPublicKeySize().
getPublicKeySize() [2/2]
size_t satox::security::pqc::MLDSA::getPublicKeySize () const
getSecurityLevel() [1/2]
MLDSA::SecurityLevel satox::security::pqc::MLDSA::getSecurityLevel () const
Definition at line 226 of file ml_dsa.cpp.
getSecurityLevel() [2/2]
SecurityLevel satox::security::pqc::MLDSA::getSecurityLevel () const
getSignatureSize() [1/2]
size_t satox::security::pqc::MLDSA::getSignatureSize () const
Definition at line 222 of file ml_dsa.cpp.
Referenced by satox::security::pqc::HybridCrypto::Impl::getCiphertextSize(), and satox::security::pqc::HybridCrypto::Impl::getSignatureSize().
getSignatureSize() [2/2]
size_t satox::security::pqc::MLDSA::getSignatureSize () const
sign() [1/2]
bool satox::security::pqc::MLDSA::sign (const std::vector< uint8_t > & message, const std::vector< uint8_t > & privateKey, std::vector< uint8_t > & signature)
Definition at line 202 of file ml_dsa.cpp.
Referenced by satox::security::pqc::HybridCrypto::Impl::hybridEncrypt(), and satox::security::pqc::HybridCrypto::Impl::hybridSign().
sign() [2/2]
bool satox::security::pqc::MLDSA::sign (const std::vector< uint8_t > & message, const std::vector< uint8_t > & privateKey, std::vector< uint8_t > & signature)
verify() [1/2]
bool satox::security::pqc::MLDSA::verify (const std::vector< uint8_t > & message, const std::vector< uint8_t > & signature, const std::vector< uint8_t > & publicKey)
Definition at line 208 of file ml_dsa.cpp.
Referenced by satox::security::pqc::HybridCrypto::Impl::hybridDecrypt(), and satox::security::pqc::HybridCrypto::Impl::hybridVerify().
verify() [2/2]
bool satox::security::pqc::MLDSA::verify (const std::vector< uint8_t > & message, const std::vector< uint8_t > & signature, const std::vector< uint8_t > & publicKey)
The documentation for this class was generated from the following files:
src/security/include/satox/security/pqc/pqc/ml_dsa.hpp
src/security/include/security/pqc/ml_dsa.hpp
src/security/pqc/ml_dsa.cpp
src/security/src/ml_dsa.cpp