SATOX SDK: satox::core::ConfigManager Class Reference
satox::core::ConfigManager Class Reference
#include <config_manager.hpp>
Classes
struct ConfigSection
struct ConfigValue
struct Stats
Public Types
enum class ValueType {
STRING , INTEGER , FLOAT , BOOLEAN ,
ARRAY , OBJECT , NULL_VALUE
}
using ConfigCallback = std::function<void(const std::string&, const ConfigValue&)>
using ErrorCallback = std::function<void(const std::string&)>
Public Member Functions
ConfigManager (const ConfigManager &)=delete
ConfigManager & operator= (const ConfigManager &)=delete
bool initialize (const std::string &config_path="")
bool shutdown ()
bool loadConfig (const std::string &path)
bool saveConfig (const std::string &path="")
bool reloadConfig ()
bool validateConfig ()
bool createSection (const std::string &section)
bool deleteSection (const std::string &section)
bool hasSection (const std::string &section) const
std::vector< std::string > getSections () const
bool setValue (const std::string &section, const std::string &key, const ConfigValue &value)
bool setString (const std::string &section, const std::string &key, const std::string &value)
bool setInt (const std::string &section, const std::string &key, int64_t value)
bool setFloat (const std::string &section, const std::string &key, double value)
bool setBool (const std::string &section, const std::string &key, bool value)
bool setArray (const std::string &section, const std::string &key, const std::vector< ConfigValue > &value)
bool setObject (const std::string &section, const std::string &key, const std::unordered_map< std::string, ConfigValue > &value)
std::optional< ConfigValue > getValue (const std::string &section, const std::string &key) const
std::optional< std::string > getString (const std::string &section, const std::string &key) const
std::optional< int64_t > getInt (const std::string &section, const std::string &key) const
std::optional< double > getFloat (const std::string &section, const std::string &key) const
std::optional< bool > getBool (const std::string &section, const std::string &key) const
std::optional< std::vector< ConfigValue > > getArray (const std::string &section, const std::string &key) const
std::optional< std::unordered_map< std::string, ConfigValue > > getObject (const std::string &section, const std::string &key) const
bool hasValue (const std::string &section, const std::string &key) const
bool deleteValue (const std::string &section, const std::string &key)
std::vector< std::string > getKeys (const std::string &section) const
bool setDefaultValue (const std::string &section, const std::string &key, const ConfigValue &value)
bool setDefaultString (const std::string &section, const std::string &key, const std::string &value)
bool setDefaultInt (const std::string &section, const std::string &key, int64_t value)
bool setDefaultFloat (const std::string &section, const std::string &key, double value)
bool setDefaultBool (const std::string &section, const std::string &key, bool value)
bool setDefaultArray (const std::string &section, const std::string &key, const std::vector< ConfigValue > &value)
bool setDefaultObject (const std::string &section, const std::string &key, const std::unordered_map< std::string, ConfigValue > &value)
bool loadFromEnvironment (const std::string &prefix="")
bool setFromEnvironment (const std::string &section, const std::string &key, const std::string &envVar)
void registerConfigCallback (ConfigCallback callback)
void registerErrorCallback (ErrorCallback callback)
bool validateValue (const ConfigValue &value) const
bool validateSection (const std::string &section) const
bool validateKey (const std::string &key) const
std::string getLastError () const
void clearLastError ()
Stats getStats () const
bool isHealthy () const
Static Public Member Functions
static ConfigManager & getInstance ()
Detailed Description
Definition at line 23 of file config_manager.hpp.
Member Typedef Documentation
ConfigCallback
using satox::core::ConfigManager::ConfigCallback = std::function<void(const std::string&, const ConfigValue&)>
Definition at line 54 of file config_manager.hpp.
ErrorCallback
using satox::core::ConfigManager::ErrorCallback = std::function<void(const std::string&)>
Definition at line 55 of file config_manager.hpp.
Member Enumeration Documentation
ValueType
enum class satox::core::ConfigManager::ValueType strong
Enumerator
STRING
INTEGER
FLOAT
BOOLEAN
ARRAY
OBJECT
NULL_VALUE
Definition at line 26 of file config_manager.hpp.
Constructor & Destructor Documentation
ConfigManager()
satox::core::ConfigManager::ConfigManager (const ConfigManager &) delete
References ConfigManager().
Referenced by ConfigManager(), getInstance(), and operator=().
Member Function Documentation
clearLastError()
void satox::core::ConfigManager::clearLastError ()
Definition at line 558 of file config_manager.cpp.
createSection()
bool satox::core::ConfigManager::createSection (const std::string & section)
Definition at line 158 of file config_manager.cpp.
References validateSection().
deleteSection()
bool satox::core::ConfigManager::deleteSection (const std::string & section)
Definition at line 174 of file config_manager.cpp.
deleteValue()
bool satox::core::ConfigManager::deleteValue (const std::string & section, const std::string & key)
Definition at line 357 of file config_manager.cpp.
getArray()
std::optional< std::vector< ConfigManager::ConfigValue > > satox::core::ConfigManager::getArray (const std::string & section, const std::string & key) const
Definition at line 325 of file config_manager.cpp.
References ARRAY, and getValue().
getBool()
std::optional< bool > satox::core::ConfigManager::getBool (const std::string & section, const std::string & key) const
Definition at line 316 of file config_manager.cpp.
References BOOLEAN, and getValue().
getFloat()
std::optional< double > satox::core::ConfigManager::getFloat (const std::string & section, const std::string & key) const
Definition at line 307 of file config_manager.cpp.
References FLOAT, and getValue().
getInstance()
ConfigManager & satox::core::ConfigManager::getInstance () static
Definition at line 36 of file config_manager.cpp.
References ConfigManager().
Referenced by satox::core::SatoxManager::getConfigManager(), and main().
getInt()
std::optional< int64_t > satox::core::ConfigManager::getInt (const std::string & section, const std::string & key) const
Definition at line 298 of file config_manager.cpp.
References getValue(), and INTEGER.
getKeys()
std::vector< std::string > satox::core::ConfigManager::getKeys (const std::string & section) const
Definition at line 374 of file config_manager.cpp.
getLastError()
std::string satox::core::ConfigManager::getLastError () const
Definition at line 553 of file config_manager.cpp.
getObject()
std::optional< std::unordered_map< std::string, ConfigManager::ConfigValue > > satox::core::ConfigManager::getObject (const std::string & section, const std::string & key) const
Definition at line 339 of file config_manager.cpp.
References getValue(), and OBJECT.
getSections()
std::vector< std::string > satox::core::ConfigManager::getSections () const
Definition at line 191 of file config_manager.cpp.
getStats()
ConfigManager::Stats satox::core::ConfigManager::getStats () const
Definition at line 563 of file config_manager.cpp.
getString()
std::optional< std::string > satox::core::ConfigManager::getString (const std::string & section, const std::string & key) const
Definition at line 289 of file config_manager.cpp.
References getValue(), and STRING.
getValue()
std::optional< ConfigManager::ConfigValue > satox::core::ConfigManager::getValue (const std::string & section, const std::string & key) const
Definition at line 272 of file config_manager.cpp.
Referenced by getArray(), getBool(), getFloat(), getInt(), getObject(), getString(), and hasValue().
hasSection()
bool satox::core::ConfigManager::hasSection (const std::string & section) const
Definition at line 186 of file config_manager.cpp.
hasValue()
bool satox::core::ConfigManager::hasValue (const std::string & section, const std::string & key) const
Definition at line 353 of file config_manager.cpp.
References getValue().
initialize()
bool satox::core::ConfigManager::initialize (const std::string & config_path = "")
Definition at line 41 of file config_manager.cpp.
References loadConfig().
isHealthy()
bool satox::core::ConfigManager::isHealthy () const
Definition at line 568 of file config_manager.cpp.
loadConfig()
bool satox::core::ConfigManager::loadConfig (const std::string & path)
Definition at line 75 of file config_manager.cpp.
Referenced by initialize(), and reloadConfig().
loadFromEnvironment()
bool satox::core::ConfigManager::loadFromEnvironment (const std::string & prefix = "")
Definition at line 457 of file config_manager.cpp.
References setValue().
operator=()
ConfigManager & satox::core::ConfigManager::operator= (const ConfigManager &) delete
References ConfigManager().
registerConfigCallback()
void satox::core::ConfigManager::registerConfigCallback (ConfigCallback callback)
Definition at line 492 of file config_manager.cpp.
registerErrorCallback()
void satox::core::ConfigManager::registerErrorCallback (ErrorCallback callback)
Definition at line 497 of file config_manager.cpp.
reloadConfig()
bool satox::core::ConfigManager::reloadConfig ()
Definition at line 129 of file config_manager.cpp.
References loadConfig().
saveConfig()
bool satox::core::ConfigManager::saveConfig (const std::string & path = "")
Definition at line 107 of file config_manager.cpp.
setArray()
bool satox::core::ConfigManager::setArray (const std::string & section, const std::string & key, const std::vector< ConfigValue > & value)
Definition at line 250 of file config_manager.cpp.
References ARRAY, satox::core::ConfigManager::ConfigValue::complexValue, setValue(), and satox::core::ConfigManager::ConfigValue::type.
setBool()
bool satox::core::ConfigManager::setBool (const std::string & section, const std::string & key, bool value)
Definition at line 242 of file config_manager.cpp.
References BOOLEAN, satox::core::ConfigManager::ConfigValue::boolValue, setValue(), and satox::core::ConfigManager::ConfigValue::type.
setDefaultArray()
bool satox::core::ConfigManager::setDefaultArray (const std::string & section, const std::string & key, const std::vector< ConfigValue > & value)
Definition at line 435 of file config_manager.cpp.
References ARRAY, satox::core::ConfigManager::ConfigValue::complexValue, setDefaultValue(), and satox::core::ConfigManager::ConfigValue::type.
setDefaultBool()
bool satox::core::ConfigManager::setDefaultBool (const std::string & section, const std::string & key, bool value)
Definition at line 427 of file config_manager.cpp.
References BOOLEAN, satox::core::ConfigManager::ConfigValue::boolValue, setDefaultValue(), and satox::core::ConfigManager::ConfigValue::type.
setDefaultFloat()
bool satox::core::ConfigManager::setDefaultFloat (const std::string & section, const std::string & key, double value)
Definition at line 419 of file config_manager.cpp.
References FLOAT, satox::core::ConfigManager::ConfigValue::floatValue, setDefaultValue(), and satox::core::ConfigManager::ConfigValue::type.
setDefaultInt()
bool satox::core::ConfigManager::setDefaultInt (const std::string & section, const std::string & key, int64_t value)
Definition at line 411 of file config_manager.cpp.
References INTEGER, satox::core::ConfigManager::ConfigValue::intValue, setDefaultValue(), and satox::core::ConfigManager::ConfigValue::type.
setDefaultObject()
bool satox::core::ConfigManager::setDefaultObject (const std::string & section, const std::string & key, const std::unordered_map< std::string, ConfigValue > & value)
Definition at line 446 of file config_manager.cpp.
References satox::core::ConfigManager::ConfigValue::complexValue, OBJECT, setDefaultValue(), and satox::core::ConfigManager::ConfigValue::type.
setDefaultString()
bool satox::core::ConfigManager::setDefaultString (const std::string & section, const std::string & key, const std::string & value)
Definition at line 403 of file config_manager.cpp.
References setDefaultValue(), STRING, satox::core::ConfigManager::ConfigValue::stringValue, and satox::core::ConfigManager::ConfigValue::type.
setDefaultValue()
bool satox::core::ConfigManager::setDefaultValue (const std::string & section, const std::string & key, const ConfigValue & value)
Definition at line 390 of file config_manager.cpp.
References validateKey(), validateSection(), and validateValue().
Referenced by setDefaultArray(), setDefaultBool(), setDefaultFloat(), setDefaultInt(), setDefaultObject(), and setDefaultString().
setFloat()
bool satox::core::ConfigManager::setFloat (const std::string & section, const std::string & key, double value)
Definition at line 234 of file config_manager.cpp.
References FLOAT, satox::core::ConfigManager::ConfigValue::floatValue, setValue(), and satox::core::ConfigManager::ConfigValue::type.
setFromEnvironment()
bool satox::core::ConfigManager::setFromEnvironment (const std::string & section, const std::string & key, const std::string & envVar)
Definition at line 479 of file config_manager.cpp.
References setValue(), STRING, satox::core::ConfigManager::ConfigValue::stringValue, and satox::core::ConfigManager::ConfigValue::type.
setInt()
bool satox::core::ConfigManager::setInt (const std::string & section, const std::string & key, int64_t value)
Definition at line 226 of file config_manager.cpp.
References INTEGER, satox::core::ConfigManager::ConfigValue::intValue, setValue(), and satox::core::ConfigManager::ConfigValue::type.
setObject()
bool satox::core::ConfigManager::setObject (const std::string & section, const std::string & key, const std::unordered_map< std::string, ConfigValue > & value)
Definition at line 261 of file config_manager.cpp.
References satox::core::ConfigManager::ConfigValue::complexValue, OBJECT, setValue(), and satox::core::ConfigManager::ConfigValue::type.
setString()
bool satox::core::ConfigManager::setString (const std::string & section, const std::string & key, const std::string & value)
Definition at line 218 of file config_manager.cpp.
References setValue(), STRING, satox::core::ConfigManager::ConfigValue::stringValue, and satox::core::ConfigManager::ConfigValue::type.
setValue()
bool satox::core::ConfigManager::setValue (const std::string & section, const std::string & key, const ConfigValue & value)
Definition at line 201 of file config_manager.cpp.
References validateKey(), validateSection(), and validateValue().
Referenced by loadFromEnvironment(), setArray(), setBool(), setFloat(), setFromEnvironment(), setInt(), setObject(), and setString().
shutdown()
bool satox::core::ConfigManager::shutdown ()
Definition at line 59 of file config_manager.cpp.
validateConfig()
bool satox::core::ConfigManager::validateConfig ()
Definition at line 140 of file config_manager.cpp.
References validateKey(), validateSection(), and validateValue().
validateKey()
bool satox::core::ConfigManager::validateKey (const std::string & key) const
Definition at line 538 of file config_manager.cpp.
Referenced by setDefaultValue(), setValue(), and validateConfig().
validateSection()
bool satox::core::ConfigManager::validateSection (const std::string & section) const
Definition at line 523 of file config_manager.cpp.
Referenced by createSection(), setDefaultValue(), setValue(), and validateConfig().
validateValue()
bool satox::core::ConfigManager::validateValue (const ConfigValue & value) const
Definition at line 502 of file config_manager.cpp.
References ARRAY, BOOLEAN, satox::core::ConfigManager::ConfigValue::complexValue, FLOAT, satox::core::ConfigManager::ConfigValue::floatValue, INTEGER, NULL_VALUE, OBJECT, STRING, satox::core::ConfigManager::ConfigValue::stringValue, and satox::core::ConfigManager::ConfigValue::type.
Referenced by setDefaultValue(), setValue(), and validateConfig().
The documentation for this class was generated from the following files:
src/core/include/satox/core/config_manager.hpp
src/core/src/config_manager.cpp