SATOX SDK: satox::nft::NFTManager Class Reference
satox::nft::NFTManager Class Reference
#include <nft_manager.hpp>
Classes
struct CacheEntry
struct Error
class ErrorHandler
class Impl
struct NFT
struct NFTEvent
class NFTEventListener
struct NFTMetadata
struct OwnershipRecord
class PerformanceOptimizer
Public Types
enum class NFTEventType {
CREATED , TRANSFERRED , BURNED , METADATA_UPDATED ,
TRANSFERABLE_CHANGED , BURNABLE_CHANGED , ROYALTY_CHANGED , ATTRIBUTE_ADDED ,
ATTRIBUTE_REMOVED
}
using EventCallback = std::function<void(const NFTEvent&)>
Public Member Functions
NFTManager (const NFTManager &)=delete
NFTManager & operator= (const NFTManager &)=delete
bool initialize ()
void shutdown ()
bool isInitialized () const
bool isHealthy () const
std::string createNFT (const std::string &contractAddress, const NFTMetadata &metadata, const std::string &creator, bool isTransferable=true, bool isBurnable=true, const std::string &royaltyRecipient="", uint32_t royaltyBasisPoints=0)
bool transferNFT (const std::string &nftId, const std::string &from, const std::string &to)
bool burnNFT (const std::string &nftId, const std::string &owner)
bool updateNFTMetadata (const std::string &nftId, const NFTMetadata &newMetadata, const std::string &updater)
bool addNFTAttribute (const std::string &nftId, const std::string &key, const std::string &value, const std::string &updater)
bool removeNFTAttribute (const std::string &nftId, const std::string &key, const std::string &updater)
bool setNFTTransferable (const std::string &nftId, bool isTransferable)
bool setNFTBurnable (const std::string &nftId, bool isBurnable)
bool setNFTRoyalty (const std::string &nftId, const std::string &recipient, uint32_t basisPoints)
bool validateNFT (const NFT &nft)
bool validateNFTMetadata (const NFTMetadata &metadata)
bool validateTransfer (const std::string &nftId, const std::string &from, const std::string &to)
NFT getNFT (const std::string &nftId)
std::vector< NFT > getNFTsByOwner (const std::string &owner)
std::vector< NFT > getNFTsByContract (const std::string &contractAddress)
std::vector< NFT > getNFTsByCreator (const std::string &creator)
bool isNFTTransferable (const std::string &nftId)
bool isNFTBurnable (const std::string &nftId)
std::string getNFTOwner (const std::string &nftId)
NFTMetadata getNFTMetadata (const std::string &nftId)
std::vector< std::string > batchCreateNFTs (const std::string &contractAddress, const std::vector< NFTMetadata > &metadataList, const std::string &creator)
bool batchTransferNFTs (const std::vector< std::string > &nftIds, const std::string &from, const std::string &to)
bool batchBurnNFTs (const std::vector< std::string > &nftIds, const std::string &owner)
void registerEventCallback (EventCallback callback)
void unregisterEventCallback ()
Error getLastError () const
void clearLastError ()
std::vector< OwnershipRecord > getOwnershipHistory (const std::string &nftId)
std::string getCurrentOwner (const std::string &nftId)
bool verifyOwnership (const std::string &nftId, const std::string &owner)
void setCacheSize (size_t size)
void setBatchSize (size_t size)
void setConnectionPoolSize (size_t size)
void clearCache ()
size_t getCacheSize () const
size_t getBatchSize () const
size_t getConnectionPoolSize () const
void setErrorCallback (std::function< void(const NFTError &)> callback)
void setRecoveryCallback (std::function< void(const NFTError &)> callback)
std::vector< NFTError > getErrorHistory () const
void clearErrorHistory ()
bool isErrorActive (const std::string &nftId) const
void addEventListener (NFTEventListener *listener)
void removeEventListener (NFTEventListener *listener)
Static Public Member Functions
static NFTManager & getInstance ()
Detailed Description
Definition at line 78 of file nft_manager.hpp.
Member Typedef Documentation
EventCallback
using satox::nft::NFTManager::EventCallback = std::function<void(const NFTEvent&)>
Definition at line 193 of file nft_manager.hpp.
Member Enumeration Documentation
NFTEventType
enum class satox::nft::NFTManager::NFTEventType strong
Enumerator
CREATED
TRANSFERRED
BURNED
METADATA_UPDATED
TRANSFERABLE_CHANGED
BURNABLE_CHANGED
ROYALTY_CHANGED
ATTRIBUTE_ADDED
ATTRIBUTE_REMOVED
Definition at line 131 of file nft_manager.hpp.
Constructor & Destructor Documentation
NFTManager()
satox::nft::NFTManager::NFTManager (const NFTManager &) delete
References NFTManager().
Referenced by getErrorHistory(), getInstance(), isErrorActive(), NFTManager(), and operator=().
Member Function Documentation
addEventListener()
void satox::nft::NFTManager::addEventListener (NFTEventListener * listener)
Definition at line 825 of file nft_manager.cpp.
References satox::nft::VALIDATION_ERROR.
addNFTAttribute()
bool satox::nft::NFTManager::addNFTAttribute (const std::string & nftId, const std::string & key, const std::string & value, const std::string & updater)
Definition at line 314 of file nft_manager.cpp.
References satox::nft::INVALID_ID, satox::nft::NOT_INITIALIZED, and satox::nft::VALIDATION_ERROR.
batchBurnNFTs()
bool satox::nft::NFTManager::batchBurnNFTs (const std::vector< std::string > & nftIds, const std::string & owner)
Definition at line 650 of file nft_manager.cpp.
References burnNFT().
batchCreateNFTs()
std::vector< std::string > satox::nft::NFTManager::batchCreateNFTs (const std::string & contractAddress, const std::vector< NFTMetadata > & metadataList, const std::string & creator)
Definition at line 626 of file nft_manager.cpp.
References createNFT().
batchTransferNFTs()
bool satox::nft::NFTManager::batchTransferNFTs (const std::vector< std::string > & nftIds, const std::string & from, const std::string & to)
Definition at line 639 of file nft_manager.cpp.
References transferNFT().
burnNFT()
bool satox::nft::NFTManager::burnNFT (const std::string & nftId, const std::string & owner)
Definition at line 246 of file nft_manager.cpp.
References satox::nft::INVALID_ID, satox::nft::INVALID_OPERATION, satox::nft::INVALID_OWNER, satox::nft::NOT_INITIALIZED, and satox::nft::QUERY_ERROR.
Referenced by batchBurnNFTs().
clearCache()
void satox::nft::NFTManager::clearCache ()
Definition at line 758 of file nft_manager.cpp.
clearErrorHistory()
void satox::nft::NFTManager::clearErrorHistory ()
Definition at line 804 of file nft_manager.cpp.
clearLastError()
void satox::nft::NFTManager::clearLastError ()
Definition at line 685 of file nft_manager.cpp.
createNFT()
std::string satox::nft::NFTManager::createNFT (const std::string & contractAddress, const NFTMetadata & metadata, const std::string & creator, bool isTransferable = true, bool isBurnable = true, const std::string & royaltyRecipient = "", uint32_t royaltyBasisPoints = 0)
Definition at line 127 of file nft_manager.cpp.
References satox::nft::NOT_INITIALIZED, validateNFTMetadata(), and satox::nft::VALIDATION_ERROR.
Referenced by batchCreateNFTs().
getBatchSize()
size_t satox::nft::NFTManager::getBatchSize () const
Definition at line 768 of file nft_manager.cpp.
getCacheSize()
size_t satox::nft::NFTManager::getCacheSize () const
Definition at line 763 of file nft_manager.cpp.
getConnectionPoolSize()
size_t satox::nft::NFTManager::getConnectionPoolSize () const
Definition at line 773 of file nft_manager.cpp.
getCurrentOwner()
std::string satox::nft::NFTManager::getCurrentOwner (const std::string & nftId)
Definition at line 736 of file nft_manager.cpp.
References getNFTOwner().
getErrorHistory()
std::vector< NFTError > satox::nft::NFTManager::getErrorHistory () const
Definition at line 787 of file nft_manager.cpp.
References NFTManager(), satox::nft::NOT_INITIALIZED, and satox::nft::QUERY_ERROR.
getInstance()
NFTManager & satox::nft::NFTManager::getInstance () static
Definition at line 39 of file nft_manager.cpp.
References NFTManager().
Referenced by satox_nft_manager_create().
getLastError()
NFTManager::Error satox::nft::NFTManager::getLastError () const
Definition at line 680 of file nft_manager.cpp.
getNFT()
NFTManager::NFT satox::nft::NFTManager::getNFT (const std::string & nftId)
Definition at line 478 of file nft_manager.cpp.
References satox::nft::INVALID_ID, satox::nft::NOT_INITIALIZED, and satox::nft::QUERY_ERROR.
Referenced by satox_nft_manager_get_nft_info().
getNFTMetadata()
NFTManager::NFTMetadata satox::nft::NFTManager::getNFTMetadata (const std::string & nftId)
Definition at line 614 of file nft_manager.cpp.
getNFTOwner()
std::string satox::nft::NFTManager::getNFTOwner (const std::string & nftId)
Definition at line 603 of file nft_manager.cpp.
Referenced by getCurrentOwner(), and verifyOwnership().
getNFTsByContract()
std::vector< NFTManager::NFT > satox::nft::NFTManager::getNFTsByContract (const std::string & contractAddress)
Definition at line 527 of file nft_manager.cpp.
References satox::nft::NOT_INITIALIZED, and satox::nft::QUERY_ERROR.
getNFTsByCreator()
std::vector< NFTManager::NFT > satox::nft::NFTManager::getNFTsByCreator (const std::string & creator)
Definition at line 554 of file nft_manager.cpp.
References satox::nft::NOT_INITIALIZED, and satox::nft::QUERY_ERROR.
getNFTsByOwner()
std::vector< NFTManager::NFT > satox::nft::NFTManager::getNFTsByOwner (const std::string & owner)
Definition at line 500 of file nft_manager.cpp.
References satox::nft::NOT_INITIALIZED, and satox::nft::QUERY_ERROR.
getOwnershipHistory()
std::vector< NFTManager::OwnershipRecord > satox::nft::NFTManager::getOwnershipHistory (const std::string & nftId)
Definition at line 691 of file nft_manager.cpp.
References satox::nft::INVALID_ID, satox::nft::NOT_INITIALIZED, satox::nft::NFTManager::OwnershipRecord::owner, satox::nft::NFTManager::OwnershipRecord::previousOwner, satox::nft::QUERY_ERROR, satox::nft::NFTManager::OwnershipRecord::reason, satox::nft::NFTManager::OwnershipRecord::timestamp, and satox::nft::NFTManager::OwnershipRecord::transactionId.
initialize()
bool satox::nft::NFTManager::initialize ()
Definition at line 60 of file nft_manager.cpp.
References satox::nft::VALIDATION_ERROR.
isErrorActive()
bool satox::nft::NFTManager::isErrorActive (const std::string & nftId) const
Definition at line 808 of file nft_manager.cpp.
References NFTManager(), satox::nft::NOT_INITIALIZED, and satox::nft::QUERY_ERROR.
isHealthy()
bool satox::nft::NFTManager::isHealthy () const
Definition at line 111 of file nft_manager.cpp.
isInitialized()
bool satox::nft::NFTManager::isInitialized () const
Definition at line 106 of file nft_manager.cpp.
isNFTBurnable()
bool satox::nft::NFTManager::isNFTBurnable (const std::string & nftId)
Definition at line 592 of file nft_manager.cpp.
isNFTTransferable()
bool satox::nft::NFTManager::isNFTTransferable (const std::string & nftId)
Definition at line 581 of file nft_manager.cpp.
operator=()
NFTManager & satox::nft::NFTManager::operator= (const NFTManager &) delete
References NFTManager().
registerEventCallback()
void satox::nft::NFTManager::registerEventCallback (EventCallback callback)
Definition at line 661 of file nft_manager.cpp.
References satox::nft::VALIDATION_ERROR.
removeEventListener()
void satox::nft::NFTManager::removeEventListener (NFTEventListener * listener)
Definition at line 834 of file nft_manager.cpp.
References satox::nft::VALIDATION_ERROR.
removeNFTAttribute()
bool satox::nft::NFTManager::removeNFTAttribute (const std::string & nftId, const std::string & key, const std::string & updater)
Definition at line 339 of file nft_manager.cpp.
References satox::nft::INVALID_ID, satox::nft::NOT_INITIALIZED, and satox::nft::VALIDATION_ERROR.
setBatchSize()
void satox::nft::NFTManager::setBatchSize (size_t size)
Definition at line 750 of file nft_manager.cpp.
setCacheSize()
void satox::nft::NFTManager::setCacheSize (size_t size)
Definition at line 745 of file nft_manager.cpp.
setConnectionPoolSize()
void satox::nft::NFTManager::setConnectionPoolSize (size_t size)
Definition at line 754 of file nft_manager.cpp.
setErrorCallback()
void satox::nft::NFTManager::setErrorCallback (std::function< void(const NFTError &)> callback)
Definition at line 779 of file nft_manager.cpp.
setNFTBurnable()
bool satox::nft::NFTManager::setNFTBurnable (const std::string & nftId, bool isBurnable)
Definition at line 389 of file nft_manager.cpp.
References satox::nft::INVALID_ID, satox::nft::NOT_INITIALIZED, and satox::nft::VALIDATION_ERROR.
setNFTRoyalty()
bool satox::nft::NFTManager::setNFTRoyalty (const std::string & nftId, const std::string & recipient, uint32_t basisPoints)
Definition at line 414 of file nft_manager.cpp.
References satox::nft::INVALID_ID, satox::nft::NOT_INITIALIZED, and satox::nft::VALIDATION_ERROR.
setNFTTransferable()
bool satox::nft::NFTManager::setNFTTransferable (const std::string & nftId, bool isTransferable)
Definition at line 364 of file nft_manager.cpp.
References satox::nft::INVALID_ID, satox::nft::NOT_INITIALIZED, and satox::nft::VALIDATION_ERROR.
setRecoveryCallback()
void satox::nft::NFTManager::setRecoveryCallback (std::function< void(const NFTError &)> callback)
Definition at line 783 of file nft_manager.cpp.
shutdown()
void satox::nft::NFTManager::shutdown ()
Definition at line 77 of file nft_manager.cpp.
References satox::nft::VALIDATION_ERROR.
transferNFT()
bool satox::nft::NFTManager::transferNFT (const std::string & nftId, const std::string & from, const std::string & to)
Definition at line 174 of file nft_manager.cpp.
References satox::nft::INVALID_ID, satox::nft::INVALID_OPERATION, satox::nft::INVALID_OWNER, satox::nft::NOT_INITIALIZED, and satox::nft::VALIDATION_ERROR.
Referenced by batchTransferNFTs().
unregisterEventCallback()
void satox::nft::NFTManager::unregisterEventCallback ()
Definition at line 670 of file nft_manager.cpp.
References satox::nft::VALIDATION_ERROR.
updateNFTMetadata()
bool satox::nft::NFTManager::updateNFTMetadata (const std::string & nftId, const NFTMetadata & newMetadata, const std::string & updater)
Definition at line 284 of file nft_manager.cpp.
References satox::nft::INVALID_ID, satox::nft::NOT_INITIALIZED, validateNFTMetadata(), and satox::nft::VALIDATION_ERROR.
validateNFT()
bool satox::nft::NFTManager::validateNFT (const NFT & nft)
Definition at line 446 of file nft_manager.cpp.
validateNFTMetadata()
bool satox::nft::NFTManager::validateNFTMetadata (const NFTMetadata & metadata)
Definition at line 450 of file nft_manager.cpp.
References satox::nft::NFTManager::NFTMetadata::name.
Referenced by createNFT(), and updateNFTMetadata().
validateTransfer()
bool satox::nft::NFTManager::validateTransfer (const std::string & nftId, const std::string & from, const std::string & to)
Definition at line 454 of file nft_manager.cpp.
verifyOwnership()
bool satox::nft::NFTManager::verifyOwnership (const std::string & nftId, const std::string & owner)
Definition at line 740 of file nft_manager.cpp.
References getNFTOwner().
The documentation for this class was generated from the following files:
src/nft/include/satox/nft/nft_manager.hpp
src/nft/src/nft_manager.cpp