SATOX SDK: satox::core::cloud::SupabaseManager::Impl Class Reference
satox::core::cloud::SupabaseManager::Impl Class Reference
Public Member Functions
Impl ()
~Impl ()
bool initialize (const SupabaseConfig &config)
bool isConnected () const
nlohmann::json executeQuery (const std::string &query, const nlohmann::json &params)
nlohmann::json executeTransaction (const std::vector< std::string > &queries, const std::vector< nlohmann::json > &params)
std::string subscribe (const std::string &table, const std::string &event, std::function< void(const nlohmann::json &)> callback)
void unsubscribe (const std::string &subscription_id)
nlohmann::json uploadFile (const std::string &bucket, const std::string &path, const std::string &file_path)
nlohmann::json downloadFile (const std::string &bucket, const std::string &path, const std::string &local_path)
nlohmann::json callFunction (const std::string &function_name, const nlohmann::json &payload)
nlohmann::json invokeFunction (const std::string &function_name, const nlohmann::json &payload)
nlohmann::json getStatus () const
void disconnect ()
Detailed Description
Definition at line 23 of file supabase_manager.cpp.
Constructor & Destructor Documentation
Impl()
satox::core::cloud::SupabaseManager::Impl::Impl () inline
Definition at line 25 of file supabase_manager.cpp.
~Impl()
satox::core::cloud::SupabaseManager::Impl::~Impl () inline
Definition at line 30 of file supabase_manager.cpp.
Member Function Documentation
callFunction()
nlohmann::json satox::core::cloud::SupabaseManager::Impl::callFunction (const std::string & function_name, const nlohmann::json & payload) inline
Definition at line 191 of file supabase_manager.cpp.
References isConnected().
Referenced by invokeFunction().
disconnect()
void satox::core::cloud::SupabaseManager::Impl::disconnect () inline
Definition at line 223 of file supabase_manager.cpp.
downloadFile()
nlohmann::json satox::core::cloud::SupabaseManager::Impl::downloadFile (const std::string & bucket, const std::string & path, const std::string & local_path) inline
Definition at line 171 of file supabase_manager.cpp.
References isConnected().
executeQuery()
nlohmann::json satox::core::cloud::SupabaseManager::Impl::executeQuery (const std::string & query, const nlohmann::json & params) inline
Definition at line 62 of file supabase_manager.cpp.
References isConnected().
executeTransaction()
nlohmann::json satox::core::cloud::SupabaseManager::Impl::executeTransaction (const std::vector< std::string > & queries, const std::vector< nlohmann::json > & params) inline
Definition at line 87 of file supabase_manager.cpp.
References isConnected().
getStatus()
nlohmann::json satox::core::cloud::SupabaseManager::Impl::getStatus () const inline
Definition at line 214 of file supabase_manager.cpp.
References isConnected().
initialize()
bool satox::core::cloud::SupabaseManager::Impl::initialize (const SupabaseConfig & config) inline
Definition at line 37 of file supabase_manager.cpp.
invokeFunction()
nlohmann::json satox::core::cloud::SupabaseManager::Impl::invokeFunction (const std::string & function_name, const nlohmann::json & payload) inline
Definition at line 210 of file supabase_manager.cpp.
References callFunction().
isConnected()
bool satox::core::cloud::SupabaseManager::Impl::isConnected () const inline
Definition at line 58 of file supabase_manager.cpp.
Referenced by callFunction(), downloadFile(), executeQuery(), executeTransaction(), getStatus(), subscribe(), and uploadFile().
subscribe()
std::string satox::core::cloud::SupabaseManager::Impl::subscribe (const std::string & table, const std::string & event, std::function< void(const nlohmann::json &)> callback) inline
Definition at line 113 of file supabase_manager.cpp.
References isConnected().
unsubscribe()
void satox::core::cloud::SupabaseManager::Impl::unsubscribe (const std::string & subscription_id) inline
Definition at line 136 of file supabase_manager.cpp.
uploadFile()
nlohmann::json satox::core::cloud::SupabaseManager::Impl::uploadFile (const std::string & bucket, const std::string & path, const std::string & file_path) inline
Definition at line 151 of file supabase_manager.cpp.
References isConnected().
The documentation for this class was generated from the following file:
src/core/cloud/supabase_manager.cpp