SATOX SDK: satox::RPCManager Class Reference
satox::RPCManager Class Reference
#include <rpc_handlers.hpp>
Public Member Functions
RPCManager ()
~RPCManager ()
RPCManager (const RPCManager &)=delete
RPCManager & operator= (const RPCManager &)=delete
RPCManager (RPCManager &&)=default
RPCManager & operator= (RPCManager &&)=default
bool initialize ()
void shutdown ()
bool isRunning () const
nlohmann::json handleRequest (const nlohmann::json &request)
void registerMethod (const std::string &method, std::function< nlohmann::json(const nlohmann::json &)> handler)
Detailed Description
Definition at line 35 of file rpc_handlers.hpp.
Constructor & Destructor Documentation
RPCManager() [1/3]
satox::RPCManager::RPCManager ()
Definition at line 35 of file rpc_handlers.cpp.
References registerMethod().
Referenced by operator=(), operator=(), RPCManager(), and RPCManager().
~RPCManager()
satox::RPCManager::~RPCManager ()
Definition at line 124 of file rpc_handlers.cpp.
References shutdown().
RPCManager() [2/3]
satox::RPCManager::RPCManager (const RPCManager &) delete
References RPCManager().
RPCManager() [3/3]
satox::RPCManager::RPCManager (RPCManager &&) default
References RPCManager().
Member Function Documentation
handleRequest()
nlohmann::json satox::RPCManager::handleRequest (const nlohmann::json & request)
Definition at line 155 of file rpc_handlers.cpp.
initialize()
bool satox::RPCManager::initialize ()
Definition at line 128 of file rpc_handlers.cpp.
isRunning()
bool satox::RPCManager::isRunning () const
Definition at line 146 of file rpc_handlers.cpp.
operator=() [1/2]
RPCManager & satox::RPCManager::operator= (const RPCManager &) delete
References RPCManager().
operator=() [2/2]
RPCManager & satox::RPCManager::operator= (RPCManager &&) default
References RPCManager().
registerMethod()
void satox::RPCManager::registerMethod (const std::string & method, std::function< nlohmann::json(const nlohmann::json &)> handler)
Definition at line 150 of file rpc_handlers.cpp.
Referenced by RPCManager().
shutdown()
void satox::RPCManager::shutdown ()
Definition at line 139 of file rpc_handlers.cpp.
Referenced by ~RPCManager().
The documentation for this class was generated from the following files:
src/network/src/rpc_handlers.hpp
src/network/src/rpc_handlers.cpp