SATOX SDK: satox::blockchain::Block Class Reference
satox::blockchain::Block Class Reference
#include <block.hpp>
Public Member Functions
Block ()=default
~Block ()=default
const std::string & getHash () const
const std::string & getPreviousHash () const
std::chrono::system_clock::time_point getTimestamp () const
const std::vector< std::shared_ptr< Transaction > > & getTransactions () const
int64_t getNonce () const
const nlohmann::json & getMetadata () const
uint32_t getDifficulty () const
const std::string & getMerkleRoot () const
uint32_t getVersion () const
uint64_t getHeight () const
const std::string & getMinerAddress () const
uint64_t getBlockReward () const
const std::string & getKawpowMixHash () const
const std::string & getKawpowHeaderHash () const
void setHash (const std::string &hash)
void setPreviousHash (const std::string &hash)
void setTimestamp (std::chrono::system_clock::time_point timestamp)
void setTransactions (const std::vector< std::shared_ptr< Transaction > > &txs)
void setNonce (int64_t nonce)
void setMetadata (const nlohmann::json &metadata)
void setDifficulty (uint32_t difficulty)
void setMerkleRoot (const std::string &root)
void setVersion (uint32_t version)
void setHeight (uint64_t height)
void setMinerAddress (const std::string &address)
void setBlockReward (uint64_t reward)
void setKawpowMixHash (const std::string &mix_hash)
void setKawpowHeaderHash (const std::string &header_hash)
bool validateKawpowProof () const
std::string calculateKawpowHeaderHash () const
std::string calculateKawpowMixHash () const
bool verifyKawpowDifficulty () const
bool isValid () const
bool verifyMerkleRoot () const
bool verifyTransactions () const
bool verifyTimestamp () const
nlohmann::json toJson () const
Static Public Member Functions
static std::shared_ptr< Block > fromJson (const nlohmann::json &json)
Detailed Description
Definition at line 40 of file block.hpp.
Constructor & Destructor Documentation
Block()
satox::blockchain::Block::Block () default
~Block()
satox::blockchain::Block::~Block () default
Member Function Documentation
calculateKawpowHeaderHash()
std::string satox::blockchain::Block::calculateKawpowHeaderHash () const
Definition at line 77 of file block.cpp.
References satox::blockchain::Kawpow::computeHash(), satox::blockchain::KAWPOW_HASH_BYTES, satox::blockchain::KAWPOW_HEADER_BYTES, and satox::blockchain::KAWPOW_MIX_BYTES.
calculateKawpowMixHash()
std::string satox::blockchain::Block::calculateKawpowMixHash () const
Definition at line 108 of file block.cpp.
References satox::blockchain::Kawpow::computeHash(), satox::blockchain::KAWPOW_HASH_BYTES, satox::blockchain::KAWPOW_HEADER_BYTES, and satox::blockchain::KAWPOW_MIX_BYTES.
fromJson()
std::shared_ptr< Block > satox::blockchain::Block::fromJson (const nlohmann::json & json) static
Definition at line 253 of file block.cpp.
References satox::blockchain::Transaction::fromJson().
getBlockReward()
uint64_t satox::blockchain::Block::getBlockReward () const inline
Definition at line 57 of file block.hpp.
getDifficulty()
uint32_t satox::blockchain::Block::getDifficulty () const inline
Definition at line 52 of file block.hpp.
getHash()
const std::string & satox::blockchain::Block::getHash () const inline
Definition at line 46 of file block.hpp.
getHeight()
uint64_t satox::blockchain::Block::getHeight () const inline
Definition at line 55 of file block.hpp.
getKawpowHeaderHash()
const std::string & satox::blockchain::Block::getKawpowHeaderHash () const inline
Definition at line 59 of file block.hpp.
getKawpowMixHash()
const std::string & satox::blockchain::Block::getKawpowMixHash () const inline
Definition at line 58 of file block.hpp.
getMerkleRoot()
const std::string & satox::blockchain::Block::getMerkleRoot () const inline
Definition at line 53 of file block.hpp.
getMetadata()
const nlohmann::json & satox::blockchain::Block::getMetadata () const inline
Definition at line 51 of file block.hpp.
getMinerAddress()
const std::string & satox::blockchain::Block::getMinerAddress () const inline
Definition at line 56 of file block.hpp.
getNonce()
int64_t satox::blockchain::Block::getNonce () const inline
Definition at line 50 of file block.hpp.
getPreviousHash()
const std::string & satox::blockchain::Block::getPreviousHash () const inline
Definition at line 47 of file block.hpp.
getTimestamp()
std::chrono::system_clock::time_point satox::blockchain::Block::getTimestamp () const inline
Definition at line 48 of file block.hpp.
getTransactions()
const std::vector< std::shared_ptr< Transaction > > & satox::blockchain::Block::getTransactions () const inline
Definition at line 49 of file block.hpp.
getVersion()
uint32_t satox::blockchain::Block::getVersion () const inline
Definition at line 54 of file block.hpp.
isValid()
bool satox::blockchain::Block::isValid () const
Definition at line 171 of file block.cpp.
References validateKawpowProof(), verifyKawpowDifficulty(), verifyMerkleRoot(), verifyTimestamp(), and verifyTransactions().
setBlockReward()
void satox::blockchain::Block::setBlockReward (uint64_t reward) inline
Definition at line 73 of file block.hpp.
setDifficulty()
void satox::blockchain::Block::setDifficulty (uint32_t difficulty) inline
Definition at line 68 of file block.hpp.
setHash()
void satox::blockchain::Block::setHash (const std::string & hash) inline
Definition at line 62 of file block.hpp.
setHeight()
void satox::blockchain::Block::setHeight (uint64_t height) inline
Definition at line 71 of file block.hpp.
setKawpowHeaderHash()
void satox::blockchain::Block::setKawpowHeaderHash (const std::string & header_hash) inline
Definition at line 75 of file block.hpp.
setKawpowMixHash()
void satox::blockchain::Block::setKawpowMixHash (const std::string & mix_hash) inline
Definition at line 74 of file block.hpp.
setMerkleRoot()
void satox::blockchain::Block::setMerkleRoot (const std::string & root) inline
Definition at line 69 of file block.hpp.
setMetadata()
void satox::blockchain::Block::setMetadata (const nlohmann::json & metadata) inline
Definition at line 67 of file block.hpp.
setMinerAddress()
void satox::blockchain::Block::setMinerAddress (const std::string & address) inline
Definition at line 72 of file block.hpp.
setNonce()
void satox::blockchain::Block::setNonce (int64_t nonce) inline
Definition at line 66 of file block.hpp.
setPreviousHash()
void satox::blockchain::Block::setPreviousHash (const std::string & hash) inline
Definition at line 63 of file block.hpp.
setTimestamp()
void satox::blockchain::Block::setTimestamp (std::chrono::system_clock::time_point timestamp) inline
Definition at line 64 of file block.hpp.
setTransactions()
void satox::blockchain::Block::setTransactions (const std::vector< std::shared_ptr< Transaction > > & txs) inline
Definition at line 65 of file block.hpp.
setVersion()
void satox::blockchain::Block::setVersion (uint32_t version) inline
Definition at line 70 of file block.hpp.
toJson()
nlohmann::json satox::blockchain::Block::toJson () const
Definition at line 225 of file block.cpp.
validateKawpowProof()
bool satox::blockchain::Block::validateKawpowProof () const
Definition at line 38 of file block.cpp.
References satox::blockchain::KAWPOW_HASH_BYTES, satox::blockchain::KAWPOW_HEADER_BYTES, satox::blockchain::KAWPOW_MIX_BYTES, and satox::blockchain::Kawpow::verifyHash().
Referenced by isValid().
verifyKawpowDifficulty()
bool satox::blockchain::Block::verifyKawpowDifficulty () const
Definition at line 139 of file block.cpp.
References satox::blockchain::Kawpow::computeHash(), satox::blockchain::KAWPOW_HASH_BYTES, satox::blockchain::KAWPOW_HEADER_BYTES, and satox::blockchain::KAWPOW_MIX_BYTES.
Referenced by isValid().
verifyMerkleRoot()
bool satox::blockchain::Block::verifyMerkleRoot () const
Definition at line 203 of file block.cpp.
Referenced by isValid().
verifyTimestamp()
bool satox::blockchain::Block::verifyTimestamp () const
Definition at line 217 of file block.cpp.
Referenced by isValid().
verifyTransactions()
bool satox::blockchain::Block::verifyTransactions () const
Definition at line 208 of file block.cpp.
Referenced by isValid().
The documentation for this class was generated from the following files:
src/blockchain/include/satox/blockchain/block.hpp
src/blockchain/src/block.cpp