SATOX SDK: satox::asset::AssetManager Class Reference
satox::asset::AssetManager Class Reference
#include <asset_manager.hpp>
Classes
struct ErrorRecoveryConfig
struct PerformanceConfig
struct RecoveryOperation
Public Types
using AssetCallback = std::function<void(const std::string&, const nlohmann::json&)>
Public Member Functions
AssetManager ()
~AssetManager ()
bool initialize (const AssetConfig &config)
void shutdown ()
bool createAsset (const AssetCreationRequest &request)
bool transferAsset (const AssetTransferRequest &request)
bool reissueAsset (const AssetReissueRequest &request)
bool burnAsset (const AssetBurnRequest &request)
bool freezeAsset (const std::string &asset_name, const std::string &owner_address)
bool unfreezeAsset (const std::string &asset_name, const std::string &owner_address)
bool destroyAsset (const std::string &asset_name, const std::string &owner_address)
bool getAssetMetadata (const std::string &asset_name, AssetMetadata &metadata) const
bool getAssetBalance (const std::string &address, const std::string &asset_name, uint64_t &balance) const
bool getAssetOwners (const std::string &asset_name, std::vector< std::string > &owners) const
bool getAssetStatus (const std::string &asset_name, AssetStatus &status) const
bool getAssetType (const std::string &asset_name, AssetType &type) const
bool verifyAsset (const std::string &asset_name, AssetVerificationResult &result) const
bool validateAssetMetadata (const AssetMetadata &metadata, AssetVerificationResult &result) const
bool validateAssetTransfer (const AssetTransferRequest &request, AssetVerificationResult &result) const
bool validateAssetReissue (const AssetReissueRequest &request, AssetVerificationResult &result) const
bool validateAssetBurn (const AssetBurnRequest &request, AssetVerificationResult &result) const
AssetState getState () const
bool isInitialized () const
bool isHealthy () const
AssetConfig getConfig () const
bool updateConfig (const AssetConfig &config)
bool validateConfig (const AssetConfig &config) const
AssetStats getStats () const
void resetStats ()
bool enableStats (bool enable)
void registerAssetCallback (AssetCallback callback)
void registerOperationCallback (OperationCallback callback)
void registerErrorCallback (ErrorCallback callback)
void unregisterAssetCallback ()
void unregisterOperationCallback ()
void unregisterErrorCallback ()
std::string getLastError () const
void clearLastError ()
bool healthCheck ()
nlohmann::json getHealthStatus ()
nlohmann::json getAssetInfo (const std::string &asset_name)
std::vector< nlohmann::json > listAssets ()
std::vector< nlohmann::json > getAssetHistory (const std::string &asset_name)
std::vector< nlohmann::json > getAssetBalances (const std::string &asset_name)
std::vector< nlohmann::json > getAssetTransactions (const std::string &asset_name)
AssetManager (const AssetManager &)=delete
AssetManager & operator= (const AssetManager &)=delete
AssetManager (AssetManager &&) noexcept=default
AssetManager & operator= (AssetManager &&) noexcept=default
bool initialize (const std::string &network)
void shutdown ()
std::string getLastError () const
bool createAsset (const Asset &asset)
bool updateAsset (const std::string &asset_id, const Asset &asset)
bool deleteAsset (const std::string &asset_id)
std::optional< Asset > getAsset (const std::string &asset_id) const
std::vector< Asset > getAssetsByOwner (const std::string &owner) const
std::vector< Asset > getAllAssets () const
bool transferAsset (const std::string &asset_id, const std::string &from, const std::string &to, uint64_t amount)
uint64_t getAssetBalance (const std::string &asset_id, const std::string &address) const
bool setPerformanceConfig (const PerformanceConfig &config)
void clearCache ()
size_t getCacheSize () const
size_t getConnectionPoolSize () const
size_t getBatchSize () const
bool processBatch (const std::vector< Asset > &assets)
void optimizeMemory ()
bool setErrorRecoveryConfig (const ErrorRecoveryConfig &config)
bool recoverFromError (const std::string &operation_id)
std::vector< RecoveryOperation > getRecoveryHistory () const
void clearRecoveryHistory ()
bool isRecoveryInProgress () const
std::string getLastRecoveryError () const
bool searchAssets (const std::string &query, std::vector< Asset > &results)
bool searchByMetadata (const std::unordered_map< std::string, std::string > &metadata_filters, std::vector< Asset > &results)
bool validateAsset (const Asset &asset) const
bool validateAssetName (const std::string &name) const
bool validateMetadata (const std::unordered_map< std::string, std::string > &metadata) const
bool setAssetPermissions (const std::string &asset_id, const std::unordered_map< std::string, std::vector< std::string > > &permissions)
bool getAssetPermissions (const std::string &asset_id, std::unordered_map< std::string, std::vector< std::string > > &permissions) const
bool checkAssetPermission (const std::string &asset_id, const std::string &address, const std::string &permission) const
bool getAssetHistory (const std::string &asset_id, std::vector< nlohmann::json > &history) const
bool addAssetHistory (const std::string &asset_id, const nlohmann::json &event)
void registerAssetCallback (AssetCallback callback)
Static Public Member Functions
static AssetManager & getInstance ()
static AssetManager & getInstance ()
Detailed Description
Definition at line 41 of file asset_manager.hpp.
Member Typedef Documentation
AssetCallback
using satox::asset::AssetManager::AssetCallback = std::function<void(const std::string&, const nlohmann::json&)>
Definition at line 164 of file asset_manager.hpp.
Constructor & Destructor Documentation
AssetManager() [1/3]
satox::asset::AssetManager::AssetManager ()
Definition at line 69 of file asset_manager.cpp.
References satox::asset::SimpleLogger::debug().
Referenced by AssetManager(), AssetManager(), getInstance(), operator=(), and operator=().
~AssetManager()
satox::asset::AssetManager::~AssetManager ()
Definition at line 74 of file asset_manager.cpp.
References satox::asset::SimpleLogger::debug(), and shutdown().
AssetManager() [2/3]
satox::asset::AssetManager::AssetManager (const AssetManager &) delete
References AssetManager().
AssetManager() [3/3]
satox::asset::AssetManager::AssetManager (AssetManager &&) default noexcept
References AssetManager().
Member Function Documentation
addAssetHistory()
bool satox::asset::AssetManager::addAssetHistory (const std::string & asset_id, const nlohmann::json & event)
burnAsset()
bool satox::asset::AssetManager::burnAsset (const AssetBurnRequest & request)
Definition at line 402 of file asset_manager.cpp.
References satox::asset::AssetBurnRequest::amount, satox::asset::AssetBurnRequest::asset_name, satox::asset::SimpleLogger::error(), satox::asset::AssetVerificationResult::error_message, satox::asset::SimpleLogger::info(), satox::asset::AssetBurnRequest::owner_address, and validateAssetBurn().
checkAssetPermission()
bool satox::asset::AssetManager::checkAssetPermission (const std::string & asset_id, const std::string & address, const std::string & permission) const
clearCache()
void satox::asset::AssetManager::clearCache ()
clearLastError()
void satox::asset::AssetManager::clearLastError ()
Definition at line 1052 of file asset_manager.cpp.
clearRecoveryHistory()
void satox::asset::AssetManager::clearRecoveryHistory ()
createAsset() [1/2]
bool satox::asset::AssetManager::createAsset (const Asset & asset)
References createAsset().
createAsset() [2/2]
bool satox::asset::AssetManager::createAsset (const AssetCreationRequest & request)
Definition at line 181 of file asset_manager.cpp.
References satox::asset::ACTIVE, satox::asset::AssetMetadata::additional_data, satox::asset::AssetCreationRequest::amount, satox::asset::AssetMetadata::decimals, satox::asset::AssetMetadata::description, satox::asset::SimpleLogger::error(), satox::asset::AssetVerificationResult::error_message, satox::asset::AssetMetadata::frozen, satox::asset::SimpleLogger::info(), satox::asset::AssetMetadata::issuer, satox::asset::AssetCreationRequest::metadata, satox::asset::AssetCreationRequest::name, satox::asset::AssetMetadata::name, satox::asset::AssetCreationRequest::owner_address, satox::asset::AssetCreationRequest::reissuable, satox::asset::AssetMetadata::reissuable, satox::asset::AssetCreationRequest::symbol, satox::asset::AssetMetadata::symbol, satox::asset::AssetMetadata::total_supply, and satox::asset::AssetCreationRequest::units.
Referenced by createAsset(), and PYBIND11_MODULE().
deleteAsset()
bool satox::asset::AssetManager::deleteAsset (const std::string & asset_id)
References deleteAsset().
Referenced by deleteAsset().
destroyAsset()
bool satox::asset::AssetManager::destroyAsset (const std::string & asset_name, const std::string & owner_address)
Definition at line 507 of file asset_manager.cpp.
References satox::asset::DESTROYED, and satox::asset::SimpleLogger::info().
enableStats()
bool satox::asset::AssetManager::enableStats (bool enable)
Definition at line 818 of file asset_manager.cpp.
References satox::asset::SimpleLogger::info().
freezeAsset()
bool satox::asset::AssetManager::freezeAsset (const std::string & asset_name, const std::string & owner_address)
Definition at line 463 of file asset_manager.cpp.
References satox::asset::FROZEN, and satox::asset::SimpleLogger::info().
getAllAssets()
std::vector< Asset > satox::asset::AssetManager::getAllAssets () const
References getAllAssets().
Referenced by getAllAssets().
getAsset()
std::optional< Asset > satox::asset::AssetManager::getAsset (const std::string & asset_id) const
References getAsset().
Referenced by getAsset().
getAssetBalance() [1/2]
bool satox::asset::AssetManager::getAssetBalance (const std::string & address, const std::string & asset_name, uint64_t & balance) const
Definition at line 541 of file asset_manager.cpp.
Referenced by getAssetBalance().
getAssetBalance() [2/2]
uint64_t satox::asset::AssetManager::getAssetBalance (const std::string & asset_id, const std::string & address) const
References getAssetBalance().
getAssetBalances()
std::vector< nlohmann::json > satox::asset::AssetManager::getAssetBalances (const std::string & asset_name)
Definition at line 924 of file asset_manager.cpp.
getAssetHistory() [1/2]
bool satox::asset::AssetManager::getAssetHistory (const std::string & asset_id, std::vector< nlohmann::json > & history) const
getAssetHistory() [2/2]
std::vector< nlohmann::json > satox::asset::AssetManager::getAssetHistory (const std::string & asset_name)
Definition at line 919 of file asset_manager.cpp.
getAssetInfo()
nlohmann::json satox::asset::AssetManager::getAssetInfo (const std::string & asset_name)
Definition at line 883 of file asset_manager.cpp.
getAssetMetadata()
bool satox::asset::AssetManager::getAssetMetadata (const std::string & asset_name, AssetMetadata & metadata) const
Definition at line 525 of file asset_manager.cpp.
Referenced by PYBIND11_MODULE().
getAssetOwners()
bool satox::asset::AssetManager::getAssetOwners (const std::string & asset_name, std::vector< std::string > & owners) const
Definition at line 564 of file asset_manager.cpp.
getAssetPermissions()
bool satox::asset::AssetManager::getAssetPermissions (const std::string & asset_id, std::unordered_map< std::string, std::vector< std::string > > & permissions) const
getAssetsByOwner()
std::vector< Asset > satox::asset::AssetManager::getAssetsByOwner (const std::string & owner) const
References getAssetsByOwner().
Referenced by getAssetsByOwner().
getAssetStatus()
bool satox::asset::AssetManager::getAssetStatus (const std::string & asset_name, AssetStatus & status) const
Definition at line 586 of file asset_manager.cpp.
getAssetTransactions()
std::vector< nlohmann::json > satox::asset::AssetManager::getAssetTransactions (const std::string & asset_name)
Definition at line 941 of file asset_manager.cpp.
getAssetType()
bool satox::asset::AssetManager::getAssetType (const std::string & asset_name, AssetType & type) const
Definition at line 596 of file asset_manager.cpp.
getBatchSize()
size_t satox::asset::AssetManager::getBatchSize () const
getCacheSize()
size_t satox::asset::AssetManager::getCacheSize () const
getConfig()
AssetConfig satox::asset::AssetManager::getConfig () const
Definition at line 768 of file asset_manager.cpp.
getConnectionPoolSize()
size_t satox::asset::AssetManager::getConnectionPoolSize () const
getHealthStatus()
nlohmann::json satox::asset::AssetManager::getHealthStatus ()
Definition at line 868 of file asset_manager.cpp.
getInstance() [1/2]
AssetManager & satox::asset::AssetManager::getInstance () static
Definition at line 63 of file asset_manager.cpp.
References AssetManager().
Referenced by PYBIND11_MODULE(), and satox_asset_manager_create().
getInstance() [2/2]
static AssetManager & satox::asset::AssetManager::getInstance () static
References AssetManager().
getLastError() [1/2]
std::string satox::asset::AssetManager::getLastError () const
Definition at line 175 of file asset_manager.cpp.
Referenced by getLastError(), and PYBIND11_MODULE().
getLastError() [2/2]
std::string satox::asset::AssetManager::getLastError () const
References getLastError().
getLastRecoveryError()
std::string satox::asset::AssetManager::getLastRecoveryError () const
getRecoveryHistory()
std::vector< RecoveryOperation > satox::asset::AssetManager::getRecoveryHistory () const
getState()
AssetState satox::asset::AssetManager::getState () const
Definition at line 757 of file asset_manager.cpp.
getStats()
AssetStats satox::asset::AssetManager::getStats () const
Definition at line 798 of file asset_manager.cpp.
References satox::asset::ACTIVE, satox::asset::AssetStats::activeAssets, satox::asset::DESTROYED, satox::asset::AssetStats::destroyedAssets, satox::asset::FROZEN, and satox::asset::AssetStats::frozenAssets.
healthCheck()
bool satox::asset::AssetManager::healthCheck ()
Definition at line 857 of file asset_manager.cpp.
initialize() [1/2]
bool satox::asset::AssetManager::initialize (const AssetConfig & config)
Definition at line 80 of file asset_manager.cpp.
References satox::asset::AssetConfig::enableLogging, satox::asset::ERROR, satox::asset::SimpleLogger::error(), satox::asset::SimpleLogger::info(), satox::asset::INITIALIZED, satox::asset::INITIALIZING, satox::asset::AssetConfig::logPath, satox::asset::AssetConfig::name, validateConfig(), and satox::asset::SimpleLogger::warn().
Referenced by initialize(), and PYBIND11_MODULE().
initialize() [2/2]
bool satox::asset::AssetManager::initialize (const std::string & network)
References initialize().
isHealthy()
bool satox::asset::AssetManager::isHealthy () const
Definition at line 762 of file asset_manager.cpp.
References satox::asset::INITIALIZED.
isInitialized()
bool satox::asset::AssetManager::isInitialized () const
Definition at line 170 of file asset_manager.cpp.
Referenced by PYBIND11_MODULE().
isRecoveryInProgress()
bool satox::asset::AssetManager::isRecoveryInProgress () const
listAssets()
std::vector< nlohmann::json > satox::asset::AssetManager::listAssets ()
Definition at line 904 of file asset_manager.cpp.
operator=() [1/2]
AssetManager & satox::asset::AssetManager::operator= (AssetManager &&) default noexcept
References AssetManager().
operator=() [2/2]
AssetManager & satox::asset::AssetManager::operator= (const AssetManager &) delete
References AssetManager().
optimizeMemory()
void satox::asset::AssetManager::optimizeMemory ()
processBatch()
bool satox::asset::AssetManager::processBatch (const std::vector< Asset > & assets)
recoverFromError()
bool satox::asset::AssetManager::recoverFromError (const std::string & operation_id)
registerAssetCallback() [1/2]
void satox::asset::AssetManager::registerAssetCallback (AssetCallback callback)
Definition at line 826 of file asset_manager.cpp.
registerAssetCallback() [2/2]
void satox::asset::AssetManager::registerAssetCallback (AssetCallback callback)
registerErrorCallback()
void satox::asset::AssetManager::registerErrorCallback (ErrorCallback callback)
Definition at line 836 of file asset_manager.cpp.
registerOperationCallback()
void satox::asset::AssetManager::registerOperationCallback (OperationCallback callback)
Definition at line 831 of file asset_manager.cpp.
reissueAsset()
bool satox::asset::AssetManager::reissueAsset (const AssetReissueRequest & request)
Definition at line 340 of file asset_manager.cpp.
References satox::asset::AssetReissueRequest::amount, satox::asset::AssetReissueRequest::asset_name, satox::asset::SimpleLogger::error(), satox::asset::AssetVerificationResult::error_message, satox::asset::SimpleLogger::info(), satox::asset::AssetReissueRequest::owner_address, and validateAssetReissue().
resetStats()
void satox::asset::AssetManager::resetStats ()
Definition at line 812 of file asset_manager.cpp.
References satox::asset::SimpleLogger::info().
searchAssets()
bool satox::asset::AssetManager::searchAssets (const std::string & query, std::vector< Asset > & results)
searchByMetadata()
bool satox::asset::AssetManager::searchByMetadata (const std::unordered_map< std::string, std::string > & metadata_filters, std::vector< Asset > & results)
setAssetPermissions()
bool satox::asset::AssetManager::setAssetPermissions (const std::string & asset_id, const std::unordered_map< std::string, std::vector< std::string > > & permissions)
setErrorRecoveryConfig()
bool satox::asset::AssetManager::setErrorRecoveryConfig (const ErrorRecoveryConfig & config)
setPerformanceConfig()
bool satox::asset::AssetManager::setPerformanceConfig (const PerformanceConfig & config)
shutdown() [1/2]
void satox::asset::AssetManager::shutdown ()
Definition at line 137 of file asset_manager.cpp.
References satox::asset::SimpleLogger::error(), satox::asset::SimpleLogger::info(), and satox::asset::SHUTDOWN.
Referenced by shutdown(), and ~AssetManager().
shutdown() [2/2]
void satox::asset::AssetManager::shutdown ()
References shutdown().
transferAsset() [1/2]
bool satox::asset::AssetManager::transferAsset (const AssetTransferRequest & request)
Definition at line 271 of file asset_manager.cpp.
References satox::asset::AssetTransferRequest::amount, satox::asset::AssetTransferRequest::asset_name, satox::asset::SimpleLogger::error(), satox::asset::AssetVerificationResult::error_message, satox::asset::AssetTransferRequest::from_address, satox::asset::FROZEN, satox::asset::SimpleLogger::info(), satox::asset::AssetTransferRequest::to_address, and validateAssetTransfer().
Referenced by transferAsset().
transferAsset() [2/2]
bool satox::asset::AssetManager::transferAsset (const std::string & asset_id, const std::string & from, const std::string & to, uint64_t amount)
References transferAsset().
unfreezeAsset()
bool satox::asset::AssetManager::unfreezeAsset (const std::string & asset_name, const std::string & owner_address)
Definition at line 485 of file asset_manager.cpp.
References satox::asset::ACTIVE, and satox::asset::SimpleLogger::info().
unregisterAssetCallback()
void satox::asset::AssetManager::unregisterAssetCallback ()
Definition at line 841 of file asset_manager.cpp.
unregisterErrorCallback()
void satox::asset::AssetManager::unregisterErrorCallback ()
Definition at line 851 of file asset_manager.cpp.
unregisterOperationCallback()
void satox::asset::AssetManager::unregisterOperationCallback ()
Definition at line 846 of file asset_manager.cpp.
updateAsset()
bool satox::asset::AssetManager::updateAsset (const std::string & asset_id, const Asset & asset)
References updateAsset().
Referenced by updateAsset().
updateConfig()
bool satox::asset::AssetManager::updateConfig (const AssetConfig & config)
Definition at line 773 of file asset_manager.cpp.
References satox::asset::SimpleLogger::info(), and satox::asset::AssetConfig::maxAssets.
validateAsset()
bool satox::asset::AssetManager::validateAsset (const Asset & asset) const
validateAssetBurn()
bool satox::asset::AssetManager::validateAssetBurn (const AssetBurnRequest & request, AssetVerificationResult & result) const
Definition at line 730 of file asset_manager.cpp.
References satox::asset::AssetBurnRequest::amount, satox::asset::AssetBurnRequest::asset_name, satox::asset::AssetVerificationResult::error_message, satox::asset::AssetBurnRequest::owner_address, satox::asset::AssetVerificationResult::valid, and satox::asset::AssetVerificationResult::warnings.
Referenced by burnAsset().
validateAssetMetadata()
bool satox::asset::AssetManager::validateAssetMetadata (const AssetMetadata & metadata, AssetVerificationResult & result) const
Definition at line 637 of file asset_manager.cpp.
References satox::asset::AssetMetadata::decimals, satox::asset::AssetVerificationResult::error_message, satox::asset::AssetMetadata::issuer, satox::asset::AssetMetadata::name, satox::asset::AssetMetadata::symbol, satox::asset::AssetMetadata::total_supply, satox::asset::AssetVerificationResult::valid, and satox::asset::AssetVerificationResult::warnings.
validateAssetName()
bool satox::asset::AssetManager::validateAssetName (const std::string & name) const
validateAssetReissue()
bool satox::asset::AssetManager::validateAssetReissue (const AssetReissueRequest & request, AssetVerificationResult & result) const
Definition at line 704 of file asset_manager.cpp.
References satox::asset::AssetReissueRequest::amount, satox::asset::AssetReissueRequest::asset_name, satox::asset::AssetVerificationResult::error_message, satox::asset::AssetReissueRequest::owner_address, satox::asset::AssetVerificationResult::valid, and satox::asset::AssetVerificationResult::warnings.
Referenced by reissueAsset().
validateAssetTransfer()
bool satox::asset::AssetManager::validateAssetTransfer (const AssetTransferRequest & request, AssetVerificationResult & result) const
Definition at line 666 of file asset_manager.cpp.
References satox::asset::AssetTransferRequest::amount, satox::asset::AssetTransferRequest::asset_name, satox::asset::AssetVerificationResult::error_message, satox::asset::AssetTransferRequest::from_address, satox::asset::AssetTransferRequest::to_address, satox::asset::AssetVerificationResult::valid, and satox::asset::AssetVerificationResult::warnings.
Referenced by transferAsset().
validateConfig()
bool satox::asset::AssetManager::validateConfig (const AssetConfig & config) const
Definition at line 793 of file asset_manager.cpp.
References satox::asset::AssetConfig::maxAssets, satox::asset::AssetConfig::name, and satox::asset::AssetConfig::timeout.
Referenced by initialize().
validateMetadata()
bool satox::asset::AssetManager::validateMetadata (const std::unordered_map< std::string, std::string > & metadata) const
verifyAsset()
bool satox::asset::AssetManager::verifyAsset (const std::string & asset_name, AssetVerificationResult & result) const
Definition at line 613 of file asset_manager.cpp.
References satox::asset::AssetVerificationResult::details, satox::asset::AssetVerificationResult::error_message, satox::asset::AssetVerificationResult::valid, and satox::asset::AssetVerificationResult::warnings.
The documentation for this class was generated from the following files:
src/asset/include/satox/asset/asset_manager.hpp
src/core/include/satox/asset/asset_manager.hpp
src/asset/src/asset_manager.cpp