SATOX SDK: satox::security::pqc::KeyManager::Impl Class Reference
satox::security::pqc::KeyManager::Impl Class Reference
Public Member Functions
Impl ()
bool generateAndStoreKey (const std::string &keyId, MLKEM::SecurityLevel kemLevel, MLDSA::SecurityLevel dsaLevel, const std::chrono::seconds &expirationTime)
bool retrieveKey (const std::string &keyId, std::vector< uint8_t > &publicKey, std::vector< uint8_t > &privateKey, KeyMetadata &metadata)
bool rotateKey (const std::string &keyId, MLKEM::SecurityLevel newKemLevel, MLDSA::SecurityLevel newDsaLevel, const std::chrono::seconds &newExpirationTime)
bool deleteKey (const std::string &keyId)
std::vector< KeyMetadata > listKeys () const
bool isKeyActive (const std::string &keyId) const
bool updateKeyMetadata (const std::string &keyId, const std::unordered_map< std::string, std::string > &metadata)
std::string getLastError () const
void clearLastError ()
Impl ()
bool generateAndStoreKey (const std::string &keyId, MLKEM::SecurityLevel kemLevel, MLDSA::SecurityLevel dsaLevel, const std::chrono::seconds &expirationTime)
bool retrieveKey (const std::string &keyId, std::vector< uint8_t > &publicKey, std::vector< uint8_t > &privateKey, KeyMetadata &metadata)
bool rotateKey (const std::string &keyId, MLKEM::SecurityLevel newKemLevel, MLDSA::SecurityLevel newDsaLevel, const std::chrono::seconds &newExpirationTime)
bool deleteKey (const std::string &keyId)
std::vector< KeyMetadata > listKeys () const
bool isKeyActive (const std::string &keyId) const
bool updateKeyMetadata (const std::string &keyId, const std::unordered_map< std::string, std::string > &metadata)
std::string getLastError () const
void clearLastError ()
Detailed Description
Definition at line 42 of file key_manager.cpp.
Constructor & Destructor Documentation
Impl() [1/2]
satox::security::pqc::KeyManager::Impl::Impl () inline
Definition at line 44 of file key_manager.cpp.
Impl() [2/2]
satox::security::pqc::KeyManager::Impl::Impl () inline
Definition at line 44 of file key_manager.cpp.
Member Function Documentation
clearLastError() [1/2]
void satox::security::pqc::KeyManager::Impl::clearLastError () inline
Definition at line 233 of file key_manager.cpp.
clearLastError() [2/2]
void satox::security::pqc::KeyManager::Impl::clearLastError () inline
Definition at line 233 of file key_manager.cpp.
deleteKey() [1/2]
bool satox::security::pqc::KeyManager::Impl::deleteKey (const std::string & keyId) inline
Definition at line 164 of file key_manager.cpp.
deleteKey() [2/2]
bool satox::security::pqc::KeyManager::Impl::deleteKey (const std::string & keyId) inline
Definition at line 164 of file key_manager.cpp.
generateAndStoreKey() [1/2]
bool satox::security::pqc::KeyManager::Impl::generateAndStoreKey (const std::string & keyId, MLKEM::SecurityLevel kemLevel, MLDSA::SecurityLevel dsaLevel, const std::chrono::seconds & expirationTime) inline
Definition at line 50 of file key_manager.cpp.
References satox::security::pqc::KeyMetadata::algorithm, satox::security::pqc::KeyMetadata::creationTime, satox::security::pqc::KeyMetadata::expirationTime, satox::security::pqc::HybridCrypto::generateHybridKeyPair(), satox::security::pqc::HybridCrypto::getLastError(), satox::security::pqc::KeyMetadata::isActive, satox::security::pqc::KeyMetadata::keyId, and satox::security::pqc::KeyMetadata::securityLevel.
generateAndStoreKey() [2/2]
bool satox::security::pqc::KeyManager::Impl::generateAndStoreKey (const std::string & keyId, MLKEM::SecurityLevel kemLevel, MLDSA::SecurityLevel dsaLevel, const std::chrono::seconds & expirationTime) inline
Definition at line 50 of file key_manager.cpp.
References satox::security::pqc::KeyMetadata::algorithm, satox::security::pqc::KeyMetadata::creationTime, satox::security::pqc::KeyMetadata::expirationTime, satox::security::pqc::HybridCrypto::generateHybridKeyPair(), satox::security::pqc::HybridCrypto::getLastError(), satox::security::pqc::KeyMetadata::isActive, satox::security::pqc::KeyMetadata::keyId, and satox::security::pqc::KeyMetadata::securityLevel.
getLastError() [1/2]
std::string satox::security::pqc::KeyManager::Impl::getLastError () const inline
Definition at line 229 of file key_manager.cpp.
getLastError() [2/2]
std::string satox::security::pqc::KeyManager::Impl::getLastError () const inline
Definition at line 229 of file key_manager.cpp.
isKeyActive() [1/2]
bool satox::security::pqc::KeyManager::Impl::isKeyActive (const std::string & keyId) const inline
Definition at line 193 of file key_manager.cpp.
isKeyActive() [2/2]
bool satox::security::pqc::KeyManager::Impl::isKeyActive (const std::string & keyId) const inline
Definition at line 193 of file key_manager.cpp.
listKeys() [1/2]
std::vector< KeyMetadata > satox::security::pqc::KeyManager::Impl::listKeys () const inline
Definition at line 181 of file key_manager.cpp.
listKeys() [2/2]
std::vector< KeyMetadata > satox::security::pqc::KeyManager::Impl::listKeys () const inline
Definition at line 181 of file key_manager.cpp.
retrieveKey() [1/2]
bool satox::security::pqc::KeyManager::Impl::retrieveKey (const std::string & keyId, std::vector< uint8_t > & publicKey, std::vector< uint8_t > & privateKey, KeyMetadata & metadata) inline
Definition at line 91 of file key_manager.cpp.
References satox::security::pqc::KeyMetadata::metadata.
retrieveKey() [2/2]
bool satox::security::pqc::KeyManager::Impl::retrieveKey (const std::string & keyId, std::vector< uint8_t > & publicKey, std::vector< uint8_t > & privateKey, KeyMetadata & metadata) inline
Definition at line 91 of file key_manager.cpp.
References satox::security::pqc::KeyMetadata::metadata.
rotateKey() [1/2]
bool satox::security::pqc::KeyManager::Impl::rotateKey (const std::string & keyId, MLKEM::SecurityLevel newKemLevel, MLDSA::SecurityLevel newDsaLevel, const std::chrono::seconds & newExpirationTime) inline
Definition at line 124 of file key_manager.cpp.
References satox::security::pqc::HybridCrypto::getLastError(), and satox::security::pqc::HybridCrypto::rotateKeys().
rotateKey() [2/2]
bool satox::security::pqc::KeyManager::Impl::rotateKey (const std::string & keyId, MLKEM::SecurityLevel newKemLevel, MLDSA::SecurityLevel newDsaLevel, const std::chrono::seconds & newExpirationTime) inline
Definition at line 124 of file key_manager.cpp.
References satox::security::pqc::HybridCrypto::getLastError(), and satox::security::pqc::HybridCrypto::rotateKeys().
updateKeyMetadata() [1/2]
bool satox::security::pqc::KeyManager::Impl::updateKeyMetadata (const std::string & keyId, const std::unordered_map< std::string, std::string > & metadata) inline
Definition at line 211 of file key_manager.cpp.
updateKeyMetadata() [2/2]
bool satox::security::pqc::KeyManager::Impl::updateKeyMetadata (const std::string & keyId, const std::unordered_map< std::string, std::string > & metadata) inline
Definition at line 211 of file key_manager.cpp.
The documentation for this class was generated from the following files:
src/security/pqc/key_manager.cpp
src/security/src/key_manager.cpp