SATOX SDK: src/blockchain/third_party/keccak/include/KeccakF-1600-reference.h File Reference
KeccakF-1600-reference.h File Reference
#include <stdint.h>
Classes
struct KeccakF_1600_State
Macros
#define KECCAK_F_1600_WIDTH 1600
#define KECCAK_F_1600_LANES 25
#define KECCAK_F_1600_ROUNDS 24
Functions
void KeccakF_1600_Initialize (KeccakF_1600_State *state)
void KeccakF_1600_StateXORBytes (KeccakF_1600_State *state, const unsigned char *data, unsigned int offset, unsigned int length)
void KeccakF_1600_StateExtractBytes (const KeccakF_1600_State *state, unsigned char *data, unsigned int offset, unsigned int length)
void KeccakF_1600_StatePermute (KeccakF_1600_State *state)
Macro Definition Documentation
KECCAK_F_1600_LANES
#define KECCAK_F_1600_LANES 25
Definition at line 7 of file KeccakF-1600-reference.h.
Referenced by KeccakF_1600_Initialize(), and KeccakF_1600_StatePermute().
KECCAK_F_1600_ROUNDS
#define KECCAK_F_1600_ROUNDS 24
Definition at line 8 of file KeccakF-1600-reference.h.
Referenced by KeccakF_1600_StatePermute().
KECCAK_F_1600_WIDTH
#define KECCAK_F_1600_WIDTH 1600
Definition at line 6 of file KeccakF-1600-reference.h.
Function Documentation
KeccakF_1600_Initialize()
void KeccakF_1600_Initialize (KeccakF_1600_State * state)
Definition at line 17 of file KeccakF-1600-reference.c.
References KeccakF_1600_State::A, and KECCAK_F_1600_LANES.
Referenced by KeccakSponge_Initialize().
KeccakF_1600_StateExtractBytes()
void KeccakF_1600_StateExtractBytes (const KeccakF_1600_State * state, unsigned char * data, unsigned int offset, unsigned int length)
Definition at line 28 of file KeccakF-1600-reference.c.
References KeccakF_1600_State::A.
Referenced by KeccakSponge_Squeeze().
KeccakF_1600_StatePermute()
void KeccakF_1600_StatePermute (KeccakF_1600_State * state)
Definition at line 32 of file KeccakF-1600-reference.c.
References KeccakF_1600_State::A, KECCAK_F_1600_LANES, KECCAK_F_1600_ROUNDS, KeccakF_RoundConstants, and ROL64.
Referenced by KeccakSponge_Absorb(), and KeccakSponge_Squeeze().
KeccakF_1600_StateXORBytes()
void KeccakF_1600_StateXORBytes (KeccakF_1600_State * state, const unsigned char * data, unsigned int offset, unsigned int length)
Definition at line 21 of file KeccakF-1600-reference.c.
References KeccakF_1600_State::A.
Referenced by KeccakSponge_Absorb().