SATOX SDK: satox::core::QuantumManager Class Reference
satox::core::QuantumManager Class Reference
#include <quantum.h>
Classes
struct AlgorithmInfo
struct QuantumEncryption
struct QuantumKeyPair
struct QuantumSignature
struct QuantumStats
Public Types
enum class Algorithm {
CRYSTALS_KYBER , CRYSTALS_DILITHIUM , FALCON , SPHINCS_PLUS ,
NTRU , SABER , SHA_3 , SHAKE_128 ,
SHAKE_256
}
using ErrorCallback = std::function<void(const std::string&)>
using StatsCallback = std::function<void(const QuantumStats&)>
Public Member Functions
QuantumManager ()
~QuantumManager ()
QuantumManager (const QuantumManager &)=delete
QuantumManager & operator= (const QuantumManager &)=delete
QuantumManager (QuantumManager &&) noexcept=default
QuantumManager & operator= (QuantumManager &&) noexcept=default
void initialize (const std::string &algorithm)
std::pair< std::string, std::string > generateKeyPair ()
std::string encrypt (const std::string &publicKey, const std::string &data)
std::string decrypt (const std::string &privateKey, const std::string &encryptedData)
std::string serializeKey (const std::string &key)
std::string deserializeKey (const std::string &serialized)
bool initialize (const nlohmann::json &config=nlohmann::json::object())
bool shutdown ()
bool isInitialized () const
QuantumKeyPair generateKeyPair (const std::string &algorithm="CRYSTALS-Kyber")
QuantumSignature sign (const std::vector< uint8_t > &data, const std::vector< uint8_t > &privateKey)
bool verify (const std::vector< uint8_t > &data, const QuantumSignature &signature)
QuantumEncryption encrypt (const std::vector< uint8_t > &data, const std::vector< uint8_t > &publicKey)
std::vector< uint8_t > decrypt (const QuantumEncryption &encryption, const std::vector< uint8_t > &privateKey)
std::vector< uint8_t > generateRandomBytes (size_t length)
uint64_t generateRandomNumber (uint64_t min, uint64_t max)
std::vector< uint8_t > hash (const std::vector< uint8_t > &data, const std::string &algorithm="SHA-3")
AlgorithmInfo getAlgorithmInfo (Algorithm algorithm) const
std::vector< Algorithm > getSupportedAlgorithms () const
QuantumStats getStats () const
bool enableStats (bool enable)
bool resetStats ()
std::string getLastError () const
bool clearLastError ()
bool registerErrorCallback (ErrorCallback callback)
bool registerStatsCallback (StatsCallback callback)
bool unregisterErrorCallback ()
bool unregisterStatsCallback ()
Static Public Member Functions
static QuantumManager & getInstance ()
Detailed Description
Definition at line 34 of file quantum.h.
Member Typedef Documentation
ErrorCallback
using satox::core::QuantumManager::ErrorCallback = std::function<void(const std::string&)>
Definition at line 125 of file quantum_manager.hpp.
StatsCallback
using satox::core::QuantumManager::StatsCallback = std::function<void(const QuantumStats&)>
Definition at line 126 of file quantum_manager.hpp.
Member Enumeration Documentation
Algorithm
enum class satox::core::QuantumManager::Algorithm strong
Enumerator
CRYSTALS_KYBER
CRYSTALS_DILITHIUM
FALCON
SPHINCS_PLUS
NTRU
SABER
SHA_3
SHAKE_128
SHAKE_256
Definition at line 79 of file quantum_manager.hpp.
Constructor & Destructor Documentation
QuantumManager() [1/3]
satox::core::QuantumManager::QuantumManager ()
Definition at line 37 of file quantum.cpp.
Referenced by getInstance(), operator=(), operator=(), QuantumManager(), and QuantumManager().
~QuantumManager()
satox::core::QuantumManager::~QuantumManager ()
Definition at line 39 of file quantum.cpp.
QuantumManager() [2/3]
satox::core::QuantumManager::QuantumManager (const QuantumManager &) delete
References QuantumManager().
QuantumManager() [3/3]
satox::core::QuantumManager::QuantumManager (QuantumManager &&) default noexcept
References QuantumManager().
Member Function Documentation
clearLastError()
bool satox::core::QuantumManager::clearLastError ()
Definition at line 1207 of file quantum_manager.cpp.
decrypt() [1/2]
std::vector< uint8_t > satox::core::QuantumManager::decrypt (const QuantumEncryption & encryption, const std::vector< uint8_t > & privateKey)
Definition at line 753 of file quantum_manager.cpp.
decrypt() [2/2]
std::string satox::core::QuantumManager::decrypt (const std::string & privateKey, const std::string & encryptedData)
Definition at line 86 of file quantum.cpp.
Referenced by operator=().
deserializeKey()
std::string satox::core::QuantumManager::deserializeKey (const std::string & serialized)
Definition at line 110 of file quantum.cpp.
Referenced by operator=().
enableStats()
bool satox::core::QuantumManager::enableStats (bool enable)
Definition at line 1190 of file quantum_manager.cpp.
encrypt() [1/2]
std::string satox::core::QuantumManager::encrypt (const std::string & publicKey, const std::string & data)
Definition at line 72 of file quantum.cpp.
Referenced by operator=().
encrypt() [2/2]
QuantumManager::QuantumEncryption satox::core::QuantumManager::encrypt (const std::vector< uint8_t > & data, const std::vector< uint8_t > & publicKey)
Definition at line 613 of file quantum_manager.cpp.
generateKeyPair() [1/2]
std::pair< std::string, std::string > satox::core::QuantumManager::generateKeyPair ()
Definition at line 58 of file quantum.cpp.
Referenced by operator=().
generateKeyPair() [2/2]
QuantumManager::QuantumKeyPair satox::core::QuantumManager::generateKeyPair (const std::string & algorithm = "CRYSTALS-Kyber")
Definition at line 87 of file quantum_manager.cpp.
generateRandomBytes()
std::vector< uint8_t > satox::core::QuantumManager::generateRandomBytes (size_t length)
Definition at line 875 of file quantum_manager.cpp.
generateRandomNumber()
uint64_t satox::core::QuantumManager::generateRandomNumber (uint64_t min, uint64_t max)
Definition at line 896 of file quantum_manager.cpp.
getAlgorithmInfo()
QuantumManager::AlgorithmInfo satox::core::QuantumManager::getAlgorithmInfo (Algorithm algorithm) const
Definition at line 1074 of file quantum_manager.cpp.
References satox::core::QuantumManager::AlgorithmInfo::ciphertextSize, CRYSTALS_DILITHIUM, CRYSTALS_KYBER, satox::core::QuantumManager::AlgorithmInfo::description, FALCON, satox::core::QuantumManager::AlgorithmInfo::isEncryption, satox::core::QuantumManager::AlgorithmInfo::isHash, satox::core::QuantumManager::AlgorithmInfo::isSignature, satox::core::QuantumManager::AlgorithmInfo::keySize, satox::core::QuantumManager::AlgorithmInfo::name, NTRU, SABER, SHA_3, SHAKE_128, SHAKE_256, satox::core::QuantumManager::AlgorithmInfo::signatureSize, and SPHINCS_PLUS.
getInstance()
QuantumManager & satox::core::QuantumManager::getInstance () static
Definition at line 34 of file quantum_manager.cpp.
References QuantumManager().
getLastError()
std::string satox::core::QuantumManager::getLastError () const
Definition at line 1202 of file quantum_manager.cpp.
getStats()
QuantumManager::QuantumStats satox::core::QuantumManager::getStats () const
Definition at line 1185 of file quantum_manager.cpp.
getSupportedAlgorithms()
std::vector< QuantumManager::Algorithm > satox::core::QuantumManager::getSupportedAlgorithms () const
Definition at line 1171 of file quantum_manager.cpp.
References CRYSTALS_DILITHIUM, CRYSTALS_KYBER, FALCON, NTRU, SABER, SHA_3, SHAKE_128, SHAKE_256, and SPHINCS_PLUS.
hash()
std::vector< uint8_t > satox::core::QuantumManager::hash (const std::vector< uint8_t > & data, const std::string & algorithm = "SHA-3")
Definition at line 916 of file quantum_manager.cpp.
initialize() [1/2]
bool satox::core::QuantumManager::initialize (const nlohmann::json & config = nlohmann::json::object())
Definition at line 39 of file quantum_manager.cpp.
initialize() [2/2]
void satox::core::QuantumManager::initialize (const std::string & algorithm)
Definition at line 45 of file quantum.cpp.
Referenced by operator=().
isInitialized()
bool satox::core::QuantumManager::isInitialized () const
Definition at line 82 of file quantum_manager.cpp.
operator=() [1/2]
QuantumManager & satox::core::QuantumManager::operator= (const QuantumManager &) delete
References QuantumManager().
operator=() [2/2]
QuantumManager & satox::core::QuantumManager::operator= (QuantumManager &&) default noexcept
References decrypt(), deserializeKey(), encrypt(), generateKeyPair(), initialize(), QuantumManager(), and serializeKey().
registerErrorCallback()
bool satox::core::QuantumManager::registerErrorCallback (ErrorCallback callback)
Definition at line 1213 of file quantum_manager.cpp.
registerStatsCallback()
bool satox::core::QuantumManager::registerStatsCallback (StatsCallback callback)
Definition at line 1219 of file quantum_manager.cpp.
resetStats()
bool satox::core::QuantumManager::resetStats ()
Definition at line 1196 of file quantum_manager.cpp.
serializeKey()
std::string satox::core::QuantumManager::serializeKey (const std::string & key)
Definition at line 100 of file quantum.cpp.
Referenced by operator=().
shutdown()
bool satox::core::QuantumManager::shutdown ()
Definition at line 66 of file quantum_manager.cpp.
sign()
QuantumManager::QuantumSignature satox::core::QuantumManager::sign (const std::vector< uint8_t > & data, const std::vector< uint8_t > & privateKey)
Definition at line 339 of file quantum_manager.cpp.
unregisterErrorCallback()
bool satox::core::QuantumManager::unregisterErrorCallback ()
Definition at line 1225 of file quantum_manager.cpp.
unregisterStatsCallback()
bool satox::core::QuantumManager::unregisterStatsCallback ()
Definition at line 1231 of file quantum_manager.cpp.
verify()
bool satox::core::QuantumManager::verify (const std::vector< uint8_t > & data, const QuantumSignature & signature)
Definition at line 506 of file quantum_manager.cpp.
References satox::core::QuantumManager::QuantumSignature::publicKey.
The documentation for this class was generated from the following files:
src/core/include/satox/core/quantum.h
src/core/include/satox/core/quantum_manager.hpp
src/core/src/quantum.cpp
src/core/src/quantum_manager.cpp