SATOX SDK: satox::core::NetworkInterface Class Reference
satox::core::NetworkInterface Class Reference
#include <network_interface.h>
Public Member Functions
NetworkInterface ()
~NetworkInterface ()
NetworkInterface (const NetworkInterface &)=delete
NetworkInterface & operator= (const NetworkInterface &)=delete
NetworkInterface (NetworkInterface &&) noexcept=default
NetworkInterface & operator= (NetworkInterface &&) noexcept=default
bool connect (const std::string &address, uint16_t port)
void disconnect ()
bool isConnected () const
void sendMessage (const NetworkMessage &message)
void setMessageCallback (std::function< void(const NetworkMessage &)> callback)
NetworkResponse waitForResponse (const std::string &requestId, std::chrono::milliseconds timeout=std::chrono::seconds(30))
void handleResponse (const NetworkMessage &response)
std::vector< std::string > getPeers () const
void addPeer (const std::string &address, uint16_t port)
void removePeer (const std::string &address)
void broadcastMessage (const NetworkMessage &message)
std::string getLatestBlock ()
std::string getBlockByHash (const std::string &hash)
std::string getTransactionByHash (const std::string &hash)
std::string getBalance (const std::string &address)
std::string sendTransaction (const std::string &transaction)
std::vector< NetworkMessage > getMessages ()
void setErrorCallback (std::function< void(const std::string &)> callback)
Detailed Description
Definition at line 70 of file network_interface.h.
Constructor & Destructor Documentation
NetworkInterface() [1/3]
satox::core::NetworkInterface::NetworkInterface ()
Definition at line 46 of file network_interface.cpp.
Referenced by NetworkInterface(), NetworkInterface(), operator=(), and operator=().
~NetworkInterface()
satox::core::NetworkInterface::~NetworkInterface ()
Definition at line 53 of file network_interface.cpp.
References disconnect().
NetworkInterface() [2/3]
satox::core::NetworkInterface::NetworkInterface (const NetworkInterface &) delete
References NetworkInterface().
NetworkInterface() [3/3]
satox::core::NetworkInterface::NetworkInterface (NetworkInterface &&) default noexcept
References NetworkInterface().
Member Function Documentation
addPeer()
void satox::core::NetworkInterface::addPeer (const std::string & address, uint16_t port)
References addPeer().
Referenced by addPeer().
broadcastMessage()
void satox::core::NetworkInterface::broadcastMessage (const NetworkMessage & message)
References broadcastMessage(), getBalance(), getBlockByHash(), getLatestBlock(), getTransactionByHash(), and sendTransaction().
Referenced by broadcastMessage().
connect()
bool satox::core::NetworkInterface::connect (const std::string & address, uint16_t port)
Definition at line 199 of file network_interface.cpp.
Referenced by operator=().
disconnect()
void satox::core::NetworkInterface::disconnect ()
Definition at line 207 of file network_interface.cpp.
References satox::core::NetworkResponse::error, and satox::core::NetworkResponse::success.
Referenced by operator=(), and ~NetworkInterface().
getBalance()
std::string satox::core::NetworkInterface::getBalance (const std::string & address)
Definition at line 354 of file network_interface.cpp.
References satox::core::NetworkMessage::payload, satox::core::NetworkMessage::requestId, sendMessage(), satox::core::NetworkMessage::SYNC_REQUEST, satox::core::NetworkMessage::timestamp, satox::core::NetworkMessage::type, and waitForResponse().
Referenced by broadcastMessage().
getBlockByHash()
std::string satox::core::NetworkInterface::getBlockByHash (const std::string & hash)
Definition at line 330 of file network_interface.cpp.
References satox::core::NetworkMessage::payload, satox::core::NetworkMessage::requestId, sendMessage(), satox::core::NetworkMessage::SYNC_REQUEST, satox::core::NetworkMessage::timestamp, satox::core::NetworkMessage::type, and waitForResponse().
Referenced by broadcastMessage().
getLatestBlock()
std::string satox::core::NetworkInterface::getLatestBlock ()
Definition at line 318 of file network_interface.cpp.
References satox::core::NetworkMessage::payload, satox::core::NetworkMessage::requestId, sendMessage(), satox::core::NetworkMessage::SYNC_REQUEST, satox::core::NetworkMessage::timestamp, satox::core::NetworkMessage::type, and waitForResponse().
Referenced by broadcastMessage().
getMessages()
std::vector< NetworkMessage > satox::core::NetworkInterface::getMessages () inline
Definition at line 111 of file network_interface.h.
References getMessages().
Referenced by getMessages().
getPeers()
std::vector< std::string > satox::core::NetworkInterface::getPeers () const
References getPeers().
Referenced by getPeers().
getTransactionByHash()
std::string satox::core::NetworkInterface::getTransactionByHash (const std::string & hash)
Definition at line 342 of file network_interface.cpp.
References satox::core::NetworkMessage::payload, satox::core::NetworkMessage::requestId, sendMessage(), satox::core::NetworkMessage::SYNC_REQUEST, satox::core::NetworkMessage::timestamp, satox::core::NetworkMessage::type, and waitForResponse().
Referenced by broadcastMessage().
handleResponse()
void satox::core::NetworkInterface::handleResponse (const NetworkMessage & response)
Definition at line 108 of file network_interface.cpp.
References satox::core::NetworkMessage::requestId.
Referenced by operator=().
isConnected()
bool satox::core::NetworkInterface::isConnected () const
Definition at line 225 of file network_interface.cpp.
Referenced by operator=().
operator=() [1/2]
NetworkInterface & satox::core::NetworkInterface::operator= (const NetworkInterface &) delete
References NetworkInterface().
operator=() [2/2]
NetworkInterface & satox::core::NetworkInterface::operator= (NetworkInterface &&) default noexcept
References connect(), disconnect(), handleResponse(), isConnected(), NetworkInterface(), sendMessage(), setMessageCallback(), and waitForResponse().
removePeer()
void satox::core::NetworkInterface::removePeer (const std::string & address)
References removePeer().
Referenced by removePeer().
sendMessage()
void satox::core::NetworkInterface::sendMessage (const NetworkMessage & message)
Definition at line 229 of file network_interface.cpp.
References satox::core::NetworkMessage::requestId, satox::core::NetworkMessage::SYNC_REQUEST, and satox::core::NetworkMessage::type.
Referenced by getBalance(), getBlockByHash(), getLatestBlock(), getTransactionByHash(), operator=(), and sendTransaction().
sendTransaction()
std::string satox::core::NetworkInterface::sendTransaction (const std::string & transaction)
Definition at line 366 of file network_interface.cpp.
References satox::core::NetworkMessage::payload, satox::core::NetworkMessage::requestId, sendMessage(), satox::core::NetworkMessage::timestamp, satox::core::NetworkMessage::TRANSACTION, satox::core::NetworkMessage::type, and waitForResponse().
Referenced by broadcastMessage().
setErrorCallback()
void satox::core::NetworkInterface::setErrorCallback (std::function< void(const std::string &)> callback)
Definition at line 195 of file network_interface.cpp.
setMessageCallback()
void satox::core::NetworkInterface::setMessageCallback (std::function< void(const NetworkMessage &)> callback)
Definition at line 191 of file network_interface.cpp.
Referenced by operator=().
waitForResponse()
std::future< NetworkMessage > satox::core::NetworkInterface::waitForResponse (const std::string & requestId, std::chrono::milliseconds timeout = std::chrono::seconds(30))
Definition at line 137 of file network_interface.cpp.
References satox::core::NetworkMessage::ERROR, satox::core::NetworkMessage::payload, and satox::core::NetworkMessage::type.
Referenced by getBalance(), getBlockByHash(), getLatestBlock(), getTransactionByHash(), operator=(), and sendTransaction().
The documentation for this class was generated from the following files:
src/core/include/satox/core/network_interface.h
src/core/src/network_interface.cpp