SATOX SDK: satox::security::monitoring::SecurityMonitor Class Reference
satox::security::monitoring::SecurityMonitor Class Reference
#include <security_monitor.hpp>
Public Member Functions
void recordOperation (const std::string &operation, const std::chrono::milliseconds &duration, bool success)
void recordKeyOperation (const std::string &operation, const std::string &keyId, bool success)
void recordCacheOperation (const std::string &operation, bool hit)
void recordResourceUsage (size_t memoryUsage, double cpuUsage)
void recordError (const std::string &operation, const std::string &errorType)
double getAverageOperationTime (const std::string &operation) const
double getOperationSuccessRate (const std::string &operation) const
double getCacheHitRate () const
size_t getCurrentMemoryUsage () const
double getCurrentCpuUsage () const
size_t getErrorCount (const std::string &operation) const
std::string exportMetrics () const
void exportToPrometheus (const std::string &endpoint)
Static Public Member Functions
static SecurityMonitor & getInstance ()
Detailed Description
Definition at line 44 of file security_monitor.hpp.
Member Function Documentation
exportMetrics()
std::string satox::security::monitoring::SecurityMonitor::exportMetrics () const
Definition at line 261 of file security_monitor.cpp.
References getAverageOperationTime(), getCacheHitRate(), getCurrentCpuUsage(), getCurrentMemoryUsage(), and getOperationSuccessRate().
exportToPrometheus()
void satox::security::monitoring::SecurityMonitor::exportToPrometheus (const std::string & endpoint)
Definition at line 297 of file security_monitor.cpp.
getAverageOperationTime()
double satox::security::monitoring::SecurityMonitor::getAverageOperationTime (const std::string & operation) const
Definition at line 210 of file security_monitor.cpp.
Referenced by exportMetrics().
getCacheHitRate()
double satox::security::monitoring::SecurityMonitor::getCacheHitRate () const
Definition at line 238 of file security_monitor.cpp.
Referenced by exportMetrics().
getCurrentCpuUsage()
double satox::security::monitoring::SecurityMonitor::getCurrentCpuUsage () const
Definition at line 251 of file security_monitor.cpp.
Referenced by exportMetrics().
getCurrentMemoryUsage()
size_t satox::security::monitoring::SecurityMonitor::getCurrentMemoryUsage () const
Definition at line 247 of file security_monitor.cpp.
Referenced by exportMetrics().
getErrorCount()
size_t satox::security::monitoring::SecurityMonitor::getErrorCount (const std::string & operation) const
Definition at line 255 of file security_monitor.cpp.
getInstance()
static SecurityMonitor & satox::security::monitoring::SecurityMonitor::getInstance () inline static
Definition at line 46 of file security_monitor.hpp.
getOperationSuccessRate()
double satox::security::monitoring::SecurityMonitor::getOperationSuccessRate (const std::string & operation) const
Definition at line 224 of file security_monitor.cpp.
Referenced by exportMetrics().
recordCacheOperation()
void satox::security::monitoring::SecurityMonitor::recordCacheOperation (const std::string & operation, bool hit)
Definition at line 166 of file security_monitor.cpp.
recordError()
void satox::security::monitoring::SecurityMonitor::recordError (const std::string & operation, const std::string & errorType)
Definition at line 197 of file security_monitor.cpp.
recordKeyOperation()
void satox::security::monitoring::SecurityMonitor::recordKeyOperation (const std::string & operation, const std::string & keyId, bool success)
Definition at line 153 of file security_monitor.cpp.
recordOperation()
void satox::security::monitoring::SecurityMonitor::recordOperation (const std::string & operation, const std::chrono::milliseconds & duration, bool success)
Definition at line 124 of file security_monitor.cpp.
recordResourceUsage()
void satox::security::monitoring::SecurityMonitor::recordResourceUsage (size_t memoryUsage, double cpuUsage)
Definition at line 177 of file security_monitor.cpp.
The documentation for this class was generated from the following files:
src/security/monitoring/security_monitor.hpp
src/security/monitoring/security_monitor.cpp