SATOX SDK: satox::core::WalletManager Class Reference
satox::core::WalletManager Class Reference
#include <wallet_manager.hpp>
Classes
struct TransactionInfo
struct WalletInfo
struct WalletStats
Public Types
enum class WalletType { HD , LEGACY , MULTISIG , WATCH_ONLY }
enum class WalletState {
UNINITIALIZED , INITIALIZED , UNLOCKED , LOCKED ,
ERROR
}
enum class TransactionType {
SEND , RECEIVE , STAKE , UNSTAKE ,
ASSET_ISSUE , ASSET_TRANSFER , ASSET_BURN , NFT_MINT ,
NFT_TRANSFER , NFT_BURN
}
enum class TransactionState { PENDING , CONFIRMED , FAILED , DROPPED }
using WalletCallback = std::function<void(const std::string&, WalletState)>
using TransactionCallback = std::function<void(const std::string&, TransactionState)>
using BalanceCallback = std::function<void(const std::string&, double)>
using ErrorCallback = std::function<void(const std::string&, const std::string&)>
Public Member Functions
bool initialize (const nlohmann::json &config)
void shutdown ()
bool createWallet (const std::string &id, const std::string &name, WalletType type)
bool importWallet (const std::string &id, const std::string &name, const std::string &privateKey)
bool exportWallet (const std::string &id, std::string &privateKey)
bool deleteWallet (const std::string &id)
bool lockWallet (const std::string &id)
bool unlockWallet (const std::string &id, const std::string &password)
bool isWalletLocked (const std::string &id) const
bool isWalletExists (const std::string &id) const
WalletInfo getWalletInfo (const std::string &id) const
std::vector< WalletInfo > getAllWallets () const
std::vector< WalletInfo > getWalletsByType (WalletType type) const
std::vector< WalletInfo > getWalletsByState (WalletState state) const
std::string generateAddress (const std::string &walletId)
bool validateAddress (const std::string &address) const
std::string getAddressFromPrivateKey (const std::string &privateKey) const
std::string getPublicKeyFromPrivateKey (const std::string &privateKey) const
bool createTransaction (const std::string &walletId, TransactionType type, const std::string &toAddress, double amount, const std::string &assetId="")
bool signTransaction (const std::string &walletId, const std::string &txId)
bool broadcastTransaction (const std::string &walletId, const std::string &txId)
bool confirmTransaction (const std::string &walletId, const std::string &txId)
bool failTransaction (const std::string &walletId, const std::string &txId)
TransactionInfo getTransactionInfo (const std::string &walletId, const std::string &txId) const
std::vector< TransactionInfo > getTransactionsByType (const std::string &walletId, TransactionType type) const
std::vector< TransactionInfo > getTransactionsByState (const std::string &walletId, TransactionState state) const
double getBalance (const std::string &walletId) const
double getAssetBalance (const std::string &walletId, const std::string &assetId) const
std::map< std::string, double > getAllBalances (const std::string &walletId) const
bool updateBalance (const std::string &walletId, double amount)
bool updateAssetBalance (const std::string &walletId, const std::string &assetId, double amount)
WalletStats getStats () const
void resetStats ()
bool enableStats (bool enable)
void registerWalletCallback (WalletCallback callback)
void registerTransactionCallback (TransactionCallback callback)
void registerBalanceCallback (BalanceCallback callback)
void registerErrorCallback (ErrorCallback callback)
void unregisterWalletCallback ()
void unregisterTransactionCallback ()
void unregisterBalanceCallback ()
void unregisterErrorCallback ()
std::string getLastError () const
void clearLastError ()
void setLastError (const std::string &error)
Static Public Member Functions
static WalletManager & getInstance ()
Detailed Description
Definition at line 39 of file wallet_manager.hpp.
Member Typedef Documentation
BalanceCallback
using satox::core::WalletManager::BalanceCallback = std::function<void(const std::string&, double)>
Definition at line 129 of file wallet_manager.hpp.
ErrorCallback
using satox::core::WalletManager::ErrorCallback = std::function<void(const std::string&, const std::string&)>
Definition at line 130 of file wallet_manager.hpp.
TransactionCallback
using satox::core::WalletManager::TransactionCallback = std::function<void(const std::string&, TransactionState)>
Definition at line 128 of file wallet_manager.hpp.
WalletCallback
using satox::core::WalletManager::WalletCallback = std::function<void(const std::string&, WalletState)>
Definition at line 127 of file wallet_manager.hpp.
Member Enumeration Documentation
TransactionState
enum class satox::core::WalletManager::TransactionState strong
Enumerator
PENDING
CONFIRMED
FAILED
DROPPED
Definition at line 73 of file wallet_manager.hpp.
TransactionType
enum class satox::core::WalletManager::TransactionType strong
Enumerator
SEND
RECEIVE
STAKE
UNSTAKE
ASSET_ISSUE
ASSET_TRANSFER
ASSET_BURN
NFT_MINT
NFT_TRANSFER
NFT_BURN
Definition at line 59 of file wallet_manager.hpp.
WalletState
enum class satox::core::WalletManager::WalletState strong
Enumerator
UNINITIALIZED
INITIALIZED
UNLOCKED
LOCKED
ERROR
Definition at line 50 of file wallet_manager.hpp.
WalletType
enum class satox::core::WalletManager::WalletType strong
Enumerator
HD
LEGACY
MULTISIG
WATCH_ONLY
Definition at line 42 of file wallet_manager.hpp.
Member Function Documentation
broadcastTransaction()
bool satox::core::WalletManager::broadcastTransaction (const std::string & walletId, const std::string & txId)
Definition at line 465 of file wallet_manager.cpp.
References CONFIRMED, and PENDING.
clearLastError()
void satox::core::WalletManager::clearLastError ()
Definition at line 755 of file wallet_manager.cpp.
confirmTransaction()
bool satox::core::WalletManager::confirmTransaction (const std::string & walletId, const std::string & txId)
Definition at line 508 of file wallet_manager.cpp.
References CONFIRMED.
createTransaction()
bool satox::core::WalletManager::createTransaction (const std::string & walletId, TransactionType type, const std::string & toAddress, double amount, const std::string & assetId = "")
Definition at line 366 of file wallet_manager.cpp.
References getBalance(), LOCKED, PENDING, and validateAddress().
createWallet()
bool satox::core::WalletManager::createWallet (const std::string & id, const std::string & name, WalletType type)
Definition at line 77 of file wallet_manager.cpp.
References INITIALIZED.
deleteWallet()
bool satox::core::WalletManager::deleteWallet (const std::string & id)
Definition at line 185 of file wallet_manager.cpp.
enableStats()
bool satox::core::WalletManager::enableStats (bool enable)
Definition at line 704 of file wallet_manager.cpp.
exportWallet()
bool satox::core::WalletManager::exportWallet (const std::string & id, std::string & privateKey)
Definition at line 162 of file wallet_manager.cpp.
References LOCKED.
failTransaction()
bool satox::core::WalletManager::failTransaction (const std::string & walletId, const std::string & txId)
Definition at line 541 of file wallet_manager.cpp.
References FAILED.
generateAddress()
std::string satox::core::WalletManager::generateAddress (const std::string & walletId)
Definition at line 315 of file wallet_manager.cpp.
References HD, LEGACY, and LOCKED.
getAddressFromPrivateKey()
std::string satox::core::WalletManager::getAddressFromPrivateKey (const std::string & privateKey) const
Definition at line 356 of file wallet_manager.cpp.
Referenced by importWallet().
getAllBalances()
std::map< std::string, double > satox::core::WalletManager::getAllBalances (const std::string & walletId) const
Definition at line 647 of file wallet_manager.cpp.
getAllWallets()
std::vector< WalletManager::WalletInfo > satox::core::WalletManager::getAllWallets () const
Definition at line 284 of file wallet_manager.cpp.
getAssetBalance()
double satox::core::WalletManager::getAssetBalance (const std::string & walletId, const std::string & assetId) const
Definition at line 633 of file wallet_manager.cpp.
getBalance()
double satox::core::WalletManager::getBalance (const std::string & walletId) const
Definition at line 617 of file wallet_manager.cpp.
Referenced by createTransaction().
getInstance()
WalletManager & satox::core::WalletManager::getInstance () static
Definition at line 37 of file wallet_manager.cpp.
Referenced by satox::core::CoreManager::getWalletManager(), and satox::core::SatoxManager::getWalletManager().
getLastError()
std::string satox::core::WalletManager::getLastError () const
Definition at line 750 of file wallet_manager.cpp.
getPublicKeyFromPrivateKey()
std::string satox::core::WalletManager::getPublicKeyFromPrivateKey (const std::string & privateKey) const
Definition at line 361 of file wallet_manager.cpp.
Referenced by importWallet().
getStats()
WalletManager::WalletStats satox::core::WalletManager::getStats () const
Definition at line 694 of file wallet_manager.cpp.
getTransactionInfo()
WalletManager::TransactionInfo satox::core::WalletManager::getTransactionInfo (const std::string & walletId, const std::string & txId) const
Definition at line 570 of file wallet_manager.cpp.
getTransactionsByState()
std::vector< WalletManager::TransactionInfo > satox::core::WalletManager::getTransactionsByState (const std::string & walletId, TransactionState state) const
Definition at line 602 of file wallet_manager.cpp.
getTransactionsByType()
std::vector< WalletManager::TransactionInfo > satox::core::WalletManager::getTransactionsByType (const std::string & walletId, TransactionType type) const
Definition at line 587 of file wallet_manager.cpp.
getWalletInfo()
WalletManager::WalletInfo satox::core::WalletManager::getWalletInfo (const std::string & id) const
Definition at line 275 of file wallet_manager.cpp.
getWalletsByState()
std::vector< WalletManager::WalletInfo > satox::core::WalletManager::getWalletsByState (WalletState state) const
Definition at line 304 of file wallet_manager.cpp.
getWalletsByType()
std::vector< WalletManager::WalletInfo > satox::core::WalletManager::getWalletsByType (WalletType type) const
Definition at line 293 of file wallet_manager.cpp.
importWallet()
bool satox::core::WalletManager::importWallet (const std::string & id, const std::string & name, const std::string & privateKey)
Definition at line 118 of file wallet_manager.cpp.
References getAddressFromPrivateKey(), getPublicKeyFromPrivateKey(), INITIALIZED, and LEGACY.
initialize()
bool satox::core::WalletManager::initialize (const nlohmann::json & config)
Definition at line 42 of file wallet_manager.cpp.
isWalletExists()
bool satox::core::WalletManager::isWalletExists (const std::string & id) const
Definition at line 270 of file wallet_manager.cpp.
isWalletLocked()
bool satox::core::WalletManager::isWalletLocked (const std::string & id) const
Definition at line 261 of file wallet_manager.cpp.
References LOCKED.
lockWallet()
bool satox::core::WalletManager::lockWallet (const std::string & id)
Definition at line 206 of file wallet_manager.cpp.
References LOCKED.
registerBalanceCallback()
void satox::core::WalletManager::registerBalanceCallback (BalanceCallback callback)
Definition at line 720 of file wallet_manager.cpp.
registerErrorCallback()
void satox::core::WalletManager::registerErrorCallback (ErrorCallback callback)
Definition at line 725 of file wallet_manager.cpp.
registerTransactionCallback()
void satox::core::WalletManager::registerTransactionCallback (TransactionCallback callback)
Definition at line 715 of file wallet_manager.cpp.
registerWalletCallback()
void satox::core::WalletManager::registerWalletCallback (WalletCallback callback)
Definition at line 710 of file wallet_manager.cpp.
resetStats()
void satox::core::WalletManager::resetStats ()
Definition at line 699 of file wallet_manager.cpp.
setLastError()
void satox::core::WalletManager::setLastError (const std::string & error)
Definition at line 760 of file wallet_manager.cpp.
shutdown()
void satox::core::WalletManager::shutdown ()
Definition at line 60 of file wallet_manager.cpp.
signTransaction()
bool satox::core::WalletManager::signTransaction (const std::string & walletId, const std::string & txId)
Definition at line 426 of file wallet_manager.cpp.
References LOCKED, and PENDING.
unlockWallet()
bool satox::core::WalletManager::unlockWallet (const std::string & id, const std::string & password)
Definition at line 231 of file wallet_manager.cpp.
References LOCKED, and UNLOCKED.
unregisterBalanceCallback()
void satox::core::WalletManager::unregisterBalanceCallback ()
Definition at line 740 of file wallet_manager.cpp.
unregisterErrorCallback()
void satox::core::WalletManager::unregisterErrorCallback ()
Definition at line 745 of file wallet_manager.cpp.
unregisterTransactionCallback()
void satox::core::WalletManager::unregisterTransactionCallback ()
Definition at line 735 of file wallet_manager.cpp.
unregisterWalletCallback()
void satox::core::WalletManager::unregisterWalletCallback ()
Definition at line 730 of file wallet_manager.cpp.
updateAssetBalance()
bool satox::core::WalletManager::updateAssetBalance (const std::string & walletId, const std::string & assetId, double amount)
Definition at line 675 of file wallet_manager.cpp.
updateBalance()
bool satox::core::WalletManager::updateBalance (const std::string & walletId, double amount)
Definition at line 656 of file wallet_manager.cpp.
validateAddress()
bool satox::core::WalletManager::validateAddress (const std::string & address) const
Definition at line 351 of file wallet_manager.cpp.
Referenced by createTransaction().
The documentation for this class was generated from the following files:
src/core/include/satox/core/wallet_manager.hpp
src/core/src/wallet_manager.cpp