SATOX SDK: satox::blockchain::BlockchainException Class Reference
satox::blockchain::BlockchainException Class Reference
#include <error.hpp>
Public Member Functions
BlockchainException (BlockchainErrorCode code, const std::string &message="")
const char * what () const noexcept override
BlockchainErrorCode code () const
const std::string & message () const
BlockchainException (const std::string &msg)
Detailed Description
Definition at line 52 of file error.hpp.
Constructor & Destructor Documentation
BlockchainException() [1/2]
satox::blockchain::BlockchainException::BlockchainException (BlockchainErrorCode code, const std::string & message = "") inline
Definition at line 54 of file error.hpp.
References code(), and message().
Referenced by satox::blockchain::BlockchainInitializationException::BlockchainInitializationException(), and satox::blockchain::BlockchainOperationException::BlockchainOperationException().
BlockchainException() [2/2]
satox::blockchain::BlockchainException::BlockchainException (const std::string & msg) inline explicit
Definition at line 35 of file exceptions.hpp.
Member Function Documentation
code()
BlockchainErrorCode satox::blockchain::BlockchainException::code () const inline
Definition at line 61 of file error.hpp.
Referenced by BlockchainException().
message()
const std::string & satox::blockchain::BlockchainException::message () const inline
Definition at line 65 of file error.hpp.
Referenced by BlockchainException(), satox::blockchain::BlockchainInitializationException::BlockchainInitializationException(), and satox::blockchain::BlockchainOperationException::BlockchainOperationException().
what()
const char * satox::blockchain::BlockchainException::what () const inline override noexcept
Definition at line 57 of file error.hpp.
The documentation for this class was generated from the following files:
src/blockchain/include/satox/blockchain/error.hpp
src/blockchain/include/satox/blockchain/exceptions.hpp