SATOX SDK: satox::database::DatabaseManager Class Reference
satox::database::DatabaseManager Class Reference
Database Manager - Manages database operations and connections.
#include <database_manager.hpp>
Public Types
using DatabaseCallback = std::function<void(const std::string& operation, bool success, const std::string& error)>
using ConnectionCallback = std::function<void(bool connected, const std::string& details)>
using HealthCallback = std::function<void(const DatabaseHealth& health)>
Public Member Functions
bool initialize (const DatabaseConfig &config=DatabaseConfig{})
void shutdown ()
bool isInitialized () const
void setConfig (const DatabaseConfig &config)
DatabaseConfig getConfig () const
bool validateConfig (const DatabaseConfig &config) const
bool createDatabase (const std::string &name)
bool deleteDatabase (const std::string &name)
bool useDatabase (const std::string &name)
std::vector< std::string > listDatabases ()
bool databaseExists (const std::string &name)
bool createTable (const std::string &name, const nlohmann::json &schema)
bool deleteTable (const std::string &name)
bool tableExists (const std::string &name)
std::vector< std::string > listTables ()
nlohmann::json getTableSchema (const std::string &name)
bool insert (const std::string &table, const nlohmann::json &data)
bool update (const std::string &table, const std::string &id, const nlohmann::json &data)
bool remove (const std::string &table, const std::string &id)
nlohmann::json find (const std::string &table, const std::string &id)
std::vector< nlohmann::json > query (const std::string &table, const nlohmann::json &query)
bool beginTransaction ()
bool commitTransaction ()
bool rollbackTransaction ()
bool isInTransaction () const
bool createIndex (const std::string &table, const std::string &field)
bool dropIndex (const std::string &table, const std::string &field)
std::vector< std::string > listIndexes (const std::string &table)
bool createBackup (const std::string &backupPath)
bool restoreFromBackup (const std::string &backupPath)
bool connect (const std::string &connectionString)
void disconnect ()
bool isConnected () const
bool reconnect ()
void setMaxConnections (size_t max)
size_t getMaxConnections () const
void setConnectionTimeout (size_t milliseconds)
size_t getConnectionTimeout () const
void setDatabaseCallback (DatabaseCallback callback)
void setConnectionCallback (ConnectionCallback callback)
void setHealthCallback (HealthCallback callback)
void clearCallbacks ()
DatabaseStats getStats () const
void resetStats ()
DatabaseHealth getHealth () const
bool isHealthy () const
bool performHealthCheck ()
nlohmann::json getHealthStatus ()
DatabaseErrorCode getLastErrorCode () const
std::string getLastError () const
void clearLastError ()
Version getVersion () const
Static Public Member Functions
static DatabaseManager & getInstance ()
Detailed Description
Database Manager - Manages database operations and connections.
This class provides a singleton interface for database operations including:
Database creation, deletion, and management
Table operations (create, delete, query)
Transaction management
Connection pooling
Backup and restore operations
Health monitoring and statistics
Definition at line 38 of file database_manager.hpp.
Member Typedef Documentation
ConnectionCallback
using satox::database::DatabaseManager::ConnectionCallback = std::function<void(bool connected, const std::string& details)>
Definition at line 42 of file database_manager.hpp.
DatabaseCallback
using satox::database::DatabaseManager::DatabaseCallback = std::function<void(const std::string& operation, bool success, const std::string& error)>
Definition at line 41 of file database_manager.hpp.
HealthCallback
using satox::database::DatabaseManager::HealthCallback = std::function<void(const DatabaseHealth& health)>
Definition at line 43 of file database_manager.hpp.
Member Function Documentation
beginTransaction()
bool satox::database::DatabaseManager::beginTransaction ()
Definition at line 776 of file database_manager.cpp.
References satox::database::NOT_INITIALIZED, and satox::database::OPERATION_FAILED.
clearCallbacks()
void satox::database::DatabaseManager::clearCallbacks ()
Definition at line 1171 of file database_manager.cpp.
clearLastError()
void satox::database::DatabaseManager::clearLastError ()
Definition at line 1266 of file database_manager.cpp.
References satox::database::SUCCESS.
commitTransaction()
bool satox::database::DatabaseManager::commitTransaction ()
Definition at line 816 of file database_manager.cpp.
References satox::database::OPERATION_FAILED.
connect()
bool satox::database::DatabaseManager::connect (const std::string & connectionString)
Definition at line 366 of file database_manager.cpp.
References satox::database::NOT_INITIALIZED, and satox::database::OPERATION_FAILED.
Referenced by reconnect().
createBackup()
bool satox::database::DatabaseManager::createBackup (const std::string & backupPath)
Definition at line 1013 of file database_manager.cpp.
References satox::database::NOT_INITIALIZED, and satox::database::OPERATION_FAILED.
createDatabase()
bool satox::database::DatabaseManager::createDatabase (const std::string & name)
Definition at line 200 of file database_manager.cpp.
References satox::database::INVALID_ARGUMENT, satox::database::DatabaseData::name, satox::database::NOT_INITIALIZED, and satox::database::OPERATION_FAILED.
Referenced by satox_database_manager_create_database().
createIndex()
bool satox::database::DatabaseManager::createIndex (const std::string & table, const std::string & field)
Definition at line 889 of file database_manager.cpp.
References satox::database::NOT_INITIALIZED, and satox::database::OPERATION_FAILED.
createTable()
bool satox::database::DatabaseManager::createTable (const std::string & name, const nlohmann::json & schema)
Definition at line 1362 of file database_manager.cpp.
References satox::database::INVALID_ARGUMENT, satox::database::NOT_INITIALIZED, satox::database::OPERATION_FAILED, and satox::database::TableData::schema.
databaseExists()
bool satox::database::DatabaseManager::databaseExists (const std::string & name)
Definition at line 260 of file database_manager.cpp.
References satox::database::NOT_INITIALIZED.
deleteDatabase()
bool satox::database::DatabaseManager::deleteDatabase (const std::string & name)
Definition at line 297 of file database_manager.cpp.
References satox::database::NOT_INITIALIZED, and satox::database::OPERATION_FAILED.
deleteTable()
bool satox::database::DatabaseManager::deleteTable (const std::string & name)
Definition at line 462 of file database_manager.cpp.
References satox::database::NOT_INITIALIZED, and satox::database::OPERATION_FAILED.
disconnect()
void satox::database::DatabaseManager::disconnect ()
Definition at line 395 of file database_manager.cpp.
Referenced by reconnect(), and shutdown().
dropIndex()
bool satox::database::DatabaseManager::dropIndex (const std::string & table, const std::string & field)
Definition at line 931 of file database_manager.cpp.
References satox::database::NOT_INITIALIZED, and satox::database::OPERATION_FAILED.
find()
nlohmann::json satox::database::DatabaseManager::find (const std::string & table, const std::string & id)
Definition at line 726 of file database_manager.cpp.
References satox::database::NOT_INITIALIZED, and satox::database::OPERATION_FAILED.
getConfig()
DatabaseConfig satox::database::DatabaseManager::getConfig () const
Definition at line 1296 of file database_manager.cpp.
getConnectionTimeout()
size_t satox::database::DatabaseManager::getConnectionTimeout () const
Definition at line 255 of file database_manager.cpp.
getHealth()
DatabaseHealth satox::database::DatabaseManager::getHealth () const
Definition at line 1210 of file database_manager.cpp.
getHealthStatus()
nlohmann::json satox::database::DatabaseManager::getHealthStatus ()
Definition at line 1588 of file database_manager.cpp.
References isHealthy().
getInstance()
DatabaseManager & satox::database::DatabaseManager::getInstance () static
Definition at line 24 of file database_manager.cpp.
Referenced by satox_database_manager_create().
getLastError()
std::string satox::database::DatabaseManager::getLastError () const
Definition at line 1261 of file database_manager.cpp.
getLastErrorCode()
DatabaseErrorCode satox::database::DatabaseManager::getLastErrorCode () const
Definition at line 1256 of file database_manager.cpp.
getMaxConnections()
size_t satox::database::DatabaseManager::getMaxConnections () const
Definition at line 250 of file database_manager.cpp.
getStats()
DatabaseStats satox::database::DatabaseManager::getStats () const
Definition at line 1190 of file database_manager.cpp.
getTableSchema()
nlohmann::json satox::database::DatabaseManager::getTableSchema (const std::string & name)
Definition at line 1408 of file database_manager.cpp.
References satox::database::NOT_INITIALIZED, and satox::database::OPERATION_FAILED.
getVersion()
Version satox::database::DatabaseManager::getVersion () const
Definition at line 1278 of file database_manager.cpp.
initialize()
bool satox::database::DatabaseManager::initialize (const DatabaseConfig & config = DatabaseConfig{})
Definition at line 49 of file database_manager.cpp.
References satox::database::ALREADY_INITIALIZED, satox::database::INITIALIZATION_ERROR, satox::database::INITIALIZED, satox::database::INVALID_ARGUMENT, satox::database::DatabaseStats::lastOperation, satox::database::DatabaseHealth::status, and validateConfig().
insert()
bool satox::database::DatabaseManager::insert (const std::string & table, const nlohmann::json & data)
Definition at line 504 of file database_manager.cpp.
References satox::database::INVALID_ARGUMENT, satox::database::NOT_INITIALIZED, and satox::database::OPERATION_FAILED.
isConnected()
bool satox::database::DatabaseManager::isConnected () const
Definition at line 245 of file database_manager.cpp.
isHealthy()
bool satox::database::DatabaseManager::isHealthy () const
Definition at line 1219 of file database_manager.cpp.
Referenced by getHealthStatus().
isInitialized()
bool satox::database::DatabaseManager::isInitialized () const
Definition at line 240 of file database_manager.cpp.
isInTransaction()
bool satox::database::DatabaseManager::isInTransaction () const
Definition at line 883 of file database_manager.cpp.
listDatabases()
std::vector< std::string > satox::database::DatabaseManager::listDatabases ()
Definition at line 277 of file database_manager.cpp.
References satox::database::NOT_INITIALIZED.
Referenced by satox_database_manager_list_databases().
listIndexes()
std::vector< std::string > satox::database::DatabaseManager::listIndexes (const std::string & table)
Definition at line 979 of file database_manager.cpp.
References satox::database::NOT_INITIALIZED, and satox::database::OPERATION_FAILED.
listTables()
std::vector< std::string > satox::database::DatabaseManager::listTables ()
Definition at line 436 of file database_manager.cpp.
References satox::database::NOT_INITIALIZED.
performHealthCheck()
bool satox::database::DatabaseManager::performHealthCheck ()
Definition at line 1230 of file database_manager.cpp.
References satox::database::ERROR, and satox::database::RUNNING.
query()
std::vector< nlohmann::json > satox::database::DatabaseManager::query (const std::string & table, const nlohmann::json & query)
Definition at line 560 of file database_manager.cpp.
References satox::database::NOT_INITIALIZED, satox::database::OPERATION_FAILED, and query().
Referenced by query().
reconnect()
bool satox::database::DatabaseManager::reconnect ()
Definition at line 1313 of file database_manager.cpp.
References connect(), disconnect(), satox::database::NOT_INITIALIZED, and satox::database::OPERATION_FAILED.
remove()
bool satox::database::DatabaseManager::remove (const std::string & table, const std::string & id)
Definition at line 674 of file database_manager.cpp.
References satox::database::NOT_INITIALIZED, and satox::database::OPERATION_FAILED.
resetStats()
void satox::database::DatabaseManager::resetStats ()
Definition at line 1199 of file database_manager.cpp.
restoreFromBackup()
bool satox::database::DatabaseManager::restoreFromBackup (const std::string & backupPath)
Definition at line 1066 of file database_manager.cpp.
References satox::database::TableData::indexes, satox::database::DatabaseData::name, satox::database::NOT_INITIALIZED, satox::database::OPERATION_FAILED, satox::database::TableData::records, satox::database::TableData::schema, and satox::database::DatabaseData::tables.
rollbackTransaction()
bool satox::database::DatabaseManager::rollbackTransaction ()
Definition at line 846 of file database_manager.cpp.
References satox::database::OPERATION_FAILED.
setConfig()
void satox::database::DatabaseManager::setConfig (const DatabaseConfig & config)
Definition at line 1283 of file database_manager.cpp.
References satox::database::DatabaseConfig::connectionTimeout, and satox::database::DatabaseConfig::maxConnections.
setConnectionCallback()
void satox::database::DatabaseManager::setConnectionCallback (ConnectionCallback callback)
Definition at line 1149 of file database_manager.cpp.
setConnectionTimeout()
void satox::database::DatabaseManager::setConnectionTimeout (size_t milliseconds)
Definition at line 1350 of file database_manager.cpp.
setDatabaseCallback()
void satox::database::DatabaseManager::setDatabaseCallback (DatabaseCallback callback)
Definition at line 1138 of file database_manager.cpp.
setHealthCallback()
void satox::database::DatabaseManager::setHealthCallback (HealthCallback callback)
Definition at line 1160 of file database_manager.cpp.
setMaxConnections()
void satox::database::DatabaseManager::setMaxConnections (size_t max)
Definition at line 1339 of file database_manager.cpp.
shutdown()
void satox::database::DatabaseManager::shutdown ()
Definition at line 110 of file database_manager.cpp.
References disconnect().
tableExists()
bool satox::database::DatabaseManager::tableExists (const std::string & name)
Definition at line 413 of file database_manager.cpp.
References satox::database::NOT_INITIALIZED.
update()
bool satox::database::DatabaseManager::update (const std::string & table, const std::string & id, const nlohmann::json & data)
Definition at line 620 of file database_manager.cpp.
References satox::database::NOT_INITIALIZED, and satox::database::OPERATION_FAILED.
useDatabase()
bool satox::database::DatabaseManager::useDatabase (const std::string & name)
Definition at line 332 of file database_manager.cpp.
References satox::database::NOT_INITIALIZED, and satox::database::OPERATION_FAILED.
validateConfig()
bool satox::database::DatabaseManager::validateConfig (const DatabaseConfig & config) const
Definition at line 1301 of file database_manager.cpp.
References satox::database::DatabaseConfig::connectionTimeout, satox::database::DatabaseConfig::maxConnections, and satox::database::DatabaseConfig::name.
Referenced by initialize().
The documentation for this class was generated from the following files:
src/database/include/satox/database/database_manager.hpp
src/database/src/database_manager.cpp