SATOX SDK: satox::network::NetworkManager::Impl Class Reference
satox::network::NetworkManager::Impl Class Reference
Public Member Functions
Impl ()
~Impl ()
bool initialize (const NetworkConfig &config)
bool shutdown ()
bool isInitialized () const
bool isRunning () const
bool isP2PRunning () const
bool isRPCRunning () const
bool startP2P ()
void stopP2P ()
bool connectToPeer (const std::string &address, uint16_t port)
void disconnectPeer (const std::string &address)
bool isPeerConnected (const std::string &address) const
std::vector< Peer > getConnectedPeers () const
int getPeerCount () const
bool startRPC ()
void stopRPC ()
bool registerRPCMethod (const std::string &method, std::function< RPCResponse(const RPCRequest &)> handler)
bool callRPC (const std::string &address, const RPCRequest &request, RPCCallback callback)
bool sendP2PMessage (const std::string &peer_address, const std::vector< uint8_t > &message)
bool sendRPCMessage (const std::string &client_address, const nlohmann::json &message)
void registerMessageCallback (MessageType type, MessageCallback callback)
void unregisterMessageCallback (MessageType type)
void registerPeerCallback (PeerCallback callback)
void unregisterPeerCallback ()
void registerErrorCallback (ErrorCallback callback)
void unregisterErrorCallback ()
bool enableEncryption (const SecurityConfig &config)
LetsEncryptManager::Certificate getCurrentCertificate () const
bool renewCertificate ()
void registerCertificateUpdateCallback (CertificateUpdateCallback callback)
NetworkStats getNetworkStats () const
bool enableStats (bool enable)
bool resetStats ()
std::string getLastError () const
bool clearLastError ()
bool healthCheck () const
Detailed Description
Definition at line 54 of file network_manager.cpp.
Constructor & Destructor Documentation
Impl()
satox::network::NetworkManager::Impl::Impl ()
Definition at line 333 of file network_manager.cpp.
~Impl()
satox::network::NetworkManager::Impl::~Impl ()
Definition at line 355 of file network_manager.cpp.
References satox::network::NetworkManager::shutdown().
Member Function Documentation
callRPC()
bool satox::network::NetworkManager::Impl::callRPC (const std::string & address, const RPCRequest & request, RPCCallback callback)
Definition at line 628 of file network_manager.cpp.
References satox::network::NetworkManager::RPCRequest::method.
clearLastError()
bool satox::network::NetworkManager::Impl::clearLastError ()
Definition at line 812 of file network_manager.cpp.
connectToPeer()
bool satox::network::NetworkManager::Impl::connectToPeer (const std::string & address, uint16_t port)
Definition at line 500 of file network_manager.cpp.
disconnectPeer()
void satox::network::NetworkManager::Impl::disconnectPeer (const std::string & address)
Definition at line 532 of file network_manager.cpp.
enableEncryption()
bool satox::network::NetworkManager::Impl::enableEncryption (const SecurityConfig & config)
Definition at line 727 of file network_manager.cpp.
enableStats()
bool satox::network::NetworkManager::Impl::enableStats (bool enable)
Definition at line 793 of file network_manager.cpp.
getConnectedPeers()
std::vector< NetworkManager::Peer > satox::network::NetworkManager::Impl::getConnectedPeers () const
Definition at line 554 of file network_manager.cpp.
getCurrentCertificate()
LetsEncryptManager::Certificate satox::network::NetworkManager::Impl::getCurrentCertificate () const
Definition at line 745 of file network_manager.cpp.
getLastError()
std::string satox::network::NetworkManager::Impl::getLastError () const
Definition at line 807 of file network_manager.cpp.
getNetworkStats()
NetworkManager::NetworkStats satox::network::NetworkManager::Impl::getNetworkStats () const
Definition at line 783 of file network_manager.cpp.
References satox::network::NetworkManager::NetworkStats::uptime_seconds.
getPeerCount()
int satox::network::NetworkManager::Impl::getPeerCount () const
Definition at line 566 of file network_manager.cpp.
healthCheck()
bool satox::network::NetworkManager::Impl::healthCheck () const
Definition at line 818 of file network_manager.cpp.
initialize()
bool satox::network::NetworkManager::Impl::initialize (const NetworkConfig & config)
Definition at line 360 of file network_manager.cpp.
References satox::network::LetsEncryptManager::Config::domain, satox::network::NetworkManager::NetworkConfig::enable_ssl, and satox::network::NetworkManager::NetworkConfig::letsencrypt_config.
isInitialized()
bool satox::network::NetworkManager::Impl::isInitialized () const
Definition at line 441 of file network_manager.cpp.
isP2PRunning()
bool satox::network::NetworkManager::Impl::isP2PRunning () const
Definition at line 451 of file network_manager.cpp.
isPeerConnected()
bool satox::network::NetworkManager::Impl::isPeerConnected (const std::string & address) const
Definition at line 549 of file network_manager.cpp.
isRPCRunning()
bool satox::network::NetworkManager::Impl::isRPCRunning () const
Definition at line 456 of file network_manager.cpp.
isRunning()
bool satox::network::NetworkManager::Impl::isRunning () const
Definition at line 446 of file network_manager.cpp.
registerCertificateUpdateCallback()
void satox::network::NetworkManager::Impl::registerCertificateUpdateCallback (CertificateUpdateCallback callback)
Definition at line 777 of file network_manager.cpp.
registerErrorCallback()
void satox::network::NetworkManager::Impl::registerErrorCallback (ErrorCallback callback)
Definition at line 715 of file network_manager.cpp.
registerMessageCallback()
void satox::network::NetworkManager::Impl::registerMessageCallback (MessageType type, MessageCallback callback)
Definition at line 691 of file network_manager.cpp.
registerPeerCallback()
void satox::network::NetworkManager::Impl::registerPeerCallback (PeerCallback callback)
Definition at line 703 of file network_manager.cpp.
registerRPCMethod()
bool satox::network::NetworkManager::Impl::registerRPCMethod (const std::string & method, std::function< RPCResponse(const RPCRequest &)> handler)
Definition at line 610 of file network_manager.cpp.
renewCertificate()
bool satox::network::NetworkManager::Impl::renewCertificate ()
Definition at line 755 of file network_manager.cpp.
resetStats()
bool satox::network::NetworkManager::Impl::resetStats ()
Definition at line 800 of file network_manager.cpp.
sendP2PMessage()
bool satox::network::NetworkManager::Impl::sendP2PMessage (const std::string & peer_address, const std::vector< uint8_t > & message)
Definition at line 646 of file network_manager.cpp.
sendRPCMessage()
bool satox::network::NetworkManager::Impl::sendRPCMessage (const std::string & client_address, const nlohmann::json & message)
Definition at line 673 of file network_manager.cpp.
shutdown()
bool satox::network::NetworkManager::Impl::shutdown ()
Definition at line 401 of file network_manager.cpp.
References satox::network::NetworkManager::stopP2P(), and satox::network::NetworkManager::stopRPC().
startP2P()
bool satox::network::NetworkManager::Impl::startP2P ()
Definition at line 461 of file network_manager.cpp.
startRPC()
bool satox::network::NetworkManager::Impl::startRPC ()
Definition at line 571 of file network_manager.cpp.
stopP2P()
void satox::network::NetworkManager::Impl::stopP2P ()
Definition at line 485 of file network_manager.cpp.
stopRPC()
void satox::network::NetworkManager::Impl::stopRPC ()
Definition at line 595 of file network_manager.cpp.
unregisterErrorCallback()
void satox::network::NetworkManager::Impl::unregisterErrorCallback ()
Definition at line 721 of file network_manager.cpp.
unregisterMessageCallback()
void satox::network::NetworkManager::Impl::unregisterMessageCallback (MessageType type)
Definition at line 697 of file network_manager.cpp.
unregisterPeerCallback()
void satox::network::NetworkManager::Impl::unregisterPeerCallback ()
Definition at line 709 of file network_manager.cpp.
The documentation for this class was generated from the following file:
src/network/src/network_manager.cpp