SATOX SDK: satox::network::NetworkManager Class Reference
satox::network::NetworkManager Class Reference
#include <network_manager.hpp>
Classes
class Impl
struct NetworkConfig
struct NetworkStats
struct RPCRequest
struct RPCResponse
struct SecurityConfig
Public Types
enum class MessageType {
P2P_MESSAGE , RPC_REQUEST , RPC_RESPONSE , HEARTBEAT ,
PEER_DISCOVERY
}
using MessageCallback = std::function<void(const std::string&, const std::vector<uint8_t>&)>
using PeerCallback = std::function<void(const std::string&, bool)>
using RPCCallback = std::function<void(const RPCResponse&)>
using MessageCallback = std::function<void(MessageType, const std::string&, const std::vector<uint8_t>&)>
using PeerCallback = std::function<void(const std::string&, bool)>
using ErrorCallback = std::function<void(const std::string&)>
using CertificateUpdateCallback = LetsEncryptManager::CertificateUpdateCallback
Public Member Functions
NetworkManager (const std::string &type, int port)
~NetworkManager ()
bool initialize ()
void shutdown ()
std::string getLastError () const
bool startListening ()
bool stopListening ()
bool connect (const std::string &address, int port)
bool disconnect (const std::string &address)
bool broadcast (const std::vector< uint8_t > &message)
bool send (const std::string &address, const std::vector< uint8_t > &message)
void registerMessageCallback (MessageCallback callback)
void registerPeerCallback (PeerCallback callback)
std::vector< std::string > getConnectedPeers () const
bool isPeerConnected (const std::string &address) const
int getPeerCount () const
bool initialize (const NetworkConfig &config=NetworkConfig{})
bool shutdown ()
bool isInitialized () const
bool isHealthy () const
bool isRunning () const
bool isP2PRunning () const
bool isRPCRunning () const
bool startP2P ()
void stopP2P ()
bool connectToPeer (const std::string &address, uint16_t port)
void disconnectPeer (const std::string &address)
bool isPeerConnected (const std::string &address) const
std::vector< Peer > getConnectedPeers () const
int getPeerCount () const
bool startRPC ()
void stopRPC ()
bool registerRPCMethod (const std::string &method, std::function< RPCResponse(const RPCRequest &)> handler)
bool callRPC (const std::string &address, const RPCRequest &request, RPCCallback callback)
bool sendP2PMessage (const std::string &peer_address, const std::vector< uint8_t > &message)
bool sendRPCMessage (const std::string &client_address, const nlohmann::json &message)
void registerMessageCallback (MessageType type, MessageCallback callback)
void unregisterMessageCallback (MessageType type)
void registerPeerCallback (PeerCallback callback)
void unregisterPeerCallback ()
void registerErrorCallback (ErrorCallback callback)
void unregisterErrorCallback ()
bool enableEncryption (const SecurityConfig &config)
bool enableSSL (const SecurityConfig &config)
bool disableSSL ()
LetsEncryptManager::Certificate getCurrentCertificate () const
bool renewCertificate ()
void registerCertificateUpdateCallback (CertificateUpdateCallback callback)
NetworkStats getNetworkStats () const
bool enableStats (bool enable)
bool resetStats ()
std::string getLastError () const
bool clearLastError ()
bool healthCheck () const
Static Public Member Functions
static NetworkManager & getInstance ()
Detailed Description
Definition at line 41 of file network_manager.hpp.
Member Typedef Documentation
CertificateUpdateCallback
using satox::network::NetworkManager::CertificateUpdateCallback = LetsEncryptManager::CertificateUpdateCallback
Definition at line 114 of file network_manager.hpp.
ErrorCallback
using satox::network::NetworkManager::ErrorCallback = std::function<void(const std::string&)>
Definition at line 113 of file network_manager.hpp.
MessageCallback [1/2]
using satox::network::NetworkManager::MessageCallback = std::function<void(const std::string&, const std::vector<uint8_t>&)>
Definition at line 43 of file network_manager.hpp.
MessageCallback [2/2]
using satox::network::NetworkManager::MessageCallback = std::function<void(MessageType, const std::string&, const std::vector<uint8_t>&)>
Definition at line 111 of file network_manager.hpp.
PeerCallback [1/2]
using satox::network::NetworkManager::PeerCallback = std::function<void(const std::string&, bool)>
Definition at line 44 of file network_manager.hpp.
PeerCallback [2/2]
using satox::network::NetworkManager::PeerCallback = std::function<void(const std::string&, bool)>
Definition at line 112 of file network_manager.hpp.
RPCCallback
using satox::network::NetworkManager::RPCCallback = std::function<void(const RPCResponse&)>
Definition at line 110 of file network_manager.hpp.
Member Enumeration Documentation
MessageType
enum class satox::network::NetworkManager::MessageType strong
Enumerator
P2P_MESSAGE
RPC_REQUEST
RPC_RESPONSE
HEARTBEAT
PEER_DISCOVERY
Definition at line 101 of file network_manager.hpp.
Constructor & Destructor Documentation
NetworkManager()
satox::network::NetworkManager::NetworkManager (const std::string & type, int port)
Referenced by getInstance(), and getLastError().
~NetworkManager()
satox::network::NetworkManager::~NetworkManager ()
Member Function Documentation
broadcast()
bool satox::network::NetworkManager::broadcast (const std::vector< uint8_t > & message)
callRPC()
bool satox::network::NetworkManager::callRPC (const std::string & address, const RPCRequest & request, RPCCallback callback)
Definition at line 228 of file network_manager.cpp.
clearLastError()
bool satox::network::NetworkManager::clearLastError ()
Definition at line 296 of file network_manager.cpp.
connect()
bool satox::network::NetworkManager::connect (const std::string & address, int port)
connectToPeer()
bool satox::network::NetworkManager::connectToPeer (const std::string & address, uint16_t port)
Definition at line 196 of file network_manager.cpp.
disableSSL()
bool satox::network::NetworkManager::disableSSL ()
Definition at line 323 of file network_manager.cpp.
disconnect()
bool satox::network::NetworkManager::disconnect (const std::string & address)
disconnectPeer()
void satox::network::NetworkManager::disconnectPeer (const std::string & address)
Definition at line 200 of file network_manager.cpp.
enableEncryption()
bool satox::network::NetworkManager::enableEncryption (const SecurityConfig & config)
Definition at line 264 of file network_manager.cpp.
enableSSL()
bool satox::network::NetworkManager::enableSSL (const SecurityConfig & config)
Definition at line 314 of file network_manager.cpp.
enableStats()
bool satox::network::NetworkManager::enableStats (bool enable)
Definition at line 284 of file network_manager.cpp.
getConnectedPeers() [1/2]
std::vector< NetworkManager::Peer > satox::network::NetworkManager::getConnectedPeers () const
Definition at line 208 of file network_manager.cpp.
getConnectedPeers() [2/2]
std::vector< Peer > satox::network::NetworkManager::getConnectedPeers () const
getCurrentCertificate()
LetsEncryptManager::Certificate satox::network::NetworkManager::getCurrentCertificate () const
Definition at line 268 of file network_manager.cpp.
getInstance()
NetworkManager & satox::network::NetworkManager::getInstance () static
Definition at line 159 of file network_manager.cpp.
References NetworkManager().
getLastError() [1/2]
std::string satox::network::NetworkManager::getLastError () const
Definition at line 292 of file network_manager.cpp.
getLastError() [2/2]
std::string satox::network::NetworkManager::getLastError () const
References NetworkManager().
getNetworkStats()
NetworkManager::NetworkStats satox::network::NetworkManager::getNetworkStats () const
Definition at line 280 of file network_manager.cpp.
getPeerCount() [1/2]
int satox::network::NetworkManager::getPeerCount () const
Definition at line 212 of file network_manager.cpp.
getPeerCount() [2/2]
int satox::network::NetworkManager::getPeerCount () const
healthCheck()
bool satox::network::NetworkManager::healthCheck () const
Definition at line 300 of file network_manager.cpp.
initialize() [1/2]
bool satox::network::NetworkManager::initialize ()
Referenced by initialize().
initialize() [2/2]
bool satox::network::NetworkManager::initialize (const NetworkConfig & config = NetworkConfig{})
Definition at line 164 of file network_manager.cpp.
References initialize().
isHealthy()
bool satox::network::NetworkManager::isHealthy () const
Definition at line 304 of file network_manager.cpp.
isInitialized()
bool satox::network::NetworkManager::isInitialized () const
Definition at line 172 of file network_manager.cpp.
isP2PRunning()
bool satox::network::NetworkManager::isP2PRunning () const
Definition at line 180 of file network_manager.cpp.
isPeerConnected() [1/2]
bool satox::network::NetworkManager::isPeerConnected (const std::string & address) const
Definition at line 204 of file network_manager.cpp.
isPeerConnected() [2/2]
bool satox::network::NetworkManager::isPeerConnected (const std::string & address) const
isRPCRunning()
bool satox::network::NetworkManager::isRPCRunning () const
Definition at line 184 of file network_manager.cpp.
isRunning()
bool satox::network::NetworkManager::isRunning () const
Definition at line 176 of file network_manager.cpp.
registerCertificateUpdateCallback()
void satox::network::NetworkManager::registerCertificateUpdateCallback (CertificateUpdateCallback callback)
Definition at line 276 of file network_manager.cpp.
registerErrorCallback()
void satox::network::NetworkManager::registerErrorCallback (ErrorCallback callback)
Definition at line 256 of file network_manager.cpp.
registerMessageCallback() [1/2]
void satox::network::NetworkManager::registerMessageCallback (MessageCallback callback)
registerMessageCallback() [2/2]
void satox::network::NetworkManager::registerMessageCallback (MessageType type, MessageCallback callback)
Definition at line 240 of file network_manager.cpp.
registerPeerCallback() [1/2]
void satox::network::NetworkManager::registerPeerCallback (PeerCallback callback)
Definition at line 248 of file network_manager.cpp.
registerPeerCallback() [2/2]
void satox::network::NetworkManager::registerPeerCallback (PeerCallback callback)
registerRPCMethod()
bool satox::network::NetworkManager::registerRPCMethod (const std::string & method, std::function< RPCResponse(const RPCRequest &)> handler)
Definition at line 224 of file network_manager.cpp.
renewCertificate()
bool satox::network::NetworkManager::renewCertificate ()
Definition at line 272 of file network_manager.cpp.
resetStats()
bool satox::network::NetworkManager::resetStats ()
Definition at line 288 of file network_manager.cpp.
send()
bool satox::network::NetworkManager::send (const std::string & address, const std::vector< uint8_t > & message)
sendP2PMessage()
bool satox::network::NetworkManager::sendP2PMessage (const std::string & peer_address, const std::vector< uint8_t > & message)
Definition at line 232 of file network_manager.cpp.
sendRPCMessage()
bool satox::network::NetworkManager::sendRPCMessage (const std::string & client_address, const nlohmann::json & message)
Definition at line 236 of file network_manager.cpp.
shutdown() [1/2]
bool satox::network::NetworkManager::shutdown ()
Definition at line 168 of file network_manager.cpp.
Referenced by satox::network::NetworkManager::Impl::~Impl().
shutdown() [2/2]
bool satox::network::NetworkManager::shutdown ()
startListening()
bool satox::network::NetworkManager::startListening ()
startP2P()
bool satox::network::NetworkManager::startP2P ()
Definition at line 188 of file network_manager.cpp.
startRPC()
bool satox::network::NetworkManager::startRPC ()
Definition at line 216 of file network_manager.cpp.
stopListening()
bool satox::network::NetworkManager::stopListening ()
stopP2P()
void satox::network::NetworkManager::stopP2P ()
Definition at line 192 of file network_manager.cpp.
Referenced by satox::network::NetworkManager::Impl::shutdown().
stopRPC()
void satox::network::NetworkManager::stopRPC ()
Definition at line 220 of file network_manager.cpp.
Referenced by satox::network::NetworkManager::Impl::shutdown().
unregisterErrorCallback()
void satox::network::NetworkManager::unregisterErrorCallback ()
Definition at line 260 of file network_manager.cpp.
unregisterMessageCallback()
void satox::network::NetworkManager::unregisterMessageCallback (MessageType type)
Definition at line 244 of file network_manager.cpp.
unregisterPeerCallback()
void satox::network::NetworkManager::unregisterPeerCallback ()
Definition at line 252 of file network_manager.cpp.
The documentation for this class was generated from the following files:
src/core/include/satox/network/network_manager.hpp
src/network/include/satox/network/network_manager.hpp
src/network/src/network_manager.cpp