SATOX SDK: satox Namespace Reference
satox Namespace Reference
Namespaces
namespace asset
namespace blockchain
namespace core
namespace database
namespace ipfs
namespace network
namespace nft
namespace rpc_proxy
namespace security
namespace wallet
Classes
struct BlockHeader
struct InvVector
class IPFSClient
class NFT
class NFTEventListener
class NFTManager
struct OutPoint
struct P2PMessage
struct P2PMessageHeader
class RateLimiter
class RPCManager
class ThreadPool
struct Transaction
struct TxIn
struct TxOut
struct VersionMessage
Enumerations
enum class P2PMessageType : uint8_t {
VERSION = 0 , VERACK = 1 , ADDR = 2 , INV = 3 ,
GETDATA = 4 , GETBLOCKS = 5 , GETHEADERS = 6 , TX = 7 ,
BLOCK = 8 , HEADERS = 9 , GETADDR = 10 , MEMPOOL = 11 ,
PING = 12 , PONG = 13 , REJECT = 14 , SENDHEADERS = 15 ,
FEEFILTER = 16 , SENDCMPCT = 17 , CMPCTBLOCK = 18 , GETBLOCKTXN = 19 ,
BLOCKTXN = 20 , ASSET = 21 , GETASSET = 22 , ASSETALLOCATION = 23 ,
GETASSETALLOCATION = 24 , IPFS = 25 , GETIPFS = 26 , NFT = 27 ,
GETNFT = 28
}
Functions
std::vector< uint8_t > doubleSHA256 (const std::vector< uint8_t > &data)
uint32_t calculateChecksum (const std::vector< uint8_t > &data)
std::string messageTypeToString (P2PMessageType type)
P2PMessageType stringToMessageType (const std::string &str)
std::vector< uint8_t > serializeMessage (const P2PMessage &message)
P2PMessage deserializeMessage (const std::vector< uint8_t > &data)
std::vector< uint8_t > serializeVersionMessage (const VersionMessage &msg)
VersionMessage deserializeVersionMessage (const std::vector< uint8_t > &data)
std::vector< uint8_t > serializeInvVector (const InvVector &inv)
InvVector deserializeInvVector (const std::vector< uint8_t > &data)
std::vector< uint8_t > serializeBlockHeader (const BlockHeader &header)
BlockHeader deserializeBlockHeader (const std::vector< uint8_t > &data)
std::vector< uint8_t > serializeTransaction (const Transaction &tx)
Transaction deserializeTransaction (const std::vector< uint8_t > &data)
Variables
constexpr uint32_t SATOX_MAGIC = 0x53545843
constexpr int32_t PROTOCOL_VERSION = 70015
constexpr const char * USER_AGENT = "/Satoxcoin:1.0.0/"
Enumeration Type Documentation
P2PMessageType
enum class satox::P2PMessageType : uint8_t strong
Enumerator
VERSION
VERACK
ADDR
INV
GETDATA
GETBLOCKS
GETHEADERS
TX
BLOCK
HEADERS
GETADDR
MEMPOOL
PING
PONG
REJECT
SENDHEADERS
FEEFILTER
SENDCMPCT
CMPCTBLOCK
GETBLOCKTXN
BLOCKTXN
ASSET
GETASSET
ASSETALLOCATION
GETASSETALLOCATION
IPFS
GETIPFS
NFT
GETNFT
Definition at line 45 of file p2p_protocol.hpp.
Function Documentation
calculateChecksum()
uint32_t satox::calculateChecksum (const std::vector< uint8_t > & data)
Definition at line 51 of file p2p_protocol.cpp.
References doubleSHA256().
Referenced by deserializeMessage(), and satox::P2PMessage::P2PMessage().
deserializeBlockHeader()
BlockHeader satox::deserializeBlockHeader (const std::vector< uint8_t > & data)
deserializeInvVector()
InvVector satox::deserializeInvVector (const std::vector< uint8_t > & data)
deserializeMessage()
P2PMessage satox::deserializeMessage (const std::vector< uint8_t > & data)
Definition at line 159 of file p2p_protocol.cpp.
References calculateChecksum(), satox::P2PMessageHeader::checksum, satox::P2PMessageHeader::command, satox::P2PMessage::header, satox::P2PMessageHeader::length, satox::P2PMessageHeader::magic, and satox::P2PMessage::payload.
deserializeTransaction()
Transaction satox::deserializeTransaction (const std::vector< uint8_t > & data)
deserializeVersionMessage()
VersionMessage satox::deserializeVersionMessage (const std::vector< uint8_t > & data)
Definition at line 286 of file p2p_protocol.cpp.
References satox::VersionMessage::addr_from_ip, satox::VersionMessage::addr_from_port, satox::VersionMessage::addr_from_services, satox::VersionMessage::addr_recv_ip, satox::VersionMessage::addr_recv_port, satox::VersionMessage::addr_recv_services, satox::VersionMessage::nonce, satox::VersionMessage::relay, satox::VersionMessage::services, satox::VersionMessage::start_height, satox::VersionMessage::timestamp, satox::VersionMessage::user_agent, and satox::VersionMessage::version.
doubleSHA256()
std::vector< uint8_t > satox::doubleSHA256 (const std::vector< uint8_t > & data)
Definition at line 35 of file p2p_protocol.cpp.
Referenced by calculateChecksum().
messageTypeToString()
std::string satox::messageTypeToString (P2PMessageType type)
Definition at line 58 of file p2p_protocol.cpp.
References BLOCK, BLOCKTXN, CMPCTBLOCK, FEEFILTER, GETBLOCKS, GETBLOCKTXN, GETDATA, GETHEADERS, HEADERS, INV, MEMPOOL, PING, PONG, REJECT, SENDCMPCT, SENDHEADERS, TX, VERACK, and VERSION.
Referenced by satox::P2PMessage::P2PMessage().
serializeBlockHeader()
std::vector< uint8_t > satox::serializeBlockHeader (const BlockHeader & header)
serializeInvVector()
std::vector< uint8_t > satox::serializeInvVector (const InvVector & inv)
serializeMessage()
std::vector< uint8_t > satox::serializeMessage (const P2PMessage & message)
Definition at line 139 of file p2p_protocol.cpp.
References satox::P2PMessageHeader::checksum, satox::P2PMessageHeader::command, satox::P2PMessage::header, satox::P2PMessageHeader::length, satox::P2PMessageHeader::magic, and satox::P2PMessage::payload.
serializeTransaction()
std::vector< uint8_t > satox::serializeTransaction (const Transaction & tx)
serializeVersionMessage()
std::vector< uint8_t > satox::serializeVersionMessage (const VersionMessage & msg)
Definition at line 201 of file p2p_protocol.cpp.
References satox::VersionMessage::addr_from_ip, satox::VersionMessage::addr_from_port, satox::VersionMessage::addr_from_services, satox::VersionMessage::addr_recv_ip, satox::VersionMessage::addr_recv_port, satox::VersionMessage::addr_recv_services, satox::VersionMessage::nonce, satox::VersionMessage::relay, satox::VersionMessage::services, satox::VersionMessage::start_height, satox::VersionMessage::timestamp, satox::VersionMessage::user_agent, and satox::VersionMessage::version.
stringToMessageType()
P2PMessageType satox::stringToMessageType (const std::string & str)
Definition at line 95 of file p2p_protocol.cpp.
References BLOCK, BLOCKTXN, CMPCTBLOCK, FEEFILTER, GETBLOCKS, GETBLOCKTXN, GETDATA, GETHEADERS, HEADERS, INV, MEMPOOL, PING, PONG, REJECT, SENDCMPCT, SENDHEADERS, TX, VERACK, and VERSION.
Variable Documentation
PROTOCOL_VERSION
int32_t satox::PROTOCOL_VERSION = 70015 constexpr
Definition at line 39 of file p2p_protocol.hpp.
SATOX_MAGIC
uint32_t satox::SATOX_MAGIC = 0x53545843 constexpr
Definition at line 36 of file p2p_protocol.hpp.
USER_AGENT
const char* satox::USER_AGENT = "/Satoxcoin:1.0.0/" constexpr
Definition at line 42 of file p2p_protocol.hpp.