SATOX SDK: src/blockchain/third_party/keccak/include/KeccakSponge.h File Reference
KeccakSponge.h File Reference
#include <stdint.h>
#include "KeccakF-1600-reference.h"
Classes
struct KeccakSponge
Macros
#define KECCAK_SPONGE_BITRATE 1088
#define KECCAK_SPONGE_CAPACITY 512
#define KECCAK_SPONGE_BLOCKSIZE (KECCAK_SPONGE_BITRATE / 8)
Functions
void KeccakSponge_Initialize (KeccakSponge *sponge, unsigned int rate, unsigned int capacity)
void KeccakSponge_Absorb (KeccakSponge *sponge, const unsigned char *data, unsigned int dataByteLen)
void KeccakSponge_Squeeze (KeccakSponge *sponge, unsigned char *data, unsigned int dataByteLen)
Macro Definition Documentation
KECCAK_SPONGE_BITRATE
#define KECCAK_SPONGE_BITRATE 1088
Definition at line 7 of file KeccakSponge.h.
KECCAK_SPONGE_BLOCKSIZE
#define KECCAK_SPONGE_BLOCKSIZE (KECCAK_SPONGE_BITRATE / 8)
Definition at line 9 of file KeccakSponge.h.
KECCAK_SPONGE_CAPACITY
#define KECCAK_SPONGE_CAPACITY 512
Definition at line 8 of file KeccakSponge.h.
Function Documentation
KeccakSponge_Absorb()
void KeccakSponge_Absorb (KeccakSponge * sponge, const unsigned char * data, unsigned int dataByteLen)
Definition at line 12 of file KeccakSponge.c.
References KeccakF_1600_StatePermute(), KeccakF_1600_StateXORBytes(), KeccakSponge::rate, and KeccakSponge::state.
KeccakSponge_Initialize()
void KeccakSponge_Initialize (KeccakSponge * sponge, unsigned int rate, unsigned int capacity)
Definition at line 4 of file KeccakSponge.c.
References KeccakSponge::bitsAvailableForSqueezing, KeccakSponge::bitsInQueue, KeccakSponge::capacity, KeccakF_1600_Initialize(), KeccakSponge::rate, and KeccakSponge::state.
KeccakSponge_Squeeze()
void KeccakSponge_Squeeze (KeccakSponge * sponge, unsigned char * data, unsigned int dataByteLen)
Definition at line 31 of file KeccakSponge.c.
References KeccakF_1600_StateExtractBytes(), KeccakF_1600_StatePermute(), KeccakSponge::rate, and KeccakSponge::state.