SATOX SDK: satox::core::CloudMonitoring Class Reference
satox::core::CloudMonitoring Class Reference
Cloud monitoring and logging manager.
#include <cloud_monitoring.hpp>
Public Member Functions
CloudMonitoring ()
Constructor.
~CloudMonitoring ()
Destructor.
bool initialize (const CloudMonitoringConfig &config)
Initialize monitoring system.
void shutdown ()
Shutdown monitoring system.
void logOperation (const CloudLogEntry &entry)
Log cloud operation.
std::string startOperation (CloudProvider provider, CloudOperation operation, const std::string &connection_id="", const nlohmann::json &metadata={})
Log operation with automatic timing.
void completeOperation (const std::string &operation_id, CloudOperationStatus status, const std::string &error_message="", const nlohmann::json &result={})
Complete operation with status.
void logError (CloudProvider provider, CloudOperation operation, const std::string &error_message, const std::string &error_code="", const std::string &connection_id="", const nlohmann::json &metadata={})
Log error.
void logPerformance (CloudProvider provider, CloudOperation operation, std::chrono::milliseconds duration, bool success, const nlohmann::json &metadata={})
Log performance metrics.
void logSecurityEvent (CloudProvider provider, const std::string &event_type, const std::string &severity, const std::string &details, const nlohmann::json &metadata={})
Log security event.
void logAuditEvent (CloudProvider provider, const std::string &user_id, const std::string &action, const std::string &resource, const std::string &result, const nlohmann::json &metadata={})
Log audit event.
CloudMetrics getMetrics (CloudProvider provider) const
Get metrics for provider.
CloudMetrics getAggregatedMetrics () const
Get aggregated metrics for all providers.
void resetMetrics (CloudProvider provider)
Reset metrics for provider.
void resetAllMetrics ()
Reset all metrics.
nlohmann::json getHealthStatus (CloudProvider provider) const
Get health status for provider.
nlohmann::json getAllHealthStatus () const
Get health status for all providers.
bool performHealthCheck (CloudProvider provider)
Perform health check for provider.
nlohmann::json getMonitoringSummary (int hours=24) const
Get monitoring summary.
void setContext (const std::string &correlation_id="", const std::string &user_id="", const std::string &session_id="", const std::string &ip_address="", const std::string &user_agent="")
Set context information.
void clearContext ()
Clear context information.
void registerLogCallback (CloudLogCallback callback)
Register log callback.
void registerAlertCallback (CloudAlertCallback callback)
Register alert callback.
void registerHealthCallback (CloudHealthCallback callback)
Register health callback.
void registerMetricsCallback (CloudMetricsCallback callback)
Register metrics callback.
CloudMonitoringConfig getConfig () const
Get configuration.
bool updateConfig (const CloudMonitoringConfig &config)
Update configuration.
bool isInitialized () const
Check if monitoring is initialized.
nlohmann::json getStatus () const
Get monitoring status.
Static Public Member Functions
static CloudMonitoring & getInstance ()
Get singleton instance.
Detailed Description
Cloud monitoring and logging manager.
Provides comprehensive monitoring, logging, metrics collection, and alerting for all cloud database providers in the Satox SDK.
Definition at line 178 of file cloud_monitoring.hpp.
Constructor & Destructor Documentation
CloudMonitoring()
satox::core::CloudMonitoring::CloudMonitoring ()
Constructor.
Definition at line 26 of file cloud_monitoring.cpp.
References satox::core::AWS, satox::core::AZURE, satox::core::FIREBASE, satox::core::GOOGLE_CLOUD, and satox::core::SUPABASE.
Referenced by getInstance().
~CloudMonitoring()
satox::core::CloudMonitoring::~CloudMonitoring ()
Destructor.
Definition at line 35 of file cloud_monitoring.cpp.
References shutdown().
Member Function Documentation
clearContext()
void satox::core::CloudMonitoring::clearContext ()
Clear context information.
Definition at line 556 of file cloud_monitoring.cpp.
completeOperation()
void satox::core::CloudMonitoring::completeOperation (const std::string & operation_id, CloudOperationStatus status, const std::string & error_message = "", const nlohmann::json & result = {})
Complete operation with status.
Parameters
operation_id Operation ID
status Operation status
error_message Error message if failed
result Result data
Definition at line 181 of file cloud_monitoring.cpp.
References satox::core::CloudLogEntry::duration, satox::core::CloudLogEntry::error_message, logOperation(), satox::core::CloudLogEntry::metadata, satox::core::CloudLogEntry::status, and satox::core::SUCCESS.
getAggregatedMetrics()
CloudMetrics satox::core::CloudMonitoring::getAggregatedMetrics () const
Get aggregated metrics for all providers.
Returns
Aggregated metrics
Definition at line 365 of file cloud_monitoring.cpp.
References satox::core::CloudMetrics::active_connections, satox::core::CloudMetrics::active_subscriptions, satox::core::CloudMetrics::authentication_errors, satox::core::CloudMetrics::connection_errors, satox::core::CloudMetrics::failed_operations, satox::core::CloudMetrics::failed_queries, satox::core::CloudMetrics::failed_requests, satox::core::CloudMetrics::network_errors, satox::core::CloudMetrics::quota_errors, satox::core::CloudMetrics::rate_limit_errors, satox::core::CloudMetrics::retry_operations, satox::core::CloudMetrics::subscription_errors, satox::core::CloudMetrics::successful_operations, satox::core::CloudMetrics::successful_queries, satox::core::CloudMetrics::successful_requests, satox::core::CloudMetrics::timeout_errors, satox::core::CloudMetrics::timeout_operations, satox::core::CloudMetrics::total_connections, satox::core::CloudMetrics::total_errors, satox::core::CloudMetrics::total_operations, satox::core::CloudMetrics::total_queries, satox::core::CloudMetrics::total_requests, and satox::core::CloudMetrics::total_subscriptions.
Referenced by getMonitoringSummary().
getAllHealthStatus()
nlohmann::json satox::core::CloudMonitoring::getAllHealthStatus () const
Get health status for all providers.
Returns
Health status JSON for all providers
Definition at line 456 of file cloud_monitoring.cpp.
References satox::core::AWS, satox::core::AZURE, satox::core::FIREBASE, getHealthStatus(), satox::core::GOOGLE_CLOUD, and satox::core::SUPABASE.
Referenced by getStatus().
getConfig()
CloudMonitoringConfig satox::core::CloudMonitoring::getConfig () const
Get configuration.
Returns
Current configuration
Definition at line 584 of file cloud_monitoring.cpp.
getHealthStatus()
nlohmann::json satox::core::CloudMonitoring::getHealthStatus (CloudProvider provider) const
Get health status for provider.
Parameters
provider Cloud provider
Returns
Health status JSON
Definition at line 418 of file cloud_monitoring.cpp.
References getMetrics().
Referenced by getAllHealthStatus(), and performHealthCheck().
getInstance()
CloudMonitoring & satox::core::CloudMonitoring::getInstance () static
Get singleton instance.
Returns
Reference to singleton instance
Definition at line 21 of file cloud_monitoring.cpp.
References CloudMonitoring().
getMetrics()
CloudMetrics satox::core::CloudMonitoring::getMetrics (CloudProvider provider) const
Get metrics for provider.
Parameters
provider Cloud provider
Returns
Metrics for the provider
Definition at line 356 of file cloud_monitoring.cpp.
Referenced by getHealthStatus(), and getMonitoringSummary().
getMonitoringSummary()
nlohmann::json satox::core::CloudMonitoring::getMonitoringSummary (int hours = 24) const
Get monitoring summary.
Parameters
hours Number of hours to include in summary
Returns
Monitoring summary JSON
Definition at line 507 of file cloud_monitoring.cpp.
References satox::core::AWS, satox::core::AZURE, satox::core::FIREBASE, getAggregatedMetrics(), getMetrics(), satox::core::GOOGLE_CLOUD, and satox::core::SUPABASE.
getStatus()
nlohmann::json satox::core::CloudMonitoring::getStatus () const
Get monitoring status.
Returns
Status JSON
Definition at line 598 of file cloud_monitoring.cpp.
References getAllHealthStatus().
initialize()
bool satox::core::CloudMonitoring::initialize (const CloudMonitoringConfig & config)
Initialize monitoring system.
Parameters
config Monitoring configuration
Returns
true if initialization successful, false otherwise
Definition at line 39 of file cloud_monitoring.cpp.
References satox::core::CloudMonitoringConfig::enable_health_checks, satox::core::CloudMonitoringConfig::enable_logging, satox::core::CloudMonitoringConfig::enable_metrics, satox::core::CloudMonitoringConfig::health_check_interval_seconds, satox::core::CloudMonitoringConfig::log_level, and satox::core::CloudMonitoringConfig::log_path.
isInitialized()
bool satox::core::CloudMonitoring::isInitialized () const
Check if monitoring is initialized.
Returns
true if initialized, false otherwise
Definition at line 594 of file cloud_monitoring.cpp.
logAuditEvent()
void satox::core::CloudMonitoring::logAuditEvent (CloudProvider provider, const std::string & user_id, const std::string & action, const std::string & resource, const std::string & result, const nlohmann::json & metadata = {})
Log audit event.
Parameters
provider Cloud provider
user_id User ID
action Action performed
resource Resource accessed
result Result of action
metadata Additional metadata
Definition at line 324 of file cloud_monitoring.cpp.
References satox::core::AUTHENTICATE, satox::core::CloudLogEntry::context, satox::core::CloudLogEntry::duration, logOperation(), satox::core::CloudLogEntry::metadata, satox::core::CloudLogEntry::operation, satox::core::CloudLogEntry::operation_id, satox::core::CloudLogEntry::provider, satox::core::CloudLogEntry::status, satox::core::SUCCESS, satox::core::CloudLogEntry::thread_id, satox::core::CloudLogEntry::timestamp, and satox::core::CloudLogEntry::user_id.
logError()
void satox::core::CloudMonitoring::logError (CloudProvider provider, CloudOperation operation, const std::string & error_message, const std::string & error_code = "", const std::string & connection_id = "", const nlohmann::json & metadata = {})
Log error.
Parameters
provider Cloud provider
operation Operation type
error_message Error message
error_code Error code
connection_id Connection ID
metadata Additional metadata
Definition at line 231 of file cloud_monitoring.cpp.
References satox::core::CloudLogEntry::connection_id, satox::core::CloudLogEntry::context, satox::core::CloudLogEntry::correlation_id, satox::core::CloudLogEntry::duration, satox::core::CloudLogEntry::error_code, satox::core::CloudLogEntry::error_message, satox::core::FAILED, logOperation(), satox::core::CloudLogEntry::metadata, satox::core::CloudLogEntry::operation, satox::core::CloudLogEntry::operation_id, satox::core::CloudLogEntry::provider, satox::core::CloudLogEntry::session_id, satox::core::CloudLogEntry::status, satox::core::CloudLogEntry::thread_id, satox::core::CloudLogEntry::timestamp, and satox::core::CloudLogEntry::user_id.
logOperation()
void satox::core::CloudMonitoring::logOperation (const CloudLogEntry & entry)
Log cloud operation.
Parameters
entry Log entry to record
Definition at line 125 of file cloud_monitoring.cpp.
Referenced by completeOperation(), logAuditEvent(), logError(), logPerformance(), and logSecurityEvent().
logPerformance()
void satox::core::CloudMonitoring::logPerformance (CloudProvider provider, CloudOperation operation, std::chrono::milliseconds duration, bool success, const nlohmann::json & metadata = {})
Log performance metrics.
Parameters
provider Cloud provider
operation Operation type
duration Operation duration
success Whether operation was successful
metadata Additional metadata
Definition at line 266 of file cloud_monitoring.cpp.
References satox::core::CloudLogEntry::context, satox::core::CloudLogEntry::duration, satox::core::FAILED, logOperation(), satox::core::CloudLogEntry::metadata, satox::core::CloudLogEntry::operation, satox::core::CloudLogEntry::operation_id, satox::core::CloudLogEntry::provider, satox::core::CloudLogEntry::status, satox::core::SUCCESS, satox::core::CloudLogEntry::thread_id, and satox::core::CloudLogEntry::timestamp.
logSecurityEvent()
void satox::core::CloudMonitoring::logSecurityEvent (CloudProvider provider, const std::string & event_type, const std::string & severity, const std::string & details, const nlohmann::json & metadata = {})
Log security event.
Parameters
provider Cloud provider
event_type Security event type
severity Security severity level
details Event details
metadata Additional metadata
Definition at line 294 of file cloud_monitoring.cpp.
References satox::core::AUTHENTICATE, satox::core::CloudLogEntry::context, satox::core::CloudLogEntry::duration, logOperation(), satox::core::CloudLogEntry::metadata, satox::core::CloudLogEntry::operation, satox::core::CloudLogEntry::operation_id, satox::core::CloudLogEntry::provider, satox::core::CloudLogEntry::status, satox::core::SUCCESS, satox::core::CloudLogEntry::thread_id, and satox::core::CloudLogEntry::timestamp.
performHealthCheck()
bool satox::core::CloudMonitoring::performHealthCheck (CloudProvider provider)
Perform health check for provider.
Parameters
provider Cloud provider
Returns
true if healthy, false otherwise
Definition at line 478 of file cloud_monitoring.cpp.
References getHealthStatus().
registerAlertCallback()
void satox::core::CloudMonitoring::registerAlertCallback (CloudAlertCallback callback)
Register alert callback.
Parameters
callback Alert callback function
Definition at line 569 of file cloud_monitoring.cpp.
registerHealthCallback()
void satox::core::CloudMonitoring::registerHealthCallback (CloudHealthCallback callback)
Register health callback.
Parameters
callback Health callback function
Definition at line 574 of file cloud_monitoring.cpp.
registerLogCallback()
void satox::core::CloudMonitoring::registerLogCallback (CloudLogCallback callback)
Register log callback.
Parameters
callback Log callback function
Definition at line 564 of file cloud_monitoring.cpp.
registerMetricsCallback()
void satox::core::CloudMonitoring::registerMetricsCallback (CloudMetricsCallback callback)
Register metrics callback.
Parameters
callback Metrics callback function
Definition at line 579 of file cloud_monitoring.cpp.
resetAllMetrics()
void satox::core::CloudMonitoring::resetAllMetrics ()
Reset all metrics.
Definition at line 411 of file cloud_monitoring.cpp.
resetMetrics()
void satox::core::CloudMonitoring::resetMetrics (CloudProvider provider)
Reset metrics for provider.
Parameters
provider Cloud provider
Definition at line 403 of file cloud_monitoring.cpp.
setContext()
void satox::core::CloudMonitoring::setContext (const std::string & correlation_id = "", const std::string & user_id = "", const std::string & session_id = "", const std::string & ip_address = "", const std::string & user_agent = "")
Set context information.
Parameters
correlation_id Correlation ID
user_id User ID
session_id Session ID
ip_address IP address
user_agent User agent
Definition at line 544 of file cloud_monitoring.cpp.
shutdown()
void satox::core::CloudMonitoring::shutdown ()
Shutdown monitoring system.
Definition at line 87 of file cloud_monitoring.cpp.
Referenced by ~CloudMonitoring().
startOperation()
std::string satox::core::CloudMonitoring::startOperation (CloudProvider provider, CloudOperation operation, const std::string & connection_id = "", const nlohmann::json & metadata = {})
Log operation with automatic timing.
Parameters
provider Cloud provider
operation Operation type
connection_id Connection ID
metadata Additional metadata
Returns
Operation ID for tracking
Definition at line 142 of file cloud_monitoring.cpp.
References satox::core::CloudLogEntry::connection_id, satox::core::CloudLogEntry::context, satox::core::CloudLogEntry::correlation_id, satox::core::CloudLogEntry::duration, satox::core::CloudLogEntry::metadata, satox::core::CloudLogEntry::operation, satox::core::CloudLogEntry::operation_id, satox::core::CloudLogEntry::provider, satox::core::CloudLogEntry::session_id, satox::core::CloudLogEntry::status, satox::core::SUCCESS, satox::core::CloudLogEntry::thread_id, satox::core::CloudLogEntry::timestamp, and satox::core::CloudLogEntry::user_id.
updateConfig()
bool satox::core::CloudMonitoring::updateConfig (const CloudMonitoringConfig & config)
Update configuration.
Parameters
config New configuration
Returns
true if update successful, false otherwise
Definition at line 588 of file cloud_monitoring.cpp.
The documentation for this class was generated from the following files:
src/core/include/satox/core/cloud/cloud_monitoring.hpp
src/core/src/cloud/cloud_monitoring.cpp