SATOX SDK: satox::asset::AssetException Class Reference
satox::asset::AssetException Class Reference
#include <error.hpp>
Public Member Functions
AssetException (AssetErrorCode code, const std::string &message="")
const char * what () const noexcept override
AssetErrorCode code () const
const std::string & message () const
Detailed Description
Definition at line 52 of file error.hpp.
Constructor & Destructor Documentation
AssetException()
satox::asset::AssetException::AssetException (AssetErrorCode code, const std::string & message = "") inline
Definition at line 54 of file error.hpp.
References code(), and message().
Referenced by satox::asset::AssetInitializationException::AssetInitializationException(), and satox::asset::AssetOperationException::AssetOperationException().
Member Function Documentation
code()
AssetErrorCode satox::asset::AssetException::code () const inline
Definition at line 61 of file error.hpp.
Referenced by AssetException().
message()
const std::string & satox::asset::AssetException::message () const inline
Definition at line 65 of file error.hpp.
Referenced by AssetException(), satox::asset::AssetInitializationException::AssetInitializationException(), and satox::asset::AssetOperationException::AssetOperationException().
what()
const char * satox::asset::AssetException::what () const inline override noexcept
Definition at line 57 of file error.hpp.
The documentation for this class was generated from the following file:
src/asset/include/satox/asset/error.hpp