SATOX SDK: src/satox_sdk_c.cpp File Reference
satox_sdk_c.cpp File Reference
#include "../include/satox_sdk.h"
#include "../include/satox/satox.hpp"
#include "satox/core/core_manager.hpp"
#include "satox/database/database_manager.hpp"
#include "satox/security/security_manager.hpp"
#include "satox/asset/asset_manager.hpp"
#include "satox/nft/nft_manager.hpp"
#include <nlohmann/json.hpp>
#include <memory>
#include <string>
#include <cstring>
Functions
char * string_to_c_string (const std::string &str)
char * json_to_c_string (const json &j)
int satox_sdk_initialize ()
void satox_sdk_shutdown ()
const char * satox_sdk_get_version ()
void * satox_security_manager_create ()
void satox_security_manager_destroy (void *handle)
int satox_security_manager_generate_keypair (void *handle, char **public_key, char **private_key)
char * satox_security_manager_sign_data (void *handle, const char *data, const char *private_key)
int satox_security_manager_verify_signature (void *handle, const char *data, const char *signature, const char *public_key)
char * satox_security_manager_sha256 (void *handle, const char *data)
char * satox_security_manager_encrypt_data (void *handle, const char *data, const char *public_key)
char * satox_security_manager_decrypt_data (void *handle, const char *encrypted_data, const char *private_key)
void * satox_database_manager_create (const char *config_json)
void satox_database_manager_destroy (void *handle)
int satox_database_manager_create_database (void *handle, const char *name)
char * satox_database_manager_list_databases (void *handle)
void * satox_asset_manager_create ()
void satox_asset_manager_destroy (void *handle)
char * satox_asset_manager_create_asset (void *handle, const char *name, const char *symbol)
char * satox_asset_manager_get_asset_info (void *handle, const char *asset_id)
void * satox_nft_manager_create ()
void satox_nft_manager_destroy (void *handle)
char * satox_nft_manager_create_nft (void *handle, const char *asset_id, const char *metadata_json, const char *owner_address)
char * satox_nft_manager_get_nft_info (void *handle, const char *nft_id)
void * satox_blockchain_manager_create (const char *config_json)
void satox_blockchain_manager_destroy (void *handle)
int satox_blockchain_manager_get_block_height (void *handle, unsigned long long *height)
char * satox_blockchain_manager_get_block_info (void *handle, const char *hash)
char * satox_blockchain_manager_get_transaction_info (void *handle, const char *txid)
char * satox_blockchain_manager_get_best_block_hash (void *handle)
char * satox_blockchain_manager_get_block_hash (void *handle, unsigned long long height)
char * satox_asset_manager_transfer_asset (void *handle, const char *asset_id, const char *from_address, const char *to_address, unsigned long long amount)
int satox_asset_manager_get_asset_balance (void *handle, const char *asset_id, const char *address, unsigned long long *balance)
char * satox_asset_manager_reissue_asset (void *handle, const char *asset_id, const char *owner_address, unsigned long long amount)
char * satox_asset_manager_burn_asset (void *handle, const char *asset_id, const char *owner_address, unsigned long long amount)
void * satox_network_manager_create (const char *config_json)
void satox_network_manager_destroy (void *handle)
int satox_network_manager_start (void *handle)
int satox_network_manager_stop (void *handle)
char * satox_network_manager_get_peers (void *handle)
char * satox_network_manager_get_stats (void *handle)
int satox_network_manager_add_peer (void *handle, const char *address, unsigned short port)
int satox_network_manager_remove_peer (void *handle, const char *address, unsigned short port)
int satox_network_manager_send_message (void *handle, const char *address, unsigned short port, const char *message)
char * satox_nft_manager_transfer_nft (void *handle, const char *nft_id, const char *from_address, const char *to_address)
char * satox_nft_manager_get_nfts_by_owner (void *handle, const char *address)
char * satox_nft_manager_update_metadata (void *handle, const char *nft_id, const char *metadata_json, const char *owner_address)
void * satox_ipfs_manager_create (const char *config_json)
void satox_ipfs_manager_destroy (void *handle)
char * satox_ipfs_manager_upload_file (void *handle, const char *file_path)
char * satox_ipfs_manager_upload_data (void *handle, const unsigned char *data, unsigned long long size, const char *filename)
int satox_ipfs_manager_download_file (void *handle, const char *hash, const char *output_path)
char * satox_ipfs_manager_get_file_info (void *handle, const char *hash)
int satox_ipfs_manager_pin_file (void *handle, const char *hash)
int satox_ipfs_manager_unpin_file (void *handle, const char *hash)
char * satox_ipfs_manager_get_gateway_url (void *handle, const char *hash)
Variables
static bool sdk_initialized = false
Function Documentation
json_to_c_string()
char * json_to_c_string (const json & j)
Definition at line 55 of file satox_sdk_c.cpp.
References string_to_c_string().
Referenced by satox_database_manager_list_databases(), satox_nft_manager_create_nft(), and satox_nft_manager_get_nft_info().
satox_asset_manager_burn_asset()
char * satox_asset_manager_burn_asset (void * handle, const char * asset_id, const char * owner_address, unsigned long long amount)
Definition at line 403 of file satox_sdk_c.cpp.
satox_asset_manager_create()
void * satox_asset_manager_create ()
Definition at line 238 of file satox_sdk_c.cpp.
References satox::asset::AssetManager::getInstance().
satox_asset_manager_create_asset()
char * satox_asset_manager_create_asset (void * handle, const char * name, const char * symbol)
Definition at line 251 of file satox_sdk_c.cpp.
satox_asset_manager_destroy()
void satox_asset_manager_destroy (void * handle)
Definition at line 247 of file satox_sdk_c.cpp.
satox_asset_manager_get_asset_balance()
int satox_asset_manager_get_asset_balance (void * handle, const char * asset_id, const char * address, unsigned long long * balance)
Definition at line 401 of file satox_sdk_c.cpp.
satox_asset_manager_get_asset_info()
char * satox_asset_manager_get_asset_info (void * handle, const char * asset_id)
Definition at line 283 of file satox_sdk_c.cpp.
satox_asset_manager_reissue_asset()
char * satox_asset_manager_reissue_asset (void * handle, const char * asset_id, const char * owner_address, unsigned long long amount)
Definition at line 402 of file satox_sdk_c.cpp.
satox_asset_manager_transfer_asset()
char * satox_asset_manager_transfer_asset (void * handle, const char * asset_id, const char * from_address, const char * to_address, unsigned long long amount)
Definition at line 400 of file satox_sdk_c.cpp.
satox_blockchain_manager_create()
void * satox_blockchain_manager_create (const char * config_json)
Definition at line 392 of file satox_sdk_c.cpp.
satox_blockchain_manager_destroy()
void satox_blockchain_manager_destroy (void * handle)
Definition at line 393 of file satox_sdk_c.cpp.
satox_blockchain_manager_get_best_block_hash()
char * satox_blockchain_manager_get_best_block_hash (void * handle)
Definition at line 397 of file satox_sdk_c.cpp.
satox_blockchain_manager_get_block_hash()
char * satox_blockchain_manager_get_block_hash (void * handle, unsigned long long height)
Definition at line 398 of file satox_sdk_c.cpp.
satox_blockchain_manager_get_block_height()
int satox_blockchain_manager_get_block_height (void * handle, unsigned long long * height)
Definition at line 394 of file satox_sdk_c.cpp.
satox_blockchain_manager_get_block_info()
char * satox_blockchain_manager_get_block_info (void * handle, const char * hash)
Definition at line 395 of file satox_sdk_c.cpp.
satox_blockchain_manager_get_transaction_info()
char * satox_blockchain_manager_get_transaction_info (void * handle, const char * txid)
Definition at line 396 of file satox_sdk_c.cpp.
satox_database_manager_create()
void * satox_database_manager_create (const char * config_json)
Definition at line 189 of file satox_sdk_c.cpp.
References satox::database::DatabaseConfig::connectionTimeout, satox::database::DatabaseConfig::enableLogging, satox::database::DatabaseManager::getInstance(), satox::database::DatabaseConfig::logPath, satox::database::DatabaseConfig::maxConnections, and satox::database::DatabaseConfig::name.
satox_database_manager_create_database()
int satox_database_manager_create_database (void * handle, const char * name)
Definition at line 214 of file satox_sdk_c.cpp.
References satox::database::DatabaseManager::createDatabase().
satox_database_manager_destroy()
void satox_database_manager_destroy (void * handle)
Definition at line 210 of file satox_sdk_c.cpp.
satox_database_manager_list_databases()
char * satox_database_manager_list_databases (void * handle)
Definition at line 223 of file satox_sdk_c.cpp.
References json_to_c_string(), and satox::database::DatabaseManager::listDatabases().
satox_ipfs_manager_create()
void * satox_ipfs_manager_create (const char * config_json)
Definition at line 419 of file satox_sdk_c.cpp.
satox_ipfs_manager_destroy()
void satox_ipfs_manager_destroy (void * handle)
Definition at line 420 of file satox_sdk_c.cpp.
satox_ipfs_manager_download_file()
int satox_ipfs_manager_download_file (void * handle, const char * hash, const char * output_path)
Definition at line 423 of file satox_sdk_c.cpp.
satox_ipfs_manager_get_file_info()
char * satox_ipfs_manager_get_file_info (void * handle, const char * hash)
Definition at line 424 of file satox_sdk_c.cpp.
satox_ipfs_manager_get_gateway_url()
char * satox_ipfs_manager_get_gateway_url (void * handle, const char * hash)
Definition at line 427 of file satox_sdk_c.cpp.
satox_ipfs_manager_pin_file()
int satox_ipfs_manager_pin_file (void * handle, const char * hash)
Definition at line 425 of file satox_sdk_c.cpp.
satox_ipfs_manager_unpin_file()
int satox_ipfs_manager_unpin_file (void * handle, const char * hash)
Definition at line 426 of file satox_sdk_c.cpp.
satox_ipfs_manager_upload_data()
char * satox_ipfs_manager_upload_data (void * handle, const unsigned char * data, unsigned long long size, const char * filename)
Definition at line 422 of file satox_sdk_c.cpp.
satox_ipfs_manager_upload_file()
char * satox_ipfs_manager_upload_file (void * handle, const char * file_path)
Definition at line 421 of file satox_sdk_c.cpp.
satox_network_manager_add_peer()
int satox_network_manager_add_peer (void * handle, const char * address, unsigned short port)
Definition at line 411 of file satox_sdk_c.cpp.
satox_network_manager_create()
void * satox_network_manager_create (const char * config_json)
Definition at line 405 of file satox_sdk_c.cpp.
satox_network_manager_destroy()
void satox_network_manager_destroy (void * handle)
Definition at line 406 of file satox_sdk_c.cpp.
satox_network_manager_get_peers()
char * satox_network_manager_get_peers (void * handle)
Definition at line 409 of file satox_sdk_c.cpp.
satox_network_manager_get_stats()
char * satox_network_manager_get_stats (void * handle)
Definition at line 410 of file satox_sdk_c.cpp.
satox_network_manager_remove_peer()
int satox_network_manager_remove_peer (void * handle, const char * address, unsigned short port)
Definition at line 412 of file satox_sdk_c.cpp.
satox_network_manager_send_message()
int satox_network_manager_send_message (void * handle, const char * address, unsigned short port, const char * message)
Definition at line 413 of file satox_sdk_c.cpp.
satox_network_manager_start()
int satox_network_manager_start (void * handle)
Definition at line 407 of file satox_sdk_c.cpp.
satox_network_manager_stop()
int satox_network_manager_stop (void * handle)
Definition at line 408 of file satox_sdk_c.cpp.
satox_nft_manager_create()
void * satox_nft_manager_create ()
Definition at line 314 of file satox_sdk_c.cpp.
References satox::nft::NFTManager::getInstance().
satox_nft_manager_create_nft()
char * satox_nft_manager_create_nft (void * handle, const char * asset_id, const char * metadata_json, const char * owner_address)
Definition at line 327 of file satox_sdk_c.cpp.
References satox::nft::NFTManager::NFTMetadata::additionalData, satox::nft::NFTManager::NFTMetadata::attributes, satox::nft::NFTManager::NFTMetadata::description, satox::nft::NFTManager::NFTMetadata::externalUrl, satox::nft::NFTManager::NFTMetadata::image, json_to_c_string(), and satox::nft::NFTManager::NFTMetadata::name.
satox_nft_manager_destroy()
void satox_nft_manager_destroy (void * handle)
Definition at line 323 of file satox_sdk_c.cpp.
satox_nft_manager_get_nft_info()
char * satox_nft_manager_get_nft_info (void * handle, const char * nft_id)
Definition at line 361 of file satox_sdk_c.cpp.
References satox::nft::NFTManager::getNFT(), and json_to_c_string().
satox_nft_manager_get_nfts_by_owner()
char * satox_nft_manager_get_nfts_by_owner (void * handle, const char * address)
Definition at line 416 of file satox_sdk_c.cpp.
satox_nft_manager_transfer_nft()
char * satox_nft_manager_transfer_nft (void * handle, const char * nft_id, const char * from_address, const char * to_address)
Definition at line 415 of file satox_sdk_c.cpp.
satox_nft_manager_update_metadata()
char * satox_nft_manager_update_metadata (void * handle, const char * nft_id, const char * metadata_json, const char * owner_address)
Definition at line 417 of file satox_sdk_c.cpp.
satox_sdk_get_version()
const char * satox_sdk_get_version ()
Definition at line 92 of file satox_sdk_c.cpp.
satox_sdk_initialize()
int satox_sdk_initialize ()
Definition at line 61 of file satox_sdk_c.cpp.
References sdk_initialized.
satox_sdk_shutdown()
void satox_sdk_shutdown ()
Definition at line 80 of file satox_sdk_c.cpp.
References sdk_initialized.
satox_security_manager_create()
void * satox_security_manager_create ()
Definition at line 101 of file satox_sdk_c.cpp.
References satox::security::SecurityManager::getInstance().
satox_security_manager_decrypt_data()
char * satox_security_manager_decrypt_data (void * handle, const char * encrypted_data, const char * private_key)
Definition at line 176 of file satox_sdk_c.cpp.
References string_to_c_string().
satox_security_manager_destroy()
void satox_security_manager_destroy (void * handle)
Definition at line 110 of file satox_sdk_c.cpp.
satox_security_manager_encrypt_data()
char * satox_security_manager_encrypt_data (void * handle, const char * data, const char * public_key)
Definition at line 164 of file satox_sdk_c.cpp.
References string_to_c_string().
satox_security_manager_generate_keypair()
int satox_security_manager_generate_keypair (void * handle, char ** public_key, char ** private_key)
Definition at line 114 of file satox_sdk_c.cpp.
References string_to_c_string().
satox_security_manager_sha256()
char * satox_security_manager_sha256 (void * handle, const char * data)
Definition at line 153 of file satox_sdk_c.cpp.
References string_to_c_string().
satox_security_manager_sign_data()
char * satox_security_manager_sign_data (void * handle, const char * data, const char * private_key)
Definition at line 129 of file satox_sdk_c.cpp.
References string_to_c_string().
satox_security_manager_verify_signature()
int satox_security_manager_verify_signature (void * handle, const char * data, const char * signature, const char * public_key)
Definition at line 141 of file satox_sdk_c.cpp.
string_to_c_string()
char * string_to_c_string (const std::string & str)
Definition at line 48 of file satox_sdk_c.cpp.
Referenced by json_to_c_string(), satox_security_manager_decrypt_data(), satox_security_manager_encrypt_data(), satox_security_manager_generate_keypair(), satox_security_manager_sha256(), and satox_security_manager_sign_data().
Variable Documentation
sdk_initialized
bool sdk_initialized = false static
Definition at line 45 of file satox_sdk_c.cpp.
Referenced by satox_sdk_initialize(), and satox_sdk_shutdown().