SATOX SDK: satox::security::pqc::HybridCrypto::Impl Class Reference
satox::security::pqc::HybridCrypto::Impl Class Reference
Public Member Functions
Impl (MLKEM::SecurityLevel kemLevel, MLDSA::SecurityLevel dsaLevel)
bool generateHybridKeyPair (std::vector< uint8_t > &publicKey, std::vector< uint8_t > &privateKey)
bool hybridEncrypt (const std::vector< uint8_t > &publicKey, const std::vector< uint8_t > &message, std::vector< uint8_t > &ciphertext)
bool hybridDecrypt (const std::vector< uint8_t > &privateKey, const std::vector< uint8_t > &ciphertext, std::vector< uint8_t > &message)
bool hybridSign (const std::vector< uint8_t > &privateKey, const std::vector< uint8_t > &message, std::vector< uint8_t > &signature)
bool hybridVerify (const std::vector< uint8_t > &publicKey, const std::vector< uint8_t > &message, const std::vector< uint8_t > &signature)
bool rotateKeys (const std::vector< uint8_t > &oldPrivateKey, std::vector< uint8_t > &newPublicKey, std::vector< uint8_t > &newPrivateKey)
size_t getPublicKeySize () const
size_t getPrivateKeySize () const
size_t getCiphertextSize () const
size_t getSignatureSize () const
MLKEM::SecurityLevel getKEMSecurityLevel () const
MLDSA::SecurityLevel getDSASecurityLevel () const
std::string getLastError () const
void clearLastError ()
Impl (MLKEM::SecurityLevel kemLevel, MLDSA::SecurityLevel dsaLevel)
bool generateHybridKeyPair (std::vector< uint8_t > &publicKey, std::vector< uint8_t > &privateKey)
bool hybridEncrypt (const std::vector< uint8_t > &publicKey, const std::vector< uint8_t > &message, std::vector< uint8_t > &ciphertext)
bool hybridDecrypt (const std::vector< uint8_t > &privateKey, const std::vector< uint8_t > &ciphertext, std::vector< uint8_t > &message)
bool hybridSign (const std::vector< uint8_t > &privateKey, const std::vector< uint8_t > &message, std::vector< uint8_t > &signature)
bool hybridVerify (const std::vector< uint8_t > &publicKey, const std::vector< uint8_t > &message, const std::vector< uint8_t > &signature)
bool rotateKeys (const std::vector< uint8_t > &oldPrivateKey, std::vector< uint8_t > &newPublicKey, std::vector< uint8_t > &newPrivateKey)
size_t getPublicKeySize () const
size_t getPrivateKeySize () const
size_t getCiphertextSize () const
size_t getSignatureSize () const
MLKEM::SecurityLevel getKEMSecurityLevel () const
MLDSA::SecurityLevel getDSASecurityLevel () const
std::string getLastError () const
void clearLastError ()
Detailed Description
Definition at line 40 of file hybrid.cpp.
Constructor & Destructor Documentation
Impl() [1/2]
satox::security::pqc::HybridCrypto::Impl::Impl (MLKEM::SecurityLevel kemLevel, MLDSA::SecurityLevel dsaLevel) inline
Definition at line 42 of file hybrid.cpp.
Impl() [2/2]
satox::security::pqc::HybridCrypto::Impl::Impl (MLKEM::SecurityLevel kemLevel, MLDSA::SecurityLevel dsaLevel) inline
Definition at line 42 of file hybrid.cpp.
Member Function Documentation
clearLastError() [1/2]
void satox::security::pqc::HybridCrypto::Impl::clearLastError () inline
Definition at line 260 of file hybrid.cpp.
clearLastError() [2/2]
void satox::security::pqc::HybridCrypto::Impl::clearLastError () inline
Definition at line 260 of file hybrid.cpp.
generateHybridKeyPair() [1/2]
bool satox::security::pqc::HybridCrypto::Impl::generateHybridKeyPair (std::vector< uint8_t > & publicKey, std::vector< uint8_t > & privateKey) inline
Definition at line 49 of file hybrid.cpp.
References satox::security::pqc::MLDSA::generateKeyPair(), satox::security::pqc::MLKEM::generateKeyPair(), satox::security::pqc::MLDSA::getLastError(), and satox::security::pqc::MLKEM::getLastError().
Referenced by rotateKeys().
generateHybridKeyPair() [2/2]
bool satox::security::pqc::HybridCrypto::Impl::generateHybridKeyPair (std::vector< uint8_t > & publicKey, std::vector< uint8_t > & privateKey) inline
Definition at line 49 of file hybrid.cpp.
References satox::security::pqc::MLDSA::generateKeyPair(), satox::security::pqc::MLKEM::generateKeyPair(), satox::security::pqc::MLDSA::getLastError(), and satox::security::pqc::MLKEM::getLastError().
getCiphertextSize() [1/2]
size_t satox::security::pqc::HybridCrypto::Impl::getCiphertextSize () const inline
Definition at line 236 of file hybrid.cpp.
References satox::security::pqc::MLKEM::getCiphertextSize(), satox::security::pqc::MLKEM::getPublicKeySize(), and satox::security::pqc::MLDSA::getSignatureSize().
getCiphertextSize() [2/2]
size_t satox::security::pqc::HybridCrypto::Impl::getCiphertextSize () const inline
Definition at line 236 of file hybrid.cpp.
References satox::security::pqc::MLKEM::getCiphertextSize(), satox::security::pqc::MLKEM::getPublicKeySize(), and satox::security::pqc::MLDSA::getSignatureSize().
getDSASecurityLevel() [1/2]
MLDSA::SecurityLevel satox::security::pqc::HybridCrypto::Impl::getDSASecurityLevel () const inline
Definition at line 252 of file hybrid.cpp.
getDSASecurityLevel() [2/2]
MLDSA::SecurityLevel satox::security::pqc::HybridCrypto::Impl::getDSASecurityLevel () const inline
Definition at line 252 of file hybrid.cpp.
getKEMSecurityLevel() [1/2]
MLKEM::SecurityLevel satox::security::pqc::HybridCrypto::Impl::getKEMSecurityLevel () const inline
Definition at line 248 of file hybrid.cpp.
getKEMSecurityLevel() [2/2]
MLKEM::SecurityLevel satox::security::pqc::HybridCrypto::Impl::getKEMSecurityLevel () const inline
Definition at line 248 of file hybrid.cpp.
getLastError() [1/2]
std::string satox::security::pqc::HybridCrypto::Impl::getLastError () const inline
Definition at line 256 of file hybrid.cpp.
getLastError() [2/2]
std::string satox::security::pqc::HybridCrypto::Impl::getLastError () const inline
Definition at line 256 of file hybrid.cpp.
getPrivateKeySize() [1/2]
size_t satox::security::pqc::HybridCrypto::Impl::getPrivateKeySize () const inline
Definition at line 230 of file hybrid.cpp.
References satox::security::pqc::MLDSA::getPrivateKeySize(), and satox::security::pqc::MLKEM::getPrivateKeySize().
getPrivateKeySize() [2/2]
size_t satox::security::pqc::HybridCrypto::Impl::getPrivateKeySize () const inline
Definition at line 230 of file hybrid.cpp.
References satox::security::pqc::MLDSA::getPrivateKeySize(), and satox::security::pqc::MLKEM::getPrivateKeySize().
getPublicKeySize() [1/2]
size_t satox::security::pqc::HybridCrypto::Impl::getPublicKeySize () const inline
Definition at line 224 of file hybrid.cpp.
References satox::security::pqc::MLDSA::getPublicKeySize(), and satox::security::pqc::MLKEM::getPublicKeySize().
getPublicKeySize() [2/2]
size_t satox::security::pqc::HybridCrypto::Impl::getPublicKeySize () const inline
Definition at line 224 of file hybrid.cpp.
References satox::security::pqc::MLDSA::getPublicKeySize(), and satox::security::pqc::MLKEM::getPublicKeySize().
getSignatureSize() [1/2]
size_t satox::security::pqc::HybridCrypto::Impl::getSignatureSize () const inline
Definition at line 243 of file hybrid.cpp.
References satox::security::pqc::MLDSA::getSignatureSize().
getSignatureSize() [2/2]
size_t satox::security::pqc::HybridCrypto::Impl::getSignatureSize () const inline
Definition at line 243 of file hybrid.cpp.
References satox::security::pqc::MLDSA::getSignatureSize().
hybridDecrypt() [1/2]
bool satox::security::pqc::HybridCrypto::Impl::hybridDecrypt (const std::vector< uint8_t > & privateKey, const std::vector< uint8_t > & ciphertext, std::vector< uint8_t > & message) inline
Definition at line 126 of file hybrid.cpp.
References satox::security::pqc::MLKEM::decapsulate(), satox::security::pqc::MLDSA::getLastError(), satox::security::pqc::MLKEM::getLastError(), and satox::security::pqc::MLDSA::verify().
hybridDecrypt() [2/2]
bool satox::security::pqc::HybridCrypto::Impl::hybridDecrypt (const std::vector< uint8_t > & privateKey, const std::vector< uint8_t > & ciphertext, std::vector< uint8_t > & message) inline
Definition at line 126 of file hybrid.cpp.
References satox::security::pqc::MLKEM::decapsulate(), satox::security::pqc::MLDSA::getLastError(), satox::security::pqc::MLKEM::getLastError(), and satox::security::pqc::MLDSA::verify().
hybridEncrypt() [1/2]
bool satox::security::pqc::HybridCrypto::Impl::hybridEncrypt (const std::vector< uint8_t > & publicKey, const std::vector< uint8_t > & message, std::vector< uint8_t > & ciphertext) inline
Definition at line 79 of file hybrid.cpp.
References satox::security::pqc::MLKEM::encapsulate(), satox::security::pqc::MLKEM::generateKeyPair(), satox::security::pqc::MLDSA::getLastError(), satox::security::pqc::MLKEM::getLastError(), and satox::security::pqc::MLDSA::sign().
hybridEncrypt() [2/2]
bool satox::security::pqc::HybridCrypto::Impl::hybridEncrypt (const std::vector< uint8_t > & publicKey, const std::vector< uint8_t > & message, std::vector< uint8_t > & ciphertext) inline
Definition at line 79 of file hybrid.cpp.
References satox::security::pqc::MLKEM::encapsulate(), satox::security::pqc::MLKEM::generateKeyPair(), satox::security::pqc::MLDSA::getLastError(), satox::security::pqc::MLKEM::getLastError(), and satox::security::pqc::MLDSA::sign().
hybridSign() [1/2]
bool satox::security::pqc::HybridCrypto::Impl::hybridSign (const std::vector< uint8_t > & privateKey, const std::vector< uint8_t > & message, std::vector< uint8_t > & signature) inline
Definition at line 164 of file hybrid.cpp.
References satox::security::pqc::MLDSA::getLastError(), and satox::security::pqc::MLDSA::sign().
hybridSign() [2/2]
bool satox::security::pqc::HybridCrypto::Impl::hybridSign (const std::vector< uint8_t > & privateKey, const std::vector< uint8_t > & message, std::vector< uint8_t > & signature) inline
Definition at line 164 of file hybrid.cpp.
References satox::security::pqc::MLDSA::getLastError(), and satox::security::pqc::MLDSA::sign().
hybridVerify() [1/2]
bool satox::security::pqc::HybridCrypto::Impl::hybridVerify (const std::vector< uint8_t > & publicKey, const std::vector< uint8_t > & message, const std::vector< uint8_t > & signature) inline
Definition at line 185 of file hybrid.cpp.
References satox::security::pqc::MLDSA::getLastError(), and satox::security::pqc::MLDSA::verify().
hybridVerify() [2/2]
bool satox::security::pqc::HybridCrypto::Impl::hybridVerify (const std::vector< uint8_t > & publicKey, const std::vector< uint8_t > & message, const std::vector< uint8_t > & signature) inline
Definition at line 185 of file hybrid.cpp.
References satox::security::pqc::MLDSA::getLastError(), and satox::security::pqc::MLDSA::verify().
rotateKeys() [1/2]
bool satox::security::pqc::HybridCrypto::Impl::rotateKeys (const std::vector< uint8_t > & oldPrivateKey, std::vector< uint8_t > & newPublicKey, std::vector< uint8_t > & newPrivateKey) inline
Definition at line 206 of file hybrid.cpp.
References generateHybridKeyPair().
rotateKeys() [2/2]
bool satox::security::pqc::HybridCrypto::Impl::rotateKeys (const std::vector< uint8_t > & oldPrivateKey, std::vector< uint8_t > & newPublicKey, std::vector< uint8_t > & newPrivateKey) inline
Definition at line 206 of file hybrid.cpp.
References generateHybridKeyPair().
The documentation for this class was generated from the following files:
src/security/pqc/hybrid.cpp
src/security/src/hybrid.cpp