SATOX SDK: satox::core::NetworkManager Class Reference
satox::core::NetworkManager Class Reference
#include <network_manager.hpp>
Classes
struct ConnectionInfo
struct NetworkStats
Public Types
enum class NetworkType { MAINNET , TESTNET , REGTEST }
enum class ConnectionState {
DISCONNECTED , CONNECTING , CONNECTED , DISCONNECTING ,
ERROR
}
enum class NodeType { FULL , LIGHT , ARCHIVE }
using ConnectionCallback = std::function<void(const std::string&, ConnectionState)>
using MessageCallback = std::function<void(const std::string&, const std::string&, const nlohmann::json&)>
using ErrorCallback = std::function<void(const std::string&, const std::string&)>
Public Member Functions
bool initialize (const nlohmann::json &config)
void shutdown ()
bool connect (const std::string &address, uint16_t port)
bool disconnect (const std::string &address)
bool isConnected (const std::string &address) const
ConnectionState getConnectionState (const std::string &address) const
std::vector< ConnectionInfo > getConnections () const
ConnectionInfo getConnectionInfo (const std::string &address) const
bool sendMessage (const std::string &address, const std::string &type, const nlohmann::json &data)
bool broadcastMessage (const std::string &type, const nlohmann::json &data)
bool subscribeToMessages (const std::string &type, MessageCallback callback)
bool unsubscribeFromMessages (const std::string &type)
bool setNetworkType (NetworkType type)
NetworkType getNetworkType () const
bool setNodeType (NodeType type)
NodeType getNodeType () const
bool setMaxConnections (size_t max)
size_t getMaxConnections () const
bool setConnectionTimeout (std::chrono::milliseconds timeout)
std::chrono::milliseconds getConnectionTimeout () const
std::vector< std::string > discoverNodes () const
bool addNode (const std::string &address, uint16_t port)
bool removeNode (const std::string &address)
bool isNodeKnown (const std::string &address) const
NetworkStats getStats () const
void resetStats ()
bool enableStats (bool enable)
void registerConnectionCallback (ConnectionCallback callback)
void registerErrorCallback (ErrorCallback callback)
void unregisterConnectionCallback ()
void unregisterErrorCallback ()
std::string getLastError () const
void clearLastError ()
Static Public Member Functions
static NetworkManager & getInstance ()
Detailed Description
Definition at line 40 of file network_manager.hpp.
Member Typedef Documentation
ConnectionCallback
using satox::core::NetworkManager::ConnectionCallback = std::function<void(const std::string&, ConnectionState)>
Definition at line 97 of file network_manager.hpp.
ErrorCallback
using satox::core::NetworkManager::ErrorCallback = std::function<void(const std::string&, const std::string&)>
Definition at line 99 of file network_manager.hpp.
MessageCallback
using satox::core::NetworkManager::MessageCallback = std::function<void(const std::string&, const std::string&, const nlohmann::json&)>
Definition at line 98 of file network_manager.hpp.
Member Enumeration Documentation
ConnectionState
enum class satox::core::NetworkManager::ConnectionState strong
Enumerator
DISCONNECTED
CONNECTING
CONNECTED
DISCONNECTING
ERROR
Definition at line 50 of file network_manager.hpp.
NetworkType
enum class satox::core::NetworkManager::NetworkType strong
Enumerator
MAINNET
TESTNET
REGTEST
Definition at line 43 of file network_manager.hpp.
NodeType
enum class satox::core::NetworkManager::NodeType strong
Enumerator
FULL
LIGHT
ARCHIVE
Definition at line 59 of file network_manager.hpp.
Member Function Documentation
addNode()
bool satox::core::NetworkManager::addNode (const std::string & address, uint16_t port)
Definition at line 412 of file network_manager.cpp.
broadcastMessage()
bool satox::core::NetworkManager::broadcastMessage (const std::string & type, const nlohmann::json & data)
Definition at line 274 of file network_manager.cpp.
References sendMessage().
clearLastError()
void satox::core::NetworkManager::clearLastError ()
Definition at line 518 of file network_manager.cpp.
connect()
bool satox::core::NetworkManager::connect (const std::string & address, uint16_t port)
Definition at line 119 of file network_manager.cpp.
References satox::core::NetworkManager::ConnectionInfo::address, CONNECTED, CONNECTING, isConnected(), satox::core::NetworkManager::ConnectionInfo::isInbound, satox::core::NetworkManager::ConnectionInfo::isOutbound, satox::core::NetworkManager::ConnectionInfo::lastPing, satox::core::NetworkManager::ConnectionInfo::lastSeen, satox::core::NetworkManager::ConnectionInfo::latency, satox::core::NetworkManager::ConnectionInfo::metadata, satox::core::NetworkManager::ConnectionInfo::networkType, satox::core::NetworkManager::ConnectionInfo::nodeType, satox::core::NetworkManager::ConnectionInfo::port, satox::core::NetworkManager::ConnectionInfo::userAgent, and satox::core::NetworkManager::ConnectionInfo::version.
disconnect()
bool satox::core::NetworkManager::disconnect (const std::string & address)
Definition at line 175 of file network_manager.cpp.
References DISCONNECTED, and DISCONNECTING.
Referenced by shutdown().
discoverNodes()
std::vector< std::string > satox::core::NetworkManager::discoverNodes () const
Definition at line 399 of file network_manager.cpp.
enableStats()
bool satox::core::NetworkManager::enableStats (bool enable)
Definition at line 481 of file network_manager.cpp.
getConnectionInfo()
NetworkManager::ConnectionInfo satox::core::NetworkManager::getConnectionInfo (const std::string & address) const
Definition at line 234 of file network_manager.cpp.
getConnections()
std::vector< NetworkManager::ConnectionInfo > satox::core::NetworkManager::getConnections () const
Definition at line 224 of file network_manager.cpp.
getConnectionState()
NetworkManager::ConnectionState satox::core::NetworkManager::getConnectionState (const std::string & address) const
Definition at line 212 of file network_manager.cpp.
References CONNECTED, and DISCONNECTED.
getConnectionTimeout()
std::chrono::milliseconds satox::core::NetworkManager::getConnectionTimeout () const
Definition at line 394 of file network_manager.cpp.
getInstance()
NetworkManager & satox::core::NetworkManager::getInstance () static
Definition at line 35 of file network_manager.cpp.
Referenced by satox::core::CoreManager::getNetworkManager(), and satox::core::SatoxManager::getNetworkManager().
getLastError()
std::string satox::core::NetworkManager::getLastError () const
Definition at line 513 of file network_manager.cpp.
getMaxConnections()
size_t satox::core::NetworkManager::getMaxConnections () const
Definition at line 372 of file network_manager.cpp.
getNetworkType()
NetworkManager::NetworkType satox::core::NetworkManager::getNetworkType () const
Definition at line 333 of file network_manager.cpp.
getNodeType()
NetworkManager::NodeType satox::core::NetworkManager::getNodeType () const
Definition at line 350 of file network_manager.cpp.
getStats()
NetworkManager::NetworkStats satox::core::NetworkManager::getStats () const
Definition at line 471 of file network_manager.cpp.
initialize()
bool satox::core::NetworkManager::initialize (const nlohmann::json & config)
Definition at line 40 of file network_manager.cpp.
References satox::core::LoggingManager::LogConfig::asyncLogging, satox::core::LoggingManager::LogConfig::consoleOutput, satox::core::LoggingManager::DEBUG, satox::core::LoggingManager::LogConfig::fileOutput, satox::core::LoggingManager::LogConfig::flushInterval, satox::core::LoggingManager::LogConfig::includeSource, satox::core::LoggingManager::LogConfig::includeThreadId, satox::core::LoggingManager::LogConfig::includeTimestamp, satox::core::LoggingManager::LogConfig::logDir, satox::core::LoggingManager::LogConfig::logFile, satox::core::LoggingManager::LogConfig::logFormat, satox::core::LoggingManager::LogConfig::maxFiles, satox::core::LoggingManager::LogConfig::maxFileSize, satox::core::LoggingManager::LogConfig::minLevel, and satox::core::LoggingManager::LogConfig::queueSize.
isConnected()
bool satox::core::NetworkManager::isConnected (const std::string & address) const
Definition at line 205 of file network_manager.cpp.
Referenced by connect(), and sendMessage().
isNodeKnown()
bool satox::core::NetworkManager::isNodeKnown (const std::string & address) const
Definition at line 454 of file network_manager.cpp.
registerConnectionCallback()
void satox::core::NetworkManager::registerConnectionCallback (ConnectionCallback callback)
Definition at line 493 of file network_manager.cpp.
registerErrorCallback()
void satox::core::NetworkManager::registerErrorCallback (ErrorCallback callback)
Definition at line 498 of file network_manager.cpp.
removeNode()
bool satox::core::NetworkManager::removeNode (const std::string & address)
Definition at line 437 of file network_manager.cpp.
resetStats()
void satox::core::NetworkManager::resetStats ()
Definition at line 476 of file network_manager.cpp.
sendMessage()
bool satox::core::NetworkManager::sendMessage (const std::string & address, const std::string & type, const nlohmann::json & data)
Definition at line 244 of file network_manager.cpp.
References isConnected().
Referenced by broadcastMessage().
setConnectionTimeout()
bool satox::core::NetworkManager::setConnectionTimeout (std::chrono::milliseconds timeout)
Definition at line 377 of file network_manager.cpp.
setMaxConnections()
bool satox::core::NetworkManager::setMaxConnections (size_t max)
Definition at line 355 of file network_manager.cpp.
setNetworkType()
bool satox::core::NetworkManager::setNetworkType (NetworkType type)
Definition at line 321 of file network_manager.cpp.
setNodeType()
bool satox::core::NetworkManager::setNodeType (NodeType type)
Definition at line 338 of file network_manager.cpp.
shutdown()
void satox::core::NetworkManager::shutdown ()
Definition at line 100 of file network_manager.cpp.
References disconnect().
subscribeToMessages()
bool satox::core::NetworkManager::subscribeToMessages (const std::string & type, MessageCallback callback)
Definition at line 297 of file network_manager.cpp.
unregisterConnectionCallback()
void satox::core::NetworkManager::unregisterConnectionCallback ()
Definition at line 503 of file network_manager.cpp.
unregisterErrorCallback()
void satox::core::NetworkManager::unregisterErrorCallback ()
Definition at line 508 of file network_manager.cpp.
unsubscribeFromMessages()
bool satox::core::NetworkManager::unsubscribeFromMessages (const std::string & type)
Definition at line 310 of file network_manager.cpp.
The documentation for this class was generated from the following files:
src/core/include/satox/core/network_manager.hpp
src/core/src/network_manager.cpp