SATOX SDK: satox::security::SecurityException Class Reference
satox::security::SecurityException Class Reference
#include <error.hpp>
Public Member Functions
SecurityException (SecurityErrorCode code, const std::string &message="")
const char * what () const noexcept override
SecurityErrorCode code () const
const std::string & message () const
Detailed Description
Definition at line 59 of file error.hpp.
Constructor & Destructor Documentation
SecurityException()
satox::security::SecurityException::SecurityException (SecurityErrorCode code, const std::string & message = "") inline
Definition at line 61 of file error.hpp.
References code(), and message().
Referenced by satox::security::PQCException::PQCException(), satox::security::RateLimitException::RateLimitException(), satox::security::SecurityInitializationException::SecurityInitializationException(), satox::security::SecurityViolationException::SecurityViolationException(), and satox::security::ValidationException::ValidationException().
Member Function Documentation
code()
SecurityErrorCode satox::security::SecurityException::code () const inline
Definition at line 68 of file error.hpp.
Referenced by SecurityException().
message()
const std::string & satox::security::SecurityException::message () const inline
Definition at line 72 of file error.hpp.
Referenced by satox::security::PQCException::PQCException(), satox::security::RateLimitException::RateLimitException(), SecurityException(), satox::security::SecurityInitializationException::SecurityInitializationException(), satox::security::SecurityViolationException::SecurityViolationException(), and satox::security::ValidationException::ValidationException().
what()
const char * satox::security::SecurityException::what () const inline override noexcept
Definition at line 64 of file error.hpp.
The documentation for this class was generated from the following file:
src/security/include/satox/security/error.hpp