SATOX SDK: satox::security::SecurityManager::Impl Class Reference
satox::security::SecurityManager::Impl Class Reference
Public Member Functions
Impl ()
bool initializePQC ()
bool loadDefaultConfig ()
bool initializeCaches ()
bool encrypt (const std::vector< uint8_t > &data, std::vector< uint8_t > &encryptedData)
bool decrypt (const std::vector< uint8_t > &encryptedData, std::vector< uint8_t > &decryptedData)
bool sign (const std::vector< uint8_t > &data, std::vector< uint8_t > &signature)
bool verify (const std::vector< uint8_t > &data, const std::vector< uint8_t > &signature)
std::string getLastError () const
Detailed Description
Definition at line 40 of file security_manager.cpp.
Constructor & Destructor Documentation
Impl()
satox::security::SecurityManager::Impl::Impl () inline
Definition at line 42 of file security_manager.cpp.
References initializeCaches(), initializePQC(), and loadDefaultConfig().
Member Function Documentation
decrypt()
bool satox::security::SecurityManager::Impl::decrypt (const std::vector< uint8_t > & encryptedData, std::vector< uint8_t > & decryptedData) inline
Definition at line 191 of file security_manager.cpp.
encrypt()
bool satox::security::SecurityManager::Impl::encrypt (const std::vector< uint8_t > & data, std::vector< uint8_t > & encryptedData) inline
Definition at line 125 of file security_manager.cpp.
getLastError()
std::string satox::security::SecurityManager::Impl::getLastError () const inline
Definition at line 305 of file security_manager.cpp.
initializeCaches()
bool satox::security::SecurityManager::Impl::initializeCaches () inline
Definition at line 106 of file security_manager.cpp.
Referenced by Impl().
initializePQC()
bool satox::security::SecurityManager::Impl::initializePQC () inline
Definition at line 58 of file security_manager.cpp.
References satox::security::pqc::MLDSA::Level3, and satox::security::pqc::MLKEM::Level3.
Referenced by Impl().
loadDefaultConfig()
bool satox::security::SecurityManager::Impl::loadDefaultConfig () inline
Definition at line 91 of file security_manager.cpp.
Referenced by Impl().
sign()
bool satox::security::SecurityManager::Impl::sign (const std::vector< uint8_t > & data, std::vector< uint8_t > & signature) inline
Definition at line 257 of file security_manager.cpp.
verify()
bool satox::security::SecurityManager::Impl::verify (const std::vector< uint8_t > & data, const std::vector< uint8_t > & signature) inline
Definition at line 281 of file security_manager.cpp.
The documentation for this class was generated from the following file:
src/security/security_manager.cpp