SATOX SDK: satox::wallet::WalletException Class Reference
satox::wallet::WalletException Class Reference
#include <error.hpp>
Public Member Functions
WalletException (WalletErrorCode code, const std::string &message="")
const char * what () const noexcept override
WalletErrorCode code () const
const std::string & message () const
Detailed Description
Definition at line 52 of file error.hpp.
Constructor & Destructor Documentation
WalletException()
satox::wallet::WalletException::WalletException (WalletErrorCode code, const std::string & message = "") inline
Definition at line 54 of file error.hpp.
References code(), and message().
Referenced by satox::wallet::WalletInitializationException::WalletInitializationException(), and satox::wallet::WalletOperationException::WalletOperationException().
Member Function Documentation
code()
WalletErrorCode satox::wallet::WalletException::code () const inline
Definition at line 61 of file error.hpp.
Referenced by WalletException().
message()
const std::string & satox::wallet::WalletException::message () const inline
Definition at line 65 of file error.hpp.
Referenced by WalletException(), satox::wallet::WalletInitializationException::WalletInitializationException(), and satox::wallet::WalletOperationException::WalletOperationException().
what()
const char * satox::wallet::WalletException::what () const inline override noexcept
Definition at line 57 of file error.hpp.
The documentation for this class was generated from the following file:
src/wallet/include/satox/wallet/error.hpp