SATOX SDK: satox::nft::NFTStorage Class Reference
satox::nft::NFTStorage Class Reference
#include <nft_storage.hpp>
Classes
struct Error
Public Member Functions
NFTStorage (const NFTStorage &)=delete
NFTStorage & operator= (const NFTStorage &)=delete
bool initialize (const std::string &storagePath)
void shutdown ()
bool storeNFT (const NFTManager::NFT &nft)
bool storeNFTMetadata (const std::string &nftId, const NFTManager::NFTMetadata &metadata)
bool storeNFTBatch (const std::vector< NFTManager::NFT > &nfts)
bool storeNFTMetadataBatch (const std::map< std::string, NFTManager::NFTMetadata > &metadataMap)
std::optional< NFTManager::NFT > getNFT (const std::string &nftId)
std::optional< NFTManager::NFTMetadata > getNFTMetadata (const std::string &nftId)
std::vector< NFTManager::NFT > getNFTsByOwner (const std::string &owner)
std::vector< NFTManager::NFT > getNFTsByContract (const std::string &contractAddress)
std::vector< NFTManager::NFT > getNFTsByCreator (const std::string &creator)
bool updateNFT (const NFTManager::NFT &nft)
bool updateNFTMetadata (const std::string &nftId, const NFTManager::NFTMetadata &metadata)
bool updateNFTBatch (const std::vector< NFTManager::NFT > &nfts)
bool updateNFTMetadataBatch (const std::map< std::string, NFTManager::NFTMetadata > &metadataMap)
bool deleteNFT (const std::string &nftId)
bool deleteNFTMetadata (const std::string &nftId)
bool deleteNFTBatch (const std::vector< std::string > &nftIds)
bool deleteNFTMetadataBatch (const std::vector< std::string > &nftIds)
std::vector< NFTManager::NFT > searchNFTs (const std::string &query)
std::vector< NFTManager::NFT > searchNFTsByMetadata (const nlohmann::json &metadataQuery)
std::vector< NFTManager::NFT > searchNFTsByAttributes (const std::map< std::string, std::string > &attributes)
void enableCache (bool enable)
void clearCache ()
void setCacheSize (size_t maxSize)
size_t getCacheSize () const
bool createBackup (const std::string &backupPath)
bool restoreFromBackup (const std::string &backupPath)
Error getLastError () const
void clearLastError ()
Static Public Member Functions
static NFTStorage & getInstance ()
Detailed Description
Definition at line 41 of file nft_storage.hpp.
Constructor & Destructor Documentation
NFTStorage()
satox::nft::NFTStorage::NFTStorage (const NFTStorage &) delete
References NFTStorage().
Referenced by getInstance(), NFTStorage(), and operator=().
Member Function Documentation
clearCache()
void satox::nft::NFTStorage::clearCache ()
Definition at line 482 of file nft_storage.cpp.
Referenced by enableCache(), restoreFromBackup(), and shutdown().
clearLastError()
void satox::nft::NFTStorage::clearLastError ()
Definition at line 560 of file nft_storage.cpp.
createBackup()
bool satox::nft::NFTStorage::createBackup (const std::string & backupPath)
Definition at line 498 of file nft_storage.cpp.
deleteNFT()
bool satox::nft::NFTStorage::deleteNFT (const std::string & nftId)
Definition at line 318 of file nft_storage.cpp.
Referenced by deleteNFTBatch().
deleteNFTBatch()
bool satox::nft::NFTStorage::deleteNFTBatch (const std::vector< std::string > & nftIds)
Definition at line 366 of file nft_storage.cpp.
References deleteNFT().
deleteNFTMetadata()
bool satox::nft::NFTStorage::deleteNFTMetadata (const std::string & nftId)
Definition at line 342 of file nft_storage.cpp.
Referenced by deleteNFTMetadataBatch().
deleteNFTMetadataBatch()
bool satox::nft::NFTStorage::deleteNFTMetadataBatch (const std::vector< std::string > & nftIds)
Definition at line 376 of file nft_storage.cpp.
References deleteNFTMetadata().
enableCache()
void satox::nft::NFTStorage::enableCache (bool enable)
Definition at line 474 of file nft_storage.cpp.
References clearCache().
getCacheSize()
size_t satox::nft::NFTStorage::getCacheSize () const
Definition at line 493 of file nft_storage.cpp.
getInstance()
NFTStorage & satox::nft::NFTStorage::getInstance () static
Definition at line 36 of file nft_storage.cpp.
References NFTStorage().
getLastError()
NFTStorage::Error satox::nft::NFTStorage::getLastError () const
Definition at line 556 of file nft_storage.cpp.
getNFT()
std::optional< NFTManager::NFT > satox::nft::NFTStorage::getNFT (const std::string & nftId)
Definition at line 162 of file nft_storage.cpp.
Referenced by getNFTsByContract(), getNFTsByCreator(), getNFTsByOwner(), searchNFTs(), searchNFTsByAttributes(), and searchNFTsByMetadata().
getNFTMetadata()
std::optional< NFTManager::NFTMetadata > satox::nft::NFTStorage::getNFTMetadata (const std::string & nftId)
Definition at line 211 of file nft_storage.cpp.
References satox::nft::NFTManager::NFTMetadata::attributes, satox::nft::NFTManager::NFTMetadata::description, satox::nft::NFTManager::NFTMetadata::image, and satox::nft::NFTManager::NFTMetadata::name.
Referenced by searchNFTsByAttributes(), and searchNFTsByMetadata().
getNFTsByContract()
std::vector< NFTManager::NFT > satox::nft::NFTStorage::getNFTsByContract (const std::string & contractAddress)
Definition at line 270 of file nft_storage.cpp.
References getNFT().
getNFTsByCreator()
std::vector< NFTManager::NFT > satox::nft::NFTStorage::getNFTsByCreator (const std::string & creator)
Definition at line 286 of file nft_storage.cpp.
References getNFT().
getNFTsByOwner()
std::vector< NFTManager::NFT > satox::nft::NFTStorage::getNFTsByOwner (const std::string & owner)
Definition at line 254 of file nft_storage.cpp.
References getNFT().
initialize()
bool satox::nft::NFTStorage::initialize (const std::string & storagePath)
Definition at line 41 of file nft_storage.cpp.
operator=()
NFTStorage & satox::nft::NFTStorage::operator= (const NFTStorage &) delete
References NFTStorage().
restoreFromBackup()
bool satox::nft::NFTStorage::restoreFromBackup (const std::string & backupPath)
Definition at line 529 of file nft_storage.cpp.
References clearCache().
searchNFTs()
std::vector< NFTManager::NFT > satox::nft::NFTStorage::searchNFTs (const std::string & query)
Definition at line 386 of file nft_storage.cpp.
References getNFT().
searchNFTsByAttributes()
std::vector< NFTManager::NFT > satox::nft::NFTStorage::searchNFTsByAttributes (const std::map< std::string, std::string > & attributes)
Definition at line 449 of file nft_storage.cpp.
References getNFT(), and getNFTMetadata().
searchNFTsByMetadata()
std::vector< NFTManager::NFT > satox::nft::NFTStorage::searchNFTsByMetadata (const nlohmann::json & metadataQuery)
Definition at line 423 of file nft_storage.cpp.
References getNFT(), and getNFTMetadata().
setCacheSize()
void satox::nft::NFTStorage::setCacheSize (size_t maxSize)
Definition at line 488 of file nft_storage.cpp.
shutdown()
void satox::nft::NFTStorage::shutdown ()
Definition at line 62 of file nft_storage.cpp.
References clearCache().
storeNFT()
bool satox::nft::NFTStorage::storeNFT (const NFTManager::NFT & nft)
Definition at line 68 of file nft_storage.cpp.
Referenced by storeNFTBatch(), and updateNFT().
storeNFTBatch()
bool satox::nft::NFTStorage::storeNFTBatch (const std::vector< NFTManager::NFT > & nfts)
Definition at line 142 of file nft_storage.cpp.
References storeNFT().
Referenced by updateNFTBatch().
storeNFTMetadata()
bool satox::nft::NFTStorage::storeNFTMetadata (const std::string & nftId, const NFTManager::NFTMetadata & metadata)
Definition at line 108 of file nft_storage.cpp.
References satox::nft::NFTManager::NFTMetadata::attributes, satox::nft::NFTManager::NFTMetadata::description, satox::nft::NFTManager::NFTMetadata::image, and satox::nft::NFTManager::NFTMetadata::name.
Referenced by storeNFTMetadataBatch(), and updateNFTMetadata().
storeNFTMetadataBatch()
bool satox::nft::NFTStorage::storeNFTMetadataBatch (const std::map< std::string, NFTManager::NFTMetadata > & metadataMap)
Definition at line 152 of file nft_storage.cpp.
References storeNFTMetadata().
Referenced by updateNFTMetadataBatch().
updateNFT()
bool satox::nft::NFTStorage::updateNFT (const NFTManager::NFT & nft)
Definition at line 302 of file nft_storage.cpp.
References storeNFT().
updateNFTBatch()
bool satox::nft::NFTStorage::updateNFTBatch (const std::vector< NFTManager::NFT > & nfts)
Definition at line 310 of file nft_storage.cpp.
References storeNFTBatch().
updateNFTMetadata()
bool satox::nft::NFTStorage::updateNFTMetadata (const std::string & nftId, const NFTManager::NFTMetadata & metadata)
Definition at line 306 of file nft_storage.cpp.
References storeNFTMetadata().
updateNFTMetadataBatch()
bool satox::nft::NFTStorage::updateNFTMetadataBatch (const std::map< std::string, NFTManager::NFTMetadata > & metadataMap)
Definition at line 314 of file nft_storage.cpp.
References storeNFTMetadataBatch().
The documentation for this class was generated from the following files:
src/nft/include/satox/nft/nft_storage.hpp
src/nft/src/nft_storage.cpp