SATOX SDK: satox::asset::SimpleLogger Class Reference
satox::asset::SimpleLogger Class Reference
Static Public Member Functions
static void debug (const std::string &msg)
static void info (const std::string &msg)
static void warn (const std::string &msg)
static void error (const std::string &msg)
Detailed Description
Definition at line 43 of file asset_manager.cpp.
Member Function Documentation
debug()
static void satox::asset::SimpleLogger::debug (const std::string & msg) inline static
Definition at line 45 of file asset_manager.cpp.
Referenced by satox::asset::AssetManager::AssetManager(), and satox::asset::AssetManager::~AssetManager().
error()
static void satox::asset::SimpleLogger::error (const std::string & msg) inline static
Definition at line 57 of file asset_manager.cpp.
Referenced by satox::asset::AssetManager::burnAsset(), satox::asset::AssetManager::createAsset(), satox::asset::AssetManager::initialize(), satox::asset::AssetManager::reissueAsset(), satox::asset::AssetManager::shutdown(), and satox::asset::AssetManager::transferAsset().
info()
static void satox::asset::SimpleLogger::info (const std::string & msg) inline static
Definition at line 49 of file asset_manager.cpp.
Referenced by satox::asset::AssetManager::burnAsset(), satox::asset::AssetManager::createAsset(), satox::asset::AssetManager::destroyAsset(), satox::asset::AssetManager::enableStats(), satox::asset::AssetManager::freezeAsset(), satox::asset::AssetManager::initialize(), satox::asset::AssetManager::reissueAsset(), satox::asset::AssetManager::resetStats(), satox::asset::AssetManager::shutdown(), satox::asset::AssetManager::transferAsset(), satox::asset::AssetManager::unfreezeAsset(), and satox::asset::AssetManager::updateConfig().
warn()
static void satox::asset::SimpleLogger::warn (const std::string & msg) inline static
Definition at line 53 of file asset_manager.cpp.
Referenced by satox::asset::AssetManager::initialize().
The documentation for this class was generated from the following file:
src/asset/src/asset_manager.cpp