SATOX SDK: satox::nft::NFTValidator Class Reference
satox::nft::NFTValidator Class Reference
#include <nft_validator.hpp>
Classes
struct Error
struct ValidationResult
Public Member Functions
NFTValidator (const NFTValidator &)=delete
NFTValidator & operator= (const NFTValidator &)=delete
bool initialize ()
void shutdown ()
ValidationResult validateNFT (const NFTManager::NFT &nft)
ValidationResult validateNFTMetadata (const NFTManager::NFTMetadata &metadata)
ValidationResult validateNFTTransfer (const std::string &nftId, const std::string &from, const std::string &to)
ValidationResult validateNFTBurn (const std::string &nftId, const std::string &owner)
ValidationResult validateNFTRoyalty (const std::string &nftId, const std::string &recipient, uint32_t basisPoints)
ValidationResult validateBatchNFTs (const std::vector< NFTManager::NFT > &nfts)
ValidationResult validateBatchTransfers (const std::vector< std::string > &nftIds, const std::string &from, const std::string &to)
ValidationResult validateBatchBurns (const std::vector< std::string > &nftIds, const std::string &owner)
bool validateSchema (const nlohmann::json &schema, const nlohmann::json &data)
bool validateMetadataSchema (const nlohmann::json &metadata)
void addValidationRule (const std::string &ruleName, std::function< bool(const NFTManager::NFT &)> rule)
void removeValidationRule (const std::string &ruleName)
bool hasValidationRule (const std::string &ruleName) const
Error getLastError () const
void clearLastError ()
Static Public Member Functions
static NFTValidator & getInstance ()
Detailed Description
Definition at line 40 of file nft_validator.hpp.
Constructor & Destructor Documentation
NFTValidator()
satox::nft::NFTValidator::NFTValidator (const NFTValidator &) delete
References NFTValidator().
Referenced by getInstance(), NFTValidator(), and operator=().
Member Function Documentation
addValidationRule()
void satox::nft::NFTValidator::addValidationRule (const std::string & ruleName, std::function< bool(const NFTManager::NFT &)> rule)
Definition at line 297 of file nft_validator.cpp.
clearLastError()
void satox::nft::NFTValidator::clearLastError ()
Definition at line 316 of file nft_validator.cpp.
getInstance()
NFTValidator & satox::nft::NFTValidator::getInstance () static
Definition at line 34 of file nft_validator.cpp.
References NFTValidator().
getLastError()
NFTValidator::Error satox::nft::NFTValidator::getLastError () const
Definition at line 312 of file nft_validator.cpp.
hasValidationRule()
bool satox::nft::NFTValidator::hasValidationRule (const std::string & ruleName) const
Definition at line 307 of file nft_validator.cpp.
initialize()
bool satox::nft::NFTValidator::initialize ()
Definition at line 39 of file nft_validator.cpp.
operator=()
NFTValidator & satox::nft::NFTValidator::operator= (const NFTValidator &) delete
References NFTValidator().
removeValidationRule()
void satox::nft::NFTValidator::removeValidationRule (const std::string & ruleName)
Definition at line 302 of file nft_validator.cpp.
shutdown()
void satox::nft::NFTValidator::shutdown ()
Definition at line 70 of file nft_validator.cpp.
validateBatchBurns()
NFTValidator::ValidationResult satox::nft::NFTValidator::validateBatchBurns (const std::vector< std::string > & nftIds, const std::string & owner)
Definition at line 222 of file nft_validator.cpp.
References satox::nft::NFTValidator::ValidationResult::errors, satox::nft::NFTValidator::ValidationResult::isValid, satox::nft::NFTValidator::ValidationResult::message, and validateNFTBurn().
validateBatchNFTs()
NFTValidator::ValidationResult satox::nft::NFTValidator::validateBatchNFTs (const std::vector< NFTManager::NFT > & nfts)
Definition at line 182 of file nft_validator.cpp.
References satox::nft::NFTValidator::ValidationResult::errors, satox::nft::NFTValidator::ValidationResult::isValid, satox::nft::NFTValidator::ValidationResult::message, and validateNFT().
validateBatchTransfers()
NFTValidator::ValidationResult satox::nft::NFTValidator::validateBatchTransfers (const std::vector< std::string > & nftIds, const std::string & from, const std::string & to)
Definition at line 202 of file nft_validator.cpp.
References satox::nft::NFTValidator::ValidationResult::errors, satox::nft::NFTValidator::ValidationResult::isValid, satox::nft::NFTValidator::ValidationResult::message, and validateNFTTransfer().
validateMetadataSchema()
bool satox::nft::NFTValidator::validateMetadataSchema (const nlohmann::json & metadata)
Definition at line 281 of file nft_validator.cpp.
References validateSchema().
validateNFT()
NFTValidator::ValidationResult satox::nft::NFTValidator::validateNFT (const NFTManager::NFT & nft)
Definition at line 76 of file nft_validator.cpp.
References satox::nft::NFTValidator::ValidationResult::errors, satox::nft::NFTValidator::ValidationResult::isValid, and satox::nft::NFTValidator::ValidationResult::message.
Referenced by validateBatchNFTs().
validateNFTBurn()
NFTValidator::ValidationResult satox::nft::NFTValidator::validateNFTBurn (const std::string & nftId, const std::string & owner)
Definition at line 134 of file nft_validator.cpp.
References satox::nft::NFTValidator::ValidationResult::errors, satox::nft::NFTValidator::ValidationResult::isValid, and satox::nft::NFTValidator::ValidationResult::message.
Referenced by validateBatchBurns().
validateNFTMetadata()
NFTValidator::ValidationResult satox::nft::NFTValidator::validateNFTMetadata (const NFTManager::NFTMetadata & metadata)
Definition at line 96 of file nft_validator.cpp.
References satox::nft::NFTValidator::ValidationResult::errors, satox::nft::NFTValidator::ValidationResult::isValid, and satox::nft::NFTValidator::ValidationResult::message.
validateNFTRoyalty()
NFTValidator::ValidationResult satox::nft::NFTValidator::validateNFTRoyalty (const std::string & nftId, const std::string & recipient, uint32_t basisPoints)
Definition at line 158 of file nft_validator.cpp.
References satox::nft::NFTValidator::ValidationResult::errors, satox::nft::NFTValidator::ValidationResult::isValid, and satox::nft::NFTValidator::ValidationResult::message.
validateNFTTransfer()
NFTValidator::ValidationResult satox::nft::NFTValidator::validateNFTTransfer (const std::string & nftId, const std::string & from, const std::string & to)
Definition at line 110 of file nft_validator.cpp.
References satox::nft::NFTValidator::ValidationResult::errors, satox::nft::NFTValidator::ValidationResult::isValid, and satox::nft::NFTValidator::ValidationResult::message.
Referenced by validateBatchTransfers().
validateSchema()
bool satox::nft::NFTValidator::validateSchema (const nlohmann::json & schema, const nlohmann::json & data)
Definition at line 242 of file nft_validator.cpp.
Referenced by validateMetadataSchema().
The documentation for this class was generated from the following files:
src/nft/include/satox/nft/nft_validator.hpp
src/nft/src/nft_validator.cpp