SATOX SDK: satox::security::SecurityManager Class Reference
satox::security::SecurityManager Class Reference
#include <security_manager.hpp>
Classes
class Impl
Public Member Functions
SecurityManager ()
~SecurityManager ()
bool initialize (const SecurityConfig &config)
void shutdown ()
bool start ()
bool stop ()
bool performOperation (const std::string &operation, const nlohmann::json &params)
SecurityResult executeOperation (const std::string &operation, const nlohmann::json &params)
bool validateOperation (const std::string &operation, const nlohmann::json &params)
SecurityState getState () const
bool isInitialized () const
bool isRunning () const
bool isHealthy () const
SecurityConfig getConfig () const
bool updateConfig (const SecurityConfig &config)
bool validateConfig (const SecurityConfig &config)
SecurityStats getStats () const
void resetStats ()
bool enableStats (bool enable)
void registerSecurityCallback (SecurityCallback callback)
void registerViolationCallback (SecurityViolationCallback callback)
void unregisterSecurityCallback ()
void unregisterViolationCallback ()
std::string getLastError () const
void clearLastError ()
bool healthCheck ()
nlohmann::json getHealthStatus ()
bool generatePQCKeyPair (const std::string &algorithm)
bool signWithPQC (const std::string &algorithm, const std::string &data)
bool verifyWithPQC (const std::string &algorithm, const std::string &data, const std::string &signature)
bool encryptWithPQC (const std::string &algorithm, const std::string &data)
bool decryptWithPQC (const std::string &algorithm, const std::string &encryptedData)
bool validateInput (const std::string &input, const std::string &type)
bool sanitizeInput (const std::string &input, std::string &sanitized)
bool validateEmail (const std::string &email)
bool validateURL (const std::string &url)
bool validateIPAddress (const std::string &ip)
bool validateJson (const std::string &json)
bool validateToken (const std::string &token)
bool checkRateLimit (const std::string &identifier, const std::string &operation)
bool setRateLimit (const std::string &identifier, int maxRequests, int timeWindow)
bool resetRateLimit (const std::string &identifier)
bool setPerformanceConfig (const nlohmann::json &config)
size_t getCacheSize () const
size_t getConnectionPoolSize () const
size_t getBatchSize () const
Static Public Member Functions
static SecurityManager & getInstance ()
Detailed Description
Definition at line 101 of file security_manager.hpp.
Constructor & Destructor Documentation
SecurityManager()
satox::security::SecurityManager::SecurityManager ()
Definition at line 457 of file security_manager.cpp.
Referenced by getInstance().
~SecurityManager()
satox::security::SecurityManager::~SecurityManager () default
Definition at line 61 of file security_manager.cpp.
References shutdown().
Member Function Documentation
checkRateLimit()
bool satox::security::SecurityManager::checkRateLimit (const std::string & identifier, const std::string & operation)
Definition at line 451 of file security_manager.cpp.
Referenced by executeOperation().
clearLastError()
void satox::security::SecurityManager::clearLastError ()
Definition at line 343 of file security_manager.cpp.
decryptWithPQC()
bool satox::security::SecurityManager::decryptWithPQC (const std::string & algorithm, const std::string & encryptedData)
Definition at line 403 of file security_manager.cpp.
enableStats()
bool satox::security::SecurityManager::enableStats (bool enable)
Definition at line 310 of file security_manager.cpp.
encryptWithPQC()
bool satox::security::SecurityManager::encryptWithPQC (const std::string & algorithm, const std::string & data)
Definition at line 398 of file security_manager.cpp.
executeOperation()
SecurityResult satox::security::SecurityManager::executeOperation (const std::string & operation, const nlohmann::json & params)
Definition at line 201 of file security_manager.cpp.
References checkRateLimit(), satox::security::SecurityResult::duration, satox::security::SecurityResult::error, satox::security::SecurityResult::success, and validateInput().
Referenced by performOperation().
generatePQCKeyPair()
bool satox::security::SecurityManager::generatePQCKeyPair (const std::string & algorithm)
Definition at line 383 of file security_manager.cpp.
getBatchSize()
size_t satox::security::SecurityManager::getBatchSize () const
Definition at line 680 of file security_manager.cpp.
getCacheSize()
size_t satox::security::SecurityManager::getCacheSize () const
Definition at line 655 of file security_manager.cpp.
getConfig()
SecurityConfig satox::security::SecurityManager::getConfig () const
Definition at line 274 of file security_manager.cpp.
getConnectionPoolSize()
size_t satox::security::SecurityManager::getConnectionPoolSize () const
Definition at line 666 of file security_manager.cpp.
getHealthStatus()
nlohmann::json satox::security::SecurityManager::getHealthStatus ()
Definition at line 370 of file security_manager.cpp.
References getState(), healthCheck(), isInitialized(), and isRunning().
getInstance()
SecurityManager & satox::security::SecurityManager::getInstance () static
Definition at line 44 of file security_manager.cpp.
References SecurityManager().
Referenced by satox_security_manager_create().
getLastError()
std::string satox::security::SecurityManager::getLastError () const
Definition at line 481 of file security_manager.cpp.
getState()
SecurityState satox::security::SecurityManager::getState () const
Definition at line 244 of file security_manager.cpp.
Referenced by getHealthStatus().
getStats()
SecurityStats satox::security::SecurityManager::getStats () const
Definition at line 300 of file security_manager.cpp.
healthCheck()
bool satox::security::SecurityManager::healthCheck ()
Definition at line 349 of file security_manager.cpp.
Referenced by getHealthStatus().
initialize()
bool satox::security::SecurityManager::initialize (const SecurityConfig & config)
Definition at line 66 of file security_manager.cpp.
References satox::security::SecurityConfig::enableLogging, satox::security::INITIALIZED, and satox::security::SecurityConfig::logPath.
isHealthy()
bool satox::security::SecurityManager::isHealthy () const
Definition at line 259 of file security_manager.cpp.
isInitialized()
bool satox::security::SecurityManager::isInitialized () const
Definition at line 249 of file security_manager.cpp.
Referenced by getHealthStatus().
isRunning()
bool satox::security::SecurityManager::isRunning () const
Definition at line 254 of file security_manager.cpp.
Referenced by getHealthStatus().
performOperation()
bool satox::security::SecurityManager::performOperation (const std::string & operation, const nlohmann::json & params)
Definition at line 166 of file security_manager.cpp.
References executeOperation(), satox::security::SecurityResult::success, and validateOperation().
registerSecurityCallback()
void satox::security::SecurityManager::registerSecurityCallback (SecurityCallback callback)
Definition at line 317 of file security_manager.cpp.
registerViolationCallback()
void satox::security::SecurityManager::registerViolationCallback (SecurityViolationCallback callback)
Definition at line 322 of file security_manager.cpp.
resetRateLimit()
bool satox::security::SecurityManager::resetRateLimit (const std::string & identifier)
Definition at line 478 of file security_manager.cpp.
resetStats()
void satox::security::SecurityManager::resetStats ()
Definition at line 305 of file security_manager.cpp.
sanitizeInput()
bool satox::security::SecurityManager::sanitizeInput (const std::string & input, std::string & sanitized)
Definition at line 418 of file security_manager.cpp.
setPerformanceConfig()
bool satox::security::SecurityManager::setPerformanceConfig (const nlohmann::json & config)
Definition at line 642 of file security_manager.cpp.
setRateLimit()
bool satox::security::SecurityManager::setRateLimit (const std::string & identifier, int maxRequests, int timeWindow)
Definition at line 465 of file security_manager.cpp.
shutdown()
void satox::security::SecurityManager::shutdown ()
Definition at line 105 of file security_manager.cpp.
References satox::security::SHUTDOWN, and satox::security::UNINITIALIZED.
Referenced by ~SecurityManager().
signWithPQC()
bool satox::security::SecurityManager::signWithPQC (const std::string & algorithm, const std::string & data)
Definition at line 388 of file security_manager.cpp.
start()
bool satox::security::SecurityManager::start ()
Definition at line 125 of file security_manager.cpp.
References satox::security::RUNNING.
stop()
bool satox::security::SecurityManager::stop ()
Definition at line 148 of file security_manager.cpp.
References satox::security::STOPPED.
unregisterSecurityCallback()
void satox::security::SecurityManager::unregisterSecurityCallback ()
Definition at line 327 of file security_manager.cpp.
unregisterViolationCallback()
void satox::security::SecurityManager::unregisterViolationCallback ()
Definition at line 332 of file security_manager.cpp.
updateConfig()
bool satox::security::SecurityManager::updateConfig (const SecurityConfig & config)
Definition at line 279 of file security_manager.cpp.
References validateConfig().
validateConfig()
bool satox::security::SecurityManager::validateConfig (const SecurityConfig & config)
Definition at line 290 of file security_manager.cpp.
References satox::security::SecurityConfig::name.
Referenced by updateConfig().
validateEmail()
bool satox::security::SecurityManager::validateEmail (const std::string & email)
Definition at line 438 of file security_manager.cpp.
References validateInput().
validateInput()
bool satox::security::SecurityManager::validateInput (const std::string & input, const std::string & type)
Definition at line 409 of file security_manager.cpp.
Referenced by executeOperation(), validateEmail(), validateIPAddress(), and validateURL().
validateIPAddress()
bool satox::security::SecurityManager::validateIPAddress (const std::string & ip)
Definition at line 446 of file security_manager.cpp.
References validateInput().
validateJson()
bool satox::security::SecurityManager::validateJson (const std::string & json)
Definition at line 612 of file security_manager.cpp.
validateOperation()
bool satox::security::SecurityManager::validateOperation (const std::string & operation, const nlohmann::json & params)
Definition at line 228 of file security_manager.cpp.
Referenced by performOperation().
validateToken()
bool satox::security::SecurityManager::validateToken (const std::string & token)
Definition at line 630 of file security_manager.cpp.
validateURL()
bool satox::security::SecurityManager::validateURL (const std::string & url)
Definition at line 442 of file security_manager.cpp.
References validateInput().
verifyWithPQC()
bool satox::security::SecurityManager::verifyWithPQC (const std::string & algorithm, const std::string & data, const std::string & signature)
Definition at line 393 of file security_manager.cpp.
The documentation for this class was generated from the following files:
src/security/include/satox/security/security_manager.hpp
src/security/security_manager.cpp
src/security/src/security_manager.cpp