SATOX SDK: satox::wallet::WalletManager Class Reference
satox::wallet::WalletManager Class Reference
#include <wallet_manager.hpp>
Classes
struct Asset
struct HardwareWallet
struct IPFSData
struct KeyPair
struct MultisigTransaction
struct Wallet
Public Types
enum class Status {
ACTIVE , LOCKED , DISABLED , PENDING_SIGNATURE ,
EXPIRED
}
enum class HardwareWalletType {
LEDGER , TREZOR , COLD_CARD , BITBOX ,
UNKNOWN
}
using WalletCallback = std::function<void(const std::string&, const WalletInfo&)>
using AddressCallback = std::function<void(const std::string&, const AddressInfo&)>
using TransactionCallback = std::function<void(const std::string&, const TransactionInfo&)>
using ErrorCallback = std::function<void(const std::string&)>
using ProgressCallback = std::function<void(const std::string&, uint32_t)>
using WalletCallback = std::function<void(const Wallet&, Status)>
using HardwareWalletCallback = std::function<void(const HardwareWallet&, bool)>
using TransactionCallback = std::function<void(const MultisigTransaction&)>
Public Member Functions
WalletManager ()
~WalletManager ()
bool initialize (const WalletConfig &config)
void shutdown ()
std::string getLastError () const
std::string createWallet (const std::string &name, const std::string &password, const std::unordered_map< std::string, std::string > &metadata={})
bool importWallet (const std::string &name, const std::string &mnemonic, const std::string &password, const std::unordered_map< std::string, std::string > &metadata={})
bool removeWallet (const std::string &wallet_id)
std::optional< WalletInfo > getWalletInfo (const std::string &wallet_id) const
std::vector< std::string > listWallets () const
bool lockWallet (const std::string &wallet_id)
bool unlockWallet (const std::string &wallet_id, const std::string &password)
bool isWalletLocked (const std::string &wallet_id) const
bool updateWalletMetadata (const std::string &wallet_id, const std::unordered_map< std::string, std::string > &metadata)
std::string generateAddress (const std::string &wallet_id, const std::unordered_map< std::string, std::string > &metadata={})
bool removeAddress (const std::string &wallet_id, const std::string &address)
std::optional< AddressInfo > getAddressInfo (const std::string &wallet_id, const std::string &address) const
std::vector< std::string > listAddresses (const std::string &wallet_id) const
bool updateAddressMetadata (const std::string &wallet_id, const std::string &address, const std::unordered_map< std::string, std::string > &metadata)
std::string createTransaction (const std::string &wallet_id, const std::string &from_address, const std::string &to_address, uint64_t amount, uint64_t fee, const std::unordered_map< std::string, std::string > &metadata={})
bool signTransaction (const std::string &wallet_id, const std::string &txid, const std::string &password)
bool broadcastTransaction (const std::string &wallet_id, const std::string &txid)
std::optional< TransactionInfo > getTransactionInfo (const std::string &wallet_id, const std::string &txid) const
std::vector< std::string > listTransactions (const std::string &wallet_id) const
bool updateTransactionMetadata (const std::string &wallet_id, const std::string &txid, const std::unordered_map< std::string, std::string > &metadata)
uint64_t getBalance (const std::string &wallet_id, const std::string &address) const
uint64_t getTotalBalance (const std::string &wallet_id) const
bool backupWallet (const std::string &wallet_id, const std::string &backup_path)
bool restoreWallet (const std::string &backup_path, const std::string &password)
bool verifyBackup (const std::string &backup_path) const
std::optional< WalletStatistics > getStatistics () const
void registerWalletCallback (WalletCallback callback)
void registerAddressCallback (AddressCallback callback)
void registerTransactionCallback (TransactionCallback callback)
void registerErrorCallback (ErrorCallback callback)
void registerProgressCallback (ProgressCallback callback)
WalletManager ()
~WalletManager ()
bool initialize ()
void shutdown ()
bool isInitialized () const
bool isHealthy () const
std::string createWallet (const std::string &name)
std::string createMultisigWallet (const std::string &name, uint32_t requiredSignatures, const std::vector< std::string > &cosigners)
std::string importWalletFromMnemonic (const std::string &mnemonic, const std::string &name)
std::string importWalletFromPrivateKey (const std::vector< uint8_t > &privateKey, const std::string &name)
bool exportWallet (const std::string &walletId, std::string &mnemonic)
bool deleteWallet (const std::string &walletId)
bool lockWallet (const std::string &walletId)
bool unlockWallet (const std::string &walletId, const std::string &password)
Status getWalletStatus (const std::string &walletId) const
bool getWallet (const std::string &walletId, Wallet &wallet) const
std::vector< HardwareWallet > listHardwareWallets () const
bool connectHardwareWallet (const std::string &walletId)
bool disconnectHardwareWallet (const std::string &walletId)
bool isHardwareWalletConnected (const std::string &walletId) const
bool getHardwareWalletInfo (const std::string &walletId, HardwareWallet &wallet) const
bool signWithHardwareWallet (const std::string &walletId, const std::vector< uint8_t > &data, std::vector< uint8_t > &signature)
bool createMultisigTransaction (const std::string &walletId, const std::vector< std::string > &inputs, const std::vector< std::string > &outputs, uint64_t amount, const std::string &assetName, MultisigTransaction &transaction)
bool signMultisigTransaction (const std::string &walletId, const std::string &txid, std::vector< uint8_t > &signature)
bool verifyMultisigTransaction (const MultisigTransaction &transaction) const
bool broadcastMultisigTransaction (const std::string &txid)
std::vector< MultisigTransaction > getPendingMultisigTransactions (const std::string &walletId) const
bool deriveKeyPair (const std::string &walletId, KeyPair &keyPair)
bool deriveHardwareKeyPair (const std::string &walletId, uint32_t index, KeyPair &keyPair)
bool validateAddress (const std::string &address) const
std::string deriveAddress (const std::vector< uint8_t > &publicKey) const
bool signMessage (const std::string &walletId, const std::string &message, std::vector< uint8_t > &signature)
bool verifySignature (const std::string &address, const std::string &message, const std::vector< uint8_t > &signature) const
bool backupKeys (const std::string &walletId, const std::string &backupPath)
bool restoreKeys (const std::string &walletId, const std::string &backupPath)
bool createAsset (const std::string &walletId, const Asset &asset)
bool transferAsset (const std::string &walletId, const std::string &assetName, const std::string &toAddress, uint64_t amount)
bool getAssetBalance (const std::string &walletId, const std::string &assetName, uint64_t &balance)
std::vector< Asset > getWalletAssets (const std::string &walletId)
bool addIPFSData (const std::string &walletId, const std::vector< uint8_t > &data, std::string &hash)
bool getIPFSData (const std::string &hash, std::vector< uint8_t > &data)
bool pinIPFSData (const std::string &walletId, const std::string &hash)
bool unpinIPFSData (const std::string &walletId, const std::string &hash)
std::vector< IPFSData > getWalletIPFSData (const std::string &walletId)
void registerCallback (WalletCallback callback)
void unregisterCallback (WalletCallback callback)
void registerHardwareWalletCallback (HardwareWalletCallback callback)
void unregisterHardwareWalletCallback (HardwareWalletCallback callback)
void registerTransactionCallback (TransactionCallback callback)
void unregisterTransactionCallback (TransactionCallback callback)
std::string getLastError () const
void clearLastError ()
Static Public Member Functions
static WalletManager & getInstance ()
Detailed Description
Definition at line 90 of file wallet_manager.hpp.
Member Typedef Documentation
AddressCallback
using satox::wallet::WalletManager::AddressCallback = std::function<void(const std::string&, const AddressInfo&)>
Definition at line 93 of file wallet_manager.hpp.
ErrorCallback
using satox::wallet::WalletManager::ErrorCallback = std::function<void(const std::string&)>
Definition at line 95 of file wallet_manager.hpp.
HardwareWalletCallback
using satox::wallet::WalletManager::HardwareWalletCallback = std::function<void(const HardwareWallet&, bool)>
Definition at line 149 of file wallet_manager.hpp.
ProgressCallback
using satox::wallet::WalletManager::ProgressCallback = std::function<void(const std::string&, uint32_t)>
Definition at line 96 of file wallet_manager.hpp.
TransactionCallback [1/2]
using satox::wallet::WalletManager::TransactionCallback = std::function<void(const std::string&, const TransactionInfo&)>
Definition at line 94 of file wallet_manager.hpp.
TransactionCallback [2/2]
using satox::wallet::WalletManager::TransactionCallback = std::function<void(const MultisigTransaction&)>
Definition at line 150 of file wallet_manager.hpp.
WalletCallback [1/2]
using satox::wallet::WalletManager::WalletCallback = std::function<void(const std::string&, const WalletInfo&)>
Definition at line 92 of file wallet_manager.hpp.
WalletCallback [2/2]
using satox::wallet::WalletManager::WalletCallback = std::function<void(const Wallet&, Status)>
Definition at line 148 of file wallet_manager.hpp.
Member Enumeration Documentation
HardwareWalletType
enum class satox::wallet::WalletManager::HardwareWalletType strong
Enumerator
LEDGER
TREZOR
COLD_CARD
BITBOX
UNKNOWN
Definition at line 139 of file wallet_manager.hpp.
Status
enum class satox::wallet::WalletManager::Status strong
Enumerator
ACTIVE
LOCKED
DISABLED
PENDING_SIGNATURE
EXPIRED
Definition at line 130 of file wallet_manager.hpp.
Constructor & Destructor Documentation
WalletManager() [1/2]
satox::wallet::WalletManager::WalletManager ()
Definition at line 176 of file wallet_manager.cpp.
Referenced by getInstance(), and ~WalletManager().
~WalletManager() [1/2]
satox::wallet::WalletManager::~WalletManager ()
Definition at line 177 of file wallet_manager.cpp.
WalletManager() [2/2]
satox::wallet::WalletManager::WalletManager ()
~WalletManager() [2/2]
satox::wallet::WalletManager::~WalletManager ()
References WalletManager().
Member Function Documentation
addIPFSData()
bool satox::wallet::WalletManager::addIPFSData (const std::string & walletId, const std::vector< uint8_t > & data, std::string & hash)
Definition at line 1126 of file wallet_manager.cpp.
backupKeys()
bool satox::wallet::WalletManager::backupKeys (const std::string & walletId, const std::string & backupPath)
Definition at line 1612 of file wallet_manager.cpp.
backupWallet()
bool satox::wallet::WalletManager::backupWallet (const std::string & wallet_id, const std::string & backup_path)
broadcastMultisigTransaction()
bool satox::wallet::WalletManager::broadcastMultisigTransaction (const std::string & txid)
Definition at line 1467 of file wallet_manager.cpp.
References verifyMultisigTransaction().
broadcastTransaction()
bool satox::wallet::WalletManager::broadcastTransaction (const std::string & wallet_id, const std::string & txid)
clearLastError()
void satox::wallet::WalletManager::clearLastError ()
Definition at line 539 of file wallet_manager.cpp.
connectHardwareWallet()
bool satox::wallet::WalletManager::connectHardwareWallet (const std::string & walletId)
Definition at line 1677 of file wallet_manager.cpp.
createAsset()
bool satox::wallet::WalletManager::createAsset (const std::string & walletId, const Asset & asset)
Definition at line 984 of file wallet_manager.cpp.
createMultisigTransaction()
bool satox::wallet::WalletManager::createMultisigTransaction (const std::string & walletId, const std::vector< std::string > & inputs, const std::vector< std::string > & outputs, uint64_t amount, const std::string & assetName, MultisigTransaction & transaction)
Definition at line 1361 of file wallet_manager.cpp.
References satox::wallet::WalletManager::MultisigTransaction::amount, satox::wallet::WalletManager::MultisigTransaction::assetName, satox::wallet::WalletManager::MultisigTransaction::createdAt, satox::wallet::WalletManager::MultisigTransaction::currentSignatures, satox::wallet::WalletManager::MultisigTransaction::expiresAt, satox::wallet::WalletManager::MultisigTransaction::inputs, satox::wallet::WalletManager::MultisigTransaction::outputs, satox::wallet::WalletManager::MultisigTransaction::requiredSignatures, satox::wallet::WalletManager::MultisigTransaction::txid, and satox::wallet::WalletManager::MultisigTransaction::walletId.
createMultisigWallet()
std::string satox::wallet::WalletManager::createMultisigWallet (const std::string & name, uint32_t requiredSignatures, const std::vector< std::string > & cosigners)
Definition at line 1294 of file wallet_manager.cpp.
References ACTIVE, and satox::wallet::WalletManager::KeyPair::publicKey.
createTransaction()
std::string satox::wallet::WalletManager::createTransaction (const std::string & wallet_id, const std::string & from_address, const std::string & to_address, uint64_t amount, uint64_t fee, const std::unordered_map< std::string, std::string > & metadata = {})
createWallet() [1/2]
std::string satox::wallet::WalletManager::createWallet (const std::string & name)
Definition at line 235 of file wallet_manager.cpp.
References ACTIVE, and satox::wallet::WalletManager::KeyPair::publicKey.
createWallet() [2/2]
std::string satox::wallet::WalletManager::createWallet (const std::string & name, const std::string & password, const std::unordered_map< std::string, std::string > & metadata = {})
deleteWallet()
bool satox::wallet::WalletManager::deleteWallet (const std::string & walletId)
Definition at line 372 of file wallet_manager.cpp.
deriveAddress()
std::string satox::wallet::WalletManager::deriveAddress (const std::vector< uint8_t > & publicKey) const
Definition at line 501 of file wallet_manager.cpp.
deriveHardwareKeyPair()
bool satox::wallet::WalletManager::deriveHardwareKeyPair (const std::string & walletId, uint32_t index, KeyPair & keyPair)
deriveKeyPair()
bool satox::wallet::WalletManager::deriveKeyPair (const std::string & walletId, KeyPair & keyPair)
Definition at line 434 of file wallet_manager.cpp.
Referenced by signMessage().
disconnectHardwareWallet()
bool satox::wallet::WalletManager::disconnectHardwareWallet (const std::string & walletId)
Definition at line 1699 of file wallet_manager.cpp.
exportWallet()
bool satox::wallet::WalletManager::exportWallet (const std::string & walletId, std::string & mnemonic)
Definition at line 364 of file wallet_manager.cpp.
generateAddress()
std::string satox::wallet::WalletManager::generateAddress (const std::string & wallet_id, const std::unordered_map< std::string, std::string > & metadata = {})
getAddressInfo()
std::optional< AddressInfo > satox::wallet::WalletManager::getAddressInfo (const std::string & wallet_id, const std::string & address) const
getAssetBalance()
bool satox::wallet::WalletManager::getAssetBalance (const std::string & walletId, const std::string & assetName, uint64_t & balance)
Definition at line 1065 of file wallet_manager.cpp.
getBalance()
uint64_t satox::wallet::WalletManager::getBalance (const std::string & wallet_id, const std::string & address) const
getHardwareWalletInfo()
bool satox::wallet::WalletManager::getHardwareWalletInfo (const std::string & walletId, HardwareWallet & wallet) const
Definition at line 1723 of file wallet_manager.cpp.
getInstance()
WalletManager & satox::wallet::WalletManager::getInstance () static
Definition at line 171 of file wallet_manager.cpp.
References WalletManager().
getIPFSData()
bool satox::wallet::WalletManager::getIPFSData (const std::string & hash, std::vector< uint8_t > & data)
Definition at line 1159 of file wallet_manager.cpp.
getLastError() [1/2]
std::string satox::wallet::WalletManager::getLastError () const
Definition at line 535 of file wallet_manager.cpp.
getLastError() [2/2]
std::string satox::wallet::WalletManager::getLastError () const
References satox::wallet::ACCOUNT_INDEX.
getPendingMultisigTransactions()
std::vector< WalletManager::MultisigTransaction > satox::wallet::WalletManager::getPendingMultisigTransactions (const std::string & walletId) const
Definition at line 1488 of file wallet_manager.cpp.
References satox::wallet::WalletManager::MultisigTransaction::currentSignatures, and satox::wallet::WalletManager::MultisigTransaction::requiredSignatures.
getStatistics()
std::optional< WalletStatistics > satox::wallet::WalletManager::getStatistics () const
getTotalBalance()
uint64_t satox::wallet::WalletManager::getTotalBalance (const std::string & wallet_id) const
getTransactionInfo()
std::optional< TransactionInfo > satox::wallet::WalletManager::getTransactionInfo (const std::string & wallet_id, const std::string & txid) const
getWallet()
bool satox::wallet::WalletManager::getWallet (const std::string & walletId, Wallet & wallet) const
Definition at line 427 of file wallet_manager.cpp.
getWalletAssets()
std::vector< WalletManager::Asset > satox::wallet::WalletManager::getWalletAssets (const std::string & walletId)
Definition at line 1094 of file wallet_manager.cpp.
getWalletInfo()
std::optional< WalletInfo > satox::wallet::WalletManager::getWalletInfo (const std::string & wallet_id) const
getWalletIPFSData()
std::vector< WalletManager::IPFSData > satox::wallet::WalletManager::getWalletIPFSData (const std::string & walletId)
Definition at line 1231 of file wallet_manager.cpp.
References satox::wallet::WalletManager::IPFSData::data, satox::wallet::WalletManager::IPFSData::hash, satox::wallet::WalletManager::IPFSData::metadata, and satox::wallet::WalletManager::IPFSData::owner.
getWalletStatus()
WalletManager::Status satox::wallet::WalletManager::getWalletStatus (const std::string & walletId) const
Definition at line 423 of file wallet_manager.cpp.
References ACTIVE.
importWallet()
bool satox::wallet::WalletManager::importWallet (const std::string & name, const std::string & mnemonic, const std::string & password, const std::unordered_map< std::string, std::string > & metadata = {})
importWalletFromMnemonic()
std::string satox::wallet::WalletManager::importWalletFromMnemonic (const std::string & mnemonic, const std::string & name)
Definition at line 276 of file wallet_manager.cpp.
References ACTIVE, and satox::wallet::WalletManager::KeyPair::publicKey.
importWalletFromPrivateKey()
std::string satox::wallet::WalletManager::importWalletFromPrivateKey (const std::vector< uint8_t > & privateKey, const std::string & name)
Definition at line 313 of file wallet_manager.cpp.
References ACTIVE.
initialize() [1/2]
bool satox::wallet::WalletManager::initialize ()
Definition at line 179 of file wallet_manager.cpp.
initialize() [2/2]
bool satox::wallet::WalletManager::initialize (const WalletConfig & config)
isHardwareWalletConnected()
bool satox::wallet::WalletManager::isHardwareWalletConnected (const std::string & walletId) const
Definition at line 1712 of file wallet_manager.cpp.
isHealthy()
bool satox::wallet::WalletManager::isHealthy () const
Definition at line 213 of file wallet_manager.cpp.
isInitialized()
bool satox::wallet::WalletManager::isInitialized () const
Definition at line 208 of file wallet_manager.cpp.
isWalletLocked()
bool satox::wallet::WalletManager::isWalletLocked (const std::string & wallet_id) const
listAddresses()
std::vector< std::string > satox::wallet::WalletManager::listAddresses (const std::string & wallet_id) const
listHardwareWallets()
std::vector< WalletManager::HardwareWallet > satox::wallet::WalletManager::listHardwareWallets () const
Definition at line 1667 of file wallet_manager.cpp.
listTransactions()
std::vector< std::string > satox::wallet::WalletManager::listTransactions (const std::string & wallet_id) const
listWallets()
std::vector< std::string > satox::wallet::WalletManager::listWallets () const
lockWallet() [1/2]
bool satox::wallet::WalletManager::lockWallet (const std::string & wallet_id)
Definition at line 377 of file wallet_manager.cpp.
References LOCKED.
lockWallet() [2/2]
bool satox::wallet::WalletManager::lockWallet (const std::string & walletId)
pinIPFSData()
bool satox::wallet::WalletManager::pinIPFSData (const std::string & walletId, const std::string & hash)
Definition at line 1183 of file wallet_manager.cpp.
registerAddressCallback()
void satox::wallet::WalletManager::registerAddressCallback (AddressCallback callback)
registerCallback()
void satox::wallet::WalletManager::registerCallback (WalletCallback callback)
Definition at line 527 of file wallet_manager.cpp.
registerErrorCallback()
void satox::wallet::WalletManager::registerErrorCallback (ErrorCallback callback)
registerHardwareWalletCallback()
void satox::wallet::WalletManager::registerHardwareWalletCallback (HardwareWalletCallback callback)
registerProgressCallback()
void satox::wallet::WalletManager::registerProgressCallback (ProgressCallback callback)
registerTransactionCallback() [1/2]
void satox::wallet::WalletManager::registerTransactionCallback (TransactionCallback callback)
registerTransactionCallback() [2/2]
void satox::wallet::WalletManager::registerTransactionCallback (TransactionCallback callback)
registerWalletCallback()
void satox::wallet::WalletManager::registerWalletCallback (WalletCallback callback)
removeAddress()
bool satox::wallet::WalletManager::removeAddress (const std::string & wallet_id, const std::string & address)
removeWallet()
bool satox::wallet::WalletManager::removeWallet (const std::string & wallet_id)
restoreKeys()
bool satox::wallet::WalletManager::restoreKeys (const std::string & walletId, const std::string & backupPath)
Definition at line 1641 of file wallet_manager.cpp.
restoreWallet()
bool satox::wallet::WalletManager::restoreWallet (const std::string & backup_path, const std::string & password)
shutdown() [1/2]
void satox::wallet::WalletManager::shutdown ()
Definition at line 198 of file wallet_manager.cpp.
shutdown() [2/2]
void satox::wallet::WalletManager::shutdown ()
signMessage()
bool satox::wallet::WalletManager::signMessage (const std::string & walletId, const std::string & message, std::vector< uint8_t > & signature)
Definition at line 891 of file wallet_manager.cpp.
References deriveKeyPair(), and satox::wallet::WalletManager::KeyPair::privateKey.
Referenced by signMultisigTransaction().
signMultisigTransaction()
bool satox::wallet::WalletManager::signMultisigTransaction (const std::string & walletId, const std::string & txid, std::vector< uint8_t > & signature)
Definition at line 1402 of file wallet_manager.cpp.
References signMessage().
signTransaction()
bool satox::wallet::WalletManager::signTransaction (const std::string & wallet_id, const std::string & txid, const std::string & password)
signWithHardwareWallet()
bool satox::wallet::WalletManager::signWithHardwareWallet (const std::string & walletId, const std::vector< uint8_t > & data, std::vector< uint8_t > & signature)
Definition at line 1588 of file wallet_manager.cpp.
transferAsset()
bool satox::wallet::WalletManager::transferAsset (const std::string & walletId, const std::string & assetName, const std::string & toAddress, uint64_t amount)
Definition at line 1019 of file wallet_manager.cpp.
unlockWallet() [1/2]
bool satox::wallet::WalletManager::unlockWallet (const std::string & wallet_id, const std::string & password)
Definition at line 398 of file wallet_manager.cpp.
References ACTIVE.
unlockWallet() [2/2]
bool satox::wallet::WalletManager::unlockWallet (const std::string & walletId, const std::string & password)
unpinIPFSData()
bool satox::wallet::WalletManager::unpinIPFSData (const std::string & walletId, const std::string & hash)
Definition at line 1205 of file wallet_manager.cpp.
unregisterCallback()
void satox::wallet::WalletManager::unregisterCallback (WalletCallback callback)
Definition at line 531 of file wallet_manager.cpp.
unregisterHardwareWalletCallback()
void satox::wallet::WalletManager::unregisterHardwareWalletCallback (HardwareWalletCallback callback)
unregisterTransactionCallback()
void satox::wallet::WalletManager::unregisterTransactionCallback (TransactionCallback callback)
updateAddressMetadata()
bool satox::wallet::WalletManager::updateAddressMetadata (const std::string & wallet_id, const std::string & address, const std::unordered_map< std::string, std::string > & metadata)
updateTransactionMetadata()
bool satox::wallet::WalletManager::updateTransactionMetadata (const std::string & wallet_id, const std::string & txid, const std::unordered_map< std::string, std::string > & metadata)
updateWalletMetadata()
bool satox::wallet::WalletManager::updateWalletMetadata (const std::string & wallet_id, const std::unordered_map< std::string, std::string > & metadata)
validateAddress()
bool satox::wallet::WalletManager::validateAddress (const std::string & address) const
verifyBackup()
bool satox::wallet::WalletManager::verifyBackup (const std::string & backup_path) const
verifyMultisigTransaction()
bool satox::wallet::WalletManager::verifyMultisigTransaction (const MultisigTransaction & transaction) const
Definition at line 1437 of file wallet_manager.cpp.
References satox::wallet::WalletManager::MultisigTransaction::amount, satox::wallet::WalletManager::MultisigTransaction::assetName, satox::wallet::WalletManager::MultisigTransaction::currentSignatures, satox::wallet::WalletManager::MultisigTransaction::requiredSignatures, satox::wallet::WalletManager::MultisigTransaction::signatures, and satox::wallet::WalletManager::MultisigTransaction::txid.
Referenced by broadcastMultisigTransaction().
verifySignature()
bool satox::wallet::WalletManager::verifySignature (const std::string & address, const std::string & message, const std::vector< uint8_t > & signature) const
Definition at line 932 of file wallet_manager.cpp.
The documentation for this class was generated from the following files:
src/core/include/satox/wallet/wallet_manager.hpp
src/wallet/include/satox/wallet/wallet_manager.hpp
src/wallet/src/wallet_manager.cpp