SATOX SDK: satox::wallet::AddressManager Class Reference
satox::wallet::AddressManager Class Reference
#include <address_manager.hpp>
Classes
struct AddressInfo
struct Error
Public Member Functions
AddressManager (const AddressManager &)=delete
AddressManager & operator= (const AddressManager &)=delete
bool initialize ()
void shutdown ()
std::string generateAddress (const std::vector< uint8_t > &publicKey)
std::string generateSegWitAddress (const std::vector< uint8_t > &publicKey)
std::string generateMultiSigAddress (const std::vector< std::vector< uint8_t > > &publicKeys, int requiredSignatures)
bool validateAddress (const std::string &address)
bool validateSegWitAddress (const std::string &address)
bool validateMultiSigAddress (const std::string &address)
std::string toLegacyAddress (const std::string &address)
std::string toSegWitAddress (const std::string &address)
std::string toMultiSigAddress (const std::string &address)
AddressInfo getAddressInfo (const std::string &address)
std::string deriveAddress (const std::vector< uint8_t > &publicKey, uint32_t purpose, uint32_t coinType, uint32_t account, uint32_t change, uint32_t addressIndex)
std::string deriveSegWitAddress (const std::vector< uint8_t > &publicKey, uint32_t purpose, uint32_t coinType, uint32_t account, uint32_t change, uint32_t addressIndex)
std::string deriveMultiSigAddress (const std::vector< std::vector< uint8_t > > &publicKeys, int requiredSignatures, uint32_t purpose, uint32_t coinType, uint32_t account, uint32_t change, uint32_t addressIndex)
void cacheAddress (const std::string &address, const AddressInfo &info)
void removeCachedAddress (const std::string &address)
AddressInfo getCachedAddress (const std::string &address)
void clearAddressCache ()
Error getLastError () const
void clearLastError ()
Static Public Member Functions
static AddressManager & getInstance ()
Detailed Description
Definition at line 44 of file address_manager.hpp.
Constructor & Destructor Documentation
AddressManager()
satox::wallet::AddressManager::AddressManager (const AddressManager &) delete
References AddressManager().
Referenced by AddressManager(), getInstance(), and operator=().
Member Function Documentation
cacheAddress()
void satox::wallet::AddressManager::cacheAddress (const std::string & address, const AddressInfo & info)
Definition at line 330 of file address_manager.cpp.
Referenced by getAddressInfo().
clearAddressCache()
void satox::wallet::AddressManager::clearAddressCache ()
Definition at line 349 of file address_manager.cpp.
clearLastError()
void satox::wallet::AddressManager::clearLastError ()
Definition at line 358 of file address_manager.cpp.
deriveAddress()
std::string satox::wallet::AddressManager::deriveAddress (const std::vector< uint8_t > & publicKey, uint32_t purpose, uint32_t coinType, uint32_t account, uint32_t change, uint32_t addressIndex)
Definition at line 318 of file address_manager.cpp.
References generateAddress().
deriveMultiSigAddress()
std::string satox::wallet::AddressManager::deriveMultiSigAddress (const std::vector< std::vector< uint8_t > > & publicKeys, int requiredSignatures, uint32_t purpose, uint32_t coinType, uint32_t account, uint32_t change, uint32_t addressIndex)
Definition at line 326 of file address_manager.cpp.
References generateMultiSigAddress().
deriveSegWitAddress()
std::string satox::wallet::AddressManager::deriveSegWitAddress (const std::vector< uint8_t > & publicKey, uint32_t purpose, uint32_t coinType, uint32_t account, uint32_t change, uint32_t addressIndex)
Definition at line 322 of file address_manager.cpp.
References generateSegWitAddress().
generateAddress()
std::string satox::wallet::AddressManager::generateAddress (const std::vector< uint8_t > & publicKey)
Definition at line 69 of file address_manager.cpp.
Referenced by deriveAddress().
generateMultiSigAddress()
std::string satox::wallet::AddressManager::generateMultiSigAddress (const std::vector< std::vector< uint8_t > > & publicKeys, int requiredSignatures)
Definition at line 123 of file address_manager.cpp.
Referenced by deriveMultiSigAddress().
generateSegWitAddress()
std::string satox::wallet::AddressManager::generateSegWitAddress (const std::vector< uint8_t > & publicKey)
Definition at line 100 of file address_manager.cpp.
Referenced by deriveSegWitAddress().
getAddressInfo()
AddressManager::AddressInfo satox::wallet::AddressManager::getAddressInfo (const std::string & address)
Definition at line 276 of file address_manager.cpp.
References satox::wallet::AddressManager::AddressInfo::address, cacheAddress(), satox::wallet::AddressManager::AddressInfo::scriptHash, satox::wallet::AddressManager::AddressInfo::type, validateAddress(), and validateSegWitAddress().
getCachedAddress()
AddressManager::AddressInfo satox::wallet::AddressManager::getCachedAddress (const std::string & address)
Definition at line 340 of file address_manager.cpp.
getInstance()
AddressManager & satox::wallet::AddressManager::getInstance () static
Definition at line 39 of file address_manager.cpp.
References AddressManager().
getLastError()
AddressManager::Error satox::wallet::AddressManager::getLastError () const
Definition at line 354 of file address_manager.cpp.
initialize()
bool satox::wallet::AddressManager::initialize ()
Definition at line 44 of file address_manager.cpp.
operator=()
AddressManager & satox::wallet::AddressManager::operator= (const AddressManager &) delete
References AddressManager().
removeCachedAddress()
void satox::wallet::AddressManager::removeCachedAddress (const std::string & address)
Definition at line 335 of file address_manager.cpp.
shutdown()
void satox::wallet::AddressManager::shutdown ()
Definition at line 57 of file address_manager.cpp.
toLegacyAddress()
std::string satox::wallet::AddressManager::toLegacyAddress (const std::string & address)
Definition at line 203 of file address_manager.cpp.
References validateSegWitAddress().
toMultiSigAddress()
std::string satox::wallet::AddressManager::toMultiSigAddress (const std::string & address)
Definition at line 270 of file address_manager.cpp.
toSegWitAddress()
std::string satox::wallet::AddressManager::toSegWitAddress (const std::string & address)
Definition at line 240 of file address_manager.cpp.
References validateAddress().
validateAddress()
bool satox::wallet::AddressManager::validateAddress (const std::string & address)
Definition at line 157 of file address_manager.cpp.
Referenced by getAddressInfo(), toSegWitAddress(), and validateMultiSigAddress().
validateMultiSigAddress()
bool satox::wallet::AddressManager::validateMultiSigAddress (const std::string & address)
Definition at line 199 of file address_manager.cpp.
References validateAddress().
validateSegWitAddress()
bool satox::wallet::AddressManager::validateSegWitAddress (const std::string & address)
Definition at line 182 of file address_manager.cpp.
Referenced by getAddressInfo(), and toLegacyAddress().
The documentation for this class was generated from the following files:
src/wallet/include/satox/wallet/address_manager.hpp
src/wallet/src/address_manager.cpp