SATOX SDK: satox::core::PluginManager Class Reference
satox::core::PluginManager Class Reference
#include <plugin_manager.hpp>
Classes
class IPlugin
class IPluginFactory
struct PluginConfig
struct PluginInfo
struct PluginStats
Public Types
enum class PluginState {
UNLOADED , LOADED , INITIALIZED , RUNNING ,
PAUSED , ERROR
}
enum class PluginType {
CORE , NETWORK , BLOCKCHAIN , WALLET ,
TRANSACTION , ASSET , NFT , IPFS ,
DATABASE , CACHE , CONFIG , SECURITY ,
CUSTOM
}
using PluginStateCallback = std::function<void(const std::string&, PluginState)>
using PluginErrorCallback = std::function<void(const std::string&, const std::string&)>
using PluginConfigCallback = std::function<void(const std::string&, const nlohmann::json&)>
Public Member Functions
PluginManager (const PluginManager &)=delete
PluginManager & operator= (const PluginManager &)=delete
bool initialize (const PluginConfig &config)
void shutdown ()
bool loadPlugin (const std::string &pluginPath)
bool unloadPlugin (const std::string &pluginName)
bool reloadPlugin (const std::string &pluginName)
bool isPluginLoaded (const std::string &pluginName) const
bool initializePlugin (const std::string &pluginName)
bool startPlugin (const std::string &pluginName)
bool stopPlugin (const std::string &pluginName)
bool pausePlugin (const std::string &pluginName)
bool resumePlugin (const std::string &pluginName)
bool updatePlugin (const std::string &pluginName, const nlohmann::json &config)
std::vector< PluginInfo > getPluginInfo () const
PluginInfo getPluginInfo (const std::string &pluginName) const
PluginState getPluginState (const std::string &pluginName) const
std::string getPluginError (const std::string &pluginName) const
std::vector< std::string > discoverPlugins () const
bool scanPluginDirectory ()
bool validatePlugin (const std::string &pluginPath) const
bool checkDependencies (const std::string &pluginName) const
bool resolveDependencies (const std::string &pluginName)
std::vector< std::string > getDependencies (const std::string &pluginName) const
std::vector< std::string > getDependents (const std::string &pluginName) const
bool setPluginConfig (const std::string &pluginName, const nlohmann::json &config)
nlohmann::json getPluginConfig (const std::string &pluginName) const
bool validatePluginConfig (const std::string &pluginName, const nlohmann::json &config) const
void registerStateCallback (PluginStateCallback callback)
void registerErrorCallback (PluginErrorCallback callback)
void registerConfigCallback (PluginConfigCallback callback)
void unregisterStateCallback ()
void unregisterErrorCallback ()
void unregisterConfigCallback ()
PluginStats getStats () const
void resetStats ()
void enableStats (bool enable)
std::string getLastError () const
void clearLastError ()
Static Public Member Functions
static PluginManager & getInstance ()
Detailed Description
Definition at line 40 of file plugin_manager.hpp.
Member Typedef Documentation
PluginConfigCallback
using satox::core::PluginManager::PluginConfigCallback = std::function<void(const std::string&, const nlohmann::json&)>
Definition at line 119 of file plugin_manager.hpp.
PluginErrorCallback
using satox::core::PluginManager::PluginErrorCallback = std::function<void(const std::string&, const std::string&)>
Definition at line 118 of file plugin_manager.hpp.
PluginStateCallback
using satox::core::PluginManager::PluginStateCallback = std::function<void(const std::string&, PluginState)>
Definition at line 117 of file plugin_manager.hpp.
Member Enumeration Documentation
PluginState
enum class satox::core::PluginManager::PluginState strong
Enumerator
UNLOADED
LOADED
INITIALIZED
RUNNING
PAUSED
ERROR
Definition at line 43 of file plugin_manager.hpp.
PluginType
enum class satox::core::PluginManager::PluginType strong
Enumerator
CORE
NETWORK
BLOCKCHAIN
WALLET
TRANSACTION
ASSET
NFT
IPFS
DATABASE
CACHE
CONFIG
SECURITY
CUSTOM
Definition at line 53 of file plugin_manager.hpp.
Constructor & Destructor Documentation
PluginManager()
satox::core::PluginManager::PluginManager (const PluginManager &) delete
References PluginManager().
Referenced by getInstance(), operator=(), and PluginManager().
Member Function Documentation
checkDependencies()
bool satox::core::PluginManager::checkDependencies (const std::string & pluginName) const
Definition at line 464 of file plugin_manager.cpp.
References RUNNING.
Referenced by initializePlugin().
clearLastError()
void satox::core::PluginManager::clearLastError ()
Definition at line 643 of file plugin_manager.cpp.
discoverPlugins()
std::vector< std::string > satox::core::PluginManager::discoverPlugins () const
Definition at line 396 of file plugin_manager.cpp.
Referenced by scanPluginDirectory().
enableStats()
void satox::core::PluginManager::enableStats (bool enable)
Definition at line 633 of file plugin_manager.cpp.
getDependencies()
std::vector< std::string > satox::core::PluginManager::getDependencies (const std::string & pluginName) const
Definition at line 518 of file plugin_manager.cpp.
getDependents()
std::vector< std::string > satox::core::PluginManager::getDependents (const std::string & pluginName) const
Definition at line 529 of file plugin_manager.cpp.
getInstance()
PluginManager & satox::core::PluginManager::getInstance () static
Definition at line 34 of file plugin_manager.cpp.
References PluginManager().
Referenced by satox::core::SatoxManager::getPluginManager().
getLastError()
std::string satox::core::PluginManager::getLastError () const
Definition at line 638 of file plugin_manager.cpp.
getPluginConfig()
nlohmann::json satox::core::PluginManager::getPluginConfig (const std::string & pluginName) const
Definition at line 566 of file plugin_manager.cpp.
Referenced by initializePlugin().
getPluginError()
std::string satox::core::PluginManager::getPluginError (const std::string & pluginName) const
Definition at line 387 of file plugin_manager.cpp.
getPluginInfo() [1/2]
std::vector< PluginManager::PluginInfo > satox::core::PluginManager::getPluginInfo () const
Definition at line 357 of file plugin_manager.cpp.
getPluginInfo() [2/2]
PluginManager::PluginInfo satox::core::PluginManager::getPluginInfo (const std::string & pluginName) const
Definition at line 367 of file plugin_manager.cpp.
getPluginState()
PluginManager::PluginState satox::core::PluginManager::getPluginState (const std::string & pluginName) const
Definition at line 377 of file plugin_manager.cpp.
References UNLOADED.
getStats()
PluginManager::PluginStats satox::core::PluginManager::getStats () const
Definition at line 623 of file plugin_manager.cpp.
initialize()
bool satox::core::PluginManager::initialize (const PluginConfig & config)
Definition at line 39 of file plugin_manager.cpp.
References scanPluginDirectory().
initializePlugin()
bool satox::core::PluginManager::initializePlugin (const std::string & pluginName)
Definition at line 174 of file plugin_manager.cpp.
References checkDependencies(), getPluginConfig(), and INITIALIZED.
Referenced by resolveDependencies().
isPluginLoaded()
bool satox::core::PluginManager::isPluginLoaded (const std::string & pluginName) const
Definition at line 169 of file plugin_manager.cpp.
Referenced by resolveDependencies().
loadPlugin()
bool satox::core::PluginManager::loadPlugin (const std::string & pluginPath)
Definition at line 86 of file plugin_manager.cpp.
References validatePlugin().
Referenced by reloadPlugin(), and scanPluginDirectory().
operator=()
PluginManager & satox::core::PluginManager::operator= (const PluginManager &) delete
References PluginManager().
pausePlugin()
bool satox::core::PluginManager::pausePlugin (const std::string & pluginName)
Definition at line 273 of file plugin_manager.cpp.
References PAUSED, and RUNNING.
registerConfigCallback()
void satox::core::PluginManager::registerConfigCallback (PluginConfigCallback callback)
Definition at line 603 of file plugin_manager.cpp.
registerErrorCallback()
void satox::core::PluginManager::registerErrorCallback (PluginErrorCallback callback)
Definition at line 598 of file plugin_manager.cpp.
registerStateCallback()
void satox::core::PluginManager::registerStateCallback (PluginStateCallback callback)
Definition at line 593 of file plugin_manager.cpp.
reloadPlugin()
bool satox::core::PluginManager::reloadPlugin (const std::string & pluginName)
Definition at line 147 of file plugin_manager.cpp.
References loadPlugin(), and unloadPlugin().
resetStats()
void satox::core::PluginManager::resetStats ()
Definition at line 628 of file plugin_manager.cpp.
resolveDependencies()
bool satox::core::PluginManager::resolveDependencies (const std::string & pluginName)
Definition at line 490 of file plugin_manager.cpp.
References initializePlugin(), isPluginLoaded(), and startPlugin().
resumePlugin()
bool satox::core::PluginManager::resumePlugin (const std::string & pluginName)
Definition at line 301 of file plugin_manager.cpp.
References PAUSED, and RUNNING.
scanPluginDirectory()
bool satox::core::PluginManager::scanPluginDirectory ()
Definition at line 407 of file plugin_manager.cpp.
References discoverPlugins(), and loadPlugin().
Referenced by initialize().
setPluginConfig()
bool satox::core::PluginManager::setPluginConfig (const std::string & pluginName, const nlohmann::json & config)
Definition at line 544 of file plugin_manager.cpp.
References updatePlugin(), and validatePluginConfig().
shutdown()
void satox::core::PluginManager::shutdown ()
Definition at line 63 of file plugin_manager.cpp.
References RUNNING.
startPlugin()
bool satox::core::PluginManager::startPlugin (const std::string & pluginName)
Definition at line 209 of file plugin_manager.cpp.
References INITIALIZED, and RUNNING.
Referenced by resolveDependencies().
stopPlugin()
bool satox::core::PluginManager::stopPlugin (const std::string & pluginName)
Definition at line 245 of file plugin_manager.cpp.
References INITIALIZED, and RUNNING.
unloadPlugin()
bool satox::core::PluginManager::unloadPlugin (const std::string & pluginName)
Definition at line 118 of file plugin_manager.cpp.
References RUNNING.
Referenced by reloadPlugin().
unregisterConfigCallback()
void satox::core::PluginManager::unregisterConfigCallback ()
Definition at line 618 of file plugin_manager.cpp.
unregisterErrorCallback()
void satox::core::PluginManager::unregisterErrorCallback ()
Definition at line 613 of file plugin_manager.cpp.
unregisterStateCallback()
void satox::core::PluginManager::unregisterStateCallback ()
Definition at line 608 of file plugin_manager.cpp.
updatePlugin()
bool satox::core::PluginManager::updatePlugin (const std::string & pluginName, const nlohmann::json & config)
Definition at line 329 of file plugin_manager.cpp.
References validatePluginConfig().
Referenced by setPluginConfig().
validatePlugin()
bool satox::core::PluginManager::validatePlugin (const std::string & pluginPath) const
Definition at line 425 of file plugin_manager.cpp.
Referenced by loadPlugin().
validatePluginConfig()
bool satox::core::PluginManager::validatePluginConfig (const std::string & pluginName, const nlohmann::json & config) const
Definition at line 578 of file plugin_manager.cpp.
Referenced by setPluginConfig(), and updatePlugin().
The documentation for this class was generated from the following files:
src/core/include/satox/core/plugin_manager.hpp
src/core/src/plugin_manager.cpp