SATOX SDK: satox::core::AssetManager Class Reference
satox::core::AssetManager Class Reference
#include <asset.h>
Classes
struct Asset
struct AssetMetadata
struct AssetStats
Public Types
enum class AssetType { TOKEN , NFT , CUSTOM }
enum class AssetState {
CREATED , ISSUED , TRANSFERRED , BURNED ,
ERROR
}
using AssetCallback = std::function<void(const std::string&, AssetState)>
using AssetMetadataCallback = std::function<void(const std::string&, const AssetMetadata&)>
using AssetErrorCallback = std::function<void(const std::string&, const std::string&)>
Public Member Functions
AssetManager ()
~AssetManager ()
AssetManager (const AssetManager &)=delete
AssetManager & operator= (const AssetManager &)=delete
AssetManager (AssetManager &&) noexcept=default
AssetManager & operator= (AssetManager &&) noexcept=default
void initialize ()
Asset createAsset (const std::string &name, const std::string &symbol, const std::string &owner, const std::string &totalSupply, const std::string &decimals="18")
bool updateAsset (const Asset &asset)
bool deleteAsset (const std::string &assetId)
Asset getAsset (const std::string &assetId)
std::vector< Asset > getAssetsByOwner (const std::string &owner)
std::vector< Asset > getAllAssets ()
bool transferAsset (const std::string &assetId, const std::string &from, const std::string &to, const std::string &amount)
std::string getAssetBalance (const std::string &assetId, const std::string &address)
bool initialize (const nlohmann::json &config)
void shutdown ()
bool createAsset (const std::string &id, const AssetMetadata &metadata)
bool issueAsset (const std::string &id)
bool transferAsset (const std::string &id, const std::string &newOwner)
bool burnAsset (const std::string &id)
bool updateAssetMetadata (const std::string &id, const AssetMetadata &metadata)
bool isAssetExists (const std::string &id) const
Asset getAsset (const std::string &id) const
std::vector< Asset > getAssetsByType (AssetType type) const
std::vector< Asset > getAssetsByOwner (const std::string &owner) const
std::vector< Asset > getAssetsByState (AssetState state) const
bool validateMetadata (const AssetMetadata &metadata) const
bool updateAssetURI (const std::string &id, const std::string &uri)
bool updateAssetHash (const std::string &id, const std::string &hash)
bool addAssetAttribute (const std::string &id, const std::string &key, const nlohmann::json &value)
bool removeAssetAttribute (const std::string &id, const std::string &key)
std::vector< std::string > getAssetHistory (const std::string &id) const
bool addAssetHistoryEntry (const std::string &id, const std::string &entry)
bool clearAssetHistory (const std::string &id)
AssetStats getStats () const
void resetStats ()
bool enableStats (bool enable)
void registerAssetCallback (AssetCallback callback)
void registerMetadataCallback (AssetMetadataCallback callback)
void registerErrorCallback (AssetErrorCallback callback)
void unregisterAssetCallback ()
void unregisterMetadataCallback ()
void unregisterErrorCallback ()
std::string getLastError () const
void clearLastError ()
Static Public Member Functions
static AssetManager & getInstance ()
Detailed Description
Definition at line 50 of file asset.h.
Member Typedef Documentation
AssetCallback
using satox::core::AssetManager::AssetCallback = std::function<void(const std::string&, AssetState)>
Definition at line 100 of file asset_manager.hpp.
AssetErrorCallback
using satox::core::AssetManager::AssetErrorCallback = std::function<void(const std::string&, const std::string&)>
Definition at line 102 of file asset_manager.hpp.
AssetMetadataCallback
using satox::core::AssetManager::AssetMetadataCallback = std::function<void(const std::string&, const AssetMetadata&)>
Definition at line 101 of file asset_manager.hpp.
Member Enumeration Documentation
AssetState
enum class satox::core::AssetManager::AssetState strong
Enumerator
CREATED
ISSUED
TRANSFERRED
BURNED
ERROR
Definition at line 49 of file asset_manager.hpp.
AssetType
enum class satox::core::AssetManager::AssetType strong
Enumerator
TOKEN
NFT
CUSTOM
Definition at line 42 of file asset_manager.hpp.
Constructor & Destructor Documentation
AssetManager() [1/3]
satox::core::AssetManager::AssetManager ()
Definition at line 35 of file asset.cpp.
Referenced by AssetManager(), AssetManager(), getInstance(), operator=(), and operator=().
~AssetManager()
satox::core::AssetManager::~AssetManager ()
Definition at line 37 of file asset.cpp.
AssetManager() [2/3]
satox::core::AssetManager::AssetManager (const AssetManager &) delete
References AssetManager().
AssetManager() [3/3]
satox::core::AssetManager::AssetManager (AssetManager &&) default noexcept
References AssetManager().
Member Function Documentation
addAssetAttribute()
bool satox::core::AssetManager::addAssetAttribute (const std::string & id, const std::string & key, const nlohmann::json & value)
Definition at line 314 of file asset_manager.cpp.
addAssetHistoryEntry()
bool satox::core::AssetManager::addAssetHistoryEntry (const std::string & id, const std::string & entry)
Definition at line 353 of file asset_manager.cpp.
burnAsset()
bool satox::core::AssetManager::burnAsset (const std::string & id)
Definition at line 174 of file asset_manager.cpp.
References BURNED.
clearAssetHistory()
bool satox::core::AssetManager::clearAssetHistory (const std::string & id)
Definition at line 366 of file asset_manager.cpp.
clearLastError()
void satox::core::AssetManager::clearLastError ()
Definition at line 430 of file asset_manager.cpp.
createAsset() [1/2]
bool satox::core::AssetManager::createAsset (const std::string & id, const AssetMetadata & metadata)
Definition at line 71 of file asset_manager.cpp.
References CREATED, and validateMetadata().
createAsset() [2/2]
Asset satox::core::AssetManager::createAsset (const std::string & name, const std::string & symbol, const std::string & owner, const std::string & totalSupply, const std::string & decimals = "18")
Definition at line 50 of file asset.cpp.
Referenced by operator=().
deleteAsset()
bool satox::core::AssetManager::deleteAsset (const std::string & assetId)
Definition at line 103 of file asset.cpp.
Referenced by operator=().
enableStats()
bool satox::core::AssetManager::enableStats (bool enable)
Definition at line 389 of file asset_manager.cpp.
getAllAssets()
std::vector< Asset > satox::core::AssetManager::getAllAssets ()
Definition at line 156 of file asset.cpp.
Referenced by operator=().
getAsset() [1/2]
Asset satox::core::AssetManager::getAsset (const std::string & assetId)
Definition at line 121 of file asset.cpp.
Referenced by operator=().
getAsset() [2/2]
AssetManager::Asset satox::core::AssetManager::getAsset (const std::string & id) const
Definition at line 235 of file asset_manager.cpp.
getAssetBalance()
std::string satox::core::AssetManager::getAssetBalance (const std::string & assetId, const std::string & address)
Definition at line 204 of file asset.cpp.
Referenced by operator=().
getAssetHistory()
std::vector< std::string > satox::core::AssetManager::getAssetHistory (const std::string & id) const
Definition at line 344 of file asset_manager.cpp.
getAssetsByOwner() [1/2]
std::vector< Asset > satox::core::AssetManager::getAssetsByOwner (const std::string & owner)
Definition at line 137 of file asset.cpp.
Referenced by operator=().
getAssetsByOwner() [2/2]
std::vector< AssetManager::Asset > satox::core::AssetManager::getAssetsByOwner (const std::string & owner) const
Definition at line 255 of file asset_manager.cpp.
getAssetsByState()
std::vector< AssetManager::Asset > satox::core::AssetManager::getAssetsByState (AssetState state) const
Definition at line 266 of file asset_manager.cpp.
getAssetsByType()
std::vector< AssetManager::Asset > satox::core::AssetManager::getAssetsByType (AssetType type) const
Definition at line 244 of file asset_manager.cpp.
getInstance()
AssetManager & satox::core::AssetManager::getInstance () static
Definition at line 34 of file asset_manager.cpp.
References AssetManager().
Referenced by satox::core::CoreManager::getAssetManager(), and satox::core::SatoxManager::getAssetManager().
getLastError()
std::string satox::core::AssetManager::getLastError () const
Definition at line 425 of file asset_manager.cpp.
getStats()
AssetManager::AssetStats satox::core::AssetManager::getStats () const
Definition at line 379 of file asset_manager.cpp.
initialize() [1/2]
void satox::core::AssetManager::initialize ()
Definition at line 43 of file asset.cpp.
Referenced by operator=().
initialize() [2/2]
bool satox::core::AssetManager::initialize (const nlohmann::json & config)
Definition at line 39 of file asset_manager.cpp.
isAssetExists()
bool satox::core::AssetManager::isAssetExists (const std::string & id) const
Definition at line 230 of file asset_manager.cpp.
issueAsset()
bool satox::core::AssetManager::issueAsset (const std::string & id)
Definition at line 110 of file asset_manager.cpp.
References CREATED, and ISSUED.
operator=() [1/2]
AssetManager & satox::core::AssetManager::operator= (AssetManager &&) default noexcept
References AssetManager(), createAsset(), deleteAsset(), getAllAssets(), getAsset(), getAssetBalance(), getAssetsByOwner(), initialize(), transferAsset(), and updateAsset().
operator=() [2/2]
AssetManager & satox::core::AssetManager::operator= (const AssetManager &) delete
References AssetManager().
registerAssetCallback()
void satox::core::AssetManager::registerAssetCallback (AssetCallback callback)
Definition at line 395 of file asset_manager.cpp.
registerErrorCallback()
void satox::core::AssetManager::registerErrorCallback (AssetErrorCallback callback)
Definition at line 405 of file asset_manager.cpp.
registerMetadataCallback()
void satox::core::AssetManager::registerMetadataCallback (AssetMetadataCallback callback)
Definition at line 400 of file asset_manager.cpp.
removeAssetAttribute()
bool satox::core::AssetManager::removeAssetAttribute (const std::string & id, const std::string & key)
Definition at line 329 of file asset_manager.cpp.
resetStats()
void satox::core::AssetManager::resetStats ()
Definition at line 384 of file asset_manager.cpp.
shutdown()
void satox::core::AssetManager::shutdown ()
Definition at line 57 of file asset_manager.cpp.
transferAsset() [1/2]
bool satox::core::AssetManager::transferAsset (const std::string & assetId, const std::string & from, const std::string & to, const std::string & amount)
Definition at line 169 of file asset.cpp.
Referenced by operator=().
transferAsset() [2/2]
bool satox::core::AssetManager::transferAsset (const std::string & id, const std::string & newOwner)
Definition at line 139 of file asset_manager.cpp.
References ISSUED, and TRANSFERRED.
unregisterAssetCallback()
void satox::core::AssetManager::unregisterAssetCallback ()
Definition at line 410 of file asset_manager.cpp.
unregisterErrorCallback()
void satox::core::AssetManager::unregisterErrorCallback ()
Definition at line 420 of file asset_manager.cpp.
unregisterMetadataCallback()
void satox::core::AssetManager::unregisterMetadataCallback ()
Definition at line 415 of file asset_manager.cpp.
updateAsset()
bool satox::core::AssetManager::updateAsset (const Asset & asset)
Definition at line 86 of file asset.cpp.
Referenced by operator=().
updateAssetHash()
bool satox::core::AssetManager::updateAssetHash (const std::string & id, const std::string & hash)
Definition at line 299 of file asset_manager.cpp.
updateAssetMetadata()
bool satox::core::AssetManager::updateAssetMetadata (const std::string & id, const AssetMetadata & metadata)
Definition at line 202 of file asset_manager.cpp.
References satox::core::AssetManager::AssetMetadata::lastModified, and validateMetadata().
updateAssetURI()
bool satox::core::AssetManager::updateAssetURI (const std::string & id, const std::string & uri)
Definition at line 284 of file asset_manager.cpp.
validateMetadata()
bool satox::core::AssetManager::validateMetadata (const AssetMetadata & metadata) const
Definition at line 277 of file asset_manager.cpp.
References satox::core::AssetManager::AssetMetadata::issuer, satox::core::AssetManager::AssetMetadata::name, satox::core::AssetManager::AssetMetadata::owner, and satox::core::AssetManager::AssetMetadata::symbol.
Referenced by createAsset(), and updateAssetMetadata().
The documentation for this class was generated from the following files:
src/core/include/satox/core/asset.h
src/core/include/satox/core/asset_manager.hpp
src/core/src/asset.cpp
src/core/src/asset_manager.cpp