SATOX SDK: satox::security::pqc::MLKEM Class Reference
satox::security::pqc::MLKEM Class Reference
#include <ml_kem.hpp>
Classes
class Impl
Public Types
enum class SecurityLevel {
Level1 = 512 , Level3 = 768 , Level5 = 1024 , Level1 = 512 ,
Level3 = 768 , Level5 = 1024
}
enum class SecurityLevel {
Level1 = 512 , Level3 = 768 , Level5 = 1024 , Level1 = 512 ,
Level3 = 768 , Level5 = 1024
}
Public Member Functions
MLKEM (SecurityLevel level=SecurityLevel::Level3)
~MLKEM ()
bool generateKeyPair (std::vector< uint8_t > &publicKey, std::vector< uint8_t > &privateKey)
bool encapsulate (const std::vector< uint8_t > &publicKey, std::vector< uint8_t > &ciphertext, std::vector< uint8_t > &sharedSecret)
bool decapsulate (const std::vector< uint8_t > &privateKey, const std::vector< uint8_t > &ciphertext, std::vector< uint8_t > &sharedSecret)
size_t getPublicKeySize () const
size_t getPrivateKeySize () const
size_t getCiphertextSize () const
size_t getSharedSecretSize () const
SecurityLevel getSecurityLevel () const
std::string getLastError () const
void clearLastError ()
MLKEM (SecurityLevel level=SecurityLevel::Level3)
~MLKEM ()
bool generateKeyPair (std::vector< uint8_t > &publicKey, std::vector< uint8_t > &privateKey)
bool encapsulate (const std::vector< uint8_t > &publicKey, std::vector< uint8_t > &ciphertext, std::vector< uint8_t > &sharedSecret)
bool decapsulate (const std::vector< uint8_t > &privateKey, const std::vector< uint8_t > &ciphertext, std::vector< uint8_t > &sharedSecret)
size_t getPublicKeySize () const
size_t getPrivateKeySize () const
size_t getCiphertextSize () const
size_t getSharedSecretSize () const
SecurityLevel getSecurityLevel () const
std::string getLastError () const
void clearLastError ()
Detailed Description
Definition at line 37 of file ml_kem.hpp.
Member Enumeration Documentation
SecurityLevel [1/2]
enum class satox::security::pqc::MLKEM::SecurityLevel strong
Enumerator
Level1
Level3
Level5
Level1
Level3
Level5
Definition at line 40 of file ml_kem.hpp.
SecurityLevel [2/2]
enum class satox::security::pqc::MLKEM::SecurityLevel strong
Enumerator
Level1
Level3
Level5
Level1
Level3
Level5
Definition at line 40 of file ml_kem.hpp.
Constructor & Destructor Documentation
MLKEM() [1/2]
satox::security::pqc::MLKEM::MLKEM (SecurityLevel level = SecurityLevel::Level3) explicit
Definition at line 204 of file ml_kem.cpp.
~MLKEM() [1/2]
satox::security::pqc::MLKEM::~MLKEM () default
MLKEM() [2/2]
satox::security::pqc::MLKEM::MLKEM (SecurityLevel level = SecurityLevel::Level3) explicit
References Level3.
~MLKEM() [2/2]
satox::security::pqc::MLKEM::~MLKEM ()
Member Function Documentation
clearLastError() [1/2]
void satox::security::pqc::MLKEM::clearLastError ()
Definition at line 250 of file ml_kem.cpp.
clearLastError() [2/2]
void satox::security::pqc::MLKEM::clearLastError ()
decapsulate() [1/2]
bool satox::security::pqc::MLKEM::decapsulate (const std::vector< uint8_t > & privateKey, const std::vector< uint8_t > & ciphertext, std::vector< uint8_t > & sharedSecret)
Definition at line 220 of file ml_kem.cpp.
Referenced by satox::security::pqc::HybridCrypto::Impl::hybridDecrypt().
decapsulate() [2/2]
bool satox::security::pqc::MLKEM::decapsulate (const std::vector< uint8_t > & privateKey, const std::vector< uint8_t > & ciphertext, std::vector< uint8_t > & sharedSecret)
encapsulate() [1/2]
bool satox::security::pqc::MLKEM::encapsulate (const std::vector< uint8_t > & publicKey, std::vector< uint8_t > & ciphertext, std::vector< uint8_t > & sharedSecret)
Definition at line 214 of file ml_kem.cpp.
Referenced by satox::security::pqc::HybridCrypto::Impl::hybridEncrypt().
encapsulate() [2/2]
bool satox::security::pqc::MLKEM::encapsulate (const std::vector< uint8_t > & publicKey, std::vector< uint8_t > & ciphertext, std::vector< uint8_t > & sharedSecret)
generateKeyPair() [1/2]
bool satox::security::pqc::MLKEM::generateKeyPair (std::vector< uint8_t > & publicKey, std::vector< uint8_t > & privateKey)
Definition at line 209 of file ml_kem.cpp.
Referenced by satox::security::pqc::HybridCrypto::Impl::generateHybridKeyPair(), and satox::security::pqc::HybridCrypto::Impl::hybridEncrypt().
generateKeyPair() [2/2]
bool satox::security::pqc::MLKEM::generateKeyPair (std::vector< uint8_t > & publicKey, std::vector< uint8_t > & privateKey)
getCiphertextSize() [1/2]
size_t satox::security::pqc::MLKEM::getCiphertextSize () const
Definition at line 234 of file ml_kem.cpp.
Referenced by satox::security::pqc::HybridCrypto::Impl::getCiphertextSize().
getCiphertextSize() [2/2]
size_t satox::security::pqc::MLKEM::getCiphertextSize () const
getLastError() [1/2]
std::string satox::security::pqc::MLKEM::getLastError () const
Definition at line 246 of file ml_kem.cpp.
Referenced by satox::security::pqc::HybridCrypto::Impl::generateHybridKeyPair(), satox::security::pqc::HybridCrypto::Impl::hybridDecrypt(), and satox::security::pqc::HybridCrypto::Impl::hybridEncrypt().
getLastError() [2/2]
std::string satox::security::pqc::MLKEM::getLastError () const
getPrivateKeySize() [1/2]
size_t satox::security::pqc::MLKEM::getPrivateKeySize () const
Definition at line 230 of file ml_kem.cpp.
Referenced by satox::security::pqc::HybridCrypto::Impl::getPrivateKeySize().
getPrivateKeySize() [2/2]
size_t satox::security::pqc::MLKEM::getPrivateKeySize () const
getPublicKeySize() [1/2]
size_t satox::security::pqc::MLKEM::getPublicKeySize () const
Definition at line 226 of file ml_kem.cpp.
Referenced by satox::security::pqc::HybridCrypto::Impl::getCiphertextSize(), and satox::security::pqc::HybridCrypto::Impl::getPublicKeySize().
getPublicKeySize() [2/2]
size_t satox::security::pqc::MLKEM::getPublicKeySize () const
getSecurityLevel() [1/2]
MLKEM::SecurityLevel satox::security::pqc::MLKEM::getSecurityLevel () const
Definition at line 242 of file ml_kem.cpp.
getSecurityLevel() [2/2]
SecurityLevel satox::security::pqc::MLKEM::getSecurityLevel () const
getSharedSecretSize() [1/2]
size_t satox::security::pqc::MLKEM::getSharedSecretSize () const
Definition at line 238 of file ml_kem.cpp.
getSharedSecretSize() [2/2]
size_t satox::security::pqc::MLKEM::getSharedSecretSize () const
The documentation for this class was generated from the following files:
src/security/include/satox/security/pqc/pqc/ml_kem.hpp
src/security/include/security/pqc/ml_kem.hpp
src/security/pqc/ml_kem.cpp
src/security/src/ml_kem.cpp