SATOX SDK: satox::core::SatoxManager Class Reference
satox::core::SatoxManager Class Reference
Main manager class for Satox SDK core functionality.
#include <satox_manager.hpp>
Classes
struct Stats
struct SystemInfo
struct SystemStats
Public Types
using StateCallback = std::function<void(const SystemInfo&)>
using ErrorCallback = std::function<void(const std::string&)>
using StatsCallback = std::function<void(const SystemStats&)>
Public Member Functions
bool initialize (const nlohmann::json &config=nlohmann::json::object())
Initialize the SDK with configuration.
bool shutdown ()
Shutdown the SDK and cleanup resources.
template<typename T>
bool registerComponent (const std::string &name, std::shared_ptr< T > component)
Register a component with the manager.
template<typename T>
std::shared_ptr< T > getComponent (const std::string &name)
Get a registered component.
bool hasComponent (const std::string &name) const
Check if a component is registered.
std::string getLastError () const
Get the last error message.
bool clearLastError ()
Clear the last error message.
bool start ()
bool stop ()
bool pause ()
bool resume ()
bool isRunning () const
bool isPaused () const
bool update (const nlohmann::json &config)
std::optional< nlohmann::json > getConfig () const
CoreManager & getCoreManager ()
NetworkManager & getNetworkManager ()
BlockchainManager & getBlockchainManager ()
TransactionManager & getTransactionManager ()
AssetManager & getAssetManager ()
WalletManager & getWalletManager ()
IPFSManager & getIPFSManager ()
DatabaseManager & getDatabaseManager ()
SecurityManager & getSecurityManager ()
NFTManager & getNFTManager ()
PluginManager & getPluginManager ()
EventManager & getEventManager ()
CacheManager & getCacheManager ()
ConfigManager & getConfigManager ()
LoggingManager & getLoggingManager ()
std::optional< SystemInfo > getSystemInfo () const
std::optional< ComponentStatus > getComponentStatus (const std::string &component) const
std::vector< std::string > getAvailableComponents () const
SystemStats getSystemStats () const
bool enableStats (bool enable)
bool resetStats ()
bool registerStateCallback (StateCallback callback)
bool registerErrorCallback (ErrorCallback callback)
bool registerStatsCallback (StatsCallback callback)
bool unregisterStateCallback ()
bool unregisterErrorCallback ()
bool unregisterStatsCallback ()
bool updateConfig (const nlohmann::json &config)
bool reloadConfig ()
Stats getStats () const
bool isHealthy () const
Static Public Member Functions
static SatoxManager & getInstance ()
Get the singleton instance of SatoxManager.
Detailed Description
Main manager class for Satox SDK core functionality.
This class serves as the central point for managing core SDK functionality, including initialization, shutdown, and component management.
Definition at line 51 of file satox_manager.hpp.
Member Typedef Documentation
ErrorCallback
using satox::core::SatoxManager::ErrorCallback = std::function<void(const std::string&)>
Definition at line 170 of file satox_manager.hpp.
StateCallback
using satox::core::SatoxManager::StateCallback = std::function<void(const SystemInfo&)>
Definition at line 169 of file satox_manager.hpp.
StatsCallback
using satox::core::SatoxManager::StatsCallback = std::function<void(const SystemStats&)>
Definition at line 171 of file satox_manager.hpp.
Member Function Documentation
clearLastError()
bool satox::core::SatoxManager::clearLastError ()
Clear the last error message.
Definition at line 107 of file satox_manager.cpp.
enableStats()
bool satox::core::SatoxManager::enableStats (bool enable)
Definition at line 289 of file satox_manager.cpp.
getAssetManager()
AssetManager & satox::core::SatoxManager::getAssetManager ()
Definition at line 190 of file satox_manager.cpp.
References satox::core::AssetManager::getInstance().
getAvailableComponents()
std::vector< std::string > satox::core::SatoxManager::getAvailableComponents () const
Definition at line 278 of file satox_manager.cpp.
getBlockchainManager()
BlockchainManager & satox::core::SatoxManager::getBlockchainManager ()
Definition at line 182 of file satox_manager.cpp.
References satox::core::BlockchainManager::getInstance().
getCacheManager()
CacheManager & satox::core::SatoxManager::getCacheManager ()
Definition at line 225 of file satox_manager.cpp.
References satox::core::CacheManager::getInstance().
getComponent()
template<typename T> std::shared_ptr< T > satox::core::SatoxManager::getComponent (const std::string & name)
Get a registered component.
Template Parameters
T Component type
Parameters
name Component name
Returns
Shared pointer to component, or nullptr if not found
Definition at line 251 of file satox_manager.hpp.
getComponentStatus()
std::optional< ComponentStatus > satox::core::SatoxManager::getComponentStatus (const std::string & component) const
Definition at line 267 of file satox_manager.cpp.
References satox::core::ComponentStatus::name, satox::core::RUNNING, and satox::core::ComponentStatus::state.
getConfig()
std::optional< nlohmann::json > satox::core::SatoxManager::getConfig () const
Definition at line 168 of file satox_manager.cpp.
getConfigManager()
ConfigManager & satox::core::SatoxManager::getConfigManager ()
Definition at line 229 of file satox_manager.cpp.
References satox::core::ConfigManager::getInstance().
getCoreManager()
CoreManager & satox::core::SatoxManager::getCoreManager ()
Definition at line 174 of file satox_manager.cpp.
References satox::core::CoreManager::getInstance().
getDatabaseManager()
DatabaseManager & satox::core::SatoxManager::getDatabaseManager ()
getEventManager()
EventManager & satox::core::SatoxManager::getEventManager ()
Definition at line 221 of file satox_manager.cpp.
References satox::core::EventManager::getInstance().
getInstance()
SatoxManager & satox::core::SatoxManager::getInstance () static
Get the singleton instance of SatoxManager.
Returns
Reference to the SatoxManager instance
Definition at line 43 of file satox_manager.cpp.
Referenced by main().
getIPFSManager()
IPFSManager & satox::core::SatoxManager::getIPFSManager ()
Definition at line 198 of file satox_manager.cpp.
References satox::core::IPFSManager::getInstance().
getLastError()
std::string satox::core::SatoxManager::getLastError () const
Get the last error message.
Returns
Last error message
Definition at line 113 of file satox_manager.cpp.
getLoggingManager()
LoggingManager & satox::core::SatoxManager::getLoggingManager ()
Definition at line 233 of file satox_manager.cpp.
getNetworkManager()
NetworkManager & satox::core::SatoxManager::getNetworkManager ()
Definition at line 178 of file satox_manager.cpp.
References satox::core::NetworkManager::getInstance().
getNFTManager()
NFTManager & satox::core::SatoxManager::getNFTManager ()
Definition at line 213 of file satox_manager.cpp.
References satox::core::NFTManager::getInstance().
getPluginManager()
PluginManager & satox::core::SatoxManager::getPluginManager ()
Definition at line 217 of file satox_manager.cpp.
References satox::core::PluginManager::getInstance().
getSecurityManager()
SecurityManager & satox::core::SatoxManager::getSecurityManager ()
getStats()
SatoxManager::Stats satox::core::SatoxManager::getStats () const
Definition at line 354 of file satox_manager.cpp.
References satox::core::SatoxManager::Stats::active_components, satox::core::SatoxManager::Stats::failed_components, satox::core::SatoxManager::Stats::last_activity, satox::core::SatoxManager::Stats::start_time, and satox::core::SatoxManager::Stats::total_components.
getSystemInfo()
std::optional< SatoxManager::SystemInfo > satox::core::SatoxManager::getSystemInfo () const
Definition at line 239 of file satox_manager.cpp.
References satox::core::SatoxManager::SystemInfo::build, satox::core::SatoxManager::SystemInfo::initialized, satox::core::SatoxManager::SystemInfo::managerStatus, satox::core::SatoxManager::SystemInfo::paused, satox::core::SatoxManager::SystemInfo::running, and satox::core::SatoxManager::SystemInfo::version.
getSystemStats()
SatoxManager::SystemStats satox::core::SatoxManager::getSystemStats () const
Definition at line 284 of file satox_manager.cpp.
getTransactionManager()
TransactionManager & satox::core::SatoxManager::getTransactionManager ()
Definition at line 186 of file satox_manager.cpp.
References satox::core::TransactionManager::getInstance().
getWalletManager()
WalletManager & satox::core::SatoxManager::getWalletManager ()
Definition at line 194 of file satox_manager.cpp.
References satox::core::WalletManager::getInstance().
hasComponent()
bool satox::core::SatoxManager::hasComponent (const std::string & name) const
Check if a component is registered.
Parameters
name Component name
Returns
true if component exists, false otherwise
initialize()
bool satox::core::SatoxManager::initialize (const nlohmann::json & config = nlohmann::json::object())
Initialize the SDK with configuration.
Parameters
configPath Path to configuration file
Returns
true if initialization successful, false otherwise
Definition at line 48 of file satox_manager.cpp.
Referenced by main().
isHealthy()
bool satox::core::SatoxManager::isHealthy () const
Definition at line 365 of file satox_manager.cpp.
isPaused()
bool satox::core::SatoxManager::isPaused () const
Definition at line 156 of file satox_manager.cpp.
isRunning()
bool satox::core::SatoxManager::isRunning () const
Definition at line 151 of file satox_manager.cpp.
pause()
bool satox::core::SatoxManager::pause ()
Definition at line 135 of file satox_manager.cpp.
registerComponent()
template<typename T> bool satox::core::SatoxManager::registerComponent (const std::string & name, std::shared_ptr< T > component)
Register a component with the manager.
Template Parameters
T Component type
Parameters
name Component name
component Component instance
Returns
true if registration successful, false otherwise
Definition at line 234 of file satox_manager.hpp.
registerErrorCallback()
bool satox::core::SatoxManager::registerErrorCallback (ErrorCallback callback)
Definition at line 310 of file satox_manager.cpp.
registerStateCallback()
bool satox::core::SatoxManager::registerStateCallback (StateCallback callback)
Definition at line 304 of file satox_manager.cpp.
registerStatsCallback()
bool satox::core::SatoxManager::registerStatsCallback (StatsCallback callback)
Definition at line 316 of file satox_manager.cpp.
reloadConfig()
bool satox::core::SatoxManager::reloadConfig ()
Definition at line 347 of file satox_manager.cpp.
resetStats()
bool satox::core::SatoxManager::resetStats ()
Definition at line 295 of file satox_manager.cpp.
References satox::core::SatoxManager::SystemStats::start_time.
resume()
bool satox::core::SatoxManager::resume ()
Definition at line 145 of file satox_manager.cpp.
shutdown()
bool satox::core::SatoxManager::shutdown ()
Shutdown the SDK and cleanup resources.
Definition at line 94 of file satox_manager.cpp.
Referenced by main().
start()
bool satox::core::SatoxManager::start ()
Definition at line 119 of file satox_manager.cpp.
stop()
bool satox::core::SatoxManager::stop ()
Definition at line 129 of file satox_manager.cpp.
unregisterErrorCallback()
bool satox::core::SatoxManager::unregisterErrorCallback ()
Definition at line 328 of file satox_manager.cpp.
unregisterStateCallback()
bool satox::core::SatoxManager::unregisterStateCallback ()
Definition at line 322 of file satox_manager.cpp.
unregisterStatsCallback()
bool satox::core::SatoxManager::unregisterStatsCallback ()
Definition at line 334 of file satox_manager.cpp.
update()
bool satox::core::SatoxManager::update (const nlohmann::json & config)
Definition at line 162 of file satox_manager.cpp.
updateConfig()
bool satox::core::SatoxManager::updateConfig (const nlohmann::json & config)
Definition at line 341 of file satox_manager.cpp.
The documentation for this class was generated from the following files:
src/core/include/satox/core/satox_manager.hpp
src/core/src/satox_manager.cpp