SATOX SDK: satox::core::NFTManager Class Reference
satox::core::NFTManager Class Reference
#include <nft.h>
Classes
struct NFT
struct NFTMetadata
struct NFTStats
Public Types
enum class NFTType {
IMAGE , VIDEO , AUDIO , DOCUMENT ,
COLLECTIBLE , GAME_ITEM , CUSTOM
}
enum class NFTState {
CREATED , MINTED , TRANSFERRED , BURNED ,
ERROR
}
using NFTCallback = std::function<void(const std::string&, NFTState)>
using NFTMetadataCallback = std::function<void(const std::string&, const NFTMetadata&)>
using NFTErrorCallback = std::function<void(const std::string&, const std::string&)>
Public Member Functions
NFTManager ()
~NFTManager ()
NFTManager (const NFTManager &)=delete
NFTManager & operator= (const NFTManager &)=delete
NFTManager (NFTManager &&) noexcept=default
NFTManager & operator= (NFTManager &&) noexcept=default
void initialize ()
NFT mintNFT (const std::string &contractAddress, const std::string &creator, const NFTMetadata &metadata, const std::string &uri="")
bool transferNFT (const std::string &nftId, const std::string &from, const std::string &to)
bool updateNFTMetadata (const std::string &nftId, const NFTMetadata &metadata)
NFT getNFT (const std::string &nftId)
std::vector< NFT > getNFTsByOwner (const std::string &owner)
std::vector< NFT > getNFTsByContract (const std::string &contractAddress)
std::vector< NFT > getAllNFTs ()
bool burnNFT (const std::string &nftId)
std::string getNFTBalance (const std::string &contractAddress, const std::string &address)
bool initialize (const nlohmann::json &config)
void shutdown ()
bool createNFT (const std::string &assetId, const NFTMetadata &metadata)
bool mintNFT (const std::string &nftId)
bool transferNFT (const std::string &nftId, const std::string &newOwner)
bool burnNFT (const std::string &nftId)
bool updateNFTMetadata (const std::string &nftId, const NFTMetadata &metadata)
bool isNFTExists (const std::string &nftId) const
NFT getNFT (const std::string &nftId) const
std::vector< NFT > getNFTsByAsset (const std::string &assetId) const
std::vector< NFT > getNFTsByOwner (const std::string &owner) const
std::vector< NFT > getNFTsByType (NFTType type) const
std::vector< NFT > getNFTsByState (NFTState state) const
bool validateMetadata (const NFTMetadata &metadata) const
bool updateNFTURI (const std::string &nftId, const std::string &uri)
bool updateNFTHash (const std::string &nftId, const std::string &hash)
bool addNFTAttribute (const std::string &nftId, const std::string &key, const nlohmann::json &value)
bool removeNFTAttribute (const std::string &nftId, const std::string &key)
std::vector< std::string > getNFTHistory (const std::string &nftId) const
bool addNFTHistoryEntry (const std::string &nftId, const std::string &entry)
bool clearNFTHistory (const std::string &nftId)
NFTStats getStats () const
void resetStats ()
bool enableStats (bool enable)
void registerNFTCallback (NFTCallback callback)
void registerMetadataCallback (NFTMetadataCallback callback)
void registerErrorCallback (NFTErrorCallback callback)
void unregisterNFTCallback ()
void unregisterMetadataCallback ()
void unregisterErrorCallback ()
std::string getLastError () const
void clearLastError ()
Static Public Member Functions
static NFTManager & getInstance ()
Detailed Description
Definition at line 58 of file nft.h.
Member Typedef Documentation
NFTCallback
using satox::core::NFTManager::NFTCallback = std::function<void(const std::string&, NFTState)>
Definition at line 102 of file nft_manager.hpp.
NFTErrorCallback
using satox::core::NFTManager::NFTErrorCallback = std::function<void(const std::string&, const std::string&)>
Definition at line 104 of file nft_manager.hpp.
NFTMetadataCallback
using satox::core::NFTManager::NFTMetadataCallback = std::function<void(const std::string&, const NFTMetadata&)>
Definition at line 103 of file nft_manager.hpp.
Member Enumeration Documentation
NFTState
enum class satox::core::NFTManager::NFTState strong
Enumerator
CREATED
MINTED
TRANSFERRED
BURNED
ERROR
Definition at line 53 of file nft_manager.hpp.
NFTType
enum class satox::core::NFTManager::NFTType strong
Enumerator
IMAGE
VIDEO
AUDIO
DOCUMENT
COLLECTIBLE
GAME_ITEM
CUSTOM
Definition at line 42 of file nft_manager.hpp.
Constructor & Destructor Documentation
NFTManager() [1/3]
satox::core::NFTManager::NFTManager ()
Definition at line 35 of file nft.cpp.
Referenced by getInstance(), NFTManager(), NFTManager(), operator=(), operator=(), and updateNFTMetadata().
~NFTManager()
satox::core::NFTManager::~NFTManager ()
Definition at line 37 of file nft.cpp.
NFTManager() [2/3]
satox::core::NFTManager::NFTManager (const NFTManager &) delete
References NFTManager().
NFTManager() [3/3]
satox::core::NFTManager::NFTManager (NFTManager &&) default noexcept
References NFTManager().
Member Function Documentation
addNFTAttribute()
bool satox::core::NFTManager::addNFTAttribute (const std::string & nftId, const std::string & key, const nlohmann::json & value)
Definition at line 335 of file nft_manager.cpp.
addNFTHistoryEntry()
bool satox::core::NFTManager::addNFTHistoryEntry (const std::string & nftId, const std::string & entry)
Definition at line 374 of file nft_manager.cpp.
burnNFT() [1/2]
bool satox::core::NFTManager::burnNFT (const std::string & nftId)
Definition at line 203 of file nft.cpp.
Referenced by operator=().
burnNFT() [2/2]
bool satox::core::NFTManager::burnNFT (const std::string & nftId)
clearLastError()
void satox::core::NFTManager::clearLastError ()
Definition at line 451 of file nft_manager.cpp.
clearNFTHistory()
bool satox::core::NFTManager::clearNFTHistory (const std::string & nftId)
Definition at line 387 of file nft_manager.cpp.
createNFT()
bool satox::core::NFTManager::createNFT (const std::string & assetId, const NFTMetadata & metadata)
Definition at line 71 of file nft_manager.cpp.
References CREATED, and validateMetadata().
enableStats()
bool satox::core::NFTManager::enableStats (bool enable)
Definition at line 410 of file nft_manager.cpp.
getAllNFTs()
std::vector< NFT > satox::core::NFTManager::getAllNFTs ()
Definition at line 190 of file nft.cpp.
Referenced by operator=().
getInstance()
NFTManager & satox::core::NFTManager::getInstance () static
Definition at line 34 of file nft_manager.cpp.
References NFTManager().
Referenced by satox::core::SatoxManager::getNFTManager().
getLastError()
std::string satox::core::NFTManager::getLastError () const
Definition at line 446 of file nft_manager.cpp.
getNFT() [1/2]
NFT satox::core::NFTManager::getNFT (const std::string & nftId)
Definition at line 136 of file nft.cpp.
Referenced by operator=().
getNFT() [2/2]
NFTManager::NFT satox::core::NFTManager::getNFT (const std::string & nftId) const
Definition at line 237 of file nft_manager.cpp.
getNFTBalance()
std::string satox::core::NFTManager::getNFTBalance (const std::string & contractAddress, const std::string & address)
Definition at line 227 of file nft.cpp.
Referenced by operator=().
getNFTHistory()
std::vector< std::string > satox::core::NFTManager::getNFTHistory (const std::string & nftId) const
Definition at line 365 of file nft_manager.cpp.
getNFTsByAsset()
std::vector< NFTManager::NFT > satox::core::NFTManager::getNFTsByAsset (const std::string & assetId) const
Definition at line 246 of file nft_manager.cpp.
getNFTsByContract()
std::vector< NFT > satox::core::NFTManager::getNFTsByContract (const std::string & contractAddress)
Definition at line 171 of file nft.cpp.
Referenced by operator=().
getNFTsByOwner() [1/2]
std::vector< NFT > satox::core::NFTManager::getNFTsByOwner (const std::string & owner)
Definition at line 152 of file nft.cpp.
Referenced by operator=().
getNFTsByOwner() [2/2]
std::vector< NFTManager::NFT > satox::core::NFTManager::getNFTsByOwner (const std::string & owner) const
Definition at line 259 of file nft_manager.cpp.
getNFTsByState()
std::vector< NFTManager::NFT > satox::core::NFTManager::getNFTsByState (NFTState state) const
Definition at line 285 of file nft_manager.cpp.
getNFTsByType()
std::vector< NFTManager::NFT > satox::core::NFTManager::getNFTsByType (NFTType type) const
Definition at line 272 of file nft_manager.cpp.
getStats()
NFTManager::NFTStats satox::core::NFTManager::getStats () const
Definition at line 400 of file nft_manager.cpp.
initialize() [1/2]
void satox::core::NFTManager::initialize ()
Definition at line 43 of file nft.cpp.
Referenced by operator=().
initialize() [2/2]
bool satox::core::NFTManager::initialize (const nlohmann::json & config)
Definition at line 39 of file nft_manager.cpp.
isNFTExists()
bool satox::core::NFTManager::isNFTExists (const std::string & nftId) const
Definition at line 232 of file nft_manager.cpp.
mintNFT() [1/2]
NFT satox::core::NFTManager::mintNFT (const std::string & contractAddress, const std::string & creator, const NFTMetadata & metadata, const std::string & uri = "")
Definition at line 50 of file nft.cpp.
References satox::core::NFTManager::NFTMetadata::name.
Referenced by operator=().
mintNFT() [2/2]
bool satox::core::NFTManager::mintNFT (const std::string & nftId)
Definition at line 112 of file nft_manager.cpp.
References CREATED, and MINTED.
operator=() [1/2]
NFTManager & satox::core::NFTManager::operator= (const NFTManager &) delete
References NFTManager().
operator=() [2/2]
NFTManager & satox::core::NFTManager::operator= (NFTManager &&) default noexcept
References burnNFT(), getAllNFTs(), getNFT(), getNFTBalance(), getNFTsByContract(), getNFTsByOwner(), initialize(), mintNFT(), NFTManager(), transferNFT(), and updateNFTMetadata().
registerErrorCallback()
void satox::core::NFTManager::registerErrorCallback (NFTErrorCallback callback)
Definition at line 426 of file nft_manager.cpp.
registerMetadataCallback()
void satox::core::NFTManager::registerMetadataCallback (NFTMetadataCallback callback)
Definition at line 421 of file nft_manager.cpp.
registerNFTCallback()
void satox::core::NFTManager::registerNFTCallback (NFTCallback callback)
Definition at line 416 of file nft_manager.cpp.
removeNFTAttribute()
bool satox::core::NFTManager::removeNFTAttribute (const std::string & nftId, const std::string & key)
Definition at line 350 of file nft_manager.cpp.
resetStats()
void satox::core::NFTManager::resetStats ()
Definition at line 405 of file nft_manager.cpp.
shutdown()
void satox::core::NFTManager::shutdown ()
Definition at line 57 of file nft_manager.cpp.
transferNFT() [1/2]
bool satox::core::NFTManager::transferNFT (const std::string & nftId, const std::string & from, const std::string & to)
Definition at line 86 of file nft.cpp.
Referenced by operator=().
transferNFT() [2/2]
bool satox::core::NFTManager::transferNFT (const std::string & nftId, const std::string & newOwner)
Definition at line 141 of file nft_manager.cpp.
References MINTED, and TRANSFERRED.
unregisterErrorCallback()
void satox::core::NFTManager::unregisterErrorCallback ()
Definition at line 441 of file nft_manager.cpp.
unregisterMetadataCallback()
void satox::core::NFTManager::unregisterMetadataCallback ()
Definition at line 436 of file nft_manager.cpp.
unregisterNFTCallback()
void satox::core::NFTManager::unregisterNFTCallback ()
Definition at line 431 of file nft_manager.cpp.
updateNFTHash()
bool satox::core::NFTManager::updateNFTHash (const std::string & nftId, const std::string & hash)
Definition at line 320 of file nft_manager.cpp.
updateNFTMetadata() [1/2]
bool satox::core::NFTManager::updateNFTMetadata (const std::string & nftId, const NFTMetadata & metadata)
Definition at line 119 of file nft.cpp.
Referenced by operator=().
updateNFTMetadata() [2/2]
bool satox::core::NFTManager::updateNFTMetadata (const std::string & nftId, const NFTMetadata & metadata)
References NFTManager().
updateNFTURI()
bool satox::core::NFTManager::updateNFTURI (const std::string & nftId, const std::string & uri)
Definition at line 305 of file nft_manager.cpp.
validateMetadata()
bool satox::core::NFTManager::validateMetadata (const NFTMetadata & metadata) const
Definition at line 298 of file nft_manager.cpp.
References satox::core::NFTManager::NFTMetadata::creator, satox::core::NFTManager::NFTMetadata::name, and satox::core::NFTManager::NFTMetadata::owner.
Referenced by createNFT().
The documentation for this class was generated from the following files:
src/core/include/satox/core/nft.h
src/core/include/satox/core/nft_manager.hpp
src/core/src/nft.cpp
src/core/src/nft_manager.cpp