SATOX SDK: satox::core::EventManager Class Reference
satox::core::EventManager Class Reference
#include <event_manager.hpp>
Classes
struct Event
struct EventStats
struct Subscription
Public Types
enum class EventType {
SYSTEM , NETWORK , BLOCKCHAIN , WALLET ,
TRANSACTION , ASSET , NFT , IPFS ,
DATABASE , CACHE , CONFIG , SECURITY ,
CUSTOM
}
enum class Priority { LOW , NORMAL , HIGH , CRITICAL }
using EventHandler = std::function<void(const Event&)>
using EventFilter = std::function<bool(const Event&)>
using SubscriptionToken = size_t
Public Member Functions
EventManager (const EventManager &)=delete
EventManager & operator= (const EventManager &)=delete
bool initialize (size_t maxQueueSize=1000, size_t numWorkers=4)
void shutdown ()
bool publishEvent (const Event &event)
bool publishEvent (EventType type, const std::string &name, const nlohmann::json &data=nlohmann::json::object(), Priority priority=Priority::NORMAL)
bool publishEventAsync (const Event &event)
bool publishEventAsync (EventType type, const std::string &name, const nlohmann::json &data=nlohmann::json::object(), Priority priority=Priority::NORMAL)
SubscriptionToken subscribe (EventType type, EventHandler handler, bool async=false, std::chrono::milliseconds timeout=std::chrono::milliseconds(0))
SubscriptionToken subscribe (EventType type, const std::string &name, EventHandler handler, bool async=false, std::chrono::milliseconds timeout=std::chrono::milliseconds(0))
SubscriptionToken subscribe (EventFilter filter, EventHandler handler, bool async=false, std::chrono::milliseconds timeout=std::chrono::milliseconds(0))
bool unsubscribe (SubscriptionToken token)
void unsubscribe (EventType type, EventHandler handler)
void unsubscribe (EventType type, const std::string &name, EventHandler handler)
void unsubscribe (EventFilter filter, EventHandler handler)
bool processEvent (const Event &event)
bool processEventAsync (const Event &event)
void processEvents ()
void waitForEvents (std::chrono::milliseconds timeout=std::chrono::milliseconds(0))
std::vector< Event > getEvents (EventType type, std::chrono::system_clock::time_point start, std::chrono::system_clock::time_point end)
std::vector< Event > getEvents (const std::string &name, std::chrono::system_clock::time_point start, std::chrono::system_clock::time_point end)
std::vector< Event > getEvents (EventFilter filter, std::chrono::system_clock::time_point start, std::chrono::system_clock::time_point end)
EventStats getStats () const
void resetStats ()
void enableStats (bool enable)
bool addFilter (EventType type, EventFilter filter)
bool addFilter (const std::string &name, EventFilter filter)
void removeFilter (EventType type, EventFilter filter)
void removeFilter (const std::string &name, EventFilter filter)
std::string getLastError () const
void clearLastError ()
Static Public Member Functions
static EventManager & getInstance ()
Detailed Description
Definition at line 43 of file event_manager.hpp.
Member Typedef Documentation
EventFilter
using satox::core::EventManager::EventFilter = std::function<bool(const Event&)>
Definition at line 86 of file event_manager.hpp.
EventHandler
using satox::core::EventManager::EventHandler = std::function<void(const Event&)>
Definition at line 83 of file event_manager.hpp.
SubscriptionToken
using satox::core::EventManager::SubscriptionToken = size_t
Definition at line 89 of file event_manager.hpp.
Member Enumeration Documentation
EventType
enum class satox::core::EventManager::EventType strong
Enumerator
SYSTEM
NETWORK
BLOCKCHAIN
WALLET
TRANSACTION
ASSET
NFT
IPFS
DATABASE
CACHE
CONFIG
SECURITY
CUSTOM
Definition at line 46 of file event_manager.hpp.
Priority
enum class satox::core::EventManager::Priority strong
Enumerator
LOW
NORMAL
HIGH
CRITICAL
Definition at line 63 of file event_manager.hpp.
Constructor & Destructor Documentation
EventManager()
satox::core::EventManager::EventManager (const EventManager &) delete
References EventManager().
Referenced by EventManager(), getInstance(), and operator=().
Member Function Documentation
addFilter() [1/2]
bool satox::core::EventManager::addFilter (const std::string & name, EventFilter filter)
Definition at line 403 of file event_manager.cpp.
addFilter() [2/2]
bool satox::core::EventManager::addFilter (EventType type, EventFilter filter)
Definition at line 397 of file event_manager.cpp.
clearLastError()
void satox::core::EventManager::clearLastError ()
Definition at line 430 of file event_manager.cpp.
enableStats()
void satox::core::EventManager::enableStats (bool enable)
Definition at line 392 of file event_manager.cpp.
getEvents() [1/3]
std::vector< EventManager::Event > satox::core::EventManager::getEvents (const std::string & name, std::chrono::system_clock::time_point start, std::chrono::system_clock::time_point end)
Definition at line 368 of file event_manager.cpp.
getEvents() [2/3]
std::vector< EventManager::Event > satox::core::EventManager::getEvents (EventFilter filter, std::chrono::system_clock::time_point start, std::chrono::system_clock::time_point end)
Definition at line 375 of file event_manager.cpp.
getEvents() [3/3]
std::vector< EventManager::Event > satox::core::EventManager::getEvents (EventType type, std::chrono::system_clock::time_point start, std::chrono::system_clock::time_point end)
Definition at line 360 of file event_manager.cpp.
getInstance()
EventManager & satox::core::EventManager::getInstance () static
Definition at line 37 of file event_manager.cpp.
References EventManager().
Referenced by satox::core::SatoxManager::getEventManager().
getLastError()
std::string satox::core::EventManager::getLastError () const
Definition at line 425 of file event_manager.cpp.
getStats()
EventManager::EventStats satox::core::EventManager::getStats () const
Definition at line 382 of file event_manager.cpp.
initialize()
bool satox::core::EventManager::initialize (size_t maxQueueSize = 1000, size_t numWorkers = 4)
Definition at line 42 of file event_manager.cpp.
operator=()
EventManager & satox::core::EventManager::operator= (const EventManager &) delete
References EventManager(), and NORMAL.
processEvent()
bool satox::core::EventManager::processEvent (const Event & event)
Definition at line 266 of file event_manager.cpp.
References satox::core::EventManager::Event::name, and satox::core::EventManager::Event::type.
Referenced by processEventAsync(), and processEvents().
processEventAsync()
bool satox::core::EventManager::processEventAsync (const Event & event)
Definition at line 316 of file event_manager.cpp.
References processEvent().
processEvents()
void satox::core::EventManager::processEvents ()
Definition at line 320 of file event_manager.cpp.
References processEvent().
publishEvent() [1/2]
bool satox::core::EventManager::publishEvent (const Event & event)
Definition at line 214 of file event_manager.cpp.
References satox::core::EventManager::Event::name, satox::core::EventManager::Event::source, and satox::core::EventManager::Event::type.
Referenced by publishEvent(), publishEventAsync(), and publishEventAsync().
publishEvent() [2/2]
bool satox::core::EventManager::publishEvent (EventType type, const std::string & name, const nlohmann::json & data = nlohmann::json::object(), Priority priority = Priority::NORMAL)
Definition at line 244 of file event_manager.cpp.
References publishEvent(), and satox::core::EventManager::Event::type.
publishEventAsync() [1/2]
bool satox::core::EventManager::publishEventAsync (const Event & event)
Definition at line 257 of file event_manager.cpp.
References publishEvent().
publishEventAsync() [2/2]
bool satox::core::EventManager::publishEventAsync (EventType type, const std::string & name, const nlohmann::json & data = nlohmann::json::object(), Priority priority = Priority::NORMAL)
Definition at line 261 of file event_manager.cpp.
References publishEvent().
removeFilter() [1/2]
void satox::core::EventManager::removeFilter (const std::string & name, EventFilter filter)
Definition at line 417 of file event_manager.cpp.
removeFilter() [2/2]
void satox::core::EventManager::removeFilter (EventType type, EventFilter filter)
Definition at line 409 of file event_manager.cpp.
resetStats()
void satox::core::EventManager::resetStats ()
Definition at line 387 of file event_manager.cpp.
shutdown()
void satox::core::EventManager::shutdown ()
Definition at line 63 of file event_manager.cpp.
subscribe() [1/3]
EventManager::SubscriptionToken satox::core::EventManager::subscribe (EventFilter filter, EventHandler handler, bool async = false, std::chrono::milliseconds timeout = std::chrono::milliseconds(0))
Definition at line 125 of file event_manager.cpp.
subscribe() [2/3]
EventManager::SubscriptionToken satox::core::EventManager::subscribe (EventType type, const std::string & name, EventHandler handler, bool async = false, std::chrono::milliseconds timeout = std::chrono::milliseconds(0))
Definition at line 107 of file event_manager.cpp.
subscribe() [3/3]
EventManager::SubscriptionToken satox::core::EventManager::subscribe (EventType type, EventHandler handler, bool async = false, std::chrono::milliseconds timeout = std::chrono::milliseconds(0))
Definition at line 89 of file event_manager.cpp.
unsubscribe() [1/4]
void satox::core::EventManager::unsubscribe (EventFilter filter, EventHandler handler)
Definition at line 206 of file event_manager.cpp.
unsubscribe() [2/4]
void satox::core::EventManager::unsubscribe (EventType type, const std::string & name, EventHandler handler)
Definition at line 195 of file event_manager.cpp.
unsubscribe() [3/4]
void satox::core::EventManager::unsubscribe (EventType type, EventHandler handler)
Definition at line 183 of file event_manager.cpp.
unsubscribe() [4/4]
bool satox::core::EventManager::unsubscribe (SubscriptionToken token)
Definition at line 142 of file event_manager.cpp.
waitForEvents()
void satox::core::EventManager::waitForEvents (std::chrono::milliseconds timeout = std::chrono::milliseconds(0))
Definition at line 351 of file event_manager.cpp.
The documentation for this class was generated from the following files:
src/core/include/satox/core/event_manager.hpp
src/core/src/event_manager.cpp