SATOX SDK: satox::nft::DatabaseConnection Class Reference
satox::nft::DatabaseConnection Class Reference abstract
#include <database_connection.hpp>
Classes
struct Config
struct QueryResult
Public Types
using QueryCallback = std::function<void(const QueryResult&)>
Public Member Functions
virtual ~DatabaseConnection ()=default
virtual bool connect ()=0
virtual void disconnect ()=0
virtual bool isConnected () const =0
virtual bool executeQuery (const std::string &query, QueryCallback callback)=0
virtual bool executeTransaction (const std::vector< std::string > &queries, QueryCallback callback)=0
virtual std::string getLastError () const =0
virtual bool ping ()=0
virtual void setConfig (const Config &config)=0
virtual Config getConfig () const =0
Static Public Member Functions
static std::shared_ptr< DatabaseConnection > create (const Config &config)
Protected Member Functions
DatabaseConnection ()=default
DatabaseConnection (const DatabaseConnection &)=delete
DatabaseConnection & operator= (const DatabaseConnection &)=delete
Detailed Description
Definition at line 38 of file database_connection.hpp.
Member Typedef Documentation
QueryCallback
using satox::nft::DatabaseConnection::QueryCallback = std::function<void(const QueryResult&)>
Definition at line 57 of file database_connection.hpp.
Constructor & Destructor Documentation
~DatabaseConnection()
virtual satox::nft::DatabaseConnection::~DatabaseConnection () virtual default
DatabaseConnection() [1/2]
satox::nft::DatabaseConnection::DatabaseConnection () protected default
Referenced by DatabaseConnection(), and operator=().
DatabaseConnection() [2/2]
satox::nft::DatabaseConnection::DatabaseConnection (const DatabaseConnection &) protected delete
References DatabaseConnection().
Member Function Documentation
connect()
virtual bool satox::nft::DatabaseConnection::connect () pure virtual
create()
static std::shared_ptr< DatabaseConnection > satox::nft::DatabaseConnection::create (const Config & config) static
disconnect()
virtual void satox::nft::DatabaseConnection::disconnect () pure virtual
executeQuery()
virtual bool satox::nft::DatabaseConnection::executeQuery (const std::string & query, QueryCallback callback) pure virtual
executeTransaction()
virtual bool satox::nft::DatabaseConnection::executeTransaction (const std::vector< std::string > & queries, QueryCallback callback) pure virtual
getConfig()
virtual Config satox::nft::DatabaseConnection::getConfig () const pure virtual
getLastError()
virtual std::string satox::nft::DatabaseConnection::getLastError () const pure virtual
isConnected()
virtual bool satox::nft::DatabaseConnection::isConnected () const pure virtual
operator=()
DatabaseConnection & satox::nft::DatabaseConnection::operator= (const DatabaseConnection &) protected delete
References DatabaseConnection().
ping()
virtual bool satox::nft::DatabaseConnection::ping () pure virtual
setConfig()
virtual void satox::nft::DatabaseConnection::setConfig (const Config & config) pure virtual
The documentation for this class was generated from the following file:
src/nft/include/satox/nft/database_connection.hpp