SATOX SDK: satox::blockchain::Kawpow Class Reference
satox::blockchain::Kawpow Class Reference
#include <kawpow.hpp>
Public Member Functions
Kawpow ()
~Kawpow ()
Kawpow (const Kawpow &)=delete
Kawpow & operator= (const Kawpow &)=delete
Kawpow (Kawpow &&) noexcept=default
Kawpow & operator= (Kawpow &&) noexcept=default
bool computeHash (const std::vector< uint8_t > &header, uint64_t nonce, std::vector< uint8_t > &hash, std::vector< uint8_t > &mix_hash)
bool verifyHash (const std::vector< uint8_t > &header, uint64_t nonce, const std::vector< uint8_t > &mix_hash, const std::vector< uint8_t > &target)
bool initializeCache (uint64_t block_number)
bool initializeDataset (uint64_t block_number)
void clearCache ()
void clearDataset ()
Detailed Description
Definition at line 49 of file kawpow.hpp.
Constructor & Destructor Documentation
Kawpow() [1/3]
satox::blockchain::Kawpow::Kawpow ()
Definition at line 39 of file kawpow.cpp.
Referenced by Kawpow(), Kawpow(), operator=(), and operator=().
~Kawpow()
satox::blockchain::Kawpow::~Kawpow ()
Definition at line 45 of file kawpow.cpp.
References clearCache(), and clearDataset().
Kawpow() [2/3]
satox::blockchain::Kawpow::Kawpow (const Kawpow &) delete
References Kawpow().
Kawpow() [3/3]
satox::blockchain::Kawpow::Kawpow (Kawpow &&) default noexcept
References Kawpow().
Member Function Documentation
clearCache()
void satox::blockchain::Kawpow::clearCache ()
Definition at line 151 of file kawpow.cpp.
Referenced by operator=(), and ~Kawpow().
clearDataset()
void satox::blockchain::Kawpow::clearDataset ()
Definition at line 156 of file kawpow.cpp.
Referenced by operator=(), and ~Kawpow().
computeHash()
bool satox::blockchain::Kawpow::computeHash (const std::vector< uint8_t > & header, uint64_t nonce, std::vector< uint8_t > & hash, std::vector< uint8_t > & mix_hash)
Definition at line 50 of file kawpow.cpp.
References initializeCache(), initializeDataset(), satox::blockchain::KAWPOW_HASH_BYTES, satox::blockchain::KAWPOW_HEADER_BYTES, and satox::blockchain::KAWPOW_MIX_BYTES.
Referenced by satox::blockchain::Block::calculateKawpowHeaderHash(), satox::blockchain::Block::calculateKawpowMixHash(), operator=(), verifyHash(), and satox::blockchain::Block::verifyKawpowDifficulty().
initializeCache()
bool satox::blockchain::Kawpow::initializeCache (uint64_t block_number)
Definition at line 116 of file kawpow.cpp.
Referenced by computeHash(), and operator=().
initializeDataset()
bool satox::blockchain::Kawpow::initializeDataset (uint64_t block_number)
Definition at line 134 of file kawpow.cpp.
Referenced by computeHash(), and operator=().
operator=() [1/2]
Kawpow & satox::blockchain::Kawpow::operator= (const Kawpow &) delete
References Kawpow().
operator=() [2/2]
Kawpow & satox::blockchain::Kawpow::operator= (Kawpow &&) default noexcept
References clearCache(), clearDataset(), computeHash(), initializeCache(), initializeDataset(), Kawpow(), and verifyHash().
verifyHash()
bool satox::blockchain::Kawpow::verifyHash (const std::vector< uint8_t > & header, uint64_t nonce, const std::vector< uint8_t > & mix_hash, const std::vector< uint8_t > & target)
Definition at line 92 of file kawpow.cpp.
References computeHash(), satox::blockchain::KAWPOW_HEADER_BYTES, and satox::blockchain::KAWPOW_MIX_BYTES.
Referenced by operator=(), and satox::blockchain::Block::validateKawpowProof().
The documentation for this class was generated from the following files:
src/blockchain/include/satox/blockchain/kawpow.hpp
src/blockchain/src/kawpow.cpp