SATOX SDK: satox::ipfs::ContentDistribution Class Reference
satox::ipfs::ContentDistribution Class Reference
#include <content_distribution.hpp>
Classes
struct DistributionStatus
struct Error
Public Types
using StatusCallback = std::function<void(const DistributionStatus&)>
Public Member Functions
bool initialize (const std::string &configPath)
void shutdown ()
std::future< bool > distributeContent (const std::string &contentHash, const std::vector< std::string > &targetNodes)
std::future< bool > distributeFile (const std::string &filePath, const std::vector< std::string > &targetNodes)
std::future< bool > distributeDirectory (const std::string &directoryPath, const std::vector< std::string > &targetNodes)
bool addNode (const std::string &nodeId, const std::string &address)
bool removeNode (const std::string &nodeId)
bool updateNode (const std::string &nodeId, const std::string &newAddress)
std::vector< std::string > getAvailableNodes () const
bool isNodeAvailable (const std::string &nodeId) const
DistributionStatus getDistributionStatus (const std::string &contentHash) const
std::vector< DistributionStatus > getActiveDistributions () const
bool cancelDistribution (const std::string &contentHash)
void setBandwidthLimit (size_t bytesPerSecond)
size_t getBandwidthLimit () const
size_t getCurrentBandwidthUsage () const
void setDistributionPriority (const std::string &contentHash, int priority)
int getDistributionPriority (const std::string &contentHash) const
void setStatusCallback (StatusCallback callback)
void clearStatusCallback ()
Error getLastError () const
void clearLastError ()
Static Public Member Functions
static ContentDistribution & getInstance ()
Detailed Description
Definition at line 40 of file content_distribution.hpp.
Member Typedef Documentation
StatusCallback
using satox::ipfs::ContentDistribution::StatusCallback = std::function<void(const DistributionStatus&)>
Definition at line 87 of file content_distribution.hpp.
Member Function Documentation
addNode()
bool satox::ipfs::ContentDistribution::addNode (const std::string & nodeId, const std::string & address)
Definition at line 223 of file content_distribution.cpp.
cancelDistribution()
bool satox::ipfs::ContentDistribution::cancelDistribution (const std::string & contentHash)
Definition at line 313 of file content_distribution.cpp.
clearLastError()
void satox::ipfs::ContentDistribution::clearLastError ()
Definition at line 372 of file content_distribution.cpp.
clearStatusCallback()
void satox::ipfs::ContentDistribution::clearStatusCallback ()
Definition at line 363 of file content_distribution.cpp.
distributeContent()
std::future< bool > satox::ipfs::ContentDistribution::distributeContent (const std::string & contentHash, const std::vector< std::string > & targetNodes)
Definition at line 106 of file content_distribution.cpp.
References satox::ipfs::ContentDistribution::DistributionStatus::completedNodes, satox::ipfs::ContentDistribution::DistributionStatus::contentHash, satox::ipfs::ContentDistribution::DistributionStatus::endTime, satox::ipfs::ContentDistribution::DistributionStatus::error, isNodeAvailable(), satox::ipfs::ContentDistribution::DistributionStatus::progress, satox::ipfs::ContentDistribution::DistributionStatus::startTime, and satox::ipfs::ContentDistribution::DistributionStatus::status.
Referenced by distributeFile().
distributeDirectory()
std::future< bool > satox::ipfs::ContentDistribution::distributeDirectory (const std::string & directoryPath, const std::vector< std::string > & targetNodes)
Definition at line 197 of file content_distribution.cpp.
References distributeFile().
distributeFile()
std::future< bool > satox::ipfs::ContentDistribution::distributeFile (const std::string & filePath, const std::vector< std::string > & targetNodes)
Definition at line 174 of file content_distribution.cpp.
References distributeContent().
Referenced by distributeDirectory().
getActiveDistributions()
std::vector< ContentDistribution::DistributionStatus > satox::ipfs::ContentDistribution::getActiveDistributions () const
Definition at line 302 of file content_distribution.cpp.
getAvailableNodes()
std::vector< std::string > satox::ipfs::ContentDistribution::getAvailableNodes () const
Definition at line 271 of file content_distribution.cpp.
References isNodeAvailable().
getBandwidthLimit()
size_t satox::ipfs::ContentDistribution::getBandwidthLimit () const
Definition at line 337 of file content_distribution.cpp.
getCurrentBandwidthUsage()
size_t satox::ipfs::ContentDistribution::getCurrentBandwidthUsage () const
Definition at line 341 of file content_distribution.cpp.
getDistributionPriority()
int satox::ipfs::ContentDistribution::getDistributionPriority (const std::string & contentHash) const
Definition at line 352 of file content_distribution.cpp.
getDistributionStatus()
ContentDistribution::DistributionStatus satox::ipfs::ContentDistribution::getDistributionStatus (const std::string & contentHash) const
Definition at line 293 of file content_distribution.cpp.
getInstance()
ContentDistribution & satox::ipfs::ContentDistribution::getInstance () static
Definition at line 56 of file content_distribution.cpp.
References satox::ipfs::instance.
getLastError()
ContentDistribution::Error satox::ipfs::ContentDistribution::getLastError () const
Definition at line 368 of file content_distribution.cpp.
initialize()
bool satox::ipfs::ContentDistribution::initialize (const std::string & configPath)
Definition at line 61 of file content_distribution.cpp.
isNodeAvailable()
bool satox::ipfs::ContentDistribution::isNodeAvailable (const std::string & nodeId) const
Definition at line 282 of file content_distribution.cpp.
Referenced by distributeContent(), and getAvailableNodes().
removeNode()
bool satox::ipfs::ContentDistribution::removeNode (const std::string & nodeId)
Definition at line 239 of file content_distribution.cpp.
setBandwidthLimit()
void satox::ipfs::ContentDistribution::setBandwidthLimit (size_t bytesPerSecond)
Definition at line 332 of file content_distribution.cpp.
setDistributionPriority()
void satox::ipfs::ContentDistribution::setDistributionPriority (const std::string & contentHash, int priority)
Definition at line 347 of file content_distribution.cpp.
setStatusCallback()
void satox::ipfs::ContentDistribution::setStatusCallback (StatusCallback callback)
Definition at line 358 of file content_distribution.cpp.
shutdown()
void satox::ipfs::ContentDistribution::shutdown ()
Definition at line 97 of file content_distribution.cpp.
updateNode()
bool satox::ipfs::ContentDistribution::updateNode (const std::string & nodeId, const std::string & newAddress)
Definition at line 249 of file content_distribution.cpp.
The documentation for this class was generated from the following files:
src/ipfs/include/satox/ipfs/content_distribution.hpp
src/ipfs/src/content_distribution.cpp