SATOX SDK: satox::blockchain::BlockchainManager Class Reference
satox::blockchain::BlockchainManager Class Reference
#include <blockchain_manager.hpp>
Public Types
using BlockCallback = std::function<void(const std::string&, const BlockInfo&)>
using TransactionCallback = std::function<void(const std::string&, const TransactionInfo&)>
using MiningCallback = std::function<void(const std::string&, const MiningInfo&)>
using ErrorCallback = std::function<void(const std::string&)>
using ProgressCallback = std::function<void(const std::string&, uint32_t)>
Public Member Functions
BlockchainManager ()
~BlockchainManager ()
bool initialize (const BlockchainConfig &config)
void shutdown ()
bool connect ()
bool disconnect ()
bool isConnected () const
bool isInitialized () const
std::shared_ptr< Block > getLatestBlock ()
std::shared_ptr< Block > getBlockByHash (const std::string &hash)
std::shared_ptr< Block > getBlockByHeight (uint64_t height)
bool validateBlock (const std::shared_ptr< Block > &block)
uint64_t getBlockCount () const
std::shared_ptr< Transaction > createTransaction (const std::string &from, const std::string &to, double value, const std::vector< uint8_t > &data={})
bool broadcastTransaction (const std::shared_ptr< Transaction > &tx)
std::shared_ptr< Transaction > getTransaction (const std::string &tx_hash)
std::string getTransactionStatus (const std::string &tx_hash)
bool validateTransaction (const std::shared_ptr< Transaction > &tx)
uint64_t getChainHeight () const
double getBalance (const std::string &address)
uint64_t getNonce (const std::string &address)
std::string getChainState () const
bool isChainSynced () const
std::vector< std::string > getConnectedPeers () const
bool addPeer (const std::string &peer_address)
bool removePeer (const std::string &peer_address)
BlockchainConfig getConfig () const
bool updateConfig (const BlockchainConfig &config)
bool validateConfig (const BlockchainConfig &config)
NetworkConfig getNetworkConfig () const
bool updateNetworkConfig (const NetworkConfig &config)
BlockchainStats getStats () const
void resetStats ()
bool enableStats (bool enable)
void registerBlockCallback (BlockCallback callback)
void registerTransactionCallback (TransactionCallback callback)
void registerErrorCallback (ErrorCallback callback)
void unregisterBlockCallback ()
void unregisterTransactionCallback ()
void unregisterErrorCallback ()
std::string getLastError () const
void clearLastError ()
bool healthCheck ()
nlohmann::json getHealthStatus ()
BlockchainState getState () const
bool isHealthy () const
BlockchainManager ()
~BlockchainManager ()
bool initialize (const BlockchainConfig &config)
void shutdown ()
std::string getLastError () const
std::optional< BlockInfo > getBlockInfo (const std::string &block_hash) const
std::optional< BlockInfo > getBlockByHeight (uint32_t height) const
std::vector< std::string > getBlockHashes (uint32_t start_height, uint32_t end_height) const
bool validateBlock (const std::string &block_hash) const
bool broadcastBlock (const std::string &block_hash)
std::optional< TransactionInfo > getTransactionInfo (const std::string &txid) const
std::vector< std::string > getBlockTransactions (const std::string &block_hash) const
std::vector< std::string > getAddressTransactions (const std::string &address) const
bool validateTransaction (const std::string &txid) const
bool broadcastTransaction (const std::string &txid)
std::vector< std::string > getMempoolTransactions () const
bool startMining (const std::string &address)
bool stopMining ()
bool isMining () const
std::optional< MiningInfo > getMiningInfo () const
bool setMiningThreads (uint32_t threads)
uint32_t getMiningThreads () const
bool startSync ()
bool stopSync ()
bool isSyncing () const
uint32_t getCurrentHeight () const
bool syncToHeight (uint32_t height)
bool verifyChain () const
uint64_t getBalance (const std::string &address) const
uint64_t getTotalSupply () const
uint32_t getDifficulty () const
std::optional< BlockchainStatistics > getStatistics () const
void registerBlockCallback (BlockCallback callback)
void registerTransactionCallback (TransactionCallback callback)
void registerMiningCallback (MiningCallback callback)
void registerErrorCallback (ErrorCallback callback)
void registerProgressCallback (ProgressCallback callback)
void setCacheConfig (const CacheConfig &config)
void setConnectionPoolConfig (const ConnectionPoolConfig &config)
void setBatchConfig (const BatchConfig &config)
void clearCache ()
size_t getCacheSize () const
size_t getConnectionPoolSize () const
size_t getBatchSize () const
void setErrorRecoveryConfig (const ErrorRecoveryConfig &config)
bool recoverFromError (const std::string &operation_id)
std::vector< RecoveryOperation > getRecoveryHistory () const
void clearRecoveryHistory ()
bool isRecoveryInProgress () const
std::string getLastRecoveryError () const
Static Public Member Functions
static BlockchainManager & getInstance ()
Detailed Description
Definition at line 54 of file blockchain_manager.hpp.
Member Typedef Documentation
BlockCallback
using satox::blockchain::BlockchainManager::BlockCallback = std::function<void(const std::string&, const BlockInfo&)>
Definition at line 206 of file blockchain_manager.hpp.
ErrorCallback
using satox::blockchain::BlockchainManager::ErrorCallback = std::function<void(const std::string&)>
Definition at line 209 of file blockchain_manager.hpp.
MiningCallback
using satox::blockchain::BlockchainManager::MiningCallback = std::function<void(const std::string&, const MiningInfo&)>
Definition at line 208 of file blockchain_manager.hpp.
ProgressCallback
using satox::blockchain::BlockchainManager::ProgressCallback = std::function<void(const std::string&, uint32_t)>
Definition at line 210 of file blockchain_manager.hpp.
TransactionCallback
using satox::blockchain::BlockchainManager::TransactionCallback = std::function<void(const std::string&, const TransactionInfo&)>
Definition at line 207 of file blockchain_manager.hpp.
Constructor & Destructor Documentation
BlockchainManager() [1/2]
satox::blockchain::BlockchainManager::BlockchainManager ()
Definition at line 28 of file blockchain_manager.cpp.
References satox::blockchain::UNINITIALIZED.
Referenced by getInstance().
~BlockchainManager() [1/2]
satox::blockchain::BlockchainManager::~BlockchainManager ()
Definition at line 43 of file blockchain_manager.cpp.
References shutdown().
BlockchainManager() [2/2]
satox::blockchain::BlockchainManager::BlockchainManager ()
~BlockchainManager() [2/2]
satox::blockchain::BlockchainManager::~BlockchainManager ()
Member Function Documentation
addPeer()
bool satox::blockchain::BlockchainManager::addPeer (const std::string & peer_address)
Definition at line 647 of file blockchain_manager.cpp.
broadcastBlock()
bool satox::blockchain::BlockchainManager::broadcastBlock (const std::string & block_hash)
broadcastTransaction() [1/2]
bool satox::blockchain::BlockchainManager::broadcastTransaction (const std::shared_ptr< Transaction > & tx)
Definition at line 402 of file blockchain_manager.cpp.
broadcastTransaction() [2/2]
bool satox::blockchain::BlockchainManager::broadcastTransaction (const std::string & txid)
clearCache()
void satox::blockchain::BlockchainManager::clearCache ()
clearLastError()
void satox::blockchain::BlockchainManager::clearLastError ()
Definition at line 860 of file blockchain_manager.cpp.
clearRecoveryHistory()
void satox::blockchain::BlockchainManager::clearRecoveryHistory ()
connect()
bool satox::blockchain::BlockchainManager::connect ()
Definition at line 120 of file blockchain_manager.cpp.
References satox::blockchain::CONNECTED, satox::blockchain::CONNECTING, and satox::blockchain::ERROR.
createTransaction()
std::shared_ptr< Transaction > satox::blockchain::BlockchainManager::createTransaction (const std::string & from, const std::string & to, double value, const std::vector< uint8_t > & data = {})
Definition at line 356 of file blockchain_manager.cpp.
disconnect()
bool satox::blockchain::BlockchainManager::disconnect ()
Definition at line 166 of file blockchain_manager.cpp.
References satox::blockchain::INITIALIZED.
Referenced by shutdown().
enableStats()
bool satox::blockchain::BlockchainManager::enableStats (bool enable)
Definition at line 812 of file blockchain_manager.cpp.
getAddressTransactions()
std::vector< std::string > satox::blockchain::BlockchainManager::getAddressTransactions (const std::string & address) const
getBalance() [1/2]
double satox::blockchain::BlockchainManager::getBalance (const std::string & address)
Definition at line 553 of file blockchain_manager.cpp.
getBalance() [2/2]
uint64_t satox::blockchain::BlockchainManager::getBalance (const std::string & address) const
getBatchSize()
size_t satox::blockchain::BlockchainManager::getBatchSize () const
getBlockByHash()
std::shared_ptr< Block > satox::blockchain::BlockchainManager::getBlockByHash (const std::string & hash)
Definition at line 244 of file blockchain_manager.cpp.
getBlockByHeight() [1/2]
std::optional< BlockInfo > satox::blockchain::BlockchainManager::getBlockByHeight (uint32_t height) const
getBlockByHeight() [2/2]
std::shared_ptr< Block > satox::blockchain::BlockchainManager::getBlockByHeight (uint64_t height)
Definition at line 282 of file blockchain_manager.cpp.
getBlockCount()
uint64_t satox::blockchain::BlockchainManager::getBlockCount () const
Definition at line 351 of file blockchain_manager.cpp.
getBlockHashes()
std::vector< std::string > satox::blockchain::BlockchainManager::getBlockHashes (uint32_t start_height, uint32_t end_height) const
getBlockInfo()
std::optional< BlockInfo > satox::blockchain::BlockchainManager::getBlockInfo (const std::string & block_hash) const
getBlockTransactions()
std::vector< std::string > satox::blockchain::BlockchainManager::getBlockTransactions (const std::string & block_hash) const
getCacheSize()
size_t satox::blockchain::BlockchainManager::getCacheSize () const
getChainHeight()
uint64_t satox::blockchain::BlockchainManager::getChainHeight () const
Definition at line 548 of file blockchain_manager.cpp.
getChainState()
std::string satox::blockchain::BlockchainManager::getChainState () const
Definition at line 621 of file blockchain_manager.cpp.
References isChainSynced().
getConfig()
BlockchainConfig satox::blockchain::BlockchainManager::getConfig () const
Definition at line 715 of file blockchain_manager.cpp.
getConnectedPeers()
std::vector< std::string > satox::blockchain::BlockchainManager::getConnectedPeers () const
Definition at line 641 of file blockchain_manager.cpp.
getConnectionPoolSize()
size_t satox::blockchain::BlockchainManager::getConnectionPoolSize () const
getCurrentHeight()
uint32_t satox::blockchain::BlockchainManager::getCurrentHeight () const
getDifficulty()
uint32_t satox::blockchain::BlockchainManager::getDifficulty () const
getHealthStatus()
json satox::blockchain::BlockchainManager::getHealthStatus ()
Definition at line 898 of file blockchain_manager.cpp.
References isHealthy().
getInstance()
BlockchainManager & satox::blockchain::BlockchainManager::getInstance () static
Definition at line 23 of file blockchain_manager.cpp.
References BlockchainManager().
getLastError() [1/2]
std::string satox::blockchain::BlockchainManager::getLastError () const
Definition at line 855 of file blockchain_manager.cpp.
getLastError() [2/2]
std::string satox::blockchain::BlockchainManager::getLastError () const
getLastRecoveryError()
std::string satox::blockchain::BlockchainManager::getLastRecoveryError () const
getLatestBlock()
std::shared_ptr< Block > satox::blockchain::BlockchainManager::getLatestBlock ()
Definition at line 211 of file blockchain_manager.cpp.
getMempoolTransactions()
std::vector< std::string > satox::blockchain::BlockchainManager::getMempoolTransactions () const
getMiningInfo()
std::optional< MiningInfo > satox::blockchain::BlockchainManager::getMiningInfo () const
getMiningThreads()
uint32_t satox::blockchain::BlockchainManager::getMiningThreads () const
getNetworkConfig()
NetworkConfig satox::blockchain::BlockchainManager::getNetworkConfig () const
Definition at line 766 of file blockchain_manager.cpp.
getNonce()
uint64_t satox::blockchain::BlockchainManager::getNonce (const std::string & address)
Definition at line 587 of file blockchain_manager.cpp.
getRecoveryHistory()
std::vector< RecoveryOperation > satox::blockchain::BlockchainManager::getRecoveryHistory () const
getState()
BlockchainState satox::blockchain::BlockchainManager::getState () const
Definition at line 918 of file blockchain_manager.cpp.
getStatistics()
std::optional< BlockchainStatistics > satox::blockchain::BlockchainManager::getStatistics () const
getStats()
BlockchainStats satox::blockchain::BlockchainManager::getStats () const
Definition at line 801 of file blockchain_manager.cpp.
getTotalSupply()
uint64_t satox::blockchain::BlockchainManager::getTotalSupply () const
getTransaction()
std::shared_ptr< Transaction > satox::blockchain::BlockchainManager::getTransaction (const std::string & tx_hash)
Definition at line 439 of file blockchain_manager.cpp.
getTransactionInfo()
std::optional< TransactionInfo > satox::blockchain::BlockchainManager::getTransactionInfo (const std::string & txid) const
getTransactionStatus()
std::string satox::blockchain::BlockchainManager::getTransactionStatus (const std::string & tx_hash)
Definition at line 478 of file blockchain_manager.cpp.
healthCheck()
bool satox::blockchain::BlockchainManager::healthCheck ()
Definition at line 865 of file blockchain_manager.cpp.
References satox::blockchain::INITIALIZED.
initialize() [1/2]
bool satox::blockchain::BlockchainManager::initialize (const BlockchainConfig & config)
Definition at line 47 of file blockchain_manager.cpp.
References satox::blockchain::BlockchainConfig::enableLogging, satox::blockchain::ERROR, satox::blockchain::INITIALIZED, satox::blockchain::INITIALIZING, satox::blockchain::BlockchainConfig::logPath, satox::blockchain::BlockchainConfig::name, and validateConfig().
initialize() [2/2]
bool satox::blockchain::BlockchainManager::initialize (const BlockchainConfig & config)
isChainSynced()
bool satox::blockchain::BlockchainManager::isChainSynced () const
Definition at line 635 of file blockchain_manager.cpp.
Referenced by getChainState().
isConnected()
bool satox::blockchain::BlockchainManager::isConnected () const
Definition at line 201 of file blockchain_manager.cpp.
isHealthy()
bool satox::blockchain::BlockchainManager::isHealthy () const
Definition at line 923 of file blockchain_manager.cpp.
Referenced by getHealthStatus().
isInitialized()
bool satox::blockchain::BlockchainManager::isInitialized () const
Definition at line 206 of file blockchain_manager.cpp.
isMining()
bool satox::blockchain::BlockchainManager::isMining () const
isRecoveryInProgress()
bool satox::blockchain::BlockchainManager::isRecoveryInProgress () const
isSyncing()
bool satox::blockchain::BlockchainManager::isSyncing () const
recoverFromError()
bool satox::blockchain::BlockchainManager::recoverFromError (const std::string & operation_id)
registerBlockCallback() [1/2]
void satox::blockchain::BlockchainManager::registerBlockCallback (BlockCallback callback)
Definition at line 819 of file blockchain_manager.cpp.
registerBlockCallback() [2/2]
void satox::blockchain::BlockchainManager::registerBlockCallback (BlockCallback callback)
registerErrorCallback() [1/2]
void satox::blockchain::BlockchainManager::registerErrorCallback (ErrorCallback callback)
Definition at line 831 of file blockchain_manager.cpp.
registerErrorCallback() [2/2]
void satox::blockchain::BlockchainManager::registerErrorCallback (ErrorCallback callback)
registerMiningCallback()
void satox::blockchain::BlockchainManager::registerMiningCallback (MiningCallback callback)
registerProgressCallback()
void satox::blockchain::BlockchainManager::registerProgressCallback (ProgressCallback callback)
registerTransactionCallback() [1/2]
void satox::blockchain::BlockchainManager::registerTransactionCallback (TransactionCallback callback)
Definition at line 825 of file blockchain_manager.cpp.
registerTransactionCallback() [2/2]
void satox::blockchain::BlockchainManager::registerTransactionCallback (TransactionCallback callback)
removePeer()
bool satox::blockchain::BlockchainManager::removePeer (const std::string & peer_address)
Definition at line 681 of file blockchain_manager.cpp.
resetStats()
void satox::blockchain::BlockchainManager::resetStats ()
Definition at line 806 of file blockchain_manager.cpp.
setBatchConfig()
void satox::blockchain::BlockchainManager::setBatchConfig (const BatchConfig & config)
setCacheConfig()
void satox::blockchain::BlockchainManager::setCacheConfig (const CacheConfig & config)
setConnectionPoolConfig()
void satox::blockchain::BlockchainManager::setConnectionPoolConfig (const ConnectionPoolConfig & config)
setErrorRecoveryConfig()
void satox::blockchain::BlockchainManager::setErrorRecoveryConfig (const ErrorRecoveryConfig & config)
setMiningThreads()
bool satox::blockchain::BlockchainManager::setMiningThreads (uint32_t threads)
shutdown() [1/2]
void satox::blockchain::BlockchainManager::shutdown ()
Definition at line 101 of file blockchain_manager.cpp.
References disconnect(), and satox::blockchain::SHUTDOWN.
Referenced by ~BlockchainManager().
shutdown() [2/2]
void satox::blockchain::BlockchainManager::shutdown ()
startMining()
bool satox::blockchain::BlockchainManager::startMining (const std::string & address)
startSync()
bool satox::blockchain::BlockchainManager::startSync ()
stopMining()
bool satox::blockchain::BlockchainManager::stopMining ()
stopSync()
bool satox::blockchain::BlockchainManager::stopSync ()
syncToHeight()
bool satox::blockchain::BlockchainManager::syncToHeight (uint32_t height)
unregisterBlockCallback()
void satox::blockchain::BlockchainManager::unregisterBlockCallback ()
Definition at line 837 of file blockchain_manager.cpp.
unregisterErrorCallback()
void satox::blockchain::BlockchainManager::unregisterErrorCallback ()
Definition at line 849 of file blockchain_manager.cpp.
unregisterTransactionCallback()
void satox::blockchain::BlockchainManager::unregisterTransactionCallback ()
Definition at line 843 of file blockchain_manager.cpp.
updateConfig()
bool satox::blockchain::BlockchainManager::updateConfig (const BlockchainConfig & config)
Definition at line 720 of file blockchain_manager.cpp.
References validateConfig().
updateNetworkConfig()
bool satox::blockchain::BlockchainManager::updateNetworkConfig (const NetworkConfig & config)
Definition at line 771 of file blockchain_manager.cpp.
References satox::blockchain::NetworkConfig::port.
validateBlock() [1/2]
bool satox::blockchain::BlockchainManager::validateBlock (const std::shared_ptr< Block > & block)
Definition at line 315 of file blockchain_manager.cpp.
validateBlock() [2/2]
bool satox::blockchain::BlockchainManager::validateBlock (const std::string & block_hash) const
validateConfig()
bool satox::blockchain::BlockchainManager::validateConfig (const BlockchainConfig & config)
Definition at line 750 of file blockchain_manager.cpp.
References satox::blockchain::BlockchainConfig::name, satox::blockchain::BlockchainConfig::networkConfig, satox::blockchain::NetworkConfig::port, and satox::blockchain::BlockchainConfig::timeout.
Referenced by initialize(), and updateConfig().
validateTransaction() [1/2]
bool satox::blockchain::BlockchainManager::validateTransaction (const std::shared_ptr< Transaction > & tx)
Definition at line 512 of file blockchain_manager.cpp.
validateTransaction() [2/2]
bool satox::blockchain::BlockchainManager::validateTransaction (const std::string & txid) const
verifyChain()
bool satox::blockchain::BlockchainManager::verifyChain () const
The documentation for this class was generated from the following files:
src/blockchain/include/satox/blockchain/blockchain_manager.hpp
src/core/include/satox/blockchain/blockchain_manager.hpp
src/blockchain/src/blockchain_manager.cpp