SATOX SDK: satox::network::NetworkException Class Reference
satox::network::NetworkException Class Reference
#include <error.hpp>
Public Member Functions
NetworkException (NetworkErrorCode code, const std::string &message="")
const char * what () const noexcept override
NetworkErrorCode code () const
const std::string & message () const
Detailed Description
Definition at line 52 of file error.hpp.
Constructor & Destructor Documentation
NetworkException()
satox::network::NetworkException::NetworkException (NetworkErrorCode code, const std::string & message = "") inline
Definition at line 54 of file error.hpp.
References code(), and message().
Referenced by satox::network::NetworkInitializationException::NetworkInitializationException(), and satox::network::NetworkOperationException::NetworkOperationException().
Member Function Documentation
code()
NetworkErrorCode satox::network::NetworkException::code () const inline
Definition at line 61 of file error.hpp.
Referenced by NetworkException().
message()
const std::string & satox::network::NetworkException::message () const inline
Definition at line 65 of file error.hpp.
Referenced by NetworkException(), satox::network::NetworkInitializationException::NetworkInitializationException(), and satox::network::NetworkOperationException::NetworkOperationException().
what()
const char * satox::network::NetworkException::what () const inline override noexcept
Definition at line 57 of file error.hpp.
The documentation for this class was generated from the following file:
src/network/include/satox/network/error.hpp