name: Hardware Wallet Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  hardware-wallet-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [Debug, Release]
        compiler: [gcc-9, clang-10]
        wallet-type: [ledger, trezor]

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libssl-dev libcurl4-openssl-dev
        sudo apt-get install -y ${{ matrix.compiler }}
        sudo apt-get install -y python3-pip libudev-dev libusb-1.0-0-dev
        pip3 install conan

    - name: Setup hardware wallet simulator
      run: |
        if [ "${{ matrix.wallet-type }}" = "ledger" ]; then
          git clone https://github.com/LedgerHQ/speculos.git
          cd speculos
          cmake -B build
          cmake --build build
          ./build/speculos --model nanos --display headless &
        elif [ "${{ matrix.wallet-type }}" = "trezor" ]; then
          git clone https://github.com/trezor/trezor-firmware.git
          cd trezor-firmware/core
          pipenv install
          pipenv run ./build.py emulator
          ./emu.py --headless &
        fi

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} \
          -DBUILD_TESTING=ON \
          -DENABLE_HARDWARE_WALLET=ON \
          -DENABLE_COVERAGE=${{ matrix.build-type == 'Debug' }}

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{ matrix.build-type }} -- -j $(nproc)

    - name: Run hardware wallet tests
      run: |
        cd ${{github.workspace}}/build
        ./satox-wallet/tests/wallet_manager_comprehensive_test --gtest_filter="*HardwareWallet*"

    - name: Run hardware wallet integration tests
      run: |
        cd ${{github.workspace}}/build
        ./satox-wallet/tests/wallet_manager_integration_tests --gtest_filter="*HardwareWallet*"

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: hardware-wallet-test-results-${{ matrix.wallet-type }}
        path: |
          ${{github.workspace}}/build/Testing
          ${{github.workspace}}/build/test-results

    - name: Upload coverage
      if: matrix.build-type == 'Debug'
      uses: codecov/codecov-action@v2
      with:
        flags: hardware-wallet-tests
        name: hardware-wallet-coverage-${{ matrix.wallet-type }} 